// These are verifier/fixture contracts, never evidence of a real UI or Windows run.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {deflateSync} from 'node:zlib';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {basicKeyAcceptanceFixture,originalBasicKeyMidi,prepareBasicKeyFixtures,BASIC_KEY_FILES,BASIC_KEY_PHASES} from '../scripts/prepare-basic-key-fixtures.mjs';
import {validateBasicKeyOpened,validateBasicKeyExport,validateBasicKeyRenderer,verifyBasicKeyNativeEvidence} from '../scripts/verify-basic-key-evidence.mjs';
import {storedZip} from './native-import-driver-fixtures.js';
import {digest} from './clean-song-package-fixtures.js';
import {readBulkEvidenceZip} from '../scripts/verify-native-bulk-import-evidence.mjs';
import {addNativeProfileEvidence} from './native-profile-evidence-fixtures.js';
const fixture=basicKeyAcceptanceFixture();
function syntheticPickerGestures(){
 const state={button:0,buttons:0,defaultPrevented:false,activation:{isActive:true,hasBeenActive:true},focus:{hasFocus:true,activeId:'import-button',visibility:'visible'},trigger:{id:'import-button',tag:'BUTTON',type:'submit',disabled:false,connected:true,inert:false},input:{id:'score-file',tag:'INPUT',type:'file',disabled:false,connected:true,inert:false,multiple:true},dialog:{id:'import-tools-dialog',open:true,modal:true}};
 return[['before-action',null,null],['pointerdown','import-button',true],['pointerup','import-button',true],['click','import-button',true],['click','score-file',false],['change','score-file',true]].map(([type,targetId,trusted])=>({...structuredClone(state),observedAtMs:1050,eventTimeMs:type==='before-action'?null:50,type,targetId,trusted}));
}
function syntheticScreenshot(){const crc=b=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=c>>>1^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;},chunk=(name,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;};const header=Buffer.alloc(13);header.writeUInt32BE(640);header.writeUInt32BE(360,4);header[8]=8;header[9]=2;const pixels=Buffer.alloc(1921*360);let value=17;for(let i=0;i<pixels.length;i++){value=(Math.imul(value,1664525)+1013904223)>>>0;pixels[i]=i%1921?value>>>24:0;}return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}

function opened(){const value=JSON.parse(readFileSync(new URL('./fixtures/basic-keys-native-open.json',import.meta.url)));const p=value.clean_package;p.score_json=fixture.files.get('score.json').toString();p.metadata_json=fixture.files.get('metadata.json').toString();p.coverage=fixture.score.coverage;p.content_sha256=fixture.manifest.package.content_sha256;p.runtime.source_sha256=fixture.manifest.source.sha256;p.runtime.compilation.timeline.duration_ms=12000;p.runtime.compilation.timeline.notes[0].duration_ms=12000;return value;}
function transport(){const state={passId:'1',captured:'1',cue:'paused',phase:'paused',hidden:false,openDialogs:[],positionMs:900,durationMs:12000};return{version:1,stage:'complete',omitted:0,rowBytes:3000,trustedPlayClicks:2,trustedKeyDowns:1,trustedKeyUps:1,current:state,rows:[{kind:'ready',elapsedMs:0,state:{...state,positionMs:0,captured:'0'}},{kind:'transport',elapsedMs:20,state:{...state,phase:'capturing',positionMs:200}},{kind:'event',elapsedMs:30,state,event:{type:'keydown',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}},{kind:'event',elapsedMs:40,state,event:{type:'keyup',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}}]};}
function renderer(phase){const o=opened(),key=`song-${o.clean_package.content_sha256}`,preview={tracks:fixture.score.performance.tracks.map(t=>`${t.name} · ${t.events.length} retained events · 保留 ${t.events.length} 个事件`),parts:[{disabled:false},{disabled:true},{disabled:false}],listenDisabled:true,practiceDisabled:false,audio:{sourceStarts:0}};return{version:1,phase,ok:true,origin:'https://wmh.localhost',profileMarkerAbsent:true,errors:[],key,opened:o,inventory:[{key}],previews:{en:{...preview,coverage:'18 source events retained · 5 attacks: 3 positive determined, 1 instantaneous, 1 unresolved',rendition:'Reference audio unavailable'},'zh-CN':{...preview,coverage:'18 个源事件 · 5 次按键：3 个已确定正时长、1 个瞬时、1 个结束未确定',rendition:'参考音频不可用'}},stageState:{target:'midi-t1-c1-r0',notationPart:'',countInDisabled:true,meter:'源拍号未确定',tempo:'120',range:'35～72 · 2 个可练目标',partCheckboxes:Array.from({length:3},()=>({disabled:true}))},noInput:{captured:'0',soundMuted:false,audio:{sourceStarts:0}},humanAudio:{sourceStarts:0},requests:[],layout:{width:1280,height:720,documentWidth:1280},trusted:[{type:'change',id:'preview-part',trusted:true},{type:'keydown',code:'KeyR',trusted:true}],negative:[{file:BASIC_KEY_FILES.profile,ready:0,statuses:[{status:'retained_nonplayable',playable:false,code:'pack_source_only',message:'Invalid complete profile; inspect source'}],text:'Invalid complete profile; inspect source',inventory:0},{file:BASIC_KEY_FILES.coverage,ready:0,statuses:[{status:'retained_nonplayable',playable:false,code:'pack_source_only',message:'Invalid complete profile; inspect source'}],text:'Invalid complete profile; inspect source · Forged coverage; re-create the complete package',inventory:0}],imports:[{body:{summary:{saved:1}}}],actions:7,pickerObservations:phase==='basic-key-seed'?[BASIC_KEY_FILES.profile,BASIC_KEY_FILES.coverage,BASIC_KEY_FILES.valid].map((filename,index)=>({sequence:index+1,filename,completed:true,gestures:syntheticPickerGestures(),changes:[{filename,trusted:true}]})):[],screenshots:Object.fromEntries(['english','chinese','track0','track1','track2','track3','track4','stage','human',...(phase==='basic-key-seed'?[BASIC_KEY_FILES.profile,BASIC_KEY_FILES.coverage]:[])].map(role=>[role,7])),assessmentRequests:[{inputs:[{midi:60}],timeline:{notes:[{id:'midi-t1-e4'}]}}],assessmentResponses:[{status:200,body:{hits:[],misses:['midi-t1-e4'],extras:[0]}}],transportAdmission:transport(),files:{machineTake:`${phase}-1.json`,humanTake:`${phase}-2.json`,...(phase==='basic-key-seed'?{package:`${phase}-3.zip`}:{})}};}
function take(human){const input={midi:60,velocity:90,at_ms:100},id=fixture.score.notation.id;return{version:1,score_id:id,practice_part:'midi-t1-c1-r0',passes:[{id:1,capture_enabled:true,timeline:{notes:[{id:'midi-t1-e4',midi:60}]},inputs:human?[input]:[],captures:human?[{event_id:1,event_wall_ms:1100,received_wall_ms:1101,input}]:[],assessment:human?{hits:[],misses:['midi-t1-e4'],extras:[0]}:null}],input_evidence:{version:1,truncated:false,omitted_observations:0,events:human?[{event_id:1,kind:'note_on',source_id:'keyboard-r',input_kind:'typing_keyboard',encoding:'key_down',midi:60,velocity:90,event_wall_ms:1100,received_wall_ms:1101,onset_capture:{pass_id:1,event_id:1}},{event_id:2,kind:'note_off',encoding:'key_up'}]:[]}};}
function exported(key){return storedZip([...fixture.files].map(([name,b])=>[`songs/${key}/${name}`,b]).concat([['manifest.json',JSON.stringify({format:'worldmusichub-song-pack',version:2,songs:[{folder:`songs/${key}`} ]})]]));}
test('original basic-key fixture retains unsupported records, all tracks and source hash',()=>{assert.equal(digest(originalBasicKeyMidi()),'7e5fea609420469fc4178cb8f1d740c80a3f07d0833632794aa0cd68375e5315');assert.equal(fixture.source.length,130);assert.deepEqual(fixture.score.performance.tracks.map(t=>t.events.length),[9,3,3,2,1]);assert.deepEqual(fixture.score.performance.tracks[0].events.slice(0,3),[[0,[176,0,7]],[0,[192,42]],[0,[176,74,91]]]);assert.deepEqual(fixture.score.notation.meters,[]);assert.deepEqual(fixture.score.notation.tempo,[]);assert.equal(fixture.score.coverage.projected_melodic_targets,2);assert.equal(fixture.score.coverage.key_attacks,5);assert.equal(fixture.score.coverage.zero_length_attacks,1);assert.equal(fixture.score.coverage.unresolved_ends,1);assert.deepEqual([...readBulkEvidenceZip(fixture.bytes).keys()].sort(),['manifest.json','songs/original-basic-key/metadata.json','songs/original-basic-key/score.json']);assert.equal(fixture.manifest.rights.license,'CC0-1.0');});
test('negative fixtures have valid outer score hashes and fail actual profile/coverage semantics',()=>{for(const[id,bytes]of Object.entries(fixture.variants)){const files=readBulkEvidenceZip(bytes),meta=JSON.parse(files.get('songs/original-basic-key/metadata.json')),scoreBytes=files.get('songs/original-basic-key/score.json'),score=JSON.parse(scoreBytes);assert.equal(meta.score.sha256,digest(scoreBytes));assert.equal(meta.score.bytes,scoreBytes.length);assert.equal(score.source.sha256,fixture.score.source.sha256);if(id==='profile')assert.notEqual(score.performance.profile,fixture.score.performance.profile);else assert.equal(score.coverage.represented_events,fixture.score.coverage.represented_events-1);}});
test('receiver proof rejects lost sources, fabricated targets and absent honest UI evidence',()=>{validateBasicKeyOpened(opened());for(const mutate of [o=>o.clean_package.content_sha256='0'.repeat(64),o=>o.clean_package.score_json+=' ',o=>o.clean_package.runtime.parts.pop(),o=>o.clean_package.runtime.compilation.timeline.notes.push({id:'drum',midi:35,duration_ms:250}),o=>o.clean_package.runtime.reference_audio='available']){const value=opened();mutate(value);assert.throws(()=>validateBasicKeyOpened(value));}const r=renderer('basic-key-seed');validateBasicKeyRenderer(r);for(const mutate of [v=>v.previews['zh-CN'].tracks.pop(),v=>v.previews.en.parts[1].disabled=false,v=>v.stageState.meter='4/4',v=>v.noInput.audio.sourceStarts=1,v=>v.trusted[0].trusted=false,v=>v.negative[0].statuses[0].playable=true,v=>v.inventory=[],v=>v.layout.documentWidth=2000]){const value=structuredClone(r);mutate(value);assert.throws(()=>validateBasicKeyRenderer(value));}});
test('export proof compares exact files including whitespace and refuses extra source payload',()=>{const key='song-test';validateBasicKeyExport(exported(key),fixture,key);const changed=new Map(readBulkEvidenceZip(exported(key)));changed.set(`songs/${key}/score.json`,Buffer.concat([fixture.files.get('score.json'),Buffer.from('\n')]));assert.throws(()=>validateBasicKeyExport(storedZip([...changed]),fixture,key));changed.set(`songs/${key}/source.mid`,fixture.source);assert.throws(()=>validateBasicKeyExport(storedZip([...changed]),fixture,key));});
async function evidence(t){const directory=await mkdtemp(join(tmpdir(),'wmh-basic-gate-'));t.after(()=>rm(directory,{recursive:true,force:true}));await prepareBasicKeyFixtures(join(directory,'fixtures'));await mkdir(join(directory,'downloads'));const save=async(p,v)=>{const full=join(directory,p);await mkdir(join(full,'..'),{recursive:true});await writeFile(full,typeof v==='object'&&!Buffer.isBuffer(v)?JSON.stringify(v):v);};const executable=join(directory,'test-exe.bin'),exe=Buffer.from('Original verifier fixture; this is not an executable');await save('test-exe.bin',exe);const sourceSha='a'.repeat(40),sourceTree='b'.repeat(40),native={version:1,ok:true,scenario:'basic-key',profile_reused:false,source_sha:sourceSha,source_tree:sourceTree,executable_sha256:digest(exe),executable_bytes:exe.length,directory:join(directory,'Scores'),phases:[]};return{directory,save,native,sourceSha,sourceTree,executable};}
test('native proof re-reads exact artifacts and rejects changed score bytes or missing screenshots',async t=>{
 const f=await evidence(t),rows=[],png=syntheticScreenshot();
 for(const [index,phase]of BASIC_KEY_PHASES.entries()){
  const r=renderer(phase),actions=[...(phase==='basic-key-seed'?[BASIC_KEY_FILES.profile,BASIC_KEY_FILES.coverage,BASIC_KEY_FILES.valid].map(file=>({kind:'picker',file})):[]),{kind:'select-last'},{kind:'select-first'},{kind:'key-r'},{kind:'click'}];r.actions=actions.length;for(const k of Object.keys(r.screenshots))r.screenshots[k]=actions.length;
  const host={phase,process_id:100+index,profile_fresh:true,profile_reused:false,renderer_ok:true,normal_close:true,executable_tcp_listeners:0,actions:r.actions,renderer_origin:r.origin};f.native.phases.push(host);
  for(const [i,a]of actions.entries()){await f.save(`action-${phase}-${i+1}.json`,{version:1,sequence:i+1,x:10,y:20,width:1280,height:720,...a});await f.save(`result-${phase}-${i+1}.json`,{ok:true,client_click:{app_hwnd:1},...(a.kind==='picker'?{owned_dialog:{app_process_id:host.process_id},picker_completion:{dialog_dismissed:true,app_enabled:true,owned_popup_visible:false}}:{})});}
  await f.save(`native-action-${phase}-${actions.length}.png`,png);await f.save(`native-${phase}.png`,png);await f.save(`renderer-${phase}.json`,r);await f.save(`downloads/${r.files.machineTake}`,take(false));await f.save(`downloads/${r.files.humanTake}`,take(true));if(phase==='basic-key-seed')await f.save(`downloads/${r.files.package}`,exported(r.key));
  for(const area of ['clean-songs','clean-backups'])for(const[path,bytes]of fixture.files){const name=`${area}/${r.key}/package/${path}`;await f.save(`Scores/${name}`,bytes);if(index===0)rows.push({path:name,bytes:bytes.length,sha256:digest(bytes)});}await f.save(`snapshot-${phase}.json`,{version:1,files:rows});
 }
 await addNativeProfileEvidence(f.native,f.save);await f.save('native-basic-key.json',f.native);const proof=await verifyBasicKeyNativeEvidence(f.directory,{sourceSha:f.sourceSha,sourceTree:f.sourceTree,executable:f.executable});assert.equal(proof.ok,true);assert.equal(proof.claims.full_acceptance,false);
 const path=`Scores/clean-backups/${renderer('basic-key-seed').key}/package/score.json`;await f.save(path,Buffer.concat([fixture.files.get('score.json'),Buffer.from(' ')]));await assert.rejects(verifyBasicKeyNativeEvidence(f.directory));await f.save(path,fixture.files.get('score.json'));await rm(join(f.directory,'native-basic-key-restart.png'));await assert.rejects(verifyBasicKeyNativeEvidence(f.directory),/ENOENT/);
});
test('source/executable gate rejects a different commit, tree and executable before trusting renderer rows',async t=>{const f=await evidence(t);await f.save('native-basic-key.json',f.native);for(const options of [{sourceSha:'c'.repeat(40)},{sourceTree:'d'.repeat(40)}])await assert.rejects(verifyBasicKeyNativeEvidence(f.directory,options),/strictly equal/);await f.save('test-exe.bin','changed executable');await assert.rejects(verifyBasicKeyNativeEvidence(f.directory,{executable:f.executable}),/strictly equal/);});
test('preview and full workflows keep real browser/Windows and exact artifact checks mandatory',async()=>{for(const name of ['basic-key-preview.yml','windows-desktop-acceptance.yml']){const path=new URL(`../.github/workflows/${name}`,import.meta.url),parsed=spawnSync('python3',['scripts/check-authoring-workflow.py',path.pathname],{encoding:'utf8'});assert.equal(parsed.status,0,parsed.stderr);const text=await readFile(path,'utf8');assert.match(text,/WMH_VIEWPORT_HEIGHT=720 node scripts\/hosted-basic-key-check\.mjs/);assert.match(text,/-Scenario basic-key/);assert.match(text,/verify-basic-key-evidence\.mjs --check desktop-basic-key/);assert.match(text,/WMH_SOURCE_SHA/);assert.match(text,/WMH_BASIC_KEY_EXECUTABLE/);assert.ok(!/continue-on-error:[^\n]*true[^]*basic-key/.test(text.slice(text.indexOf('Native original basic-key'))));}const host=await readFile(new URL('../scripts/hosted-basic-key-check.mjs',import.meta.url),'utf8');assert.match(host,/GITHUB_ACTIONS/);assert.match(host,/WMH_SOURCE_SHA,head/);assert.match(host,/driver_sha256=digest/);assert.match(host,/chromium.launch/);assert.match(host,/validateBasicKeyTakes/);assert.match(host,/validateBasicKeyExport/);assert.match(host,/new Set\(report.phases.map/);});
