import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareCleanSong,isCleanSong} from '../web/clean-song-package.js';
import {openScoreStorage} from '../web/native-score-storage.js';
import {cleanDescriptor,cleanSong,fixtureKey,mediaFixture} from './clean-song-fixtures.js';
import {nativeScoreServer,nativeResponse} from './native-storage-app-fixtures.js';

test('native complete descriptor binds full parts, source-free notation and exact clock',()=>{const song=cleanSong();assert.ok(isCleanSong(song));assert.equal(song.score.performance.tracks.length,3);assert.equal(song.runtime.notes.length,5);assert.equal(song.runtime.duration_ms,1800);assert.equal(song.runtime.notes.at(-1).end_ms-song.runtime.notes.at(-1).start_ms,800);assert.equal(song.score.notation.source,null);assert.ok(Object.isFrozen(song.runtime.notes));assert.equal(isCleanSong(structuredClone(song)),false);});
test('raw optional defaults and JSON ordering use normalized native score equality',()=>{const descriptor=cleanDescriptor(({score})=>{delete score.notation.source;delete score.notation.composer;});const normalized=descriptor.runtime.compilation.score;assert.ok(prepareCleanSong(fixtureKey,descriptor,Object.fromEntries(Object.entries(normalized).reverse())));});
test('wrong package identity, canonical mutation, missing notes and path handles are rejected',()=>{for(const mutate of [d=>d.content_sha256='d'.repeat(64),d=>d.runtime.compilation.score.title='Changed',d=>d.runtime.notes.pop(),d=>d.runtime.notes[0].channel=5]){const d=cleanDescriptor(),score=structuredClone(d.runtime.compilation.score);mutate(d);assert.throws(()=>prepareCleanSong(fixtureKey,d,score),error=>error.code==='clean_package_invalid');}});
test('native media fetch requires admitted handle, matching MIME size and digest',async()=>{const asset=mediaFixture(),d=cleanDescriptor(({metadata})=>metadata.media.push(asset.descriptor)),score=d.runtime.compilation.score,server=await nativeScoreServer();const key=fixtureKey.slice(7);server.records.set(key,{entry:{key,revision:1,title:score.title,composer:'',score_id:score.id,label:score.title,score_bytes:JSON.stringify(score).length,saved_at_unix_ms:1700000000000,clean_package:{version:2}},score_json:JSON.stringify(score),clean_package:d});let corrupt=false;
server.setRoute(({path})=>path==='/api/library/asset'?{ok:true,url:'https://wmh.localhost/api/library/asset',redirected:false,headers:{get:()=>asset.descriptor.mime},arrayBuffer:async()=>Uint8Array.from(corrupt?Buffer.from('bad'):asset.data).buffer}:undefined);
const storage=await openScoreStorage({fetcher:server.fetcher,origin:'https://wmh.localhost',validateScore:async()=>true});await assert.rejects(storage.loadAsset(fixtureKey,d.media[0].handle));const loaded=await storage.load(fixtureKey);assert.ok(loaded.cleanSong);const blob=await storage.loadAsset(fixtureKey,d.media[0].handle);assert.equal(await blob.text(),'authored-media');corrupt=true;await assert.rejects(storage.loadAsset(fixtureKey,d.media[0].handle));await assert.rejects(storage.exportBackup(),error=>error.code==='clean_pack_export_required');storage.close();});
