import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {completePracticeFixture,originalCompletePracticeMidi,COMPLETE_PRACTICE_PHASES} from '../scripts/prepare-complete-practice-fixtures.mjs';
import {validateCompleteOpened,validateCompleteGeometry,validateCompletePracticeTakes,validateCompletePracticeRenderer} from '../scripts/verify-complete-practice-evidence.mjs';
import {digest} from './clean-song-package-fixtures.js';
const root=fileURLToPath(new URL('../',import.meta.url)),source=name=>readFile(new URL(`../${name}`,import.meta.url),'utf8');
const f=completePracticeFixture(),human=['midi-t1-c1-r0','midi-t2-c2-r0'];
function takes(){const target={id:'midi-t1-e2',midi:72,start_ms:1500,duration_ms:1000,velocity:90},notes=[target,{id:'midi-t1-e4'},{id:'midi-t2-e3'}],plan={source_note_count:4,target_count:3,timeline:{notes},groups:[{target_id:'midi-t1-e2',source_occurrence_ids:['midi-t1-e2','midi-t2-e1'],source_note_ids:['midi-t1-e2','midi-t2-e1'],part_ids:human}]};const pass={interpretation:{practice_selection:{kind:'parts',part_ids:human},source_target_ids:f.manifest.human_source_ids,source_sha256:f.manifest.source.sha256},timeline:{notes},inputs:[]};const machine={practice_selection:{kind:'parts',part_ids:human},target_plan:plan,view_configuration:{practice_layout:'complete'},passes:[pass]};const player=structuredClone(machine);player.passes[0].inputs=[{midi:72,at_ms:1500}];player.passes[0].assessment={hits:[{note_id:'midi-t1-e2',delta_ms:0}],misses:['midi-t1-e4','midi-t2-e3'],extras:[]};return{machine,human:player};}
function report(){return{phase:'complete-practice-seed',requests:[{path:'/api/assess',body:{timeline:{notes:f.manifest.target_ids.map(id=>({id}))},inputs:[{midi:72}]}}]};}
test('public fixture is mechanical C/E/G original with exact converter byte hashes',()=>{assert.equal(originalCompletePracticeMidi().length,115);assert.equal(digest(originalCompletePracticeMidi()),'4835ffbbf6102a664ec63c1e6a1761b777157391bb1ecbd78d73378ef1e56233');assert.equal(f.manifest.rights.license,'CC0-1.0');assert.equal(f.score.coverage.source_tracks,3);assert.equal(f.score.coverage.key_attacks,6);assert.equal(f.score.coverage.unresolved_ends,0);assert.ok(f.score.notation.parts.flatMap(p=>p.notes).every(n=>['C','E','G'].includes(n.pitch.step)));assert.equal(f.score.source.sha256,f.manifest.source.sha256);for(const row of f.manifest.files){assert.equal(row.bytes,f.files.get(row.path).length);assert.equal(row.sha256,digest(f.files.get(row.path)));}assert.equal(f.manifest.vsq.generator,'crates/desktop-shell/examples/generate_vsq_fixture.rs');});
test('take oracle rejects duplicate-unison hits, machine capture, missing source identity and changed union',()=>{validateCompletePracticeTakes(takes(),report());for(const mutate of [
 x=>x.human.target_plan.target_count++,x=>x.human.target_plan.source_note_count--,x=>x.human.target_plan.groups[0].source_occurrence_ids.pop(),x=>x.human.target_plan.groups[0].part_ids.pop(),x=>x.human.target_plan.timeline.notes[0].duration_ms=500,x=>x.human.target_plan.timeline.notes[0].velocity=80,x=>x.human.passes[0].interpretation.source_target_ids.pop(),x=>x.human.passes[0].interpretation.source_sha256='0'.repeat(64),x=>x.human.passes[0].inputs.push({midi:60}),x=>x.machine.passes[0].inputs.push({midi:72}),x=>x.human.passes[0].assessment.hits.push({note_id:'midi-t2-e1',delta_ms:0}),x=>x.human.passes[0].assessment.hits[0].delta_ms=181,x=>x.human.passes[0].timeline.notes.push({id:'midi-t3-e1'}),x=>x.human.practice_selection={kind:'all',part_ids:human}
 ]){const changed=takes();mutate(changed);assert.throws(()=>validateCompletePracticeTakes(changed,report()));}});
test('native geometry requires measured pixels, owned foreground, actual work area and both supported heights',()=>{for(const [width,height]of [[1280,720],[1264,681],[960,640]]){const r={width,height,dpr:1,documentWidth:width},g={version:1,kind:'native-window-geometry',phase:COMPLETE_PRACTICE_PHASES[0],stage:`native-action-${COMPLETE_PRACTICE_PHASES[0]}-1`,process_id:42,owner_process_id:42,hwnd:100,root_hwnd:100,foreground_hwnd:100,reported_viewport:[width,height],client_rect:[0,0,width,height],client_origin:[8,31],window_rect:[0,0,width+16,height+39],work_area:[0,0,1920,1040],monitor_rect:[0,0,1920,1080],monitor_scale_hresult:0,window_dpi:96,monitor_scale_percent:100},options={phase:g.phase,processId:42,png:{width,height},sequence:1};validateCompleteGeometry(g,r,options);for(const change of [v=>v.foreground_hwnd++,v=>v.owner_process_id++,v=>v.client_rect[2]++,v=>v.window_dpi=144,v=>v.work_area[3]=height,v=>v.reported_viewport[1]++,v=>v.monitor_scale_hresult=-1]){const changed=structuredClone(g);change(changed);assert.throws(()=>validateCompleteGeometry(changed,r,options));}assert.throws(()=>validateCompleteGeometry(g,{...r,height:639},options));}});
test('causal renderer failure is reported before dependent data validation',()=>{assert.throws(()=>validateCompletePracticeRenderer({ok:false,phase:'complete-practice-seed',stage:'cold-apply',error:'AudioContext resume denied'}),/cold-apply: AudioContext resume denied/);});
test('canvas observer forwards exact native calls and records independent color/dash/text evidence',async()=>{const text=await source('crates/desktop-shell/complete-practice-acceptance.js'),calls=[];class Context{constructor(id){this.canvas={id};this.fillStyle='#8a91ac';this.shadowBlur=0;this.lineWidth=2;}getLineDash(){return[5,4];}}for(const method of ['clearRect','fill','stroke','fillText'])Context.prototype[method]=function(...args){calls.push({method,receiver:this,args});return 'unchanged';};const originals=Object.fromEntries(['clearRect','fill','stroke','fillText'].map(name=>[name,Context.prototype[name]]));const ctx=vm.createContext({structuredClone,CanvasRenderingContext2D:Context});vm.runInContext(text.slice(0,text.indexOf('(() => {'))+';globalThis.create=observeCompletePracticeCanvas;',ctx);const observer=ctx.create(),canvas=new Context('falling-notes');assert.equal(canvas.clearRect(1,2,3,4),'unchanged');assert.equal(canvas.fill(),'unchanged');canvas.stroke();canvas.fillText('C5',10,20);assert.deepEqual(JSON.parse(JSON.stringify(observer.snapshot())),{fills:[{color:'#8a91ac',shadow:0}],strokes:[{dash:[5,4],width:2}],labels:['C5']});assert.equal(calls[0].receiver,canvas);assert.deepEqual(calls[0].args,[1,2,3,4]);new Context('other-canvas').clearRect();assert.equal(observer.snapshot().fills.length,1);canvas.clearRect();assert.equal(observer.snapshot().fills.length,0);assert.equal(observer.restore(),true);for(const[name,fn]of Object.entries(originals))assert.equal(Context.prototype[name],fn);});
test('focused workflow really invokes browser and native gates with no autoplay bypass',async()=>{const [workflow,host,renderer,native,profile,rust,windows]=await Promise.all(['.github/workflows/complete-practice-preview.yml','scripts/hosted-complete-practice-check.mjs','crates/desktop-shell/complete-practice-acceptance.js','scripts/windows-desktop-acceptance.ps1','scripts/windows-desktop-profile.ps1','crates/desktop-shell/src/acceptance.rs','crates/desktop-shell/src/windows.rs'].map(source));const python=process.platform==='win32'?'python':'python3',parsed=spawnSync(python,['scripts/check-authoring-workflow.py','.github/workflows/complete-practice-preview.yml'],{cwd:root,encoding:'utf8'});assert.equal(parsed.status,0,parsed.stderr);for(const token of ['WMH_VIEWPORT_WIDTH=1280 WMH_VIEWPORT_HEIGHT=720','WMH_VIEWPORT_WIDTH=960 WMH_VIEWPORT_HEIGHT=640','-Scenario complete-practice','verify-complete-practice-evidence.mjs --check','WMH_COMPLETE_PRACTICE_EXECUTABLE','check-complete-practice-native.mjs'])assert.ok(workflow.includes(token));assert.doesNotMatch(workflow,/continue-on-error|always\(\).*acceptance/);assert.match(host,/GITHUB_ACTIONS/);assert.match(host,/assert.equal\(process.env.WMH_SOURCE_SHA,head/);assert.match(host,/chromium.launch\(\{headless:true\}\)/);assert.doesNotMatch(host,/autoplay-policy|dispatchEvent|\.evaluate\([^\n]*\.click\(/);assert.match(host,/validateCompletePracticeTakes/);assert.match(renderer,/navigator.userActivation\?\.isActive/);assert.match(renderer,/location.reload\(\)/);assert.match(renderer,/report.coldApplyAction=await native\('click',\$\('complete-practice-apply'\)\)/);assert.match(native,/complete-practice.*verify-complete-practice-evidence.mjs/);for(const phase of COMPLETE_PRACTICE_PHASES){assert.ok(rust.includes(phase));assert.ok(profile.includes(phase));}assert.match(rust,/include_str!\("\.\.\/complete-practice-acceptance.js"\)/);assert.match(windows,/COMPLETE_PRACTICE_PHASES.contains/);assert.match(native,/-ClientOnly:\(\$Scenario -cin @\('library-catalog','complete-practice'\)\)/);});
test('hosted runner refuses a local browser attempt before launching tools',()=>{const run=spawnSync(process.execPath,['scripts/hosted-complete-practice-check.mjs'],{cwd:root,env:{...process.env,GITHUB_ACTIONS:'false',WMH_HOSTED_BROWSER:'0'},encoding:'utf8'});assert.notEqual(run.status,0);assert.match(run.stderr,/Only the authorized hosted browser runner/);assert.doesNotMatch(run.stderr,/executable doesn't exist|browserType.launch|EADDR/);});

test('only the generated complete-practice evidence directory is ignored',()=>{const ignored=spawnSync('git',['check-ignore','--no-index','desktop-complete-practice/report.json'],{cwd:root,encoding:'utf8'});assert.equal(ignored.status,0);assert.equal(ignored.stdout.trim(),'desktop-complete-practice/report.json');const source=spawnSync('git',['check-ignore','--no-index','crates/desktop-shell/complete-practice-acceptance.js'],{cwd:root,encoding:'utf8'});assert.equal(source.status,1);});
