import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {DENSE_STREAM,originalDenseRenditionMidi,expectedDenseAttacks,denseDigest} from '../scripts/prepare-dense-rendition-fixture.mjs';
import {observeDenseRenditionAudio,installDenseRenditionObserver} from '../scripts/dense-rendition-observer.mjs';
import {denseTimingMetrics,validateDenseRenditionEvidence} from '../scripts/verify-dense-rendition-evidence.mjs';
const sourceSha='1732e837773757a00212a03374e9111a4e0f4662d920f45461ffb64f46247ba7';
test('original dense MIDI has an independent complete one-based source inventory and bounded allocation',()=>{
 const bytes=originalDenseRenditionMidi();assert.equal(bytes.length,49380);assert.equal(denseDigest(bytes),sourceSha);assert.equal(bytes.toString('ascii',0,4),'MThd');assert.equal(bytes.readUInt16BE(8),1);assert.equal(bytes.readUInt16BE(10),5);assert.equal(bytes.readUInt16BE(12),96);
 let offset=14;const tracks=[];
 for(let track=1;track<=5;track++){assert.equal(bytes.toString('ascii',offset,offset+4),'MTrk');const end=offset+8+bytes.readUInt32BE(offset+4);offset+=8;let tick=0,event=0;const rows=[],vlq=()=>{let value=0,byte;do{byte=bytes[offset++];value=value*128+(byte&127);}while(byte&128);return value;};while(offset<end){tick+=vlq();const status=bytes[offset++];event++;if(status===255){const kind=bytes[offset++],length=vlq(),data=bytes.subarray(offset,offset+length);offset+=length;rows.push({track,event,tick,status,kind,data});}else{const data=bytes.subarray(offset,offset+(status>>4===12?1:2));offset+=data.length;rows.push({track,event,tick,status,data});}}assert.equal(offset,end);tracks.push(rows);}
 assert.equal(offset,bytes.length);assert.deepEqual(tracks[0].map(row=>row.kind),[81,88,89,47]);assert.deepEqual(tracks[0].map(row=>row.tick),[0,0,0,9216]);
 const expected=expectedDenseAttacks(sourceSha),actual=[];for(const rows of tracks.slice(1)){assert.equal(rows[0].event,1);assert.equal(rows[0].kind,3);assert.match(rows[0].data.toString(),/^Original arithmetic part [1-4]$/);assert.equal(rows[1].event,2);assert.equal(rows[1].status>>4,12);assert.equal(rows[1].data[0],0);assert.equal(rows.at(-1).tick,9216);let index=0;for(const row of rows)if(row.status>>4===9){const release=rows[row.event];assert.equal(row.event,3+index*2);assert.equal(release.status>>4,8);assert.equal(release.tick-row.tick,3);actual.push({id:`midi-t${row.track}-e${row.event}`,eventId:`midi:${sourceSha}:t${row.track}:e${row.event}`,part:`midi-t${row.track}-c${(row.status&15)+1}-r0`,key:row.data[0],velocity:row.data[1],startMs:row.tick*500/96,durationMs:(release.tick-row.tick)*500/96});index++;}assert.equal(index,1536);}
 actual.sort((a,b)=>a.startMs-b.startMs||a.part.localeCompare(b.part));assert.equal(actual.length,6144);for(const[index,row]of actual.entries())assert.deepEqual(row,expected[index],`Source target ${index}`);
 const edges=actual.flatMap(n=>[{time:n.startMs-100,delta:1},{time:n.startMs+n.durationMs,delta:-1}]).sort((a,b)=>a.time-b.time||a.delta-b.delta);let live=0,max=0;for(const edge of edges){live+=edge.delta;max=Math.max(max,live);}assert.equal(max,16);assert.ok(max<=128);for(const start of [0,16000,32000])assert.equal(actual.filter(n=>n.startMs>=start&&n.startMs<start+16000).length,2048);
});
test('dense audio observation forwards every real method and does not inherit the old 512-source ceiling',()=>{
 const calls=[];class Audio{currentTime=0;createOscillator(...args){calls.push(['create',this,args]);return{start(...values){calls.push(['start',this,values]);return 'started';},stop(){return 'stopped';},disconnect(){return 'disconnected';}};}createBufferSource(){return this.createOscillator();}}
 const original=Audio.prototype.createOscillator,probe=observeDenseRenditionAudio({AudioContext:Audio}),context=new Audio();
 for(let i=0;i<6144;i++){const node=context.createOscillator(i);assert.equal(node.start(1),'started');assert.equal(node.stop(2),'stopped');assert.equal(node.disconnect(),'disconnected');}
 assert.equal(probe.snapshot().created,6144);assert.equal(probe.snapshot().sourceStarts,6144);assert.equal(probe.snapshot().oscillatorStarts,6144);assert.equal(probe.snapshot().overflow,false);assert.equal(probe.snapshot().activeSources,0);assert.equal(calls[0][1],context);assert.deepEqual(calls[0][2],[0]);assert.equal(probe.restore(),true);assert.equal(Audio.prototype.createOscillator,original);
});
test('dense trace preserves pump, renderer promises, allocation errors and original cleanup',async t=>{
 const oldDocument=globalThis.document,nodes={progress:{value:10},'clean-song-stage':{dataset:{rendererState:'playing'}},workspace:{dataset:{scoreState:'active'},addEventListener(){},removeEventListener(){}},'engraving-range':{textContent:'Measures 9–16 / 24'},'hud-captured':{textContent:'0'},notice:{textContent:''}};globalThis.document={getElementById:id=>nodes[id]};t.after(()=>{globalThis.document=oldDocument;});
 const calls=[],error=Object.assign(new Error('real late sentinel'),{code:'clean_late_scheduler',detail:{eventId:'exact-source-event',lateSeconds:.25}}),context={currentTime:1,state:'running',addEventListener(){},removeEventListener(){}};
 class Player{constructor(){this.context=context;this.running=true;this.noteCursor=0;this.onError=e=>{calls.push(['error',e]);};}pump(...args){calls.push(['pump',this,args]);this.noteCursor++;this.onError(error);return 'pumped';}}
 class Receiver{constructor(){this.context=context;}schedule(...args){calls.push(['schedule',this,args]);throw error;}}
 const promise=Promise.resolve('loaded');class Renderer{load(...args){calls.push(['load',this,args]);return promise;}updateGraphic(){return 'graphic';}render(...args){calls.push(['render',this,args]);return 'rendered';}}
 const originals=[Player.prototype.pump,Receiver.prototype.schedule,Renderer.prototype.load,Renderer.prototype.render],trace=await installDenseRenditionObserver({library:{BasicKeyPlayer:Player,ReferenceAudioReceiver:Receiver,Renderer},audioProbe:{snapshot:()=>({}),restore:()=>true}}),player=new Player(),handler=player.onError,receiver=new Receiver(),renderer=new Renderer();
 assert.equal(player.pump(4,true),'pumped');assert.equal(renderer.load('exact-doc'),promise);assert.equal(renderer.render('real-options'),'rendered');assert.throws(()=>receiver.schedule({eventId:'exact-source-event',key:60,velocity:90},.5,.6,{}),e=>e===error);await promise;const value=trace.stop();assert.equal(value.errors[0].code,error.code);assert.equal(value.errors[0].eventId,'exact-source-event');assert.equal(value.errors[0].lateSeconds,.25);assert.equal(value.schedules[0].error.code,error.code);assert.equal(value.cleanup.restored,true);assert.equal(player.onError,handler);assert.deepEqual([Player.prototype.pump,Receiver.prototype.schedule,Renderer.prototype.load,Renderer.prototype.render],originals);assert.equal(calls.find(c=>c[0]==='pump')[1],player);assert.deepEqual(calls.find(c=>c[0]==='pump')[2],[4,true]);assert.equal(calls.find(c=>c[0]==='error')[1],error);
});
function syntheticProof(){
 // Synthetic verifier records only; these never establish a browser/audio run.
 const expected=expectedDenseAttacks(sourceSha),trace={cleanup:{restored:true,stopped:true,players:1,contexts:1},errors:[],overflow:[],states:[{state:'running'}],longTasks:[{startTime:16000,duration:200}],counts:{pumps:200,schedules:6144},pumps:Array.from({length:200},(_,i)=>({gapMs:i?20:null,durationMs:1,audioTime:i*.24,afterAudioTime:i*.24,audioState:'running'})),listeningStarted:{audioTime:0,wall:0},current:{renderer:'ended',position:48000,captured:'0',audioState:'running',audioTime:48.1,wall:48100},audio:{created:6144,overflow:false,sourceStarts:6144,oscillatorStarts:6144,activeSources:0,pendingSources:0},schedules:expected.map(n=>({eventId:n.eventId,key:n.key,velocity:n.velocity,start:.1+n.startMs/1000,end:.1+(n.startMs+n.durationMs)/1000,audioNow:n.startMs/1000,returnedVoice:true,voiceStart:.1+n.startMs/1000,voiceEnd:.1+(n.startMs+n.durationMs)/1000})),scope:[0,8,16].map(first=>({scope:'all',status:'ready',range:`第 ${first+1}–${first+8} 小节，共24小节`,renderer:first?'playing':'ready',parts:[2,3,4,5].map((track,i)=>`midi-t${track}-c${i+1}-r0`),sourceIds:expected.filter(n=>n.startMs>=first*2000&&n.startMs<(first+8)*2000).map(n=>n.id),svg:4,heads:2048,loadMs:30})),renders:[9,17].map(from=>({method:'render',renderer:'playing',range:`Measures ${from}–${from+7} / 24`,durationMs:200}))};trace.listeningEnded={...trace.current};return{ok:true,locale:'zh-CN',fixture:{source_sha256:sourceSha,fixture:DENSE_STREAM,pages:Array(12).fill({})},trace,metrics:denseTimingMetrics(trace),assessmentRequests:0,results:{historyHidden:true,passOptions:[''],exportDisabled:true,assessmentDisabled:true},actions:Array.from({length:10},()=>({completed:true})),pageErrors:[],claims:{physical_audio:false,synthetic_clock:false,production_behavior_changed:false}};
}
test('dense proof rejects lost onsets, late errors, paused clocks, fake page coverage and machine input',()=>{
 const good=syntheticProof();validateDenseRenditionEvidence(good);assert.equal(good.metrics.maxRenderMs,200,'Long measured rendering is reported without being hidden or relabeled');
 for(const change of [r=>r.trace.errors.push({code:'clean_late_scheduler'}),r=>r.trace.schedules.pop(),r=>r.trace.schedules[1].eventId=r.trace.schedules[0].eventId,r=>r.trace.schedules[0].start=-1,r=>r.trace.scope[1].sourceIds.pop(),r=>r.trace.scope[2].renderer='paused',r=>r.trace.current.captured='1',r=>r.trace.states.push({state:'suspended'}),r=>r.trace.pumps[1].audioTime=-1,r=>r.trace.current.renderer='paused',r=>r.trace.audio.activeSources=1,r=>r.trace.cleanup.restored=false,r=>r.assessmentRequests=1,r=>r.metrics.maxRenderMs=0]){const value=structuredClone(good);change(value);assert.throws(()=>validateDenseRenditionEvidence(value));}
 const failed={...good,ok:false,error:'native scheduling sentinel'};assert.throws(()=>validateDenseRenditionEvidence(failed),/native scheduling sentinel/);
});
test('dense CI uses the prepared exact-source driver, retains original evidence and refuses local launch',async()=>{
 for(const[name,job]of [['basic-key-preview.yml','basic-key-browser'],['windows-desktop-acceptance.yml','bulk-import-browser']]){const result=spawnSync('python',['scripts/check-authoring-workflow.py','--json',fileURLToPath(new URL(`../.github/workflows/${name}`,import.meta.url))],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);const steps=JSON.parse(result.stdout).jobs[job].steps,run=steps.find(row=>row.run==='node scripts/hosted-dense-rendition-check.mjs');assert.ok(run);assert.equal(run['continue-on-error'],undefined);assert.equal(run.if,"${{ !cancelled() && steps.dense_native_driver.outcome == 'success' && steps.dense_browser_setup.outcome == 'success' }}");assert.equal(steps.find(row=>row.id==='dense_native_driver').run,'cargo build -p worldmusichub-desktop --example native_import_driver --locked');assert.equal(steps.find(row=>row.id==='dense_browser_setup').run,'npx playwright install --with-deps chromium');assert.equal(run.env.WMH_SOURCE_SHA,'${{ github.sha }}');assert.equal(run.env.WMH_NATIVE_IMPORT_DRIVER,'${{ github.workspace }}/target/debug/examples/native_import_driver');const artifact=steps.find(row=>row.with?.name==='dense-rendition-browser-${{ github.sha }}');assert.equal(artifact.if,'always()');assert.ok(artifact.with.path.includes('fixture/*'));assert.ok(artifact.with.path.includes('ui-pages/*.json'));assert.ok(!artifact.with.path.includes('Scores'));}
 const script=fileURLToPath(new URL('../scripts/hosted-dense-rendition-check.mjs',import.meta.url)),refused=spawnSync(process.execPath,[script],{env:{...process.env,GITHUB_ACTIONS:'false',WMH_HOSTED_BROWSER:'0'},encoding:'utf8'});assert.equal(refused.status,1);assert.match(refused.stderr,/require the authorized hosted Actions runner/);const source=await readFile(script,'utf8');assert.doesNotMatch(source,/waitForTimeout|lookAheadMs\s*=|transport\.seek|progress[^\n]*\.value\s*=/);
});
