import test from 'node:test';
import {syntheticAudioThreadRun,syntheticAudioThreadStatus} from './audio-thread-proof-fixtures.js';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import vm from 'node:vm';
import {finishDenseReport} from '../scripts/dense-report-cleanup.mjs';
import {DENSE_STREAM,originalDenseRenditionMidi,expectedDenseAttacks,denseDigest} from '../scripts/prepare-dense-rendition-fixture.mjs';
import {observeDenseRenditionAudio,denseRenditionBootstrap} from '../scripts/dense-rendition-observer.mjs';
import {denseTimingMetrics,validateDenseRenditionEvidence} from '../scripts/verify-dense-rendition-evidence.mjs';
const sourceSha='1732e837773757a00212a03374e9111a4e0f4662d920f45461ffb64f46247ba7';
test('original dense MIDI has an independent complete one-based source inventory and bounded allocation',()=>{
 const bytes=originalDenseRenditionMidi();assert.equal(bytes.length,49380);assert.equal(denseDigest(bytes),sourceSha);assert.equal(bytes.toString('ascii',0,4),'MThd');assert.equal(bytes.readUInt16BE(8),1);assert.equal(bytes.readUInt16BE(10),5);assert.equal(bytes.readUInt16BE(12),96);
 let offset=14;const tracks=[];
 for(let track=1;track<=5;track++){assert.equal(bytes.toString('ascii',offset,offset+4),'MTrk');const end=offset+8+bytes.readUInt32BE(offset+4);offset+=8;let tick=0,event=0;const rows=[],vlq=()=>{let value=0,byte;do{byte=bytes[offset++];value=value*128+(byte&127);}while(byte&128);return value;};while(offset<end){tick+=vlq();const status=bytes[offset++];event++;if(status===255){const kind=bytes[offset++],length=vlq(),data=bytes.subarray(offset,offset+length);offset+=length;rows.push({track,event,tick,status,kind,data});}else{const data=bytes.subarray(offset,offset+(status>>4===12?1:2));offset+=data.length;rows.push({track,event,tick,status,data});}}assert.equal(offset,end);tracks.push(rows);}
 assert.equal(offset,bytes.length);assert.deepEqual(tracks[0].map(row=>row.kind),[81,88,89,47]);assert.deepEqual(tracks[0].map(row=>row.tick),[0,0,0,9216]);
 const expected=expectedDenseAttacks(sourceSha),actual=[];for(const rows of tracks.slice(1)){assert.equal(rows[0].event,1);assert.equal(rows[0].kind,3);assert.match(rows[0].data.toString(),/^Original arithmetic part [1-4]$/);assert.equal(rows[1].event,2);assert.equal(rows[1].status>>4,12);assert.equal(rows[1].data[0],0);assert.equal(rows.at(-1).tick,9216);let index=0;for(const row of rows)if(row.status>>4===9){const release=rows[row.event];assert.equal(row.event,3+index*2);assert.equal(release.status>>4,8);assert.equal(release.tick-row.tick,3);actual.push({id:`midi-t${row.track}-e${row.event}`,eventId:`midi:${sourceSha}:t${row.track-1}:e${row.event-1}`,part:`midi-t${row.track}-c${(row.status&15)+1}-r0`,key:row.data[0],velocity:row.data[1],startMs:row.tick*500/96,durationMs:(release.tick-row.tick)*500/96});index++;}assert.equal(index,1536);}
 actual.sort((a,b)=>a.startMs-b.startMs||a.part.localeCompare(b.part));assert.equal(actual.length,6144);for(const[index,row]of actual.entries())assert.deepEqual(row,expected[index],`Source target ${index}`);
 const edges=actual.flatMap(n=>[{time:n.startMs-100,delta:1},{time:n.startMs+n.durationMs,delta:-1}]).sort((a,b)=>a.time-b.time||a.delta-b.delta);let live=0,max=0;for(const edge of edges){live+=edge.delta;max=Math.max(max,live);}assert.equal(max,16);assert.ok(max<=128);for(const start of [0,16000,32000])assert.equal(actual.filter(n=>n.startMs>=start&&n.startMs<start+16000).length,2048);
});
test('dense audio observation forwards every real method and does not inherit the old 512-source ceiling',()=>{
 const calls=[];class Audio{currentTime=0;createOscillator(...args){calls.push(['create',this,args]);return{start(...values){calls.push(['start',this,values]);return 'started';},stop(){return 'stopped';},disconnect(){return 'disconnected';}};}createBufferSource(){return this.createOscillator();}}
 const original=Audio.prototype.createOscillator,probe=observeDenseRenditionAudio({AudioContext:Audio}),context=new Audio();
 for(let i=0;i<6144;i++){const node=context.createOscillator(i);assert.equal(node.start(1),'started');assert.equal(node.stop(2),'stopped');assert.equal(node.disconnect(),'disconnected');}
 assert.equal(probe.snapshot().created,6144);assert.equal(probe.snapshot().sourceStarts,6144);assert.equal(probe.snapshot().oscillatorStarts,6144);assert.equal(probe.snapshot().overflow,false);assert.equal(probe.snapshot().activeSources,0);assert.equal(calls[0][1],context);assert.deepEqual(calls[0][2],[0]);assert.equal(probe.restore(),true);assert.equal(Audio.prototype.createOscillator,original);
});
test('dense init namespace survives the real init-script closure boundary',()=>{
 const writes=[],realm=vm.createContext({localStorage:{setItem:(...args)=>writes.push(args)}});
 vm.runInContext(`(()=>{${denseRenditionBootstrap()}})();`,realm);
 assert.equal(vm.runInContext('typeof installDenseRenditionObserver',realm),'undefined','Local init names are intentionally not page globals');
 assert.equal(typeof realm.__wmhDenseObserverTools.install,'function');assert.equal(typeof realm.__wmhDenseObserverTools.observeAudio,'function');assert.equal(Object.isFrozen(realm.__wmhDenseObserverTools),true);
 assert.deepEqual(writes,[['worldmusichub.locale.v1','zh-CN']]);delete realm.__wmhDenseObserverTools;assert.equal(realm.__wmhDenseObserverTools,undefined);
});
test('dense trace preserves renderer promises and frame callbacks without inventing main-thread audio pumps',async()=>{
 const nodes={progress:{value:10},'clean-song-stage':{dataset:{rendererState:'playing'}},workspace:{dataset:{scoreState:'active'},addEventListener(){},removeEventListener(){}},'engraving-range':{textContent:'Measures 9–16 / 24'},'hud-captured':{textContent:'0'},notice:{textContent:''}},calls=[],context={currentTime:1,state:'running',addEventListener(){},removeEventListener(){}},promise=Promise.resolve('loaded');
 class Renderer{load(...args){calls.push(['load',this,args]);return promise;}updateGraphic(){return 'graphic';}render(...args){calls.push(['render',this,args]);return 'rendered';}}
 const frameCalls=[],requestFrame=function(callback){if(typeof callback!=='function')throw new TypeError('Original frame callback required');frameCalls.push({owner:this,callback});return 73;},realm=vm.createContext({document:{getElementById:id=>nodes[id]},performance,structuredClone,requestAnimationFrame:requestFrame,localStorage:{setItem(){}}});vm.runInContext(`(()=>{${denseRenditionBootstrap()}})();`,realm);
 const original=Renderer.prototype.load,observeReceiver=async(_,{onContext,onStart})=>{onContext(context);onStart();return{status:()=>({...syntheticAudioThreadStatus(),receivers:1}),snapshot:()=>[],count:()=>1,quiet:()=>true,restore:()=>({restored:true,overflow:false,errors:[],cleanupErrors:[]})};};
 const trace=await realm.__wmhDenseObserverTools.install({library:{Renderer,observeReceiver},audioProbe:{snapshot:()=>({}),restore:()=>true}}),renderer=new Renderer();
 assert.throws(()=>realm.requestAnimationFrame(null),/Original frame callback required/);const frameOwner={},callbackOwner={},seen=[];assert.equal(realm.requestAnimationFrame.call(frameOwner,function animate(value){seen.push([this,value]);return 'painted';}),73);assert.equal(frameCalls[0].owner,frameOwner);assert.equal(frameCalls[0].callback.call(callbackOwner,123),'painted');assert.equal(seen[0][0],callbackOwner);assert.equal(seen[0][1],123);
 assert.equal(renderer.load('exact-doc'),promise);assert.equal(renderer.render('real-options'),'rendered');await promise;const value=trace.stop();assert.equal(value.frames.length,1);assert.equal(value.frames[0].callback,'animate');assert.ok(value.frames[0].durationMs>=0);assert.equal(realm.requestAnimationFrame,requestFrame);assert.equal(frameCalls[0].callback.call(callbackOwner,125),'painted');assert.equal(trace.snapshot().frames.length,1);assert.deepEqual([...value.pumps],[]);assert.deepEqual([...value.schedules],[]);assert.equal(value.cleanup.restored,true);assert.equal(Renderer.prototype.load,original);assert.equal(calls[0][1],renderer);assert.deepEqual(calls[0][2],['exact-doc']);
});
test('dense frame diagnostics preserve cancellation and remain bounded without suppressing callbacks',async()=>{
 const nodes={progress:{value:1},'clean-song-stage':{dataset:{rendererState:'playing'}},workspace:{dataset:{scoreState:'session'},addEventListener(){},removeEventListener(){}},'engraving-range':{textContent:''},'hud-captured':{textContent:'0'},notice:{textContent:''}};
 const callbacks=new Map();let next=0,painted=0;
 const requestAnimationFrame=callback=>{if(typeof callback!=='function')throw new TypeError('callback');callbacks.set(++next,callback);return next;},cancelAnimationFrame=id=>callbacks.delete(id);
 class Player{constructor(){this.running=true;this.noteCursor=0;this.context={currentTime:0,state:'running'};this.onError=()=>{};}pump(){}}
 class Receiver{schedule(){}}class Renderer{load(){}updateGraphic(){}render(){}}
 const realm=vm.createContext({document:{getElementById:id=>nodes[id]},performance,structuredClone,requestAnimationFrame,cancelAnimationFrame,localStorage:{setItem(){}}});vm.runInContext(`(()=>{${denseRenditionBootstrap()}})();`,realm);
 const probe=await realm.__wmhDenseObserverTools.install({library:{Renderer,observeReceiver:async(_,{onContext,onStart})=>{onContext({currentTime:0,state:'running'});onStart();return{status:()=>syntheticAudioThreadStatus(),snapshot:()=>[],count:()=>1,quiet:()=>true,restore:()=>({restored:true,overflow:false,errors:[],cleanupErrors:[]})};}},audioProbe:{snapshot:()=>({}),restore:()=>true}});
 const cancelled=realm.requestAnimationFrame(()=>{throw Error('Cancelled callback ran');});realm.cancelAnimationFrame(cancelled);assert.equal(callbacks.has(cancelled),false);assert.equal(realm.cancelAnimationFrame,cancelAnimationFrame);
 for(let i=0;i<4100;i++){const handle=realm.requestAnimationFrame(()=>++painted);assert.equal(callbacks.get(handle)(i),i+1);callbacks.delete(handle);}
 const value=probe.stop();assert.equal(painted,4100);assert.equal(value.frames.length,4096);assert.deepEqual([...value.overflow],['frames']);assert.equal(value.cleanup.restored,true);assert.equal(realm.requestAnimationFrame,requestAnimationFrame);assert.equal(callbacks.size,0);
});
test('dense evidence survives cleanup failure and never loses the primary playback cause',async()=>{
 const writes=[],calls=[],report={ok:false,error:'original late scheduling',trace:{exact:'retained'}};
 const resources=['context','browser','driver'].map(name=>({name,present:true,close:async()=>{calls.push(name);assert.ok(writes.length);assert.equal(writes[0].ok,false);assert.equal(writes[0].cleanup.status,'pending');if(name==='driver')throw Error('close exceeded5000ms');}}));
 await finishDenseReport(report,{resources,persist:async value=>writes.push(structuredClone(value)),validate(){throw Error('Failed playback cannot be validated as success');}});
 assert.deepEqual(calls,['context','browser','driver']);assert.equal(report.ok,false);assert.equal(report.error,'original late scheduling');assert.equal(report.cleanup.status,'failed');assert.equal(report.cleanup.errors[0].name,'driver');assert.deepEqual(writes.at(-1).trace,{exact:'retained'});
});
test('dense pending report is unaccepted, every cleanup runs and final validation is mandatory',async()=>{
 const writes=[],calls=[],resources=['context','browser','driver'].map(name=>({name,present:true,close:async()=>calls.push(name)})),report={ok:true};let validated=0;
 await finishDenseReport(report,{resources,persist:async value=>writes.push(structuredClone(value)),validate(value){validated++;assert.equal(value.cleanup.status,'complete');}});
 assert.equal(validated,1);assert.equal(report.ok,true);assert.ok(writes.slice(0,-1).every(row=>row.ok===false));assert.deepEqual(calls,['context','browser','driver']);
 const invalid={ok:true};await finishDenseReport(invalid,{resources,persist:async()=>{},validate(){throw Error('source identity failure');}});assert.equal(invalid.ok,false);assert.match(invalid.error,/source identity failure/);
 const writeFailed={ok:true},closed=[];await assert.rejects(finishDenseReport(writeFailed,{resources:resources.map(row=>({...row,close:async()=>closed.push(row.name)})),persist:async()=>{throw Error('quota');},validate(){}}),/evidence write failed/);assert.deepEqual(closed,['context','browser','driver']);assert.equal(writeFailed.ok,false);
});
function syntheticProof(){
 // Synthetic verifier records only; these never establish a browser/audio run.
 const expected=expectedDenseAttacks(sourceSha),trace={version:2,cleanup:{restored:true,stopped:true,players:1,contexts:1,errors:[],receiver:{restored:true,overflow:false,errors:[],cleanupErrors:[]}},errors:[],overflow:[],states:[{state:'running'}],longTasks:[{startTime:16000,duration:200}],counts:{pumps:0,schedules:0},pumps:[],schedules:[],frames:Array.from({length:200},(_,i)=>({durationMs:1,audioTime:i*.24,audioState:'running',renderer:'playing'})),listeningStarted:{audioTime:0,wall:0},current:{renderer:'ended',position:48000,captured:'0',audioState:'running',audioTime:48.1,wall:48100},audio:{created:0,overflow:false,sourceStarts:0,oscillatorStarts:0,activeSources:0,pendingSources:0},receiver:syntheticAudioThreadStatus(),audioThread:[syntheticAudioThreadRun(expected,{sourceSha256:sourceSha,durationMs:48000})],scope:[0,8,16].map(first=>({scope:'all',status:'ready',range:`第 ${first+1}–${first+8} 小节，共24小节`,renderer:first?'playing':'ready',parts:[2,3,4,5].map((track,i)=>`midi-t${track}-c${i+1}-r0`),sourceIds:expected.filter(n=>n.startMs>=first*2000&&n.startMs<(first+8)*2000).map(n=>n.id),svg:4,heads:2048,loadMs:30})),renders:[9,17].map(from=>({method:'render',renderer:'playing',range:`Measures ${from}–${from+7} / 24`,durationMs:200}))};trace.listeningEnded={...trace.current};return{ok:true,origin:'https://wmh.localhost',cleanup:{status:'complete',resources:['context','browser','driver'].map(name=>({name,status:'closed'})),errors:[],writeErrors:[]},locale:'zh-CN',fixture:{source_sha256:sourceSha,fixture:DENSE_STREAM,pages:Array(12).fill({})},trace,metrics:denseTimingMetrics(trace),assessmentRequests:0,results:{historyHidden:true,passOptions:[''],exportDisabled:true,assessmentDisabled:true},actions:Array.from({length:10},()=>({completed:true})),pageErrors:[],claims:{physical_audio:false,synthetic_clock:false,production_behavior_changed:false}};
}
test('dense proof rejects lost processor onsets, stale generations, fake PCM, paused clocks and machine input',()=>{
 const good=syntheticProof();validateDenseRenditionEvidence(good);assert.equal(good.metrics.maxRenderMs,200,'Long measured rendering is reported without being hidden or relabeled');assert.equal(good.metrics.processorStarted,6144);
 for(const change of [r=>delete r.cleanup,r=>r.cleanup.status='pending',r=>r.cleanup.resources[2].status='failed',r=>r.trace.errors.push({code:'audio_processor_error'}),r=>r.trace.audioThread[0].terminals[0].record.ledger.actualStarts.pop(),r=>r.trace.audioThread[0].plan.notes[1][1]=r.trace.audioThread[0].plan.notes[0][1],r=>r.trace.audioThread[0].terminals[0].record.ledger.actualStarts[0]++,r=>r.trace.audioThread[0].terminals[0].record.ledger.actualEnds[0]++,r=>r.trace.audioThread[0].messages[1].generation++,r=>r.trace.audioThread[0].messages[0].isTrusted=false,r=>r.trace.audioThread[0].pcm.blocks[0].peak=0,r=>r.trace.audioThread[0].started.graphToDestination=null,r=>r.trace.scope[1].sourceIds.pop(),r=>r.trace.scope[2].renderer='paused',r=>r.trace.current.captured='1',r=>r.trace.states.push({state:'suspended'}),r=>r.trace.frames[1].audioTime=-1,r=>r.trace.current.renderer='paused',r=>r.trace.audio.activeSources=1,r=>r.trace.cleanup.restored=false,r=>r.assessmentRequests=1,r=>r.metrics.maxRenderMs=0]){const value=structuredClone(good);change(value);assert.throws(()=>validateDenseRenditionEvidence(value));}
 const failed={...good,ok:false,error:'native scheduling sentinel'};assert.throws(()=>validateDenseRenditionEvidence(failed),/native scheduling sentinel/);
 const legacy=structuredClone(good);legacy.trace.version=1;legacy.trace.audio={created:6144,sourceStarts:6144,oscillatorStarts:6144};delete legacy.trace.audioThread;assert.throws(()=>validateDenseRenditionEvidence(legacy),/Legacy main-thread/,'Old 314/317 oscillator traces cannot masquerade as worklet completion');
});
test('dense CI uses the prepared exact-source driver, retains original evidence and refuses local launch',async()=>{
 for(const[name,job]of [['basic-key-preview.yml','basic-key-browser'],['windows-desktop-acceptance.yml','bulk-import-browser']]){const result=spawnSync('python',['scripts/check-authoring-workflow.py','--json',fileURLToPath(new URL(`../.github/workflows/${name}`,import.meta.url))],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);const steps=JSON.parse(result.stdout).jobs[job].steps,run=steps.find(row=>row.run==='node scripts/hosted-dense-rendition-check.mjs');assert.ok(run);assert.equal(run['continue-on-error'],undefined);assert.equal(run.if,"${{ !cancelled() && steps.notation_server.outcome == 'success' && steps.dense_native_driver.outcome == 'success' && steps.dense_browser_setup.outcome == 'success' }}");assert.equal(steps.find(row=>row.id==='dense_native_driver').run,'cargo build -p worldmusichub-desktop --example native_import_driver --locked');assert.equal(steps.find(row=>row.id==='dense_browser_setup').run,'npx playwright install --with-deps chromium');assert.equal(run.env.WMH_SOURCE_SHA,'${{ github.sha }}');assert.equal(run.env.WMH_NATIVE_IMPORT_DRIVER,'${{ github.workspace }}/target/debug/examples/native_import_driver');const artifact=steps.find(row=>row.with?.name==='dense-rendition-browser-${{ github.sha }}');assert.equal(artifact.if,'always()');assert.ok(artifact.with.path.includes('fixture/*'));assert.ok(artifact.with.path.includes('ui-pages/*.json'));assert.ok(!artifact.with.path.includes('Scores'));}
 const script=fileURLToPath(new URL('../scripts/hosted-dense-rendition-check.mjs',import.meta.url)),refused=spawnSync(process.execPath,[script],{env:{...process.env,GITHUB_ACTIONS:'false',WMH_HOSTED_BROWSER:'0'},encoding:'utf8'});assert.equal(refused.status,1);assert.match(refused.stderr,/require the authorized hosted Actions runner/);const source=await readFile(script,'utf8');assert.doesNotMatch(source,/waitForTimeout|lookAheadMs\s*=|transport\.seek|progress[^\n]*\.value\s*=/);
});

test('dense observer attempts all cleanup after listener and receiver failures without replacing the product cause',async()=>{
 const calls=[],fail=name=>{calls.push(name);throw Error(`${name} cleanup failure`);},nodes={progress:{value:10},'clean-song-stage':{dataset:{rendererState:'paused'}},workspace:{dataset:{scoreState:'session'},addEventListener(){},removeEventListener(){fail('scope');}},'engraving-range':{textContent:'Measures 1–8 / 24'},'hud-captured':{textContent:'0'},notice:{textContent:'original product failure'}},context={currentTime:1,state:'running',addEventListener(){},removeEventListener(){fail('context');}};
 class Renderer{load(){}updateGraphic(){}render(){}}
 const originalMethods=[Renderer.prototype.load,Renderer.prototype.updateGraphic,Renderer.prototype.render],requestAnimationFrame=()=>1,realm=vm.createContext({document:{getElementById:id=>nodes[id]},performance,structuredClone,requestAnimationFrame,localStorage:{setItem(){}}});vm.runInContext(`(()=>{${denseRenditionBootstrap()}})();`,realm);
 const productError={code:'audio_processor_error',message:'original product failure'},observeReceiver=async(_,{onContext,onStart})=>{onContext(context);onStart();return{status:()=>({...syntheticAudioThreadStatus(),errors:[productError]}),snapshot:()=>[],count:()=>1,quiet:()=>true,restore:()=>fail('receiver')};};
 const observer=await realm.__wmhDenseObserverTools.install({library:{Renderer,observeReceiver},audioProbe:{snapshot:()=>({}),restore:()=>fail('legacy')}}),trace=observer.stop();
 assert.equal(trace.cleanup.restored,false);assert.equal(trace.cleanup.errors.length,4);assert.deepEqual(calls,['scope','receiver','context','legacy']);assert.deepEqual([Renderer.prototype.load,Renderer.prototype.updateGraphic,Renderer.prototype.render],originalMethods);assert.equal(realm.requestAnimationFrame,requestAnimationFrame);assert.equal(trace.receiver.errors[0].message,'original product failure');
 const report={ok:false,error:'original product failure',trace};await finishDenseReport(report,{resources:['context','browser','driver'].map(name=>({name,present:true,close:async()=>calls.push(name)})),persist:async()=>{},validate(){throw Error('Failed audio cannot pass');}});assert.equal(report.error,'original product failure');assert.equal(report.trace.cleanup.errors.length,4);assert.deepEqual(calls.slice(-3),['context','browser','driver']);
});


test('dense startup failure exposes initialization phase and product notice before any prepared audio row exists',async()=>{
 const nodes={progress:{value:0},'clean-song-stage':{dataset:{rendererState:'ready'}},workspace:{dataset:{scoreState:'inspection'},addEventListener(){},removeEventListener(){}},'engraving-range':{textContent:'Measures 1–8'},'hud-captured':{textContent:'0'},notice:{textContent:'Actual startup module failure'}};
 class Receiver{static create(){return Promise.reject(Object.assign(new Error('Module import failed'),{code:'audio_worklet_unavailable',details:{phase:'module-load',causeName:'AbortError',causeMessage:'Underlying loader rejection'}}));}prepare(){}start(){}}
 class Renderer{load(){}updateGraphic(){}render(){}}
 const realm=vm.createContext({document:{getElementById:id=>nodes[id]},performance,structuredClone,Float32Array,localStorage:{setItem(){}}});vm.runInContext(`(()=>{${denseRenditionBootstrap()}})();`,realm);
 const original=Receiver.create,observer=await realm.__wmhDenseObserverTools.install({library:{BasicKeyAudioReceiver:Receiver,Renderer},audioProbe:{snapshot:()=>({}),restore:()=>true}});await assert.rejects(Receiver.create({state:'running'},{}),/Module import failed/);
 const status=observer.status();assert.equal(status.schedules,0);assert.equal(status.current.position,0);assert.equal(status.errors[0].details.phase,'module-load');assert.equal(status.errors[0].details.causeMessage,'Underlying loader rejection');assert.equal(status.current.notice,'Actual startup module failure');assert.equal(observer.snapshot().receiver.initializations[0].ok,false);assert.equal(observer.stop().cleanup.restored,true);assert.equal(Receiver.create,original);
 const host=await readFile(new URL('../scripts/hosted-dense-rendition-check.mjs',import.meta.url),'utf8');assert.match(host,/Actual audio failure:/);assert.match(host,/Production UI: '\+status.current.notice/);
});
