import test from 'node:test';
import assert from 'node:assert/strict';
import {PIANO_RANGES, keyboardGeometry, jianpu, pitchMidi, midiName, transposeTempo, renderNotation, fretPositions} from '../web/music.js';
import {Transport, Synth} from '../web/transport.js';

import {fixture} from './frontend-fixtures.js';

test('all keyboard ranges contain exact MIDI endpoints and bounded geometry', () => {
 for (const [count, endpoints] of Object.entries(PIANO_RANGES)) { const keys=keyboardGeometry(count); assert.equal(keys.length,Number(count)); assert.equal(keys[0].midi,endpoints[0]); assert.equal(keys.at(-1).midi,endpoints[1]); assert.ok(keys.every(k => k.x >= 0 && k.x + k.width <= 1.000001)); }
});
test('pitch spelling and fixed-C jianpu retain accidentals and octave information', () => {
 assert.equal(pitchMidi({step:'B',alter:-1,octave:3}),58); assert.equal(midiName(60),'C4'); assert.deepEqual(jianpu({step:'D',alter:1,octave:5}),{number:'2',accidental:'♯',octave:1}); assert.equal(jianpu(null).number,'0');
});
test('tempo change preserves relative tempo map and leaves source untouched', () => {
 const score=structuredClone(fixture); score.tempo.push({at:{numerator:4,denominator:1},bpm:60}); const modified=transposeTempo(score,90); assert.deepEqual(modified.tempo.map(t=>t.bpm),[90,45]); assert.equal(score.tempo[0].bpm,120);
});
test('notation escapes all score-provided SVG text and note identifiers', () => {
 const score=structuredClone(fixture); score.parts[0].name='<script>bad()</script>'; score.parts[0].notes[0].id='" onload="bad'; const svg=renderNotation(score); assert.ok(svg.includes('&lt;script&gt;')); assert.ok(!svg.includes('<script>')); assert.ok(svg.includes('&quot; onload=&quot;')); assert.ok(renderNotation(score,'jianpu').includes('Fixed C numbered pitch view'));
});
test('guitar options never invent frets outside instrument range', () => { assert.deepEqual(fretPositions(40),[{string:5,fret:0}]); assert.equal(fretPositions(90).length,0); assert.ok(fretPositions(64).every(p=>p.fret>=0&&p.fret<=12)); });
const notes=[{id:'one',start_ms:0,duration_ms:500},{id:'two',start_ms:500,duration_ms:500}];
test('transport count-in schedules exactly once, then resumes a sustained note', () => {
 const t=new Transport(); t.start(1000,notes,1000); assert.equal(t.time(1000),-1000); assert.deepEqual(t.due(1000,notes),[]); assert.equal(t.due(1950,notes)[0].delay_ms,50); assert.equal(t.due(1950,notes).length,0); t.pause(2200); assert.equal(t.position,200); t.start(5000,notes); const due=t.due(5000,notes); assert.equal(due.length,1); assert.equal(due[0].remaining_ms,300); assert.equal(t.time(5100),300);
});
test('transport repeated starts, reset and completion cannot accumulate clock drift', () => {
 const t=new Transport(); t.start(0,notes); t.start(50,notes); assert.equal(t.time(100),100); t.finish(1000); assert.equal(t.running,false); t.start(1200,notes); assert.equal(t.time(1200),0); t.reset(); assert.equal(t.position,0); assert.equal(t.cursor,0);
});
test('synth is silent until user gesture unlock and silence cancels all scheduled voices', async () => {
 const calls=[]; class Param {setValueAtTime(...a){calls.push(['value',...a])}linearRampToValueAtTime(){}exponentialRampToValueAtTime(){}setTargetAtTime(){}cancelScheduledValues(){calls.push(['cancel'])}}
 class Audio {state='running';currentTime=2;destination={};createGain(){return{gain:new Param(),connect(){},disconnect(){}}}createOscillator(){return{frequency:{},connect(){},disconnect(){},start(at){calls.push(['start',at])},stop(at){calls.push(['stop',at])}}}}
 const old=globalThis.AudioContext; globalThis.AudioContext=Audio; try {const synth=new Synth();synth.play('a',60);assert.equal(calls.length,0);await synth.unlock();synth.play('a',60,1000,500);synth.play('b',64,null);assert.equal(synth.voices.size,2);synth.silence();assert.equal(synth.voices.size,0);assert.equal(calls.filter(x=>x[0]==='cancel').length,2);assert.ok(calls.some(x=>x[0]==='stop'&&x[1]===2));}finally{globalThis.AudioContext=old}
});

import {validHex, validTheme, isDark} from '../web/themes.js';
import {parsePitch, reviewedScore} from '../web/image-review.js';
import {decodeMidi} from '../web/midi.js';
test('theme configuration rejects arbitrary CSS and falls back for corrupt storage', () => { assert.equal(validHex('url(https://bad)'),false);assert.equal(validHex('#aAbBcC'),true);assert.equal(validTheme({mode:'custom',accent:'red',background:'#111111'}).accent,'#326b4c');assert.equal(validTheme(null).mode,'system');assert.equal(isDark('#111111'),true);assert.equal(isDark('#ffffff'),false); });
test('review editor requires manually confirmed timing and validates pitch range', () => {assert.deepEqual(parsePitch('Bb3'),{step:'B',alter:-1,octave:3});assert.throws(()=>parsePitch('<script>'));assert.throws(()=>parsePitch('G#9'));assert.throws(()=>reviewedScore({title:'test',rows:[{pitch:'C4',duration:''}],filename:'example.png',originalImage:'data:',review:null,crop:null}),/duration/);});
test('image review preserves source, manual durations, rests and exact rational time', () => {const rows=[{pitch:'C4',duration:'0.5'},{pitch:'F#4',duration:'1'},{pitch:'0',duration:'0.25'}];const score=reviewedScore({title:'Reviewed',rows,filename:'notes.png',originalImage:'data:image/png;base64,original',review:{requires_review:true},crop:{x:0,y:0,width:10,height:20}});assert.deepEqual(score.parts[0].notes[1].at,{numerator:2,denominator:4});assert.equal(score.parts[0].notes[2].pitch,null);assert.equal(score.provenance.kind,'user_reviewed_image');assert.equal(JSON.parse(score.source.content).original_image_data_url,'data:image/png;base64,original');assert.deepEqual(JSON.parse(score.source.content).manual_notes,rows);});
test('MIDI parser handles note-off, zero-velocity note-on and rejects non-note messages', () => {assert.deepEqual(decodeMidi([0x92,64,90]),{kind:'on',channel:2,midi:64,velocity:90});assert.equal(decodeMidi([0x90,60,0]).kind,'off');assert.equal(decodeMidi([0x80,60,40]).kind,'off');assert.equal(decodeMidi([0xb0,64,127]),null);assert.equal(decodeMidi([0x90,129,100]),null);assert.equal(decodeMidi([0xf8]),null);});

import {notationPageCount} from '../web/music.js';
import {TimelineIndex} from '../web/transport.js';
test('notation windows keep huge or sparse score geometry bounded and preserve later pages', () => {const score=structuredClone(fixture);score.parts[0].notes[1].at={numerator:1000000,denominator:1};const svg=renderNotation(score);assert.ok(svg.length<4000);assert.ok(!svg.includes('data-note-id="e4"'));assert.equal(notationPageCount(score),62501);const later=renderNotation(score,'jianpu',{startBeat:1000000});assert.ok(later.includes('data-note-id="e4"'));assert.ok(!later.includes('data-note-id="c4"'));});
test('timeline index includes long overlapping sustains, chords, and exact note boundaries', () => {const notes=[{id:'long',start_ms:0,duration_ms:5000},{id:'a',start_ms:0,duration_ms:500},{id:'b',start_ms:500,duration_ms:500},{id:'c',start_ms:500,duration_ms:250},{id:'late',start_ms:2000,duration_ms:500}];const index=new TimelineIndex(notes);assert.deepEqual(index.range(500).map(n=>n.id),['long','b','c']);assert.deepEqual(index.range(1000,2100).map(n=>n.id),['long','late']);assert.deepEqual(index.range(5000),[]);});
test('timeline index matches a full scan over dense mixed-duration notes', () => {const notes=Array.from({length:10000},(_,i)=>({id:String(i),start_ms:i*8,duration_ms:50+(i%19)*10}));const index=new TimelineIndex(notes);for(let time=0;time<80000;time+=733){assert.deepEqual(index.range(time,time+1000).map(n=>n.id),notes.filter(n=>n.start_ms<=time+1000&&n.start_ms+n.duration_ms>time).map(n=>n.id));}});

import {keyTonic, keyAt} from '../web/music.js';
import {compensateInput, validLatency, parseBeatInput, windowNotes} from '../web/practice-settings.js';
test('latency offset is bounded, signed and never silently clamps early input', () => {assert.equal(compensateInput(120,80),40);assert.equal(compensateInput(20,80),-60);assert.equal(compensateInput(20,-80),100);assert.equal(validLatency(''),false);assert.equal(validLatency(null),false);assert.equal(validLatency(500),true);assert.equal(validLatency(500.1),false);assert.throws(()=>compensateInput(100,501));});
test('practice beat fields preserve fractions and reject ambiguous/oversized values', () => {assert.deepEqual(parseBeatInput('3/2'),{numerator:3,denominator:2});assert.deepEqual(parseBeatInput('1.25'),{numerator:125,denominator:100});assert.deepEqual(parseBeatInput('0'),{numerator:0,denominator:1});for(const invalid of ['1/0','-1','one','1e5','1.1234567','1000000001',''])assert.throws(()=>parseBeatInput(invalid));});
test('loop note clipping resumes crossing sustains but does not mutate canonical notes', () => {const notes=[{id:'cross',start_ms:100,duration_ms:600},{id:'inside',start_ms:400,duration_ms:200},{id:'after',start_ms:800,duration_ms:100}];const clipped=windowNotes(notes,300,500);assert.deepEqual(clipped.map(n=>[n.id,n.start_ms,n.duration_ms]),[['cross',300,200],['inside',400,100]]);assert.equal(notes[0].start_ms,100);assert.equal(notes[0].duration_ms,600);});
test('transport seeks a nonzero loop start, counts in once and repeats without accumulated drift', () => {const t=new Transport();const notes=[{id:'loop',start_ms:2000,duration_ms:500}];t.seek(2000);t.start(1000,notes,1000);assert.equal(t.time(1000),1000);assert.equal(t.due(1950,notes)[0].delay_ms,50);t.pause(2100);t.start(3000,notes,1000);assert.equal(t.time(3000),2100);t.seek(2000);t.start(9000,notes,0);assert.equal(t.time(9000),2000);assert.equal(t.due(9000,notes).length,1);});
test('movable tonic numbering preserves sharps, flats, minor scale and octave relation', () => {const g={fifths:1,mode:'major'};assert.equal(keyTonic(g).name,'G');assert.deepEqual(jianpu({step:'F',alter:1,octave:4},g),{number:'7',accidental:'',octave:-1});assert.deepEqual(jianpu({step:'F',alter:0,octave:4},g),{number:'7',accidental:'♭',octave:-1});assert.deepEqual(jianpu({step:'C',alter:0,octave:5},{fifths:0,mode:'minor'}),{number:'3',accidental:'',octave:0});assert.deepEqual(jianpu({step:'B',alter:-1,octave:4},{fifths:-2,mode:'major'}),{number:'1',accidental:'',octave:0});assert.equal(keyTonic({fifths:1,mode:'dorian'}),null);});
test('key changes select the correct reference and render explicit tonic labels', () => {const score=structuredClone(fixture);score.keys.push({at:{numerator:1,denominator:1},fifths:1,mode:'major'});assert.equal(keyAt(score,0).fifths,0);assert.equal(keyAt(score,1).fifths,1);const svg=renderNotation(score,'jianpu',{numberedMode:'movable'});assert.ok(svg.includes('1 = C4 (major)'));assert.ok(svg.includes('1 = G4 (major)'));assert.ok(svg.includes('Movable tonic numbered pitch view'));});

import {parseTuning, guitarProfile, pianoProfile} from '../web/instrument-profile.js';
test('custom keyboard geometry includes black boundary notes without clipping', () => {for(const count of [12,13,25,61,128])for(const low of [0,1,13,36,61]){if(low+count>128)continue;const keys=keyboardGeometry(count,low);assert.equal(keys.length,count);assert.equal(keys[0].midi,low);assert.equal(keys.at(-1).midi,low+count-1);assert.ok(keys.every(key=>key.x>=0&&key.x+key.width<=1.000001));}assert.throws(()=>keyboardGeometry(88,60));});
test('instrument profile fields keep explicit pitch/tuning rather than silently transposing', () => {assert.deepEqual(parseTuning('E4 B3 G3 D3 A2 D2'),[64,59,55,50,45,38]);assert.deepEqual(pianoProfile('25','C#4'),{kind:'piano',key_count:25,lowest_midi:61});assert.deepEqual(guitarProfile('E4, B3, G3, D3, A2, E2','24','2'),{kind:'guitar',tuning:[64,59,55,50,45,40],frets:24,capo:2});assert.throws(()=>pianoProfile(128,'C4'));assert.throws(()=>guitarProfile('E4 B3',12,13));assert.throws(()=>parseTuning(''));});
test('synth uses actual MIDI velocity and caps overlapping preview voices',async()=>{const peaks=[];class Audio{state='running';currentTime=0;destination={};createGain(){return{gain:{value:0,setValueAtTime(){},linearRampToValueAtTime(v){peaks.push(v)},exponentialRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}},connect(){},disconnect(){}}}createOscillator(){return{frequency:{},connect(){},disconnect(){},start(){},stop(){}}}}const previous=globalThis.AudioContext;globalThis.AudioContext=Audio;try{const synth=new Synth();await synth.unlock();synth.play('soft',60,null,0,'piano',30);synth.play('loud',60,null,0,'piano',120);assert.ok(peaks[1]>peaks[0]*4);synth.play('silent',60,null,0,'piano',0);assert.equal(synth.voices.has('silent'),false);for(let i=0;i<100;i++)synth.play(`dense-${i}`,60);assert.equal(synth.voices.size,64);assert.ok(synth.droppedVoices>0);synth.silence();assert.equal(synth.voices.size,0);}finally{globalThis.AudioContext=previous}});
