import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './frontend-fixtures.js';
import {NotationNavigationIndex,sourceMeasurePage,setupNotationFollowing} from '../web/notation-follow.js';
function setup(){
 const score=structuredClone(fixture);score.measures=[7,7,19,0].map((number,index)=>({number,at:{numerator:index,denominator:1},length:{numerator:1,denominator:1}}));score.parts[0].notes.push({id:'rest',pitch:null,at:{numerator:2,denominator:1},duration:{numerator:1,denominator:1}});score.repeats=[{from:{numerator:1,denominator:1},to:{numerator:3,denominator:1},times:2}];
 const notes=[['attack-0','c4',0],['attack-1','e4',500],['attack-2','e4',1500]].map(([id,source,start_ms])=>({id,source_note_id:source,source_note_ids:[source],part_id:'piano',start_ms,duration_ms:500}));const timeline={notes,duration_ms:3000};
 const occurrences=[0,1,2,1,2,3].map((index,position)=>({id:`m-${position}`,source_measure_index:index,measure_number:score.measures[index].number,source_from:score.measures[index].at,source_to:{numerator:index+1,denominator:1},start_ms:position*500,end_ms:(position+1)*500,repeat_region_index:position>0&&position<5?0:null,repeat_pass:position>0&&position<5?position<3?1:2:null,repeat_times:position>0&&position<5?2:null,written_note_ids:index===0?['c4']:index===1?['e4']:index===2?['rest']:[],continuing_note_ids:[]}));
 return{score,timeline,response:{version:1,source_measure_count:4,duration_ms:3000,occurrences,sounding_groups:notes.map(note=>({occurrence_id:note.id,part_id:note.part_id,source_note_ids:note.source_note_ids,start_ms:note.start_ms,end_ms:note.start_ms+note.duration_ms})),diagnostics:[]}};
}
test('Rust occurrence lookup uses half-open boundaries through duplicate labels, repeat passes and rests',()=>{const{score,timeline,response}=setup(),before=JSON.stringify({score,timeline,response}),index=new NotationNavigationIndex(response,score,timeline);assert.equal(index.at(-1),null);assert.equal(index.at(0).source_measure_index,0);assert.equal(index.at(499.999).repeat_pass,null);assert.equal(index.at(500).source_measure_index,1);assert.equal(index.at(1000).written_note_ids[0],'rest');assert.equal(index.at(1500).source_measure_index,1);assert.equal(index.at(1500).repeat_pass,2);assert.equal(index.at(2999).measure_number,0);for(const value of [3000,3001,Infinity,NaN])assert.equal(index.at(value),null);assert.equal(index.soundingGroups.get('attack-2').source_note_ids[0],'e4');assert.equal(index.sourceNotes.get('rest').note.pitch,null);assert.equal(JSON.stringify({score,timeline,response}),before);});
test('source measure paging uses ordinal indices rather than printed labels and is bounded',()=>{assert.equal(sourceMeasurePage(0,8),1);assert.equal(sourceMeasurePage(7,8),1);assert.equal(sourceMeasurePage(8,8),9);assert.equal(sourceMeasurePage(31,16),17);for(const[index,size]of[[-1,8],[0,0],[1,65],[1.5,8]])assert.throws(()=>sourceMeasurePage(index,size));});
test('navigation schema, source identities, repeat metadata and compiled tie identities must agree before following',()=>{for(const mutate of[r=>r.version=2,r=>r.source_measure_count=5,r=>r.duration_ms=2999,r=>r.occurrences[1].start_ms=501,r=>r.occurrences[1].measure_number=8,r=>r.occurrences[1].repeat_pass=3,r=>r.occurrences[1].repeat_region_index=1,r=>r.occurrences[0].written_note_ids=['unknown'],r=>r.occurrences[0].written_note_ids=['e4'],r=>r.occurrences[0].source_to={numerator:2,denominator:1},r=>r.occurrences[0].continuing_note_ids=['c4'],r=>r.sounding_groups[0].source_note_ids=['e4'],r=>r.sounding_groups[0].end_ms=501]){const{score,timeline,response}=setup();mutate(response);assert.throws(()=>new NotationNavigationIndex(response,score,timeline),/does not match/)}});
function environment(){const prior={document:globalThis.document,window:globalThis.window},checkbox={checked:false,addEventListener(_,handler){this.change=handler}},status={textContent:'',setAttribute(){}},calls=[],pages=[];let context=setup(),playback={position:1500,running:true};const view={isActive:()=>true,followMeasure:index=>pages.push(index),navigationState:()=>({ready:true})};globalThis.document={getElementById:id=>id==='engraving-follow'?checkbox:status};globalThis.window={addEventListener(){}};const follow=setupNotationFollowing({api:()=>new Promise((resolve,reject)=>calls.push({resolve,reject})),getContext:()=>context,getPlayback:()=>playback,view});return{follow,checkbox,status,calls,pages,context,setContext:value=>context=value,setPlayback:value=>playback=value,restore(){follow.suspend();for(const[key,value]of Object.entries(prior))if(value===undefined)delete globalThis[key];else globalThis[key]=value}}}
test('following is opt-in, reuses a validated response, and manual suspension prevents late activation',async()=>{const env=environment();try{assert.equal(env.calls.length,0);env.checkbox.checked=true;const pending=env.checkbox.change();env.follow.suspend();env.calls[0].resolve(env.context.response);await pending;assert.equal(env.pages.length,0);assert.equal(env.checkbox.checked,false);env.checkbox.checked=true;const ready=env.checkbox.change();env.calls[1].resolve(env.context.response);await ready;assert.equal(env.pages.at(-1),1);assert.match(env.status.textContent,/pass 2\/2/);env.follow.suspend();env.checkbox.checked=true;await env.checkbox.change();assert.equal(env.calls.length,2);env.follow.tick(3000,false);assert.match(env.status.textContent,/End of performance/);env.follow.tick(-1,true);assert.match(env.status.textContent,/Count-in/);}finally{env.restore()}});
test('replacement or failed preparation disables only optional following',async()=>{const env=environment();try{env.checkbox.checked=true;const pending=env.checkbox.change();env.follow.scoreChanged();env.setContext(setup());env.calls[0].resolve(env.context.response);await pending;assert.equal(env.pages.length,0);env.checkbox.checked=true;const failing=env.checkbox.change();env.calls[1].reject(Error('No complete measure map'));await failing;assert.equal(env.checkbox.checked,false);assert.match(env.status.textContent,/No complete measure map/);assert.match(env.status.textContent,/playback is unchanged/);assert.equal(env.pages.length,0);}finally{env.restore()}});
