import test from 'node:test';
import assert from 'node:assert/strict';
import {sourceCheckSummary,setupSourceArchiveView} from '../web/source-archive-view.js';
const file={filename:'original.xml',declaredSha256:null,declaredBytes:null};
const result={filename:file.filename,mime:'application/octet-stream',bytes:new Uint8Array([0,1,2]),sha256:'a'.repeat(64),checksumMatches:null,sizeMatches:null};
test('source comparisons keep unknown, matching and mismatched declarations distinct',()=>{let summary=sourceCheckSummary(file,result);assert.match(summary.hash,/Unknown: no declared/);assert.match(summary.size,/Unknown/);assert.equal(summary.mismatch,false);assert.equal(summary.computedHash,result.sha256);summary=sourceCheckSummary({...file,declaredSha256:'b'.repeat(64),declaredBytes:4},{...result,checksumMatches:false,sizeMatches:false});assert.equal(summary.mismatch,true);assert.match(summary.hash,/Mismatch/);assert.equal(summary.computedBytes,'3');summary=sourceCheckSummary({...file,declaredSha256:result.sha256,declaredBytes:3},{...result,checksumMatches:true,sizeMatches:true});assert.match(summary.hash,/matches/);assert.match(summary.size,/matches/);assert.equal(summary.mismatch,false);assert.match(sourceCheckSummary(file,{...result,sha256:null}).hash,/unavailable/);});
class Element{constructor(){this.children=[];this.dataset={};this.listeners={};this.attributes={};this.classList={toggle(){}};this.open=false;this.disabled=false;this.textContent='';}append(...values){this.children.push(...values)}replaceChildren(...values){this.children=[...values]}setAttribute(key,value){this.attributes[key]=String(value)}addEventListener(name,handler){this.listeners[name]=handler}querySelectorAll(name){return this.children.flatMap(child=>[...(child.tagName===name?[child]:[]),...(child.querySelectorAll?.(name)||[])])}showModal(){this.open=true}close(){this.open=false}click(){if(!this.disabled)return this.listeners.click?.()}}
function environment(){const prior={document:globalThis.document,window:globalThis.window},nodes=new Map(),requests=[];let context={score:{title:'Original',source:{format:'musicxml',filename:'original.xml',content:'\uFEFF<score/>\r\n'}},version:1},pauses=0;const node=id=>{if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id)};globalThis.document={getElementById:node,createElement:tagName=>{const element=new Element();element.tagName=tagName;return element},body:{append(dialog){nodes.set(dialog.id,dialog)}}};globalThis.window={addEventListener(){}};const view=setupSourceArchiveView({getContext:()=>context,pausePlayback:()=>pauses++,inspectFile:file=>new Promise(resolve=>requests.push({file,resolve}))});return{nodes,requests,view,node,get pauses(){return pauses},get context(){return context},setContext:value=>context=value,firstButton:()=>node('source-archive-files').children[0].children[1],restore(){view.close();for(const[key,value]of Object.entries(prior))if(value===undefined)delete globalThis[key];else globalThis[key]=value}}}
test('closing the retained-source view ignores a late digest and never prepares a hidden download',async()=>{const env=environment();try{env.node('source-files-button').click();assert.equal(env.pauses,1);const pending=env.firstButton().click();assert.equal(env.requests.length,1);assert.equal(env.firstButton().disabled,true);env.node('source-archive-close').click();env.requests[0].resolve(result);await pending;assert.equal(env.node('source-archive-dialog').open,false);assert.equal(env.node('source-archive-download').disabled,true);assert.equal(env.node('source-archive-inspection').hidden,true);}finally{env.restore()}});
test('source replacement and refresh discard old inspection bytes and permit only the new file',async()=>{const env=environment();try{env.node('source-files-button').click();const old=env.firstButton().click();env.setContext({score:{title:'New',source:{format:'musicxml',filename:'new.xml',content:'<new/>'}},version:2});env.view.scoreChanged();assert.match(env.node('source-archive-status').textContent,/loaded score changed/);env.node('source-archive-refresh').click();assert.equal(env.firstButton().disabled,true);env.requests[0].resolve(result);await old;assert.equal(env.node('source-archive-download').disabled,true);assert.equal(env.firstButton().disabled,false);assert.match(env.node('source-archive-status').textContent,/Cancelled inspection discarded/);const current=env.firstButton().click();assert.equal(env.requests[1].file.filename,'new.xml');env.requests[1].resolve({...result,filename:'new.xml'});await current;assert.equal(env.node('source-archive-selected').textContent,'new.xml');assert.equal(env.node('source-archive-download').disabled,false);env.setContext({...env.context,version:3});env.node('source-archive-download').click();assert.match(env.node('source-archive-status').textContent,/No file was downloaded/);assert.equal(env.node('source-archive-download').disabled,true);}finally{env.restore()}});
test('an inconsistent inspection result cannot prepare another file under the selected label',async()=>{const env=environment();try{env.node('source-files-button').click();const pending=env.firstButton().click();env.requests[0].resolve({...result,filename:'different.xml'});await pending;assert.match(env.node('source-archive-status').textContent,/unexpected file data/);assert.equal(env.node('source-archive-download').disabled,true);}finally{env.restore()}});
