import test from 'node:test';
import assert from 'node:assert/strict';
import {PIANO_RANGES, keyboardGeometry, jianpu, pitchMidi, midiName, transposeTempo, renderNotation, fretPositions} from '../web/music.js';
import {Transport, Synth} from '../web/transport.js';

import {fixture} from './frontend-fixtures.js';

test('all keyboard ranges contain exact MIDI endpoints and bounded geometry', () => {
 for (const [count, endpoints] of Object.entries(PIANO_RANGES)) { const keys=keyboardGeometry(count); assert.equal(keys.length,Number(count)); assert.equal(keys[0].midi,endpoints[0]); assert.equal(keys.at(-1).midi,endpoints[1]); assert.ok(keys.every(k => k.x >= 0 && k.x + k.width <= 1.000001)); }
});
test('pitch spelling and fixed-C jianpu retain accidentals and octave information', () => {
 assert.equal(pitchMidi({step:'B',alter:-1,octave:3}),58); assert.equal(midiName(60),'C4'); assert.deepEqual(jianpu({step:'D',alter:1,octave:5}),{number:'2',accidental:'♯',octave:1}); assert.equal(jianpu(null).number,'0');
});
test('tempo change preserves relative tempo map and leaves source untouched', () => {
 const score=structuredClone(fixture); score.tempo.push({at:{numerator:4,denominator:1},bpm:60}); const modified=transposeTempo(score,90); assert.deepEqual(modified.tempo.map(t=>t.bpm),[90,45]); assert.equal(score.tempo[0].bpm,120);
});
test('notation escapes all score-provided SVG text and note identifiers', () => {
 const score=structuredClone(fixture); score.parts[0].name='<script>bad()</script>'; score.parts[0].notes[0].id='" onload="bad'; const svg=renderNotation(score); assert.ok(svg.includes('&lt;script&gt;')); assert.ok(!svg.includes('<script>')); assert.ok(svg.includes('&quot; onload=&quot;')); assert.ok(renderNotation(score,'jianpu').includes('Fixed C numbered pitch view'));
});
test('guitar options never invent frets outside instrument range', () => { assert.deepEqual(fretPositions(40),[{string:5,fret:0}]); assert.equal(fretPositions(90).length,0); assert.ok(fretPositions(64).every(p=>p.fret>=0&&p.fret<=12)); });
const notes=[{id:'one',start_ms:0,duration_ms:500},{id:'two',start_ms:500,duration_ms:500}];
test('transport count-in schedules exactly once, then resumes a sustained note', () => {
 const t=new Transport(); t.start(1000,notes,1000); assert.equal(t.time(1000),-1000); assert.deepEqual(t.due(1000,notes),[]); assert.equal(t.due(1950,notes)[0].delay_ms,50); assert.equal(t.due(1950,notes).length,0); t.pause(2200); assert.equal(t.position,200); t.start(5000,notes); const due=t.due(5000,notes); assert.equal(due.length,1); assert.equal(due[0].remaining_ms,300); assert.equal(t.time(5100),300);
});
test('transport repeated starts, reset and completion cannot accumulate clock drift', () => {
 const t=new Transport(); t.start(0,notes); t.start(50,notes); assert.equal(t.time(100),100); t.finish(1000); assert.equal(t.running,false); t.start(1200,notes); assert.equal(t.time(1200),0); t.reset(); assert.equal(t.position,0); assert.equal(t.cursor,0);
});
test('synth is silent until user gesture unlock and silence cancels all scheduled voices', async () => {
 const calls=[]; class Param {setValueAtTime(...a){calls.push(['value',...a])}linearRampToValueAtTime(){}exponentialRampToValueAtTime(){}setTargetAtTime(){}cancelScheduledValues(){calls.push(['cancel'])}}
 class Audio {state='running';currentTime=2;destination={};createGain(){return{gain:new Param(),connect(){},disconnect(){}}}createOscillator(){return{frequency:{},connect(){},disconnect(){},start(at){calls.push(['start',at])},stop(at){calls.push(['stop',at])}}}}
 const old=globalThis.AudioContext; globalThis.AudioContext=Audio; try {const synth=new Synth();synth.play('a',60);assert.equal(calls.length,0);await synth.unlock();synth.play('a',60,1000,500);synth.play('b',64,null);assert.equal(synth.voices.size,2);synth.silence();assert.equal(synth.voices.size,0);assert.equal(calls.filter(x=>x[0]==='cancel').length,2);assert.ok(calls.some(x=>x[0]==='stop'&&x[1]===2));}finally{globalThis.AudioContext=old}
});

import {validHex, validTheme, isDark} from '../web/themes.js';
import {parsePitch, reviewedScore} from '../web/image-review.js';
import {decodeMidi} from '../web/midi.js';
test('theme configuration rejects arbitrary CSS and falls back for corrupt storage', () => { assert.equal(validHex('url(https://bad)'),false);assert.equal(validHex('#aAbBcC'),true);assert.equal(validTheme({mode:'custom',accent:'red',background:'#111111'}).accent,'#326b4c');assert.equal(validTheme(null).mode,'system');assert.equal(isDark('#111111'),true);assert.equal(isDark('#ffffff'),false); });
test('review editor requires manually confirmed timing and validates pitch range', () => {assert.deepEqual(parsePitch('Bb3'),{step:'B',alter:-1,octave:3});assert.throws(()=>parsePitch('<script>'));assert.throws(()=>parsePitch('G#9'));assert.throws(()=>reviewedScore({title:'test',rows:[{pitch:'C4',duration:''}],filename:'example.png',originalImage:'data:',review:null,crop:null}),/duration/);});
test('image review preserves source, manual durations, rests and exact rational time', () => {const rows=[{pitch:'C4',duration:'0.5'},{pitch:'F#4',duration:'1'},{pitch:'0',duration:'0.25'}];const score=reviewedScore({title:'Reviewed',rows,filename:'notes.png',originalImage:'data:image/png;base64,original',review:{requires_review:true},crop:{x:0,y:0,width:10,height:20}});assert.deepEqual(score.parts[0].notes[1].at,{numerator:1,denominator:2});assert.equal(score.parts[0].notes[2].pitch,null);assert.equal(score.provenance.kind,'user_reviewed_image');assert.equal(JSON.parse(score.source.content).original_image_data_url,'data:image/png;base64,original');assert.deepEqual(JSON.parse(score.source.content).manual_notes,rows);});
test('MIDI parser handles note-off, zero-velocity note-on and rejects non-note messages', () => {assert.deepEqual(decodeMidi([0x92,64,90]),{kind:'on',channel:2,midi:64,velocity:90});assert.equal(decodeMidi([0x90,60,0]).kind,'off');assert.equal(decodeMidi([0x80,60,40]).kind,'off');assert.equal(decodeMidi([0xb0,64,127]),null);assert.equal(decodeMidi([0x90,129,100]),null);assert.equal(decodeMidi([0xf8]),null);});

import {notationPageCount} from '../web/music.js';
import {TimelineIndex} from '../web/transport.js';
test('notation windows keep huge or sparse score geometry bounded and preserve later pages', () => {const score=structuredClone(fixture);score.parts[0].notes[1].at={numerator:1000000,denominator:1};const svg=renderNotation(score);assert.ok(svg.length<4000);assert.ok(!svg.includes('data-note-id="e4"'));assert.equal(notationPageCount(score),62501);const later=renderNotation(score,'jianpu',{startBeat:1000000});assert.ok(later.includes('data-note-id="e4"'));assert.ok(!later.includes('data-note-id="c4"'));});
test('timeline index includes long overlapping sustains, chords, and exact note boundaries', () => {const notes=[{id:'long',start_ms:0,duration_ms:5000},{id:'a',start_ms:0,duration_ms:500},{id:'b',start_ms:500,duration_ms:500},{id:'c',start_ms:500,duration_ms:250},{id:'late',start_ms:2000,duration_ms:500}];const index=new TimelineIndex(notes);assert.deepEqual(index.range(500).map(n=>n.id),['long','b','c']);assert.deepEqual(index.range(1000,2100).map(n=>n.id),['long','late']);assert.deepEqual(index.range(5000),[]);});
test('timeline index matches a full scan over dense mixed-duration notes', () => {const notes=Array.from({length:10000},(_,i)=>({id:String(i),start_ms:i*8,duration_ms:50+(i%19)*10}));const index=new TimelineIndex(notes);for(let time=0;time<80000;time+=733){assert.deepEqual(index.range(time,time+1000).map(n=>n.id),notes.filter(n=>n.start_ms<=time+1000&&n.start_ms+n.duration_ms>time).map(n=>n.id));}});

import {keyTonic, keyAt} from '../web/music.js';
import {compensateInput, validLatency, parseBeatInput, windowNotes} from '../web/practice-settings.js';
test('latency offset is bounded, signed and never silently clamps early input', () => {assert.equal(compensateInput(120,80),40);assert.equal(compensateInput(20,80),-60);assert.equal(compensateInput(20,-80),100);assert.equal(validLatency(''),false);assert.equal(validLatency(null),false);assert.equal(validLatency(500),true);assert.equal(validLatency(500.1),false);assert.throws(()=>compensateInput(100,501));});
test('practice beat fields preserve fractions and reject ambiguous/oversized values', () => {assert.deepEqual(parseBeatInput('3/2'),{numerator:3,denominator:2});assert.deepEqual(parseBeatInput('1.25'),{numerator:125,denominator:100});assert.deepEqual(parseBeatInput('0'),{numerator:0,denominator:1});for(const invalid of ['1/0','-1','one','1e5','1.1234567','1000000001',''])assert.throws(()=>parseBeatInput(invalid));});
test('loop note clipping resumes crossing sustains but does not mutate canonical notes', () => {const notes=[{id:'cross',start_ms:100,duration_ms:600},{id:'inside',start_ms:400,duration_ms:200},{id:'after',start_ms:800,duration_ms:100}];const clipped=windowNotes(notes,300,500);assert.deepEqual(clipped.map(n=>[n.id,n.start_ms,n.duration_ms]),[['cross',300,200],['inside',400,100]]);assert.equal(notes[0].start_ms,100);assert.equal(notes[0].duration_ms,600);});
test('transport seeks a nonzero loop start, counts in once and repeats without accumulated drift', () => {const t=new Transport();const notes=[{id:'loop',start_ms:2000,duration_ms:500}];t.seek(2000);t.start(1000,notes,1000);assert.equal(t.time(1000),1000);assert.equal(t.due(1950,notes)[0].delay_ms,50);t.pause(2100);t.start(3000,notes,1000);assert.equal(t.time(3000),2100);t.seek(2000);t.start(9000,notes,0);assert.equal(t.time(9000),2000);assert.equal(t.due(9000,notes).length,1);});
test('movable tonic numbering preserves sharps, flats, minor scale and octave relation', () => {const g={fifths:1,mode:'major'};assert.equal(keyTonic(g).name,'G');assert.deepEqual(jianpu({step:'F',alter:1,octave:4},g),{number:'7',accidental:'',octave:-1});assert.deepEqual(jianpu({step:'F',alter:0,octave:4},g),{number:'7',accidental:'♭',octave:-1});assert.deepEqual(jianpu({step:'C',alter:0,octave:5},{fifths:0,mode:'minor'}),{number:'3',accidental:'',octave:0});assert.deepEqual(jianpu({step:'B',alter:-1,octave:4},{fifths:-2,mode:'major'}),{number:'1',accidental:'',octave:0});assert.equal(keyTonic({fifths:1,mode:'dorian'}),null);});
test('key changes select the correct reference and render explicit tonic labels', () => {const score=structuredClone(fixture);score.keys.push({at:{numerator:1,denominator:1},fifths:1,mode:'major'});assert.equal(keyAt(score,0).fifths,0);assert.equal(keyAt(score,1).fifths,1);const svg=renderNotation(score,'jianpu',{numberedMode:'movable'});assert.ok(svg.includes('1 = C4 (major)'));assert.ok(svg.includes('1 = G4 (major)'));assert.ok(svg.includes('Movable tonic numbered pitch view'));});

import {parseTuning, guitarProfile, pianoProfile} from '../web/instrument-profile.js';
test('custom keyboard geometry includes black boundary notes without clipping', () => {for(const count of [12,13,25,61,128])for(const low of [0,1,13,36,61]){if(low+count>128)continue;const keys=keyboardGeometry(count,low);assert.equal(keys.length,count);assert.equal(keys[0].midi,low);assert.equal(keys.at(-1).midi,low+count-1);assert.ok(keys.every(key=>key.x>=0&&key.x+key.width<=1.000001));}assert.throws(()=>keyboardGeometry(88,60));});
test('instrument profile fields keep explicit pitch/tuning rather than silently transposing', () => {assert.deepEqual(parseTuning('E4 B3 G3 D3 A2 D2'),[64,59,55,50,45,38]);assert.deepEqual(pianoProfile('25','C#4'),{kind:'piano',key_count:25,lowest_midi:61});assert.deepEqual(guitarProfile('E4, B3, G3, D3, A2, E2','24','2'),{kind:'guitar',tuning:[64,59,55,50,45,40],frets:24,capo:2});assert.throws(()=>pianoProfile(128,'C4'));assert.throws(()=>guitarProfile('E4 B3',12,13));assert.throws(()=>parseTuning(''));});
test('synth uses actual MIDI velocity and caps overlapping preview voices',async()=>{const peaks=[];class Audio{state='running';currentTime=0;destination={};createGain(){return{gain:{value:0,setValueAtTime(){},linearRampToValueAtTime(v){peaks.push(v)},exponentialRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}},connect(){},disconnect(){}}}createOscillator(){return{frequency:{},connect(){},disconnect(){},start(){},stop(){}}}}const previous=globalThis.AudioContext;globalThis.AudioContext=Audio;try{const synth=new Synth();await synth.unlock();synth.play('soft',60,null,0,'piano',30);synth.play('loud',60,null,0,'piano',120);assert.ok(peaks[1]>peaks[0]*4);synth.play('silent',60,null,0,'piano',0);assert.equal(synth.voices.has('silent'),false);for(let i=0;i<100;i++)synth.play(`dense-${i}`,60);assert.equal(synth.voices.size,64);assert.ok(synth.droppedVoices>0);synth.silence();assert.equal(synth.voices.size,0);}finally{globalThis.AudioContext=previous}});

import {feedbackView} from '../web/feedback-view.js';
test('empty target sets never show legacy 100% as successful practice', () => {const view=feedbackView({hits:[],misses:[],extras:[],accuracy_percent:100,mean_abs_error_ms:null},0);assert.equal(view.accuracy,'—');assert.equal(view.coverage,'—');assert.match(view.advice[0].message,/does not demonstrate/);});
test('feedback summary uses Rust bias and spread while retaining older response fallback', () => {const assessment={hits:[{grade:'good'}],misses:['miss'],extras:[],accuracy_percent:50,mean_abs_error_ms:60,summary:{expected_notes:2,matched_notes:1,coverage_percent:50,timing_bias_ms:-60,timing_stddev_ms:0,advice:[{severity:'warning',code:'small_sample',message:'A small sample.'}]}};const view=feedbackView(assessment,100);assert.equal(view.expected,2);assert.equal(view.coverage,'50%');assert.equal(view.bias,'-60 ms early');assert.equal(view.spread,'0 ms');assert.equal(view.advice[0].code,'small_sample');delete assessment.summary;const older=feedbackView(assessment,2);assert.equal(older.coverage,'50%');assert.equal(older.bias,'—');assert.equal(older.hasSummary,false);});

import {practiceScope} from '../web/practice-settings.js';
test('practice part selection preserves source timing, scoring targets and exportable notes', () => {const timeline={duration_ms:3000,notes:[{id:'lead-a',part_id:'lead',start_ms:0,duration_ms:600,midi:60},{id:'bass-a',part_id:'bass',start_ms:0,duration_ms:2000,midi:48},{id:'lead-b',part_id:'lead',start_ms:1000,duration_ms:500,midi:64}]};const before=structuredClone(timeline);const selected=practiceScope(timeline,'lead');assert.deepEqual(selected.targets.notes.map(n=>n.id),['lead-a','lead-b']);assert.equal(selected.targets.notes[1].start_ms,1000);assert.equal(selected.targets.duration_ms,3000);assert.deepEqual(timeline,before);assert.equal(practiceScope(timeline).targets.notes.length,3);});
test('loop IDs intersect selected part while held-note preview remains separate from onset assessment', () => {const timeline={duration_ms:3000,notes:[{id:'held',part_id:'bass',start_ms:0,duration_ms:2000,midi:48},{id:'bass-hit',part_id:'bass',start_ms:1000,duration_ms:500,midi:50},{id:'lead-hit',part_id:'lead',start_ms:1000,duration_ms:500,midi:64}]};const loop={start_ms:500,end_ms:1500,target_note_ids:['bass-hit','lead-hit']};const result=practiceScope(timeline,'bass',loop);assert.deepEqual([...result.targetIds],['bass-hit']);assert.deepEqual(result.targets.notes.map(n=>n.id),['bass-hit']);assert.deepEqual(result.playbackNotes.map(n=>[n.id,n.start_ms,n.duration_ms]),[['held',500,1000],['bass-hit',1000,500]]);assert.equal(practiceScope(timeline,'missing',loop).targets.notes.length,0);});
test('a legitimate part named all can still be selected independently', () => {const timeline={duration_ms:1000,notes:[{id:'a',part_id:'all',start_ms:0,duration_ms:500},{id:'b',part_id:'other',start_ms:0,duration_ms:500}]};assert.equal(practiceScope(timeline,'all').targets.notes.length,1);assert.equal(practiceScope(timeline,null).targets.notes.length,2);});

import {THEME_PALETTES, contrastRatio, readableText, safeText} from '../web/themes.js';
import {notationLayout} from '../web/music.js';
test('light and dark body/secondary theme tokens meet WCAG AA contrast on every surface', () => {for(const [name,palette] of Object.entries(THEME_PALETTES))for(const surface of [palette.background,palette.paper,palette.surface])for(const color of [palette.text,palette.muted])assert.ok(contrastRatio(color,surface)>=4.5,`${name}: ${color} on ${surface}`);assert.ok(Math.abs(contrastRatio('#000000','#ffffff')-21)<0.0001);});
test('custom background and accent colors always get AA-readable foreground fallback', () => {for(const red of [0,51,102,153,204,255])for(const green of [0,51,102,153,204,255])for(const blue of [0,51,102,153,204,255]){const background='#'+[red,green,blue].map(v=>v.toString(16).padStart(2,'0')).join('');assert.ok(contrastRatio(readableText(background),background)>=4.5);assert.ok(contrastRatio(safeText('#526650',background),background)>=4.5);}assert.throws(()=>contrastRatio('red','#ffffff'));});
test('responsive notation fits a complete current page at mobile, tablet and desktop widths', () => {for(const width of [288,354,600,930,1050]){const layout=notationLayout(width);assert.ok([4,8,16].includes(layout.spanBeats));assert.equal(layout.width,width);const svg=renderNotation(fixture,'staff',{...layout,startBeat:0});assert.ok(svg.includes(`viewBox="0 0 ${width} `));}assert.equal(notationLayout(354).spanBeats,4);assert.equal(notationLayout(600).spanBeats,8);assert.equal(notationLayout(1050).spanBeats,16);});

import {normalizeEventTime} from '../web/midi.js';
test('MIDI timestamps use event time rather than delayed callback delivery time', () => {const timestamp=normalizeEventTime(1200,{now:1500,timeOrigin:1700000000000});assert.equal(timestamp,1200);const t=new Transport();t.start(1000,[]);assert.equal(t.time(timestamp),200);assert.equal(t.time(1500),500);assert.equal(compensateInput(t.time(timestamp),40),160);});
test('MIDI timestamp normalization handles epoch clocks, missing values and invalid futures', () => {const clock={now:2000,timeOrigin:1700000000000};assert.equal(normalizeEventTime(1700000001500,clock),1500);for(const value of [undefined,null,NaN,Infinity,-1,0,2200,1700000100000])assert.equal(normalizeEventTime(value,clock),2000);assert.equal(normalizeEventTime(10,clock),10,'Old valid events keep their age so the take can reject pre-start events');assert.equal(normalizeEventTime(2010,clock),2000,'Small timestamp rounding cannot put input in the future');});

import {JIANPU_EXAMPLE} from '../web/jianpu-editor.js';
test('numbered-text editor starts with an explicit bounded original example', () => {assert.ok(JIANPU_EXAMPLE.startsWith('format=worldmusichub-jianpu-text-v1\n'));assert.ok(JIANPU_EXAMPLE.includes('composer=WorldMusicHub original exercise'));assert.ok(JIANPU_EXAMPLE.includes('1 2 3 0 |'));assert.ok(JIANPU_EXAMPLE.includes("1' - - - |"));});

import {engravingWindow, mappedPartIds} from '../web/engraved-view.js';
test('engraved pages use one-based measure ordinals and bounded explicit windows', () => {assert.deepEqual(engravingWindow(20,9,8),{total:20,from:9,to:16});assert.deepEqual(engravingWindow(20,17,8),{total:20,from:17,to:20});assert.throws(()=>engravingWindow(20,0,8));assert.throws(()=>engravingWindow(20,21,8));assert.throws(()=>engravingWindow(200,1,65));});
test('engraving part selections use Rust maps and never guess XML IDs', () => {assert.deepEqual(mappedPartIds({part_id_map:{'user:part':'P2'}},'user:part'),['P2']);assert.equal(mappedPartIds({part_id_map:{}},null),null);assert.throws(()=>mappedPartIds({part_id_map:{}},'P1'));assert.throws(()=>mappedPartIds({part_id_map:{}},'toString'));});

import {compatibilityStatus} from '../web/instrument-profile.js';
test('practice compatibility fails closed for unavailable, partial or source-changing reports', () => {const targets=[{id:'a'},{id:'b'}];assert.equal(compatibilityStatus(null,targets).status,'error');assert.equal(compatibilityStatus({note_options:[{note_id:'a',playable:true}],diagnostics:[]},targets).status,'error');assert.equal(compatibilityStatus({note_options:[{note_id:'a',playable:true},{note_id:'a',playable:true}],diagnostics:[]},targets).status,'error');assert.equal(compatibilityStatus({note_options:[],diagnostics:[],changed_source_notes:true},[]).status,'error');});
test('practice is blocked by unplayable pitches, string conflicts and empty target windows', () => {const targets=[{id:'a'}];const report={note_options:[{note_id:'a',playable:false}],diagnostics:[],changed_source_notes:false};assert.equal(compatibilityStatus(report,targets).status,'blocked');report.note_options[0].playable=true;report.diagnostics=[{code:'guitar_string_conflict'}];assert.equal(compatibilityStatus(report,targets).status,'blocked');report.diagnostics=[{code:'guitar_fingering_advisory'}];assert.equal(compatibilityStatus(report,targets).status,'ready');assert.equal(compatibilityStatus({note_options:[],diagnostics:[]},[]).status,'blocked');});

import {PracticeRecorder} from '../web/practice-recorder.js';
import {accidentalGlyph} from '../web/music.js';
test('basic staff guide spells double accidentals and natural cancellation explicitly on every page', () => {assert.equal(accidentalGlyph(2),'♯♯');assert.equal(accidentalGlyph(-2),'♭♭');assert.equal(accidentalGlyph(0),'♮');const score=structuredClone(fixture);score.parts[0].notes=[{...fixture.parts[0].notes[0],id:'double',pitch:{step:'F',alter:2,octave:4}},{...fixture.parts[0].notes[1],id:'flat',pitch:{step:'B',alter:-2,octave:4}},{...fixture.parts[0].notes[0],id:'natural',at:{numerator:4,denominator:1},pitch:{step:'F',alter:0,octave:4}}];const whole=renderNotation(score);assert.ok(whole.includes('>♯♯</text>'));assert.ok(whole.includes('>♭♭</text>'));assert.ok(whole.includes('>♮</text>'));const boundary=renderNotation(score,'staff',{startBeat:4,spanBeats:4});assert.ok(boundary.includes('data-note-id="natural"'));assert.ok(boundary.includes('>♮</text>'));});
function recorderPass(recorder,wallTime=0,position=0,label='Take'){return recorder.begin({wallTime,position,startMs:0,endMs:500,timeline:{duration_ms:500,notes:[{id:'last',midi:60,start_ms:450,duration_ms:50}]},label})}
test('positive latency tail retains the audit reproduction instead of finalizing at +200ms', () => {const recorder=new PracticeRecorder({latencyMs:500,toleranceMs:180});const pass=recorderPass(recorder);recorder.closeAtEnd(500);assert.equal(pass.deadline,1180);assert.equal(recorder.ready(700).length,0);const captured=recorder.capture({midi:60,eventWall:950,receivedWall:950});assert.equal(captured.pass.id,1);assert.equal(captured.input.at_ms,450);assert.equal(recorder.ready(1000).length,0);assert.equal(recorder.ready(1180).length,1);});
test('loop passes keep independent input clocks while delayed events arrive in later loops', () => {const recorder=new PracticeRecorder({latencyMs:500});const first=recorderPass(recorder,0,0,'Loop 1');recorder.closeAtEnd(500);const second=recorderPass(recorder,500,0,'Loop 2');const delayed=recorder.capture({midi:60,eventWall:950,receivedWall:960});assert.equal(delayed.pass,first);assert.equal(delayed.input.at_ms,450);const next=recorder.capture({midi:60,eventWall:1000,receivedWall:1001});assert.equal(next.pass,second);assert.equal(next.input.at_ms,0);assert.equal(first.inputs.length,1);assert.equal(second.inputs.length,1);});
test('paused clock segments preserve score time and keep device compensation separate', () => {const recorder=new PracticeRecorder({latencyMs:500});const pass=recorderPass(recorder);recorder.pause(300);recorder.resume(1300,300);const captured=recorder.capture({midi:60,eventWall:1950});assert.equal(captured.input.at_ms,450);recorder.closeAtEnd(1500);assert.equal(pass.deadline,2180);assert.equal(recorder.capture({midi:61,eventWall:1200}),null,'Compensated input in the paused gap is not assigned to music');});
test('late native delivery revises its original pass after assessment instead of disappearing', () => {const recorder=new PracticeRecorder({latencyMs:500});const pass=recorderPass(recorder);recorder.closeAtEnd(500);const firstJob=recorder.submit(recorder.ready(1180)[0]);recorder.complete(firstJob,{hits:[],misses:['last']});assert.equal(pass.assessedRevision,0);recorder.capture({midi:60,eventWall:950,receivedWall:2200});assert.equal(pass.inputs[0].at_ms,450);assert.equal(recorder.ready(2200)[0],pass);const corrected=recorder.submit(pass);assert.equal(corrected.inputs.length,1);assert.equal(firstJob.inputs.length,0,'Submitted snapshots are immutable');assert.equal(recorder.exportData().passes[0].captures[0].received_wall_ms,2200);});
test('slow or failed assessment does not discard subsequent pass inputs and can retry', () => {const recorder=new PracticeRecorder();const first=recorderPass(recorder);recorder.closeAtEnd(500);const second=recorderPass(recorder,500);recorder.capture({midi:60,eventWall:950});recorder.closeAtEnd(1000);const one=recorder.submit(recorder.ready(1200)[0]);assert.equal(recorder.ready(1200)[0],second);recorder.fail(one,'offline');assert.equal(first.error,'offline');assert.equal(second.inputs.length,1);recorder.retryFailed();assert.equal(recorder.ready(1200)[0],first);});
test('manual assessment waits for compensated paused-tail input and can resume the same pass', () => {const recorder=new PracticeRecorder({latencyMs:500});const pass=recorderPass(recorder);recorder.pause(300);recorder.requestAssessment(300);assert.equal(recorder.ready(900).length,0);recorder.capture({midi:60,eventWall:700});assert.equal(pass.inputs[0].at_ms,200);const job=recorder.submit(recorder.ready(980)[0]);recorder.complete(job,{hits:[]});assert.equal(pass.manualDeadline,null);recorder.resume(1500,300);recorder.capture({midi:64,eventWall:2100});assert.equal(pass.inputs[1].at_ms,400);assert.equal(recorder.ready(2100).length,0,'Resumed playback is not scored on every keystroke');});
test('MIDI All Sound Off and All Notes Off are channel controls, not scored onsets', () => {assert.deepEqual(decodeMidi([0xb2,120,0]),{kind:'panic',channel:2,controller:120});assert.deepEqual(decodeMidi([0xbf,123,0]),{kind:'panic',channel:15,controller:123});assert.equal(decodeMidi([0xb0,64,127]),null);assert.equal(decodeMidi([0x90,-1,90]),null);});
test('MIDI retriggers retain separate positive NoteOn events in a pass buffer', () => {const recorder=new PracticeRecorder();const pass=recorderPass(recorder);recorder.capture({midi:60,eventWall:100,velocity:40});recorder.capture({midi:60,eventWall:130,velocity:100});assert.equal(pass.inputs.length,2);assert.deepEqual(pass.inputs.map(event=>event.velocity),[40,100]);});
test('calibrated early first-note input is retained while real pre-start events remain excluded', () => {const recorder=new PracticeRecorder({latencyMs:150});const pass=recorderPass(recorder,1000);assert.equal(recorder.capture({midi:60,eventWall:1020}).input.at_ms,-130);assert.equal(pass.inputs.length,1);assert.equal(recorder.capture({midi:60,eventWall:999}),null);});
test('cross-pass tolerance ambiguity is marked for review without a second JS note matcher', () => {const recorder=new PracticeRecorder();const timeline={duration_ms:500,notes:[{id:'first',midi:62,start_ms:0,duration_ms:50},{id:'last',midi:60,start_ms:450,duration_ms:50}]};const one=recorder.begin({wallTime:0,position:0,startMs:0,endMs:500,timeline});recorder.closeAtEnd(500);const two=recorder.begin({wallTime:500,position:0,startMs:0,endMs:500,timeline});const event=recorder.capture({midi:60,eventWall:550});assert.equal(event.pass,two,'Ownership remains deterministic corrected clock');assert.equal(one.boundaryReviews.length,1);assert.equal(two.boundaryReviews.length,1);assert.equal(recorder.exportData().passes[1].ownership,'deterministic_corrected_clock');assert.equal(one.inputs.length,0);assert.equal(two.inputs.length,1);});
test('a next pass beginning after an early input can flag the retained earlier ownership', () => {const recorder=new PracticeRecorder();const timeline={duration_ms:500,notes:[{id:'start',midi:60,start_ms:0,duration_ms:50}]};const one=recorder.begin({wallTime:0,position:0,startMs:0,endMs:500,timeline});recorder.capture({midi:60,eventWall:450});recorder.closeAtEnd(500);const two=recorder.begin({wallTime:500,position:0,startMs:0,endMs:500,timeline});assert.equal(one.boundaryReviews.length,1);assert.equal(two.boundaryReviews.length,1);assert.equal(one.inputs.length,1,'Input is never moved or discarded by the warning');});

import {validateTargetPlan, mappedSourceIds} from '../web/physical-targets.js';
function targetPlanFixture() {
 const source={duration_ms:1000,notes:[{id:'first:pass',source_note_ids:['tie-head','tie-end'],part_id:'upper:part',midi:60,start_ms:0,duration_ms:1000},{id:'second:pass',source_note_ids:['other'],part_id:'lower:part',midi:60,start_ms:0,duration_ms:500},{id:'repeat',part_id:'upper:part',midi:60,start_ms:10,duration_ms:500}]};
 const plan={timeline:{duration_ms:1000,notes:[{...source.notes[0],source_note_ids:['tie-head','tie-end','other']},source.notes[2]]},groups:[{target_id:'first:pass',source_occurrence_ids:['first:pass','second:pass'],source_note_ids:['tie-head','tie-end','other'],part_ids:['upper:part','lower:part']},{target_id:'repeat',source_occurrence_ids:['repeat'],source_note_ids:['repeat'],part_ids:['upper:part']}],diagnostics:[],source_note_count:3,target_count:2,playable:true};
 return{source,plan};
}
test('Rust physical plans preserve exact attacks, all source occurrences and complete tie chains',()=>{const{source,plan}=targetPlanFixture();const before=structuredClone(source);assert.equal(validateTargetPlan(plan,source),plan);assert.deepEqual(mappedSourceIds(plan.timeline.notes[0],plan.groups[0]),['tie-head','tie-end','other']);assert.deepEqual(mappedSourceIds(source.notes[0]),['tie-head','tie-end']);assert.deepEqual(mappedSourceIds(source.notes[2]),['repeat']);assert.deepEqual(source,before);});
test('incomplete physical plans and tolerance-based merging fail closed rather than dropping sources',()=>{for(const mutate of [p=>p.groups[0].source_occurrence_ids.pop(),p=>p.groups[0].source_occurrence_ids.push('repeat'),p=>p.groups[0].source_note_ids.pop(),p=>p.groups[0].part_ids.pop(),p=>p.timeline.notes[0].start_ms=1,p=>p.timeline.notes[0].duration_ms=500,p=>p.timeline.notes[0].midi=61,p=>p.groups[1].target_id='first:pass',p=>p.timeline.duration_ms=999]){const{source,plan}=targetPlanFixture();mutate(plan);assert.throws(()=>validateTargetPlan(plan,source),/physical target plan/);}});
test('empty target plans remain unplayable and mapped IDs support older canonical responses',()=>{const source={duration_ms:1000,notes:[]};const plan={timeline:source,groups:[],diagnostics:[],source_note_count:0,target_count:0,playable:false};assert.equal(validateTargetPlan(plan,source),plan);plan.playable=true;assert.throws(()=>validateTargetPlan(plan,source));assert.deepEqual(mappedSourceIds({id:'occurrence',source_note_id:'canonical'}),['canonical']);});

import {librarySize,scoreFilename} from '../web/library-view.js';
test('saved-library display sizes and download names stay bounded without changing canonical IDs',()=>{assert.equal(librarySize(1024),'1.0 KiB');assert.equal(librarySize(1572864),'1.5 MiB');const score={id:'../a/b:音符'};assert.equal(scoreFilename(score),'.._a_b___.json');assert.equal(score.id,'../a/b:音符');assert.equal(scoreFilename({id:'a'.repeat(500)}).length,125);});

test('late animation frames wrap on exact wall boundaries without accumulating loop drift',()=>{
 const transport=new Transport(),notes=[{id:'short',start_ms:200,duration_ms:100}];transport.seek(200);transport.start(1000,notes);
 for(let pass=1;pass<=1000;pass++){const boundary=1000+pass*100;const frame=boundary+7+(pass%3);const result=transport.wrapLoop(frame,notes,{start:200,end:300});assert.equal(result.status,'wrapped');assert.equal(result.boundaryWall,boundary);assert.equal(transport.time(frame),200+frame-boundary);assert.equal(transport.startedAt,boundary)}
});
test('exact loop wrapping preserves repeated count-ins and pause/resume segments',()=>{
 const transport=new Transport(),notes=[{id:'note',start_ms:2000,duration_ms:300}];transport.seek(2000);transport.start(1000,notes,400);
 let result=transport.wrapLoop(1717,notes,{start:2000,end:2300,countIn:400});assert.equal(result.boundaryWall,1700);assert.equal(transport.time(1717),1617);
 result=transport.wrapLoop(2411,notes,{start:2000,end:2300,countIn:400});assert.equal(result.boundaryWall,2400);assert.equal(transport.time(2411),1611);
 transport.pause(2600);transport.start(4000,notes,400);result=transport.wrapLoop(4513,notes,{start:2000,end:2300,countIn:400});assert.equal(result.boundaryWall,4500);assert.equal(transport.time(4513),1613);
});
test('late MIDI delivery advances a shared exact loop clock before pass assignment',()=>{
 const transport=new Transport(),recorder=new PracticeRecorder({latencyMs:500});const timeline={duration_ms:500,notes:[{id:'first',midi:60,start_ms:0,duration_ms:500}]};
 transport.start(1000,timeline.notes);const first=recorder.begin({wallTime:1000,position:0,startMs:0,endMs:500,timeline});
 const wrap=transport.wrapLoop(1520,timeline.notes,{start:0,end:500});recorder.closeAtEnd(wrap.boundaryWall);const second=recorder.begin({wallTime:wrap.boundaryWall,position:transport.position,startMs:0,endMs:500,timeline});
 assert.equal(first.closedWall,1500);assert.equal(first.deadline,2180);assert.equal(second.startedWall,1500);
 assert.equal(recorder.capture({midi:60,eventWall:1950,receivedWall:2200}).pass,first);const onset=recorder.capture({midi:60,eventWall:2010,receivedWall:2200});assert.equal(onset.pass,second);assert.equal(onset.input.at_ms,10);
});
test('whole missed loop passes pause without fabricating takes and retain unassigned gap events',()=>{
 const transport=new Transport(),recorder=new PracticeRecorder({latencyMs:100}),timeline={duration_ms:500,notes:[{id:'note',midi:60,start_ms:0,duration_ms:500}]};transport.start(1000,timeline.notes);recorder.begin({wallTime:1000,position:0,startMs:0,endMs:500,timeline});
 const result=transport.wrapLoop(2700,timeline.notes,{start:0,end:500});assert.equal(result.status,'stalled');assert.equal(result.boundaryWall,1500);assert.equal(result.skippedPasses,2);assert.equal(transport.running,false);assert.equal(transport.position,0);
 recorder.closeAtEnd(result.boundaryWall);recorder.recordInterruption({boundaryWall:result.boundaryWall,observedWall:2700,skippedPasses:result.skippedPasses});const captured=recorder.capture({midi:64,eventWall:2300,receivedWall:2800});assert.equal(captured.pass,null);assert.equal(captured.unassigned.corrected_wall_ms,2200);assert.equal(recorder.passes.length,1);assert.equal(recorder.passes[0].inputs.length,0);assert.equal(recorder.exportData().unassigned_captures.length,1);assert.equal(recorder.exportData().interruptions[0].skipped_passes,2);
 assert.equal(recorder.capture({midi:67,eventWall:4000}),null,'Free play after the known gap is not fabricated into practice');transport.start(5000,timeline.notes);assert.equal(transport.time(5000),0);
});
test('a complete next pass includes its count-in when deciding whether a frame stall skipped it',()=>{const transport=new Transport();transport.start(0,[],300);assert.equal(transport.wrapLoop(1799,[],{start:0,end:600,countIn:300}).status,'wrapped');assert.equal(transport.time(1799),599);assert.equal(transport.wrapLoop(2700,[],{start:0,end:600,countIn:300}).status,'stalled');});

import {validateJianpuExport} from '../web/jianpu-export.js';
test('numbered-text preview verifies every canonical note/rest identity and labels inserted gaps',()=>{const result={text:'1:1/1 3:1/1 0:2/1',note_map:['c4','e4',null],diagnostics:[]};assert.deepEqual(validateJianpuExport(result,fixture),{sourceNotes:2,gapRests:1});for(const ids of [['c4'],['c4','c4'],['c4','e4','unknown'],['c4','e4',5]])assert.throws(()=>validateJianpuExport({...result,note_map:ids},fixture),/incomplete/);assert.throws(()=>validateJianpuExport({...result,text:'x'.repeat(1024*1024+1)},fixture));});

import {installLoopClockFixture} from './frontend-clock-fixture.js';
test('controlled loop fixture preserves ordinary RAF callbacks and cancellation for browser polling',()=>{
 const forwarded=[],cancelled=[],target={performance:{now:()=>5},requestAnimationFrame(callback){forwarded.push(callback);return forwarded.length},cancelAnimationFrame(id){cancelled.push(id)}};
 installLoopClockFixture(target);function animate(){}function next(){}
 assert.equal(target.requestAnimationFrame(animate),-1);assert.equal(target.loopTestFrame,animate);assert.equal(target.requestAnimationFrame(next),1);assert.deepEqual(forwarded,[next]);target.cancelAnimationFrame(1);assert.deepEqual(cancelled,[1]);target.cancelAnimationFrame(-1);assert.equal(target.loopTestFrame,null);assert.deepEqual(cancelled,[1]);target.loopTestClock=1517;assert.equal(target.performance.now(),1517);
});

import {REVIEW_DURATIONS,MAX_REVIEW_NOTES} from '../web/image-review.js';
const makeReview=rows=>reviewedScore({title:'Exact rhythm',rows,filename:'original.png',originalImage:'data:image/png;base64,original',review:{requires_review:true},crop:{x:0,y:0,width:10,height:20}});
test('reviewed dotted and triplet choices preserve exact mixed note and measure times',()=>{
 const rows=[{pitch:'C4',duration:'0.75'},{pitch:'D4',duration:'1.5'},{pitch:'0',duration:'3'},{pitch:'F##4',duration:'1/3'},{pitch:'Bbb3',duration:'2/3'}],before=structuredClone(rows),score=makeReview(rows);
 assert.deepEqual(score.parts[0].notes.map(note=>note.at),[{numerator:0,denominator:1},{numerator:3,denominator:4},{numerator:9,denominator:4},{numerator:21,denominator:4},{numerator:67,denominator:12}]);
 assert.deepEqual(score.parts[0].notes.map(note=>note.duration),[{numerator:3,denominator:4},{numerator:3,denominator:2},{numerator:3,denominator:1},{numerator:1,denominator:3},{numerator:2,denominator:3}]);assert.deepEqual(score.measures.map(measure=>measure.length),[{numerator:4,denominator:1},{numerator:9,denominator:4}]);assert.deepEqual(score.parts[0].notes.map(note=>note.velocity),[90,90,0,90,90]);assert.deepEqual(JSON.parse(score.source.content).manual_notes,before);assert.deepEqual(rows,before);
});
test('512 triplets accumulate with no floating rounding and 513 rows are explicitly rejected intact',()=>{
 assert.equal(MAX_REVIEW_NOTES,512);const rows=Array.from({length:MAX_REVIEW_NOTES},()=>({pitch:'C4',duration:'1/3'}));const score=makeReview(rows);assert.deepEqual(score.parts[0].notes.at(-1).at,{numerator:511,denominator:3});assert.equal(score.measures.length,43);assert.deepEqual(score.measures.at(-1).length,{numerator:8,denominator:3});rows.push({pitch:'C4',duration:'1/3'});assert.throws(()=>makeReview(rows),/at most 512.*no rows were discarded/);assert.equal(rows.length,513);
});
test('review duration options are exact explicit choices and pitch correction preserves double spelling',()=>{
 assert.deepEqual(parsePitch('F##4'),{step:'F',alter:2,octave:4});assert.deepEqual(parsePitch('Bbb3'),{step:'B',alter:-2,octave:3});for(const bad of ['C#b4','F###4','Cbb-1','G##9'])assert.throws(()=>parsePitch(bad));
 for(const choice of REVIEW_DURATIONS){const note=makeReview([{pitch:'0',duration:choice.value}]).parts[0].notes[0];assert.equal(note.duration.numerator*12,note.duration.denominator*choice.ticks);assert.equal(note.velocity,0)}
 for(const duration of ['0.3333333333','0.6666666667','','1/5','-1',Infinity])assert.throws(()=>makeReview([{pitch:'C4',duration}]),/Choose the duration/);
});

import {validateMetronomeGrid,scopedClicks,ClickScheduler,MIN_CLICK_GAP_MS} from '../web/metronome.js';
const clickGrid=(times=[0,500,1000,1500],duration=2000)=>({duration_ms:duration,pulse:'notated_unit',accent_policy:'written_measure_boundary',diagnostics:[],ticks:times.map((start_ms,index)=>({id:`tick-${index}`,source_tick_id:`source-${index}`,source_at:{numerator:index,denominator:1},start_ms,measure_number:1,unit_index:index,accent:index===0}))});
test('metronome uses supplied Rust pulses with half-open loop filtering and no invented A onset',()=>{const grid=clickGrid(),before=structuredClone(grid);assert.equal(validateMetronomeGrid(grid,'notated_unit',2000),grid);assert.deepEqual(scopedClicks(grid,{from:250,to:1500,loop:true}).map(tick=>tick.start_ms),[500,1000]);assert.deepEqual(grid,before);assert.equal(scopedClicks(grid,{from:100,to:200,loop:true}).length,0);});
test('too-dense clicks and compressed loop joins are rejected rather than silently decimated',()=>{assert.equal(MIN_CLICK_GAP_MS,100);assert.throws(()=>scopedClicks(clickGrid([0,50,100])),/coarser pulse/);assert.throws(()=>scopedClicks(clickGrid([500,1000]),{from:499,to:1001,loop:true}),/loop join/);assert.equal(scopedClicks(clickGrid([500,1000]),{from:499,to:1001,loop:true,countInMs:2000}).length,2);assert.equal(scopedClicks(clickGrid([0,100,200])).length,3);});
test('metronome validation rejects stale duration, wrong pulse, duplicate identity and unknown accent policy',()=>{for(const mutate of [g=>g.duration_ms=1999,g=>g.pulse='quarter',g=>g.ticks[1].id='tick-0',g=>g.ticks[1].start_ms=-1,g=>g.ticks[1].accent='yes',g=>g.accent_policy='inferred_strong_beat']){const grid=clickGrid();mutate(grid);assert.throws(()=>validateMetronomeGrid(grid,'notated_unit',2000));}});
test('click scheduling shares exact transport positions and cancels queued clicks on pause or loop reset',()=>{const scheduler=new ClickScheduler(clickGrid().ticks);let clock={position:-150,segment:1000,startPosition:-500};assert.deepEqual(scheduler.due(clock),[]);clock.position=-50;assert.equal(scheduler.due(clock)[0].delay_ms,50);assert.equal(scheduler.due(clock).length,0);scheduler.reset();clock={position:475,segment:3000,startPosition:475};assert.equal(scheduler.due(clock)[0].start_ms,500);assert.equal(scheduler.due(clock).length,0);clock={position:17,segment:4000,startPosition:0};assert.equal(scheduler.due(clock)[0].start_ms,0);});
test('clicks do not catch up in bursts when rendering falls behind and mid-play enable starts at a future pulse',()=>{const scheduler=new ClickScheduler(clickGrid().ticks);scheduler.prime(250,1000);assert.equal(scheduler.due({position:410,segment:1000,startPosition:0})[0].start_ms,500);assert.throws(()=>scheduler.due({position:1200,segment:1000,startPosition:0}),/fell behind/);});
test('metronome synthesis is opt-in, shares one audio context, respects mute and releases every click',async()=>{
 const starts=[],levels=[];let contexts=0;class Audio{state='running';currentTime=2;destination={};constructor(){contexts++}createGain(){return{gain:{value:0,setValueAtTime(){},linearRampToValueAtTime(value){levels.push(value)},exponentialRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}},connect(){},disconnect(){}}}createOscillator(){return{frequency:{},connect(){},disconnect(){},start(time){starts.push(time)},stop(){}}}}
 const previous=globalThis.AudioContext;globalThis.AudioContext=Audio;try{const synth=new Synth();synth.click('locked');assert.equal(contexts,0);await synth.unlock();synth.play('note',60);synth.click('pulse',true,50,0.25);assert.equal(contexts,1);assert.equal(starts.at(-1),2.05);assert.equal(synth.clickVoices.size,1);assert.equal(synth.voices.size,1);assert.equal(levels.at(-1),0.055);synth.silenceClicks();assert.equal(synth.clickVoices.size,0);assert.equal(synth.voices.size,1);synth.muted=true;synth.click('muted');assert.equal(synth.clickVoices.size,0);synth.muted=false;for(let index=0;index<8;index++)synth.click(`click-${index}`);assert.throws(()=>synth.click('overflow'),/safe voice budget/);synth.silence();assert.equal(synth.voices.size,0);assert.equal(synth.clickVoices.size,0);}finally{globalThis.AudioContext=previous}
});

import {SCORE_SOURCES,filterScoreSources,unsupportedImportHint} from '../web/score-sources.js';
test('source directory is an explicit three-source list with fixed official HTTPS references',()=>{
 assert.equal(SCORE_SOURCES.length,3);assert.deepEqual(SCORE_SOURCES.map(source=>source.url),['https://github.com/OpenScore/Lieder','https://www.mutopiaproject.org/','https://imslp.org/wiki/Main_Page']);for(const source of SCORE_SOURCES){assert.equal(new URL(source.url).protocol,'https:');assert.equal(new URL(source.rightsUrl).protocol,'https:');assert.ok(source.importNote.length>20);assert.ok(source.rights.length>20)}assert.match(SCORE_SOURCES[0].importNote,/does not import MSCX/);assert.match(SCORE_SOURCES[2].rights,/your country/);
});
test('source search only filters local directory metadata and distinguishes import routes',()=>{
 assert.deepEqual(filterScoreSources('ＭＩＤＩ').map(source=>source.id),['openscore-lieder','mutopia']);assert.deepEqual(filterScoreSources('','musicxml').map(source=>source.id),['openscore-lieder']);assert.equal(filterScoreSources('PDF','image').length,3);assert.deepEqual(filterScoreSources('cc BY-SA').map(source=>source.id),['mutopia']);assert.equal(filterScoreSources('a score that is not in this directory').length,0);assert.equal(filterScoreSources('','unknown').length,0);assert.equal(SCORE_SOURCES.length,3);
});
test('unsupported score formats explain conversion or review instead of treating scans as playable JSON',()=>{
 assert.match(unsupportedImportHint('scan.PDF'),/not imported as playable/);for(const name of ['score.mscx','score.MSCZ'])assert.match(unsupportedImportHint(name),/not imported directly/);assert.match(unsupportedImportHint('source.ly'),/Renaming/);assert.match(unsupportedImportHint('staff.jpeg'),/Review image/);for(const name of ['score.json','score.musicxml','score.mxl','score.mid','score.jianpu'])assert.equal(unsupportedImportHint(name),null);
});

import {beat} from '../web/music.js';
import {octaveOperation,equivalentJson,validateAdaptationPreview} from '../web/adaptation-view.js';
function adaptationFixture(original=fixture,operation={part_id:null,octaves:1}){
 const copy=structuredClone(original);copy.id+=':copy';copy.title+=' [octave +1]';let count=0;for(const part of copy.parts)if(operation.part_id===null||part.id===operation.part_id)for(const note of part.notes)if(note.pitch){note.pitch.octave+=operation.octaves;count++}copy.source={format:'octave-adaptation',filename:null,content:JSON.stringify({version:1,operation,original})};const notes=copy.parts.flatMap(part=>part.notes.filter(note=>note.pitch).map(note=>({id:note.id,part_id:part.id,midi:pitchMidi(note.pitch),start_ms:beat(note.at)*500,duration_ms:beat(note.duration)*500})));const selected=notes.filter(note=>operation.part_id===null||note.part_id===operation.part_id);return{compilation:{score:copy,timeline:{notes,duration_ms:2000},diagnostics:[]},operation,changed_note_count:count,original_preserved:true,instrument_report:{note_options:selected.map(note=>({note_id:note.id,playable:true})),diagnostics:[],changed_source_notes:false},scored_mode_allowed:true};
}
test('octave preview keeps complete original source, exact note properties and unselected parts',()=>{
 const original=structuredClone(fixture);original.source={format:'original',filename:'score.xml',content:'\uFEFF<source>\r\n原始</source>'};original.parts[0].notes[0].pitch.alter=2;original.parts.push({...structuredClone(original.parts[0]),id:'bass',notes:original.parts[0].notes.map(note=>({...structuredClone(note),id:`bass-${note.id}`}))});const before=structuredClone(original),operation=octaveOperation('selected','bass','-1'),preview=adaptationFixture(original,operation);assert.equal(validateAdaptationPreview(preview,original,operation),preview);assert.equal(preview.changed_note_count,2);assert.deepEqual(preview.compilation.score.parts[0],original.parts[0]);assert.deepEqual(JSON.parse(preview.compilation.score.source.content).original,original);assert.deepEqual(original,before);
});
test('octave preview cannot silently drop notes, rewrite timing or lose the original envelope',()=>{for(const mutate of [p=>p.compilation.score.parts[0].notes.pop(),p=>p.compilation.score.parts[0].notes[0].duration.numerator=3,p=>p.compilation.score.parts[0].notes[0].pitch.alter=1,p=>p.original_preserved=false,p=>p.changed_note_count=1,p=>p.operation.octaves=2,p=>p.compilation.score.source.content='{}',p=>p.instrument_report.note_options.pop()]){const operation={part_id:null,octaves:1},preview=adaptationFixture(fixture,operation);mutate(preview);assert.throws(()=>validateAdaptationPreview(preview,fixture,{part_id:null,octaves:1}),/preserve/)}});
test('octave scope and confirmation comparisons reject missing parts and invalid shifts',()=>{assert.deepEqual(octaveOperation('all',null,'2'),{part_id:null,octaves:2});for(const value of ['',0,'1.5',9,-9,Infinity])assert.throws(()=>octaveOperation('all',null,value));assert.throws(()=>octaveOperation('selected',null,-1));assert.equal(equivalentJson({a:1,b:{c:2}},{b:{c:2},a:1}),true);assert.equal(equivalentJson({a:1},{a:2}),false);assert.equal(equivalentJson([1,2],[2,1]),false);});
