import test from 'node:test';
import assert from 'node:assert/strict';
import {getAppI18n} from '../web/app-locale.js';
import {cleanDescriptor,fixtureKey,mediaFixture} from './clean-song-fixtures.js';
import {nativeScoreServer,nativeStorageApp,deferred} from './native-storage-app-fixtures.js';
async function setup({media=false,now}={}){
 const assets=media?[mediaFixture(),mediaFixture({id:'bg',role:'background',content:'authored-bg'}),mediaFixture({id:'pv',role:'pv',mime:'video/webm',content:'authored-pv'})]:[];
 const descriptor=cleanDescriptor(({metadata})=>metadata.media=assets.map(item=>item.descriptor)),score=descriptor.runtime.compilation.score,server=await nativeScoreServer(),key=fixtureKey.slice(7);
 server.records.set(key,{entry:{key,revision:1,title:score.title,composer:'',score_id:score.id,label:score.title,score_bytes:JSON.stringify(score).length,saved_at_unix_ms:1700000000000,clean_package:{version:2,content_sha256:descriptor.content_sha256,media:descriptor.media}},score_json:JSON.stringify(score),clean_package:descriptor});
 if(media)server.setRoute(({path,body})=>{if(path==='/api/library/asset'){const asset=assets.find(item=>'asset-'+item.descriptor.sha256===body.handle);return{ok:true,url:'https://wmh.localhost/api/library/asset',headers:{get:()=>asset.descriptor.mime},arrayBuffer:async()=>Uint8Array.from(asset.data).buffer};}});
 const app=await nativeStorageApp(server,{now});await app.until(()=>app.savedButton(key)&&!app.$('start-listen').disabled);await app.click('home-single-player');app.savedButton(key).click();await app.until(()=>!app.$('start-listen').disabled&&!app.$('clean-song-preview').hidden,'Clean preview did not load');app.$('count-in').checked=false;return{app,server,descriptor,score,key};
}
async function activate(app,mode){await app.click(`start-${mode}`);await app.until(()=>app.document.body.dataset.screen==='stage'&&!app.$('play-button').disabled);}
const runningOscillators=app=>app.audioNodes.filter(node=>node.kind==='oscillator'&&!node.disconnected);

test('ordinary library consumes exact runtime, all-part notation and program-aware Listen without recompiling timing',async()=>{const {app,descriptor}=await setup();try{
 assert.equal(app.$('preview-part').children.length,2);assert.equal(app.$('preview-part').value,descriptor.runtime.compilation.score.parts[0].id);assert.match(app.$('clean-song-preview-status').textContent,/3 tracks.*2 parts.*5 notes/);assert.equal(app.document.querySelector('.lobby-audition').hidden,true);
 const compiledBefore=app.requests.filter(request=>request.path==='/api/compile').length;await activate(app,'listen');assert.equal(app.$('clean-song-stage').dataset.rendererState,'playing');assert.equal(app.$('notation-part').value,'');assert.equal(app.$('engraving-part').value,'');assert.equal(app.requests.filter(request=>request.path==='/api/compile').length,compiledBefore);assert.equal(runningOscillators(app).length,4);assert.equal(app.plays.filter(args=>String(args[0]).startsWith('score:')).length,0);assert.equal(app.$('tempo').disabled,true);assert.equal(app.$('loop-enabled').disabled,true);assert.equal(app.$('export-button').disabled,true);
 await app.click('play-button');assert.equal(app.$('clean-song-stage').dataset.rendererState,'paused');assert.equal(runningOscillators(app).length,0);assert.ok(app.audioNodes.filter(node=>node.kind==='convolver').every(node=>node.buffer===null));await app.click('play-button');assert.equal(runningOscillators(app).length,4);await app.click('reset-button');assert.equal(app.$('clean-song-stage').dataset.rendererState,'ready');assert.equal(runningOscillators(app).length,0);assert.equal(app.$('progress').value,0);
 }finally{await app.close();}});

test('practice target and accompaniment toggles keep stable controls; only human input can enter scoring',async()=>{const {app,score}=await setup();try{
 await activate(app,'practice');assert.equal(runningOscillators(app).length,2);await app.click('play-button');let take=await app.exported('export-takes');assert.deepEqual(take.passes[0].inputs,[]);assert.deepEqual(take.passes[0].captures,[]);assert.ok(take.passes[0].timeline.notes.every(note=>note.part_id===score.parts[0].id));assert.equal(take.passes[0].timeline.notes.at(-1).duration_ms,800);
 const target=app.$('clean-song-target'),checkbox=app.document.querySelector(`#clean-song-parts input[data-part-id="${score.parts[0].id}"]`);target.value=score.parts[1].id;app.emit(target,'change');await app.until(()=>!app.$('play-button').disabled);assert.equal(app.$('clean-song-target'),target);assert.equal(app.document.querySelector(`#clean-song-parts input[data-part-id="${score.parts[0].id}"]`),checkbox);checkbox.checked=false;app.emit(checkbox,'change');await app.click('play-button');assert.equal(runningOscillators(app).length,0);take=await app.exported('export-takes');assert.equal(take.practice_part,score.parts[1].id);assert.equal(take.passes[0].timeline.notes.length,2);assert.deepEqual(take.passes[0].inputs,[]);await app.click('play-button');checkbox.checked=true;app.emit(checkbox,'change');await app.click('play-button');assert.equal(runningOscillators(app).length,2);await app.click('back-to-library');assert.equal(runningOscillators(app).length,0);
 }finally{await app.close();}});

test('complete-song media has gesture lifecycle, localized optional failure and navigation cleanup',async()=>{let clock=1000;const {app}=await setup({media:true,now:()=>clock});try{
 await app.until(()=>Boolean(app.$('clean-song-cover').src));app.$('clean-song-cover').onload();assert.equal(app.$('clean-song-cover').hidden,false);
 const video=app.$('clean-song-pv');let plays=0,pauses=0;video.pause=()=>{pauses++;video.paused=true;};video.play=()=>{plays++;video.paused=false;return Promise.resolve();};video.load=()=>{};
 assert.equal(plays,0);await activate(app,'listen');await app.until(()=>Boolean(video.src));video.onloadeddata();app.frame();assert.equal(video.muted,true);assert.equal(plays,0,'Shared start admission has not reached song zero yet');clock+=65;app.frame();await app.tick();assert.equal(plays,1);
 await app.click('play-button');assert.equal(video.paused,true);getAppI18n(app.document).setLocale('zh-CN');app.$('clean-song-background').onerror();assert.match(app.$('clean-song-media-status').textContent,/背景无法显示/);assert.doesNotMatch(app.$('clean-song-preview').textContent,/inferred|Reference|channel /);await app.click('back-to-library');assert.equal(video.hidden,true);assert.equal(video.paused,true);assert.ok(pauses>0);
 }finally{await app.close();}});

test('a late audio unlock cannot activate clean audio after another song selection',async()=>{const {app}=await setup();try{const pending=deferred();app.setUnlock(()=>pending.promise);await app.click('start-listen');await app.click('home-single-player');const bundled=app.document.querySelector('#catalog [data-score-id]');bundled.click();await app.until(()=>app.$('clean-song-preview').hidden);pending.resolve();await app.tick();assert.equal(runningOscillators(app).length,0);}finally{await app.close();}});

test('range summary retains all notes and 88-key action changes device range without transposition',async()=>{const {app,score}=await setup();try{await activate(app,'listen');await app.click('play-button');assert.match(app.$('song-complete-range-text').textContent,/5 notes/);const original=JSON.stringify(score.parts);await app.click('song-use-piano-88');assert.equal(app.$('key-count').value,'88');assert.equal(JSON.stringify(score.parts),original);assert.equal(app.$('song-use-piano-88').hidden,true);app.$('tempo').value='130';app.emit(app.$('tempo'),'change');assert.equal(app.$('tempo').value,'120');assert.equal(app.requests.filter(request=>request.path==='/api/transpose').length,0);}finally{await app.close();}});


test('ordinary source part selection keeps written focus and does not add complete-song stage controls',async()=>{const {app,score}=await setup();try{
 await app.click('home-single-player');const standard=structuredClone(score);standard.id='ordinary-two-part';app.importFile(standard);await app.until(()=>app.$('score-title')?.textContent===standard.title&&!app.$('play-button').disabled);
 assert.equal(app.$('song-parts-tools').hidden,true);const second=standard.parts[1].id;app.$('practice-part').value=second;app.emit(app.$('practice-part'),'change');await app.until(()=>!app.$('play-button').disabled);assert.equal(app.$('notation-part').value,second);assert.equal(app.$('engraving-part').value,second);
 }finally{await app.close();}});
