import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeScoreServer,nativeStorageApp} from './native-storage-app-fixtures.js';
import {originalMultipartNotation} from './notation-scope-fixtures.js';

test('ordinary twelve-part notation reaches every All part page without changing the human target',async()=>{
 const score=originalMultipartNotation(),before=JSON.stringify(score),server=await nativeScoreServer({scores:[score]}),app=await nativeStorageApp(server);
 try{const key=[...server.records.keys()][0];await app.until(()=>app.savedButton(key)&&!app.$('start-listen').disabled);await app.click('home-single-player');app.savedButton(key).click();await app.until(()=>!app.$('start-listen').disabled&&app.$('preview-part').options.length>1);await app.click('sound-button');await app.click('start-listen');await app.until(()=>app.document.body.dataset.screen==='stage');await app.click('play-button');if(app.$('notation-toggle').getAttribute('aria-expanded')!=='true')await app.click('notation-toggle');await app.click('jianpu-button');app.$('notation-scope').value='all';app.emit(app.$('notation-scope'),'change');await app.until(()=>app.$('notation').querySelectorAll('[data-note-id^="original-held-"]').length===4);const human=app.$('practice-part').value,all=[];
  for(let page=0;page<3;page++){const ids=JSON.parse(app.$('workspace').dataset.renderedNotationParts||'[]');assert.deepEqual(ids,score.parts.slice(page*4,page*4+4).map(part=>part.id));all.push(...ids);assert.match(app.$('notation-scope-status').textContent,new RegExp(`Part page ${page+1} / 3`));assert.equal(app.$('practice-part').value,human);if(page<2){await app.click('notation-parts-next');await app.until(()=>JSON.parse(app.$('workspace').dataset.renderedNotationParts||'[]')[0]===score.parts[(page+1)*4].id);}}
  assert.equal(new Set(all).size,12);assert.equal(app.$('notation-parts-next').disabled,true);app.$('practice-part').value=score.parts[10].id;app.emit(app.$('practice-part'),'change');await app.until(()=>!app.$('play-button').disabled);assert.equal(app.$('notation-scope').value,'all');app.$('notation-scope').value='current';app.emit(app.$('notation-scope'),'change');await app.until(()=>JSON.parse(app.$('workspace').dataset.renderedNotationParts||'[]').join()===score.parts[10].id);assert.equal(app.$('notation').querySelectorAll('[data-note-id^="original-held-"]').length,1);assert.equal(app.$('practice-part').value,score.parts[10].id);assert.equal(JSON.stringify(score),before);
  app.$('session-mode').value='listen';app.emit(app.$('session-mode'),'change');assert.equal(app.$('notation-scope').value,'current','An explicit scope survives mode changes');assert.equal(app.requests.some(request=>request.path==='/api/assess'),false);
 }finally{await app.close();}
});
