// Pure verifier fixtures only: no browser, AudioContext, executable or server.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {assistanceNativeFixtures,ASSISTANCE_PHASES} from '../scripts/native-assistance-fixtures.mjs';
import {assistanceNativeSinglePreset,validateAssistancePresetControls,validateAssistanceRequestCompletion,validateAssistanceNativeActions,validateAssistanceSources,validateAssistanceTake,validateAssistanceStorage,validateAssistanceOffMarker,validateAssistanceOffTake,validateAssistanceAudio,assistanceTakeIdentity,assistanceExpectedSchedules,assistanceExpectedAudioPlan,ASSISTANCE_CLAIMS} from '../scripts/verify-native-assistance-evidence.mjs';
import {assistanceText} from '../web/practice-assistance-locales.js';
import {syntheticAudioThreadRun,syntheticAudioThreadStatus} from './audio-thread-proof-fixtures.js';
const fixtures=assistanceNativeFixtures(),checked=fixtures.basic.automatic.checked,clone=structuredClone;
function take(human=false){const song_mod={config:{parts:checked.plan.selection.selected_part_ids.map(partId=>({partId,performer:'human',instrument:partId==='midi-t1-c1-r0'?'reed':'source'}))}},identity=assistanceTakeIdentity(checked),input={midi:72,velocity:90,at_ms:750};return{practice_assistance:clone(identity),practice_selection:{kind:'all',part_ids:clone(checked.plan.selection.selected_part_ids)},target_plan:clone(checked.human_targets),song_mod,input_evidence:{version:1,truncated:false,omitted_observations:0,events:human?[{kind:'note_on',input_kind:'typing_keyboard',encoding:'key_down',midi:72,raw_timestamp_ms:750,onset_capture:{pass_id:1,event_id:1}}]:[]},passes:[{id:1,capture_enabled:true,pending:false,timeline:clone(checked.human_targets.timeline),interpretation:{practice_assistance:clone(identity),song_mod:clone(song_mod),source_revision:{songId:JSON.parse(fixtures.basic.opened.clean_package.score_json).notation.id,sourceRevision:{kind:'clean-package-sha256',value:fixtures.basic.source.content_sha256}}},inputs:human?[input]:[],captures:human?[{input}]:[],assessment:{hits:human?[{note_id:'midi-t1-e11'}]:[],misses:checked.human_targets.timeline.notes.filter(n=>!human||n.id!=='midi-t1-e11').map(n=>n.id),extras:[]}}]};}
function recipe(kind,label){const f=fixtures[kind],p=f[label].checked.plan,s=f.source,key=JSON.stringify([s.key,s.content_sha256,s.profile,s.choice,s.runtime_policy]);return ['worldmusichub.practice-assistance.v1.'+encodeURIComponent(key),JSON.stringify({format:'wmc-practice-assistance-recipe',version:1,preference_key:key,source:s,selection:p.selection,mode:p.mode,settings:p.settings,planner_revision:p.planner_revision,revision:p.revision,expected_selection_digest:p.selection_digest})];}
function offMarker(){const source=fixtures.basic.source;return{format:'wmc-practice-assistance-off',version:1,preference_key:JSON.stringify([source.key,source.content_sha256,source.profile,source.choice,source.runtime_policy]),source:clone(source)};}
function storage(){const saved=Object.fromEntries([recipe('basic','automatic'),recipe('vsq','narrow_scope')]);return[{phase:ASSISTANCE_PHASES[0],storageBefore:{},storageAfter:saved},{phase:ASSISTANCE_PHASES[1],storageBefore:clone(saved),storageAfter:Object.fromEntries([[recipe('basic','automatic')[0],JSON.stringify(offMarker())],recipe('vsq','narrow_scope')])}];}
function sources(){return Object.fromEntries(['basic','vsq'].map(kind=>[kind,{key:fixtures[kind].source.key,before:clone(kind==='basic'?fixtures.basic.opened:fixtures.vsqOpened),after:clone(kind==='basic'?fixtures.basic.opened:fixtures.vsqOpened)}]));}
function audio(){const runtime=fixtures.basic.opened.clean_package.runtime;return{runs:[syntheticAudioThreadRun(assistanceExpectedSchedules(),{sourceSha256:runtime.source_sha256,durationMs:1000,sourceNotes:6,planOracle:assistanceExpectedAudioPlan})],status:syntheticAudioThreadStatus()};}
test('only original CC0 native fixtures enter the bounded pack and retained APIs',()=>{assert.equal(fixtures.manifest.sources.basic.key,fixtures.basic.source.key);assert.equal(fixtures.manifest.sources.vsq.key,fixtures.vsq.source.key);assert.equal(fixtures.bytes.length,fixtures.manifest.bytes);assert.ok(fixtures.bytes.length<100000);assert.equal(ASSISTANCE_CLAIMS.physical_audio,false);assert.equal(ASSISTANCE_CLAIMS.physical_midi,false);assert.equal(ASSISTANCE_CLAIMS.full_acceptance,false);});
test('native source comparison rejects score, metadata, retained gate and key mutation',()=>{validateAssistanceSources(sources());for(const mutate of [s=>s.basic.after.score_json+=' ',s=>s.basic.after.clean_package.metadata_json+=' ',s=>s.basic.before.clean_package.runtime.rendition.notes[1][2]=[0,4],s=>s.vsq.key=s.basic.key]){const s=sources();mutate(s);assert.throws(()=>validateAssistanceSources(s));}});
test('machine-only and one trusted human take validators retain complete checked target identity',()=>{validateAssistanceTake(take());validateAssistanceTake(take(true),{human:true});});
test('take validator rejects machine targets/inputs, stale receipts, missing owners and machine scores',()=>{for(const mutate of [t=>t.passes[0].inputs.push({midi:67,at_ms:500}),t=>t.target_plan.timeline.notes.push({id:'midi-t1-e8'}),t=>t.practice_assistance.plan.selection_digest='f'.repeat(64),t=>t.passes[0].interpretation.practice_assistance.machine_occurrence_ids=[],t=>t.passes[0].assessment.hits[0].note_id='midi-t1-e8',t=>t.input_evidence.events[0].input_kind='machine',t=>t.passes[0].pending=true,t=>t.passes[0].captures=[]]){const t=take(true);mutate(t);assert.throws(()=>validateAssistanceTake(t,{human:true}));}});
test('same-profile restart restores Automatic then only Basic receives a source-bound Off marker',()=>{validateAssistanceStorage(storage());for(const mutate of [s=>s[1].storageBefore={},s=>{const k=Object.keys(s[0].storageAfter)[0],r=JSON.parse(s[0].storageAfter[k]);r.plan=checked.plan;s[0].storageAfter[k]=JSON.stringify(r);s[1].storageBefore=clone(s[0].storageAfter);},s=>{const k=Object.keys(s[1].storageAfter)[0],r=JSON.parse(s[1].storageAfter[k]);r.expected_selection_digest='f'.repeat(64);s[1].storageAfter[k]=JSON.stringify(r);}]){const s=storage();mutate(s);assert.throws(()=>validateAssistanceStorage(s));}});
test('pure synthetic records exercise machine gate validator but do not claim native execution',()=>{const a=audio();assert.deepEqual(validateAssistanceAudio(a.runs,a.status),{runs:1,naturalCount:1,attacks:2});assert.deepEqual(a.runs[0].plan.notes.map(n=>n[0]),['midi-t1-e8','midi-t1-e13']);assert.deepEqual(a.runs[0].plan.timbres,[3,0]);});
test('worklet validator rejects different source gates, full-part fallback, forged/untrusted ledgers and stale assistance',()=>{for(const mutate of [a=>a.runs[0].plan.notes[0][3]++,a=>a.runs[0].plan.notes.pop(),a=>a.runs[0].plan.assistanceFingerprint='f'.repeat(64),a=>a.runs[0].terminals[0].record.ledger.actualStarts[0]++,a=>a.runs[0].rawTerminals[0].isTrusted=false,a=>a.runs[0].messages[0].portMatches=false,a=>a.status.ownedNodes[0].connected=true,a=>a.runs[0].positionFrame=-48000]){const a=audio();mutate(a);assert.throws(()=>validateAssistanceAudio(a.runs,a.status));}});
test('renderer and injected helper prefixes parse without launching a browser',()=>{const root=new URL('../',import.meta.url),read=p=>readFileSync(new URL(p,root),'utf8');const text=[read('crates/desktop-shell/acceptance-wait.js'),read('crates/desktop-shell/reference-acceptance.js'),read('crates/desktop-shell/vsq-song-acceptance.js').split('(() => {')[0],read('crates/desktop-shell/canonical-practice-acceptance.js').split('(() => {')[0],read('scripts/native-assistance-renderer.js')].join('\n');new vm.Script(text);assert.match(text,/fixed difficulty|Fixed difficulty/);assert.doesNotMatch(read('scripts/native-assistance-renderer.js'),/dispatchEvent\(new KeyboardEvent|new AudioContext|\.core\.process/);});
test('closed native registration keeps separate phases and verifier without weakening existing scenarios',()=>{const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8'),rust=read('crates/desktop-shell/src/acceptance.rs'),host=read('scripts/windows-desktop-acceptance.ps1'),profile=read('scripts/windows-desktop-profile.ps1'),input=read('scripts/native-assistance-input.cs');for(const phase of ASSISTANCE_PHASES){assert.ok(rust.includes(phase));assert.ok(host.includes(phase));assert.ok(profile.includes(phase));}assert.ok(rust.includes('include_str!("../../../scripts/native-assistance-renderer.js")'));assert.ok(host.includes("'verify-native-assistance-evidence.mjs'"));assert.ok(host.includes("'native-assistance-input.cs'"));assert.match(input,/default:throw/);assert.ok(host.includes("'human-mod-timbre'"));assert.ok(host.includes("'canonical-practice'"));});

function nativeActions(){const host={actions:3,process_id:42},target={x:10,y:20,width:100,height:30},actions=[1,2,3].map(sequence=>({version:1,sequence,kind:sequence===3?'assistance-key-c5':'click',x:60,y:35,width:1280,height:720})),hit={app_hwnd:44,hit_hwnd:45,hit_root:44,foreground:44,viewport:[1280,720],client:[0,0,1280,720],origin:[100,100],requested:[160,135],actual:[160,135],work_area:[0,0,2000,1500]},results=[{ok:true,client_click:clone(hit)},{ok:true,client_click:clone(hit)},{ok:true,native_key:{app_hwnd:44,foreground:44,app_process_id:42,app_enabled:true,code:'Digit2',virtual_key:50,hold_ms:40,focus_reacquired:false,pointer_clicked:false}}],report={phase:'assistance-restart',actions:3,keyAction:3,controls:actions.slice(0,2).map((a,i)=>({sequence:a.sequence,kind:'click',id:i?'start-performance':'song-mod-apply',request:{...a,target},samples:[{hitOwned:true,target},{hitOwned:true,target}],clicks:[{sequence:a.sequence,owned:true,trusted:true}]})),trusted:['keydown','keyup'].map(type=>({sequence:3,type,code:'Digit2',trusted:true,id:'stage-title',phase:'capturing',position:700})),inputPreparation:{focused:true,clock:{positionMs:100}},pickerObservations:[]};return{report,host,actions,results};}
test('native owner validator binds the timed key to the same foreground window, PID and genuine events',()=>{const n=nativeActions();validateAssistanceNativeActions(n.report,n.host,n.actions,n.results);for(const mutate of [v=>v.results[2].native_key.app_process_id++,v=>v.results[2].native_key.foreground++,v=>v.results[0].client_click.actual[0]++,v=>v.report.trusted[0].trusted=false,v=>v.report.controls[0].clicks[0].owned=false,v=>v.report.inputPreparation.clock.positionMs=650,v=>v.results[2].native_key.pointer_clicked=true]){const v=nativeActions();mutate(v);assert.throws(()=>validateAssistanceNativeActions(v.report,v.host,v.actions,v.results));}});

test('native assistance workflow uses the exact full Windows gate toolchain and parser dependency',async()=>{
 const {spawnSync}=await import('node:child_process'),root=new URL('../',import.meta.url),python=process.env.PYTHON||(process.platform==='win32'?'python':'python3');
 const parse=file=>{const r=spawnSync(python,['scripts/check-authoring-workflow.py',file,'--json'],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);};
 const focused=parse('.github/workflows/native-assistance.yml').jobs.assistance,full=parse('.github/workflows/windows-desktop-acceptance.yml').jobs['native-feature-acceptance'];
 for(const[prefix,key,expected]of [['actions/setup-node@','node-version','22.23.3'],['actions/setup-python@','python-version','3.12.10'],['dtolnay/rust-toolchain@','toolchain','1.99.0']]){const setting=job=>job.steps.find(s=>s.uses?.startsWith(prefix)).with[key];assert.equal(setting(full),expected);assert.equal(setting(focused),expected);}
 assert.ok(focused.steps.some(s=>s.run==='python -m pip install PyYAML==6.0.3'));assert.ok(focused.steps.some(s=>s.run==='cargo test -p worldmusichub-desktop --lib acceptance::tests --release --locked'));assert.ok(focused.steps.some(s=>s.run==='cargo build -p worldmusichub-desktop --release --locked'));assert.ok(focused.steps.every(s=>s['continue-on-error']===undefined));
});
test('assistance inventory binds actual nested source adapters and consumed renderer/audio dependencies',async()=>{
 const {ASSISTANCE_SOURCE_FILES:files,ASSISTANCE_RUNTIME_DEPENDENCIES:dependencies}=await import('../scripts/verify-native-assistance-evidence.mjs');assert.ok(files.length<=320);assert.equal(new Set(files).size,files.length);
 for(const name of ['crates/score-core/src/assistance.rs','crates/score-core/src/automatic_assistance/tests.rs','crates/score-core/src/practice_source/bounded_tests.rs','crates/score-core/src/basic_keys/conversion.rs','crates/score-core/src/basic_keys/rendition.rs','crates/score-core/src/clean_song/runtime.rs','crates/score-core/src/vsq_clean/model.rs','crates/score-core/src/vsq_clean/runtime.rs','crates/score-core/src/vsq_clean/validate.rs','crates/desktop-shell/src/clean_package.rs','web/basic-key-audio-processor.js','web/basic-key-rendition.js','web/piano-fingering.js','web/guitar-fingering.js','web/physical-targets.js','web/app-assistance.js','web/practice-assistance-display.js','web/clean-song.css'])assert.ok(files.includes(name),name);
 for(const file of dependencies)assert.ok(files.includes(file));assert.ok(files.includes('scripts/check-authoring-workflow.py'));
});

function requestObserver(owner,readContext=()=>({actionSequence:1,screen:'library',previewId:'original-fixture'})){
 const source=readFileSync(new URL('../scripts/native-assistance-renderer.js',import.meta.url),'utf8').split('(() => {')[0],rows=[],errors=[];
 const factory=vm.runInNewContext(source+';createNativeAssistanceRequestObserver',{Promise,structuredClone,TextEncoder});
 const observer=factory({fetchOwner:owner,onRequest:row=>rows.push(row),onError:error=>errors.push(error),readContext});return{observer,rows,errors};
}
test('request observer retains consumed native JSON when immediate adoption aborts a competing clone',async()=>{
 const controller=new AbortController(),response=new Response(JSON.stringify({original:'VSQ result',source:fixtures.vsq.source})),originalJson=response.json;let cloneCalls=0,jsonPromise;
 response.clone=()=>{cloneCalls++;throw new DOMException('The user aborted a request.','AbortError');};
 response.json=function(...args){jsonPromise=Reflect.apply(originalJson,this,args);return jsonPromise;};const ownJson=response.json;
 const promise=Promise.resolve(response),options={method:'POST',body:JSON.stringify({key:fixtures.vsq.source.key}),signal:controller.signal};let seen;
 const owner={fetch(...args){seen={self:this,args};return promise;}},original=owner.fetch,{observer,rows,errors}=requestObserver(owner);
 try{const returned=owner.fetch('/api/library/runtime',options);assert.equal(returned,promise);assert.equal(seen.self,owner);assert.equal(seen.args[1],options);const actual=await returned;assert.equal(actual,response);const body=actual.json();assert.equal(body,jsonPromise);const value=await body;controller.abort();await Promise.resolve();assert.equal(cloneCalls,0);assert.equal(rows[0].observation,'consumed');assert.equal(rows[0].status,200);assert.deepEqual(rows[0].response,value);assert.equal(rows[0].canceled,false);assert.equal(observer.settled(),true);assert.deepEqual(errors,[]);assert.equal(response.json,ownJson);}finally{assert.equal(observer.restore(),true);assert.equal(owner.fetch,original);}
});
test('request observer records real cancellation without changing the original rejected promise',async()=>{
 const controller=new AbortController();let reject;const promise=new Promise((_,no)=>{reject=no;}),owner={fetch:()=>promise},{observer,rows,errors}=requestObserver(owner);const failure=new DOMException('obsolete source generation','AbortError');
 try{const returned=owner.fetch('/api/library/assistance/generate',{body:'{}',signal:controller.signal});assert.equal(returned,promise);controller.abort();reject(failure);await assert.rejects(returned,error=>error===failure);await Promise.resolve();assert.equal(rows[0].observation,'fetch-rejected');assert.equal(rows[0].status,null);assert.equal(rows[0].response,null);assert.equal(rows[0].signalAborted,true);assert.equal(rows[0].errorName,'AbortError');assert.equal(rows[0].canceled,true);assert.equal(rows[0].signalGeneration,1);assert.equal(observer.settled(),true);assert.deepEqual(errors,[]);}finally{observer.restore();}
});
test('a200 response never consumed remains pending, and an actual parse failure remains a failure',async()=>{
 for(const consume of [false,true]){const response=new Response('not JSON'),json=response.json,promise=Promise.resolve(response),owner={fetch:()=>promise},{observer,rows,errors}=requestObserver(owner);try{const returned=owner.fetch('/api/library/runtime',{body:'{}'});assert.equal(await returned,response);if(consume){await assert.rejects(response.json(),SyntaxError);await Promise.resolve();assert.equal(rows[0].observation,'body-rejected');assert.equal(rows[0].canceled,false);assert.match(rows[0].error,/SyntaxError/);assert.equal(observer.settled(),true);assert.equal(errors.length,1);}else{assert.equal(rows[0].observation,'awaiting-json');assert.equal(observer.settled(),false);assert.equal(response.bodyUsed,false);assert.deepEqual(errors,[]);}assert.equal(rows[0].status,200);assert.equal(rows[0].response,null);}finally{observer.restore();assert.equal(response.json,json);}}
});
test('cancellation verifier admits only observed obsolete Basic generations at actual navigation',()=>{
 const request={source:fixtures.basic.source,selection:checked.plan.selection,settings:checked.plan.settings},started={actionSequence:1,screen:'library',previewId:`native:${fixtures.basic.source.key}`},settled={actionSequence:2,screen:'stage',previewId:started.previewId};
 const prior={path:'/api/library/assistance/generate',request,observation:'consumed',signalGeneration:1},canceled={path:prior.path,request,status:null,response:null,observation:'fetch-rejected',signalGeneration:2,signalAbortedAtStart:false,signalAborted:true,canceled:true,errorName:'AbortError',error:'AbortError: signal is aborted without reason',started,settled};
 const make=()=>({actions:2,controls:[{sequence:2,id:'start-performance'}],requests:clone([prior,canceled])});const report=make();assert.equal(validateAssistanceRequestCompletion(report.requests[1],report,1),false);
 for(const mutate of [r=>r.requests[1].path='/api/library/runtime',r=>r.requests[1].signalAborted=false,r=>r.requests[1].signalGeneration=1,r=>r.requests[1].errorName='TypeError',r=>r.requests[1].request.selection.selected_part_ids=[],r=>r.controls[0].id='song-mod-apply',r=>r.requests[1].settled.screen='library',r=>r.requests[0].observation='fetch-rejected']){const r=make();mutate(r);assert.throws(()=>validateAssistanceRequestCompletion(r.requests[1],r,1));}
});

function offTake(){const assisted=take(true),result=clone(assisted),targets=fixtures.basic.original.checked.human_targets;result.practice_assistance=null;result.practice_assistance_disabled=true;result.target_plan=clone(targets);delete result.input_evidence;const pass=result.passes[0];pass.capture_enabled=false;pass.timeline=clone(targets.timeline);pass.inputs=[];pass.captures=[];pass.interpretation.practice_assistance=null;pass.interpretation.practice_assistance_disabled=true;pass.assessment={hits:[],extras:[],misses:targets.timeline.notes.map(n=>n.id)};return{assisted,result};}
test('explicit Off marker is closed and bound to the exact current native source',()=>{validateAssistanceOffMarker(offMarker(),fixtures.basic.source);for(const mutate of [m=>m.source.content_sha256='f'.repeat(64),m=>m.source.choice='base_notes_instrumental',m=>m.preference_key='other',m=>m.version=2,m=>m.mode='original',m=>m.plan=checked.plan]){const m=offMarker();mutate(m);assert.throws(()=>validateAssistanceOffMarker(m,fixtures.basic.source));}});
test('Off reset admits a fresh silent full-part assessment with null assistance and no old input history',()=>{const {assisted,result}=offTake();validateAssistanceOffTake(result,assisted);assert.equal(result.target_plan.target_count,6);assert.equal(result.target_plan.timeline.duration_ms,1000);for(const mutate of [r=>r.practice_assistance=clone(checked),r=>r.practice_assistance_disabled=false,r=>r.target_plan.timeline.notes.pop(),r=>r.target_plan.groups[0].source_occurrence_ids=[],r=>r.passes[0].capture_enabled=true,r=>r.passes[0].inputs=[{midi:72,at_ms:750}],r=>r.input_evidence={events:[]},r=>r.passes[0].interpretation.practice_assistance_disabled=false,r=>r.passes[0].interpretation.source_revision.sourceRevision.value='f'.repeat(64)]){const f=offTake();mutate(f.result);assert.throws(()=>validateAssistanceOffTake(f.result,f.assisted));}});
test('legacy native final reset retains explicit Off and both original phases',()=>{const source=readFileSync(new URL('../scripts/native-assistance-renderer.js',import.meta.url),'utf8'),begin=source.indexOf("if(phase==='assistance-restart'){\n    await click('edit-song-mod')"),end=source.indexOf("\n   }else{",begin),section=source.slice(begin,end);assert.ok(begin>=0&&end>begin);assert.equal((section.match(/click\('song-mod-assistance-off'\)/g)||[]).length,2);assert.ok(section.includes("click('song-mod-assistance-reset')"));assert.ok(section.includes("download('off',{assess:true})"));assert.ok(section.indexOf('report.reset=')<section.indexOf("download('off'"));assert.doesNotMatch(section,/assistance-mode|assistance-check|assistance\/original/);assert.deepEqual(ASSISTANCE_PHASES.slice(0,2),['assistance-seed','assistance-restart']);});

test('only the exact assistance seed picker uses the existing verified native Edit path without UIA polling',()=>{
 const read=name=>readFileSync(new URL('../'+name,import.meta.url),'utf8'),host=read('scripts/windows-desktop-acceptance.ps1'),start=host.indexOf("    if($Scenario -ceq 'assistance' -and $env:WMH_DESKTOP_ACCEPTANCE_PHASE -ceq 'assistance-seed' -and $Action.kind -ceq 'picker' -and $Action.file -ceq 'assistance-original-songs.zip') {"),end=host.indexOf("    Record-PickerObservation $Observation 'filename-ready'",start),block=host.slice(start,end);
 assert.ok(start>=0&&end>start);const [direct,fallback]=block.split('    } else {');assert.ok(direct.includes("filename_selection_policy='closed-assistance-verified-native-first'"));assert.ok(direct.includes('Set-NativeFileName $root $dialog $App $path $Evidence'));assert.doesNotMatch(direct,/Find-FileNameEntry|Start-Sleep/);assert.ok(fallback.includes('Find-FileNameEntry $root $Evidence'));assert.ok(fallback.includes("filename_entry_method='UIA_ValuePattern'"));
 const native=host.slice(host.indexOf('function Set-NativeFileName('),host.indexOf('function Get-PickerButtonCandidate('));for(const guard of ['SelectFileNameHost','ValidateFileNameTarget','SetFileName','exact_readback=$true'])assert.ok(native.includes(guard));assert.ok(host.includes("$submittedClock=Click-PickerAction $root $dialog $App $Evidence 1 $Observation"));assert.ok(host.includes('Wait-PickerDismissal $dialog $App $Evidence $Observation $submittedClock'));assert.match(read('scripts/native-assistance-renderer.js'),/until=\(fn,label,ms=15000\)/);
 const contract=read('scripts/native-assistance-contract.ps1');for(const guard of ['SelectFileNameHost','ValidateFileNameTarget','ValidateFileNameReadback','EditReadOnly=$true','RootOwner=[IntPtr]99'])assert.ok(contract.includes(guard));assert.doesNotMatch(contract,/::SetFileName\(|::FileNameEdit\(|::Key\(|::Edit\(/);
});


// UI records below are synthetic mutation inputs; their ownership is copied
// unchanged from Rust fixtures and never presented as native execution evidence.
function presetControlReport(phase='assistance-seed'){
 const single=assistanceNativeSinglePreset(),basic=fixtures.basic.automatic;
 const view=(id,settings,response=null)=>{const {algorithm_id,...limits}=settings,c=response?.checked.coverage;return{preset:id,settings:limits,state:c?'checked':'unchecked',unitsHidden:!c,units:c?assistanceText('en','units',{human:c.human_source_unit_count,machine:c.machine_source_unit_count,total:c.source_unit_count}):'',status:c?assistanceText('en','counts',{human:c.human_target_count,machine:c.machine_occurrence_count})+(response.checked.scored_mode_allowed?'':' · '+assistanceText('en','noScore')):assistanceText('en','unchecked')};};
 const checkpoints=[['basic-single-draft',1,view('single',single.settings)],['basic-single-checked',2,view('single',single.settings,single.response)],['basic-custom-draft',6,view('custom',checked.plan.settings)],['basic-checked',7,view('custom',checked.plan.settings,basic)],['basic-custom-reopened',10,view('custom',checked.plan.settings,basic)]];
 return{phase,checkpoints:phase==='assistance-seed'?checkpoints.map(([label,actionSequence,preset])=>({label,actionSequence,preset})):[{label:'basic-custom-restored',actionSequence:2,preset:view('custom',checked.plan.settings,basic)}],controls:[{sequence:1,id:'song-mod-assistance-preset',kind:'select-first'},... [2,7].map(sequence=>({sequence,id:'song-mod-assistance-check',kind:'click'}))],trusted:[{sequence:1,id:'song-mod-assistance-preset',type:'change',trusted:true,owned:true,value:'single'}],requests:[[2,single.response],[7,basic]].map(([actionSequence,response])=>({started:{actionSequence},observation:'consumed',response:clone(response)}))};
}
test('native preset verifier requires owned Single selection, real checked counts and Custom reopen',()=>{
 validateAssistancePresetControls(presetControlReport());validateAssistancePresetControls(presetControlReport('assistance-restart'));
 for(const mutate of [r=>r.checkpoints.pop(),r=>r.trusted[0].trusted=false,r=>r.trusted[0].owned=false,r=>r.trusted[0].value='balanced',r=>r.controls[0].kind='click',
  r=>r.checkpoints[1].preset.status='99 human targets · 0 machine occurrences',r=>r.checkpoints[2].preset.units='stale Single counts',r=>r.checkpoints[2].preset.unitsHidden=false,
  r=>r.checkpoints[4].preset.settings.min_onset_interval_ms=500,r=>r.requests[0].started.actionSequence=7,r=>r.requests[0].response.checked.machine_occurrence_ids=[],r=>r.requests[1].observation='awaiting-json']){
  const report=presetControlReport();mutate(report);assert.throws(()=>validateAssistancePresetControls(report));
 }
 const restored=presetControlReport('assistance-restart');restored.checkpoints[0].preset.preset='single';assert.throws(()=>validateAssistancePresetControls(restored));
});
