import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Script,runInNewContext} from 'node:vm';
import {humanModTimbreFixture} from '../scripts/prepare-human-mod-timbre-fixtures.mjs';
import {humanModTimbreBootstrap,HUMAN_MOD_TIMBRE_BROWSER_CASE} from './human-mod-timbre-browser-regression.js';
const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8'),renderer=read('crates/desktop-shell/human-mod-timbre-acceptance.js'),shared=read('crates/desktop-shell/live-tone-navigation-acceptance.js').split('(() => {')[0];
function harness(phase){const posted=[],node={id:'import-button',isConnected:true,disabled:false,contains:()=>false,scrollIntoView(){},getBoundingClientRect:()=>({x:20,y:20,width:100,height:40})},doc={defaultView:{innerWidth:1280,innerHeight:720,performance:{timeOrigin:1000}},elementFromPoint:()=>node},context={structuredClone,TextEncoder,waitCanonicalPracticeControl:async()=>{},prepareCanonicalPracticeTarget:async()=>{},observeCanonicalPracticeOwnedClick:()=>({events:[],restore(){}}),requireCanonicalPracticeOwnedClick:async()=>{}};const make=runInNewContext(shared+'\ncreateNativeLiveToneNavigationControls',context),dispatch=make({document:doc,phase,until:async fn=>{assert.ok(await fn());},readClock:()=>({running:false}),frame:async()=>{},postAction:async row=>posted.push(row),readResult:async()=>({ok:true}),report:{controlActions:[],keyPreparations:[]},controls:{beginPicker(){},endPicker(){}}});return{node,posted,dispatch};}

test('native renderer and browser bootstrap parse and retain only the existing passive observers',()=>{assert.doesNotThrow(()=>new Script(renderer));assert.doesNotThrow(()=>new Script(humanModTimbreBootstrap));assert.doesNotMatch(renderer,/dispatchEvent|new KeyboardEvent|\.value\s*=(?!=)|\.checked\s*=(?!=)|\.click\(|\.focus\(|createOscillator|setInterval|AudioWorkletNode\(/);assert.match(renderer,/observeLiveToneAudio\(document,\{keyCode:'KeyR',midi:60/);assert.match(renderer,/observeNativeReferenceTransport\(document/);assert.match(renderer,/live\.checkpoint\('released'\)/);assert.match(renderer,/native\('live-key-r-down'/);assert.match(renderer,/native\('live-key-r-up'/);assert.ok(read('tests/full-app-browser.test.js').includes('registerHumanModTimbreBrowserRegression({'));assert.ok(HUMAN_MOD_TIMBRE_BROWSER_CASE.startsWith('real human Mod'));});

test('only three exact human phases can reuse the fixed native picker controls',async()=>{for(const phase of ['human-timbre-seed','human-timbre-migrate','human-timbre-restart']){const h=harness(phase);await assert.rejects(h.dispatch.native('picker',h.node,'live-tone-navigation-original.json'));await assert.rejects(h.dispatch.native('picker',h.node,'private-score.json'));assert.equal(h.posted.length,0);if(phase==='human-timbre-seed'){await h.dispatch.native('picker',h.node,'human-mod-timbre-original.json');assert.equal(h.posted[0].file,'human-mod-timbre-original.json');}else await assert.rejects(h.dispatch.native('picker',h.node,'human-mod-timbre-original.json'));}for(const phase of ['human-timbre','human-timbre-restart-extra','human-timbre-other'])assert.throws(()=>harness(phase));});

test('selectors use existing closed positions and unchanged 64-action bound',async()=>{const h=harness('human-timbre-migrate');for(let i=0;i<64;i++)await h.dispatch.native(i===0?'select-second':'click',h.node);assert.equal(h.posted.length,64);await assert.rejects(h.dispatch.native('click',h.node),/bound exceeded/);assert.equal(h.posted.length,64);await assert.rejects(h.dispatch.native('select-third',h.node),/Unsupported/);});

test('fixture generation is original, exact-rational and does not relabel a production source',()=>{const f=humanModTimbreFixture();assert.equal(f.score.parts.length,2);assert.equal(f.manifest.sourceNotes,4);assert.equal(f.manifest.targetNotes,2);assert.equal(f.manifest.midi,60);for(const part of f.score.parts){assert.deepEqual(part.notes.map(n=>n.at),[{numerator:0,denominator:1},{numerator:63,denominator:1}]);assert.equal(part.notes[0].pitch.octave,4);}assert.match(f.score.provenance.attribution,/Self-authored/);assert.ok(f.score.source.content.startsWith('\uFEFF'));assert.ok(f.score.source.content.includes('\r\n'));assert.doesNotMatch(read('scripts/prepare-human-mod-timbre-fixtures.mjs'),/Unity|user_import/);});
