import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validateHumanModStorageSequence,validateHumanModRenderer,validateHumanNativeSelectActivations} from '../scripts/verify-native-human-mod-timbre-evidence.mjs';
import {defaultSongMod,songModIdentity,songModConfigFingerprint,SongModStore,SONG_MOD_LEGACY_STORAGE_PREFIX} from '../web/song-mod.js';
import {humanModTimbreFixture} from '../scripts/prepare-human-mod-timbre-fixtures.mjs';
import {humanModFixtureCompilation,humanModFixtureTargets} from '../scripts/human-mod-timbre-sample-proof.mjs';
import {syntheticFixture,addSyntheticReleasedCheckpoint} from './human-mod-proof-fixtures.js';
import {liveToneCleanup} from './live-tone-evidence-fixtures.js';
// Synthetic contract fixtures only, never Windows acceptance records.
function sequence(){
 const {score}=humanModTimbreFixture(),identity=songModIdentity({score}),store=new SongModStore(),mod=defaultSongMod({score,practiceSelection:{kind:'all'}});mod.config.parts.forEach((p,i)=>p.instrument=i?'triangle':'reed');mod.configFingerprint=songModConfigFingerprint(mod.config);
 const legacy=structuredClone(mod);legacy.version=1;legacy.config.parts.forEach(p=>delete p.liveInstrument);legacy.configFingerprint=songModConfigFingerprint(legacy.config,1);
 const keys={legacyKey:store.key(identity,SONG_MOD_LEGACY_STORAGE_PREFIX),v2Key:store.key(identity)},empty={...keys,legacy:null,v2:null},old={...empty,legacy:JSON.stringify(legacy)},saved={...old,v2:JSON.stringify(mod)};
 const override=structuredClone(mod);override.config.parts[0].liveInstrument='piano';override.configFingerprint=songModConfigFingerprint(override.config);const seeded={...old,v2:JSON.stringify(override)};
 return [{version:1,evidenceRevision:2,phase:'human-timbre-seed',storageBefore:empty,storageAfter:old},{version:1,evidenceRevision:2,phase:'human-timbre-migrate',storageBefore:old,storageAfter:seeded,savedOverrideFixture:{kind:'saved-v2-compatibility-setup',before:saved.v2,after:seeded.v2}},{version:1,evidenceRevision:2,phase:'human-timbre-restart',storageBefore:seeded,storageAfter:saved,resetCancelStorage:seeded.v2}];
}
test('revision 2 discloses fixture setup separately from real migrated bytes and preserves Cancel',()=>validateHumanModStorageSequence(sequence()));
for(const [name,mutate]of [
 ['missing setup',r=>delete r[1].savedOverrideFixture],['fixture disguised as UI migration',r=>r[1].savedOverrideFixture.before=r[1].savedOverrideFixture.after],['altered legacy',r=>r[2].storageAfter.legacy+=' '],['Cancel rewrites',r=>r[2].resetCancelStorage=r[2].storageAfter.v2],['unreset override',r=>r[2].storageAfter.v2=r[2].storageBefore.v2],['mixed revision',r=>r[2].evidenceRevision=1],['undisclosed fixture mutation',r=>{const m=JSON.parse(r[1].savedOverrideFixture.after);m.config.parts[1].muted=true;m.configFingerprint=songModConfigFingerprint(m.config);r[1].savedOverrideFixture.after=r[1].storageAfter.v2=r[2].storageBefore.v2=JSON.stringify(m);r[2].resetCancelStorage=JSON.stringify(m);}]
])test(`revision 2 storage rejects ${name}`,()=>{const r=sequence();mutate(r);assert.throws(()=>validateHumanModStorageSequence(r));});
function renderer(){
 const source=humanModTimbreFixture(),report={...sequence()[1],scenario:'human-mod-timbre',origin:'https://wmh.localhost',ok:true,stage:'complete',physicalAudio:false,errors:[],actions:40,sourceScoreJson:source.bytes.toString(),compilation:humanModFixtureCompilation(),cleanup:{live:liveToneCleanup,source:liveToneCleanup},states:[{label:'legacy-read',removedLiveControls:0,resetVisible:false,parts:JSON.parse(sequence()[1].savedOverrideFixture.before).config.parts}],samples:[],files:{}},exported={};
 for(const [i,instrument]of ['guitar','piano'].entries()){
  const f=syntheticFixture({instrument}),take=structuredClone(f.options.take),plan=humanModFixtureTargets(instrument);take.score_id=source.score.id;take.practice_part=null;take.practice_selection={kind:'all',part_ids:source.score.parts.map(p=>p.id)};take.song_mod=JSON.parse(report.savedOverrideFixture.before);take.target_plan=plan;take.passes[0].timeline=structuredClone(plan.timeline);take.passes[0].range={start_ms:0,end_ms:64000};const hit=take.passes[0].assessment.hits[0];hit.note_id=plan.timeline.notes[0].id;hit.expected_ms=0;hit.delta_ms=hit.actual_ms;take.passes[0].assessment.misses=plan.timeline.notes.filter(n=>n.id!==hit.note_id).map(n=>n.id);
  const file=`human-timbre-migrate-${i+1}.json`;report.files[`${instrument}Take`]=file;exported[`${instrument}Take`]=Buffer.from(JSON.stringify(take));report.samples.push({label:instrument,expectedInstrument:instrument,performanceInstrument:instrument,keyDown:10+i*10,keyUp:11+i*10,audio:addSyntheticReleasedCheckpoint(f.e),transport:f.options.transport,takeFile:file});
 }
 report.files.afterCancel='human-timbre-migrate-3.json';exported.afterCancel=Buffer.from(exported.guitarTake);report.files.score='human-timbre-migrate-4.json';exported.score=source.bytes;return{report,exported};
}
test('revision 2 samples resolve Follow from actual settings with exact Rust target plans',()=>{const f=renderer();validateHumanModRenderer(f.report,f.exported);});
for(const [name,mutate]of [['removed control restored',f=>f.report.states[0].removedLiveControls=1],['unnecessary reset exposed',f=>f.report.states[0].resetVisible=true],['wrong actual profile',f=>f.report.samples[0].performanceInstrument='piano'],['invented PCM recipe',f=>f.report.samples[0].expectedInstrument='piano'],['Cancel changes take',f=>f.exported.afterCancel=Buffer.from('{}')],['take override masks Follow',f=>{const t=JSON.parse(f.exported.guitarTake);t.song_mod.config.parts.forEach(p=>p.liveInstrument='guitar');t.song_mod.configFingerprint=songModConfigFingerprint(t.song_mod.config);f.exported.guitarTake=f.exported.afterCancel=Buffer.from(JSON.stringify(t));}]])test(`revision 2 renderer rejects ${name}`,()=>{const f=renderer();mutate(f);assert.throws(()=>validateHumanModRenderer(f.report,f.exported));});
test('historical removed-selector receipts cannot satisfy current selection contract',()=>{const evidence=JSON.parse(readFileSync(new URL('./fixtures/native-human-timbre/windows-select-activation.json',import.meta.url)));for(const original of evidence.reports){validateHumanNativeSelectActivations(original);assert.throws(()=>validateHumanNativeSelectActivations({...original,evidenceRevision:2}));}});
function restartedRenderer(){
 const f=renderer(),r=f.report;Object.assign(r,sequence()[2]);const sample=r.samples[0];sample.label='follow';sample.takeFile='human-timbre-restart-1.json';r.samples=[sample];r.files={followTake:sample.takeFile,score:'human-timbre-restart-2.json'};r.states=[{label:'v2-reopened',removedLiveControls:0,resetVisible:false,parts:JSON.parse(r.storageBefore.v2).config.parts},{label:'listen-mode',mode:'listen'},{label:'human-mode',mode:'practice'},{label:'changed-default-conflict',startDisabled:true,summary:'Human 1 piano; Human 2 guitar'},{label:'reset-draft',resetVisible:false,applyDisabled:false,parts:JSON.parse(r.storageAfter.v2).config.parts},{label:'reset-reopened',resetVisible:true},{label:'reset-applied',resetVisible:false}];delete r.savedOverrideFixture;return{report:r,exported:{followTake:f.exported.guitarTake,score:f.exported.score}};
}
test('revision 2 restart retains compatible old preferences and proves reset-only recovery',()=>{const f=restartedRenderer();validateHumanModRenderer(f.report,f.exported);});
for(const [name,mutate]of [['silently normalized reopen',r=>r.states[0].parts[0].liveInstrument='follow'],['Start permits conflict',r=>r.states[3].startDisabled=false],['missing named owner',r=>r.states[3].summary='Human 1'],['reset still blocked',r=>r.states[4].applyDisabled=true],['reset retains override',r=>r.states[4].parts[0].liveInstrument='piano'],['Cancel loses conflict',r=>r.states[5].resetVisible=false],['Apply retains conflict',r=>r.states[6].resetVisible=true]])test(`revision 2 restart rejects ${name}`,()=>{const f=restartedRenderer();mutate(f.report);assert.throws(()=>validateHumanModRenderer(f.report,f.exported));});
