import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {runInNewContext} from 'node:vm';
import {deflateSync} from 'node:zlib';
import {storedZip} from './native-import-driver-fixtures.js';
import {digest} from './clean-song-package-fixtures.js';
import {cleanAcceptanceFixture,prepareCleanFixtures} from '../scripts/prepare-clean-song-fixtures.mjs';
import {verifyNativeCleanSongEvidence,CLEAN_PHASES,CLEAN_CHECKS,CLEAN_REPORT_BYTES} from '../scripts/verify-native-clean-song-evidence.mjs';
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
function crc32(b){let c=0xffffffff;for(const v of b){c^=v;for(let bit=0;bit<8;bit++)c=c>>>1^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function screenshot(){const chunk=(n,p)=>{const b=Buffer.alloc(p.length+12);b.writeUInt32BE(p.length);b.write(n,4);p.copy(b,8);b.writeUInt32BE(crc32(b.subarray(4,-4)),b.length-4);return b;},header=Buffer.alloc(13);header.writeUInt32BE(640);header.writeUInt32BE(360,4);header[8]=8;header[9]=2;const p=Buffer.alloc((640*3+1)*360);let state=17;for(let i=0;i<p.length;i++){state=(Math.imul(state,1664525)+1013904223)>>>0;p[i]=i%(640*3+1)===0?0:state>>>24;}return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(p)),chunk('IEND',Buffer.alloc(0))]);}
const PNG=screenshot();
function take(scoreId,target,human=false){const input={midi:60,velocity:90,at_ms:100};return{version:1,score_id:scoreId,practice_part:target,passes:[{id:1,capture_enabled:true,inputs:human?[input]:[],captures:human?[{event_id:1,event_wall_ms:1100,received_wall_ms:1101,input:{...input}}]:[],assessment:null}],input_evidence:{version:1,truncated:false,omitted_observations:0,events:human?[{event_id:1,kind:'note_on',source_id:'keyboard-r',source_generation:null,input_kind:'typing_keyboard',encoding:'key_down',midi:60,velocity:90,event_wall_ms:1100,received_wall_ms:1101,onset_capture:{pass_id:1,event_id:1}},{event_id:2,kind:'note_off',source_id:'keyboard-r',source_generation:null,input_kind:'typing_keyboard',encoding:'key_up',event_wall_ms:1110,received_wall_ms:1111,onset_capture:null},{event_id:3,kind:'boundary',source_id:null,reason:'pause',event_wall_ms:1120,received_wall_ms:1120,onset_capture:null}]:[]}};}
function transport(){const state={passId:'1',captured:'1',cue:'paused',phase:'paused',hidden:false,openDialogs:[],positionMs:900,durationMs:32000};return{version:1,stage:'complete',omitted:0,rowBytes:3000,trustedPlayClicks:2,trustedKeyDowns:1,trustedKeyUps:1,current:state,rows:[{kind:'ready',elapsedMs:0,state:{...state,positionMs:500,captured:'0'}},{kind:'event',elapsedMs:10,state:{...state},event:{type:'click',trusted:true,control:'play-button'}},{kind:'transport',elapsedMs:20,state:{...state,phase:'capturing',positionMs:600}},{kind:'event',elapsedMs:30,state:{...state},event:{type:'keydown',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}},{kind:'event',elapsedMs:40,state:{...state},event:{type:'keyup',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}},{kind:'event',elapsedMs:50,state:{...state},event:{type:'click',trusted:true,control:'play-button'}}]};}
// Protocol fixtures exercise the verifier only. No Windows, browser, server or audio is launched.
async function evidence(t){
 const directory=await mkdtemp(join(tmpdir(),'wmh-clean-proof-'));t.after(()=>rm(directory,{recursive:true,force:true}));await mkdir(join(directory,'downloads'));await prepareCleanFixtures(join(directory,'fixtures'));const fixture=cleanAcceptanceFixture(),identity=digest(JSON.stringify(fixture.metadata)),key=`song-${identity}`,runtime=JSON.parse(await readFile(new URL('./fixtures/clean-song-v2-long-runtime.json',import.meta.url))),parts=fixture.score.performance.parts.map(p=>p.id),assets=fixture.metadata.media.map(({id,role,mime,bytes,sha256,offset_ms})=>({id,role,mime,bytes,sha256,handle:`asset-${digest(`${identity}\0${id}\0${sha256}`)}`,...(offset_ms===undefined?{}:{offset_ms})}));
 const entry={library_format_version:2,revision:1,key,content_sha256:identity,score_id:fixture.metadata.id,title:fixture.metadata.title,retained_source:null,clean_package:{version:2,content_sha256:identity,bytes:[...fixture.files.values()].reduce((sum,b)=>sum+b.length,0),media:assets,coverage:fixture.score.coverage,notation_available:true}};
 const pkg={key,content_sha256:identity,metadata_sha256:digest(fixture.files.get('metadata.json')),score_sha256:digest(fixture.files.get('score.json')),runtime_sha256:digest(JSON.stringify(stable(runtime))),tracks:3,parts,notes:30,events:14,source_events:74,duration_ms:32000,media:assets};
 const exported=storedZip([...[...fixture.files].map(([p,b])=>[`songs/${key}/${p}`,b]),['manifest.json',JSON.stringify({format:'worldmusichub-song-pack',version:2,songs:[{folder:`songs/${key}`} ]})]]);
 const definitions={'clean-seed':[['picker',fixture.filename],['click'],['click'],['select-last'],['click'],['click'],['click'],['click'],['click'],['key-r'],['click'],['picker','clean-seed-3.zip'],['click']], 'clean-restart':[['click'],['select-last'],['click'],['click'],['click'],['click']]};
 const native={version:1,scenario:'clean-song',ok:true,profile_reused:false,source_sha:'1'.repeat(40),source_tree:'2'.repeat(40),executable_sha256:'3'.repeat(64),executable_bytes:80000,directory:join(directory,'Scores'),phases:CLEAN_PHASES.map((phase,i)=>({phase,process_id:100+i,renderer_ok:true,normal_close:true,renderer_origin:'https://wmh.localhost',executable_tcp_listeners:0,launched_new_process:true,profile_fresh:true,profile_reused:false,actions:definitions[phase].length}))};
 const media=Object.fromEntries(fixture.metadata.media.map(a=>[a.role,{role:a.role,width:a.role==='cover'?96:a.role==='background'?160:320,height:a.role==='cover'?64:a.role==='background'?90:180,drawnWidth:100,drawnHeight:80,bytes:a.bytes,sha256:a.sha256,pixels_sha256:'4'.repeat(64),unique_pixel_values:128,visible:true,...(a.role==='pv'?{muted:true,paused:false,currentTime:.5,readyState:4}:{})}]));
 const files={'clean-seed':{machineTake:'clean-seed-1.json',humanTake:'clean-seed-2.json',package:'clean-seed-3.zip',afterReimportTake:'clean-seed-4.json'},'clean-restart':{machineTake:'clean-restart-1.json'}},reports={},rows=[];
 const save=async(path,value)=>writeFile(join(directory,path),JSON.stringify(value,null,2)+'\n');
 for(const phase of CLEAN_PHASES){const host=native.phases.find(p=>p.phase===phase),grades=Object.fromEntries(Array.from({length:11},(_,i)=>[`grade-${i}`,'—']));reports[phase]={version:1,phase,ok:true,origin:'https://wmh.localhost',profileMarkerAbsent:true,actions:host.actions,checks:[...CLEAN_CHECKS[phase]],errors:[],openedScoreDatabases:[],package:structuredClone(pkg),directory:native.directory,inventory:[entry],media:structuredClone(media),machineBefore:{captured:'0',grades},machinePlaying:{captured:'0',grades,positionMs:600,audio:{sourceStarts:3,oscillatorStarts:3}},audioStopped:{sourceStarts:3,activeSources:0,pendingSources:0},videoFrames:{count:5,last:{presentedFrames:5,width:320,height:180,mediaTime:.5}},controls:{initialTarget:parts[0],target:parts[1],other:parts[0],humanDisabled:true,humanMachineEnabled:false,otherRestored:true},trusted:[{type:'change',trusted:true,id:'clean-song-target',value:parts[1]},{type:'change',trusted:true,part:parts[0],checked:false},{type:'change',trusted:true,part:parts[0],checked:true}],chooserObservations:definitions[phase].flatMap(([kind],i)=>kind==='picker'?[{sequence:i+1,kind,started_wall_ms:2000+i*100,finished_wall_ms:2050+i*100,completed:true,blurs:[]}]:[]),files:files[phase],downloads:Object.values(files[phase]).map(file=>({file,complete:true,success:true})),screenshots:phase==='clean-seed'?{cover:3,parts:5,playing:7,preflight:2}:{cover:1,parts:3,playing:5},importReports:[]};
  for(const [i,[kind,file]]of definitions[phase].entries()){await save(`action-${phase}-${i+1}.json`,{version:1,sequence:i+1,kind,x:10,y:20,width:1024,height:768,...(file?{file}:{})});await save(`result-${phase}-${i+1}.json`,{ok:true,client_click:{app_hwnd:1,foreground:1,actual:[10,20],requested:[10,20],viewport:[1024,768],hit_hwnd:1},...(kind==='picker'?{owned_dialog:{class:'#32770',hwnd:2,app_hwnd:1,root_owner_hwnd:1,process_id:host.process_id,app_process_id:host.process_id},picker_completion:{dialog_dismissed:true,app_enabled:true,owned_popup_visible:false}}:{})});}
  for(const n of Object.values(reports[phase].screenshots))await writeFile(join(directory,`native-action-${phase}-${n}.png`),PNG);await writeFile(join(directory,`native-${phase}.png`),PNG);await save(`downloads/${files[phase].machineTake}`,take(fixture.metadata.id,parts[1]));
 }
 const seed=reports['clean-seed'];seed.reimportAfterSequence=11;seed.transportAdmission=transport();const human=take(fixture.metadata.id,parts[1],true);await save(`downloads/${seed.files.humanTake}`,human);await save(`downloads/${seed.files.afterReimportTake}`,human);await writeFile(join(directory,'downloads',seed.files.package),exported);
 for(const [i,source]of [fixture.bytes,fixture.bytes,exported,exported].entries()){const mode=i%2?'commit':'preview';seed.importReports.push({status:200,filename:i<2?fixture.filename:seed.files.package,mode,body:{mode,source:{sha256:digest(source),bytes:source.length,retained:mode==='commit'},items:[{status:['ready','saved','duplicate','duplicate'][i],playable:true}]}});}
 const archive=async(path,b)=>{await mkdir(join(directory,'Scores',path.slice(0,path.lastIndexOf('/'))),{recursive:true});await writeFile(join(directory,'Scores',path),b);rows.push({path,bytes:b.length,sha256:digest(b)});};
 for(const area of ['clean-songs','clean-backups']){await archive(`${area}/${key}/entry.json`,Buffer.from(JSON.stringify(entry)));for(const [p,b]of fixture.files)await archive(`${area}/${key}/package/${p}`,b);}
 for(const area of ['imports','import-backups'])for(const source of [fixture.bytes,exported])await archive(`${area}/pack-${digest(source)}/source.bin`,source);
 for(const phase of CLEAN_PHASES){await save(`snapshot-${phase}.json`,{version:1,files:rows});await save(`renderer-${phase}.json`,reports[phase]);}await save('native-clean-song.json',native);return{directory,fixture,entry,key,native,reports,save,rows};
}

test('clean native verifier rederives the complete authored package and new-process evidence',async t=>{const f=await evidence(t),proof=await verifyNativeCleanSongEvidence(f.directory);assert.equal(proof.ok,true);assert.equal(proof.notes,30);assert.equal(proof.events,14);assert.equal(proof.source_events,74);assert.equal(proof.decoded_media,3);assert.equal(proof.claims.actual_audibility,false);assert.equal(proof.claims.latency_or_hardware,false);});
test('clean native verifier rejects changed native process, media, inputs and inventory',async t=>{const f=await evidence(t),original=f.reports['clean-restart'];for(const change of [r=>r.package.events=74,r=>r.package.source_events=73,r=>r.media.pv.sha256='0'.repeat(64),r=>r.media.cover.width=0,r=>r.videoFrames.count=0,r=>r.machinePlaying.captured='1',r=>r.machinePlaying.grades={grade:100},r=>r.audioStopped.pendingSources=1,r=>r.trusted[0].trusted=false,r=>r.controls.humanMachineEnabled=true,r=>r.inventory=[]]){const value=structuredClone(original);change(value);await f.save('renderer-clean-restart.json',value);await assert.rejects(verifyNativeCleanSongEvidence(f.directory));}await f.save('renderer-clean-restart.json',original);const host=structuredClone(f.native);host.phases[1].process_id=host.phases[0].process_id;await f.save('native-clean-song.json',host);await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/new process/);});
test('clean native verifier rejects exact asset loss, backup tampering and absent native chooser ownership',async t=>{const f=await evidence(t),path=`Scores/clean-backups/${f.key}/package/media/pv.webm`,original=await readFile(join(f.directory,path));await writeFile(join(f.directory,path),original.subarray(0,-1));await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/exact file changed/);await writeFile(join(f.directory,path),original);await f.save('result-clean-seed-1.json',{ok:true,client_click:{app_hwnd:1,foreground:1,actual:[10,20],requested:[10,20],viewport:[1024,768],hit_hwnd:1}});await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/picker ownership/);});
test('clean native verifier rejects machine notes masquerading as recorded human input',async t=>{const f=await evidence(t),path=`downloads/${f.reports['clean-seed'].files.machineTake}`;await f.save(path,take(f.fixture.metadata.id,f.reports['clean-seed'].controls.target,true));await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/Machine sources entered/);});
test('clean report producer, Rust admission, verifier and boundary tests share 1 MiB budget',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),post=runInNewContext(`${prefix}\npostCleanAcceptanceReport`,{TextEncoder});assert.equal(CLEAN_REPORT_BYTES,1024*1024);const rust=await readFile(new URL('../crates/desktop-shell/src/acceptance.rs',import.meta.url),'utf8');assert.match(rust,/MAX_CLEAN_REPORT_BYTES: usize = 1024 \* 1024/);assert.match(rust,/MAX_CLEAN_REPORT_BYTES \+ 1/);let sent=[];const waits={json:async(_,path,options)=>{sent.push(JSON.parse(options.body));return{};}};const large={version:1,phase:'clean-seed',ok:true,padding:'x'.repeat(77092)};assert.equal((await post({report:large,fetcher:null,waits})).delivered,true);assert.deepEqual(sent[0],large);sent=[];assert.equal((await post({report:{...large,padding:'x'.repeat(CLEAN_REPORT_BYTES)},fetcher:null,waits})).delivered,false);assert.equal(sent.length,1);assert.equal(sent[0].ok,false);assert.equal(sent[0].report_failure.limit_bytes,CLEAN_REPORT_BYTES);});
test('clean chooser observation waits until later native blur handlers finish',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),create=runInNewContext(`${prefix}\ncreateCleanChooserObserver`),listeners={},pending=[];let time=1;const target={addEventListener:(name,fn)=>listeners[name]=fn,removeEventListener:()=>{}};const observer=create({target,now:()=>time,defer:fn=>pending.push(fn)});observer.begin(1,'picker');time=2;listeners.blur({target,isTrusted:true});time=3;let ended=false;const task=observer.end(1,true).then(()=>ended=true);await Promise.resolve();assert.equal(ended,false);time=4;pending[0]();await task;assert.equal(observer.records[0].blurs[0].finished_wall_ms,4);assert.equal(observer.records[0].finished_wall_ms,4);});
test('actual Rust fixture has fourteen state commands and thirty paired notes covering seventy-four source events',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),validate=runInNewContext(`${prefix}\nvalidateCleanFixtureInventory`);const score=JSON.parse(await readFile(new URL('./fixtures/clean-song-v2-long/score.json',import.meta.url))),runtime=JSON.parse(await readFile(new URL('./fixtures/clean-song-v2-long-runtime.json',import.meta.url)));assert.deepEqual(JSON.parse(JSON.stringify(validate(score,runtime))),{tracks:3,parts:score.performance.parts.map(p=>p.id),notes:30,events:14,source_events:74,duration_ms:32000});for(const mutate of [(s,r)=>s.performance.notes.pop(),(s,r)=>s.performance.events.pop(),(s,r)=>s.coverage.source_events--,(s,r)=>s.coverage.represented_events--,(s,r)=>r.events.pop(),(s,r)=>r.notes.pop()]){const s=structuredClone(score),r=structuredClone(runtime);mutate(s,r);assert.throws(()=>validate(s,r),/inventory changed/);}});
test('native PV observation is preceded by real Reset and clock readiness',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8');const reset=source.indexOf("await native('click',$('reset-button'))"),ready=source.indexOf("Number($('progress').value)===0&&!$('play-button').disabled",reset),callback=source.indexOf('callback=video.requestVideoFrameCallback(onFrame)',ready),play=source.indexOf("await native('click',$('play-button'))",callback);assert.ok(reset>0&&ready>reset&&callback>ready&&play>callback);assert.ok(!source.includes("$('progress').value=0"));});

test('clean reimport preserves distinct boundary and receipt clocks within its observed chooser interval',async t=>{
 const f=await evidence(t),seed=f.reports['clean-seed'],row=seed.chooserObservations.find(item=>item.sequence>seed.reimportAfterSequence),time=row.started_wall_ms+10;
 row.blurs=[{trusted:true,started_wall_ms:time-1,finished_wall_ms:time+1}];await f.save('renderer-clean-seed.json',seed);
 const file=`downloads/${seed.files.afterReimportTake}`,value=JSON.parse(await readFile(join(f.directory,file),'utf8'));
 value.input_evidence.events.push({event_id:4,kind:'boundary',source_id:null,source_generation:null,input_kind:null,channel:null,midi:null,velocity:null,encoding:null,reason:'blur',event_wall_ms:time,received_wall_ms:time+.1,timestamp_basis:'application_clock',raw_timestamp_ms:null,boundary_wall_ms:time,onset_capture:null});
 await f.save(file,value);assert.equal((await verifyNativeCleanSongEvidence(f.directory)).ok,true);
 for(const edit of [event=>event.received_wall_ms=time-1,event=>event.received_wall_ms=time+2,event=>event.received_wall_ms=String(time),event=>event.boundary_wall_ms=event.received_wall_ms]){const changed=structuredClone(value);edit(changed.input_evidence.events.at(-1));await f.save(file,changed);await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/boundary|evidence/i);}
});
