import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
import {bulkAcceptanceFixtures} from '../scripts/prepare-bulk-import-fixtures.mjs';
import {storedZip,authoredLegacyPack} from './native-import-driver-fixtures.js';
import {verifyNativeBulkImportEvidence,validateBulkTakePreservation,bulkFixtureContentHash,readBulkEvidenceZip,BULK_IMPORT_PHASES,BULK_IMPORT_CHECKS} from '../scripts/verify-native-bulk-import-evidence.mjs';

const hash=value=>createHash('sha256').update(value).digest('hex'),clone=structuredClone,run=promisify(execFile);

test('streaming ZIP fixture preserves UTF-8 member names independently of Python text encoding',async()=>{
 const fixture=authoredLegacyPack(),moduleUrl=new URL('./native-import-driver-fixtures.js',import.meta.url).href;
 const program=`import {authoredLegacyPack} from ${JSON.stringify(moduleUrl)};process.stdout.write(authoredLegacyPack().bytes.toString('base64'));`;
 const {stdout}=await run(process.execPath,['--input-type=module','-e',program],{env:{...process.env,PYTHONIOENCODING:'latin-1'}});
 const fromNonUtf8=Buffer.from(stdout.trim(),'base64');
 assert.deepEqual(fromNonUtf8,fixture.bytes,'Binary UTF-8 input must not depend on a Windows stdin code page');
 const members=readBulkEvidenceZip(fromNonUtf8);
 assert.deepEqual([...members.keys()].sort(),fixture.entries.map(([name])=>name).sort());
 for(const [name,bytes]of fixture.entries)assert.deepEqual(members.get(name),Buffer.from(bytes),`Complete authored member retained: ${name}`);
 assert.ok(members.has('原创曲包/一键导入曲库.json'));
});
const script=fileURLToPath(new URL('../scripts/verify-native-bulk-import-evidence.mjs',import.meta.url));
const statuses=['ready','saved','duplicate','conflict','retained_nonplayable','error'];
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function screenshot(){
  const chunk=(name,payload)=>{const bytes=Buffer.alloc(payload.length+12);bytes.writeUInt32BE(payload.length);bytes.write(name,4);payload.copy(bytes,8);bytes.writeUInt32BE(crc32(bytes.subarray(4,-4)),bytes.length-4);return bytes;};
  const header=Buffer.alloc(13);header.writeUInt32BE(640);header.writeUInt32BE(360,4);header[8]=8;header[9]=2;
  const pixels=Buffer.alloc((640*3+1)*360);let state=17;for(let offset=0;offset<pixels.length;offset++){state=(Math.imul(state,1664525)+1013904223)>>>0;pixels[offset]=offset%(640*3+1)===0?0:state>>>24;}
  return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);
}
const PNG=screenshot();
function take(scoreId){const input={midi:60,velocity:90,at_ms:100};return{version:1,score_id:scoreId,passes:[{id:1,capture_enabled:true,inputs:[input],captures:[{event_id:1,event_wall_ms:1100,received_wall_ms:1101,input:{...input}}],assessment:{hits:[{note_id:'c4',input_index:0}],misses:[],extra_inputs:[]}}],input_evidence:{version:1,truncated:false,omitted_observations:0,events:[{event_id:1,kind:'note_on',source_id:'keyboard-r',source_generation:null,input_kind:'typing_keyboard',encoding:'key_down',midi:60,velocity:90,event_wall_ms:1100,received_wall_ms:1101,onset_capture:{pass_id:1,event_id:1}},{event_id:2,kind:'note_off',source_id:'keyboard-r',source_generation:null,input_kind:'typing_keyboard',encoding:'key_up',event_wall_ms:1110,received_wall_ms:1111,onset_capture:null},{event_id:3,kind:'boundary',source_id:null,reason:'pause',event_wall_ms:1120,received_wall_ms:1120,onset_capture:null}]}};}
function transport(){const state={passId:'1',captured:'1',cue:'paused',phase:'paused',hidden:false,openDialogs:[],positionMs:300,durationMs:8000};return{version:1,stage:'complete',omitted:0,rowBytes:3000,trustedPlayClicks:2,trustedKeyDowns:1,trustedKeyUps:1,current:state,rows:[{kind:'ready',elapsedMs:0,state:{...state,positionMs:0,captured:'0'}},{kind:'event',elapsedMs:10,state:{...state},event:{type:'click',trusted:true,control:'play-button'}},{kind:'transport',elapsedMs:20,state:{...state,phase:'capturing',positionMs:100}},{kind:'event',elapsedMs:30,state:{...state},event:{type:'keydown',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}},{kind:'event',elapsedMs:40,state:{...state},event:{type:'keyup',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}},{kind:'event',elapsedMs:50,state:{...state},event:{type:'click',trusted:true,control:'play-button'}}]};}
function zipInventory(bytes,filename){const members=/\.zip$/i.test(filename)?readBulkEvidenceZip(bytes):new Map([[filename,bytes]]);return{files:[...members].map(([path,value])=>({path,bytes:value.length,sha256:hash(value)})).sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0),expanded_bytes:[...members.values()].reduce((sum,value)=>sum+value.length,0)};}

// Independently authored protocol observations only. These tests launch Node,
// never a native app, GUI, browser, or server. They are verifier unit tests.
async function evidence(t){
  const directory=await mkdtemp(join(tmpdir(),'wmh-bulk-verifier-'));t.after(()=>rm(directory,{recursive:true,force:true}));const fixtures=bulkAcceptanceFixtures(),original=fixtures.files.get('原创曲包_日本語.zip'),originalZip=readBulkEvidenceZip(original),conflictZip=readBulkEvidenceZip(fixtures.files.get('bulk-conflict.zip'));
  await mkdir(join(directory,'downloads'));await mkdir(join(directory,'fixtures'));await writeFile(join(directory,'fixtures','bulk-fixtures.json'),JSON.stringify(fixtures.manifest));for(const [name,bytes]of fixtures.files)await writeFile(join(directory,'fixtures',name),bytes);for(const area of ['songs','backups','imports','import-backups','.staging','.import-staging'])await mkdir(join(directory,'Scores',area),{recursive:true});
  const snapshots=[],payloads=new Map(),entries=fixtures.scores.map((score,index)=>{const raw=[...originalZip.values(),...conflictZip.values()].find(value=>{try{return JSON.stringify(JSON.parse(value))===JSON.stringify(score);}catch{return false;}}),key=`song-${bulkFixtureContentHash(score)}`,source=Buffer.from(score.source.content);payloads.set(key,raw);return{library_format_version:1,revision:1,key,content_sha256:key.slice(5),score_sha256:hash(raw),score_bytes:raw.length,score_id:score.id,title:score.title,composer:score.composer,label:score.title,saved_at_unix_ms:1700000000000+index,provenance:score.provenance,retained_source:{format:score.source.format,filename:score.source.filename,bytes:source.length,sha256:hash(source)}};});
  const unifiedMembers=[],folders=[];for(const [index,entry]of entries.entries()){const folder=`songs/${entry.key}`;folders.push({folder});unifiedMembers.push([`${folder}/score.json`,payloads.get(entry.key)],[`${folder}/metadata.json`,JSON.stringify({format:'worldmusichub-song',version:1,title:entry.title,score:'score.json',sources:[],media:{},label:entry.label})]);}unifiedMembers.push(['manifest.json',JSON.stringify({format:'worldmusichub-song-pack',version:1,songs:folders})]);const unified=storedZip(unifiedMembers);
  const seedFiles={beforeScore:'bulk-seed-1.json',beforeTake:'bulk-seed-2.json',original:'bulk-seed-3.zip',unified:'bulk-seed-4.zip',afterScore:'bulk-seed-5.json',afterTake:'bulk-seed-6.json'},restartFiles={original:'bulk-restart-1.zip'},sources=new Map(fixtures.files);sources.set(seedFiles.unified,unified);
  function report(filename,mode,outcomes,{index=null,keepBoth=false}={}){const bytes=sources.get(filename),items=outcomes.map(([status,entryIndex],index)=>({index,path:status==='retained_nonplayable'?'original-events/metadata.json':`song-${index}/score.json`,title:entryIndex===undefined?'Original unsupported event source':entries[entryIndex].title,status,code:status==='conflict'?'library_id_conflict':`pack_${status}`,message:`Authored ${status} result`,playable:status!=='retained_nonplayable',...(['saved','duplicate','conflict'].includes(status)?{entry:clone(entries[entryIndex])}:{})}));return{status:200,filename,mode,index,keepBoth,body:{format:'worldmusichub-import-report',version:1,mode,source:{filename,sha256:hash(bytes),bytes:bytes.length,retained:mode==='commit',archive_key:`pack-${hash(bytes)}`},items,summary:{...Object.fromEntries(statuses.map(status=>[status,items.filter(item=>item.status===status).length])),total:items.length},inventory:zipInventory(bytes,filename),warnings:[]}};}
  const observations=[report('原创曲包_日本語.zip','preview',[['ready',0],['ready',1],['retained_nonplayable']]),report('原创曲包_日本語.zip','commit',[['saved',0],['saved',1],['retained_nonplayable']]),report('原创曲包_日本語.zip','preview',[['duplicate',0],['duplicate',1],['retained_nonplayable']]),report('原创曲包_日本語.zip','commit',[['duplicate',0],['duplicate',1],['retained_nonplayable']]),report('bulk-backup.json','preview',[['duplicate',0],['duplicate',1]]),report('bulk-backup.json','commit',[['duplicate',0],['duplicate',1]]),report('bulk-conflict.zip','preview',[['conflict',0]]),report('bulk-conflict.zip','commit',[['conflict',0]]),report('bulk-conflict.zip','commit',[['saved',2]],{index:0,keepBoth:true}),report(seedFiles.unified,'preview',[['duplicate',0],['duplicate',1],['duplicate',2]]),report(seedFiles.unified,'commit',[['duplicate',0],['duplicate',1],['duplicate',2]]),{status:400,filename:'bulk-malformed.zip',mode:'preview',index:null,keepBoth:false,body:{code:'pack_invalid',error:'Original intentionally malformed ZIP'}}];
  observations.splice(6,0,report('bulk-standard-a.json','preview',[['duplicate',0]]),report('bulk-standard-b.json','preview',[['duplicate',1]]),report('bulk-standard-a.json','commit',[['duplicate',0]]),report('bulk-standard-b.json','commit',[['duplicate',1]]));
  const definitions={'bulk-seed':[['click'],['key-r'],['click'],['picker','原创曲包_日本語.zip'],['click'],['click'],['picker','原创曲包_日本語.zip'],['click'],['picker','bulk-backup.json'],['click'],['picker','bulk-multiple'],['click'],['picker','bulk-conflict.zip'],['click'],['click'],['picker',seedFiles.unified],['click'],['cancel-picker'],['picker','bulk-malformed.zip'],['click']], 'bulk-restart':[['click'],['click'],['click']], 'bulk-failure':[['picker','bulk-failure.zip'],['click']]};
  const phases=BULK_IMPORT_PHASES.map((phase,index)=>({phase,process_id:100+index,renderer_ok:true,renderer_origin:'https://wmh.localhost',normal_close:true,executable_tcp_listeners:0,launched_new_process:true,profile_fresh:true,profile_reused:false,actions:definitions[phase].length})),native={version:1,scenario:'bulk-import',ok:true,profile_reused:false,source_sha:'1'.repeat(40),source_tree:'2'.repeat(40),executable_sha256:'3'.repeat(64),executable_bytes:80000,directory:join(directory,'Scores'),phases};
  const reports=Object.fromEntries(BULK_IMPORT_PHASES.map((phase,index)=>[phase,{version:1,phase,ok:true,origin:'https://wmh.localhost',profileMarkerAbsent:true,checks:[...BULK_IMPORT_CHECKS[phase]],openedScoreDatabases:[],errors:[],directory:native.directory,actions:phases[index].actions,importReports:[],downloads:[],files:{}}]));
  Object.assign(reports['bulk-seed'],{inventory:clone(entries),importReports:observations,files:seedFiles,transportAdmission:transport(),screenshots:{preflight:5,saved:6,history:20}});Object.assign(reports['bulk-restart'],{inventory:clone(entries),files:restartFiles,audition:{sourceStarts:2,activeSources:0,pendingSources:0},screenshots:{history:3}});
  Object.assign(reports['bulk-failure'],{screenshots:{failure:2},importReports:[report('bulk-failure.zip','preview',[['ready',0]]),{status:422,filename:'bulk-failure.zip',mode:'commit',index:null,keepBoth:false,body:{code:'library_unsafe_path',error:'Native .import-staging path is not an ordinary directory'}}],failure:{filename:'bulk-failure.zip',code:'library_unsafe_path',phase:'failed',persistence:'not-saved',retryVisible:true,message:'Native storage is unavailable. Retry this file after restoring access.'}});
  for(const phase of ['bulk-seed','bulk-restart'])reports[phase].downloads=Object.values(reports[phase].files).map(file=>({file,complete:true,success:true}));
  const values={beforeScore:clone(fixtures.scores[0]),afterScore:clone(fixtures.scores[0]),beforeTake:take(fixtures.scores[0].id),afterTake:take(fixtures.scores[0].id)};
  for(const phase of BULK_IMPORT_PHASES)reports[phase].chooserObservations=definitions[phase].map(([kind],index)=>({sequence:index+1,kind,started_wall_ms:2000+(index+1)*100,finished_wall_ms:2050+(index+1)*100,completed:true,blurs:[]})).filter(row=>['picker','cancel-picker'].includes(row.kind));
  reports['bulk-seed'].chooserObservations.forEach((row,index)=>{const time=row.started_wall_ms+10;row.blurs.push({trusted:true,started_wall_ms:time-1,finished_wall_ms:time+1});values.afterTake.input_evidence.events.push({event_id:4+index,kind:'boundary',source_id:null,source_generation:null,input_kind:null,channel:null,midi:null,velocity:null,encoding:null,reason:'blur',event_wall_ms:time,received_wall_ms:time,timestamp_basis:'application_clock',raw_timestamp_ms:null,boundary_wall_ms:time,onset_capture:null})});
  async function saveJson(path,value){await writeFile(join(directory,path),JSON.stringify(value,null,2)+'\n');}
  async function writeReport(phase){await saveJson(`renderer-${phase}.json`,reports[phase]);}
  async function archive(path,bytes){await mkdir(join(directory,'Scores',path.slice(0,path.lastIndexOf('/'))),{recursive:true});await writeFile(join(directory,'Scores',path),bytes);snapshots.push({path,sha256:hash(bytes),bytes:bytes.length});}
  for(const area of ['songs','backups'])for(const [index,entry]of entries.entries())for(const [name,bytes]of [['metadata.json',Buffer.from(JSON.stringify(entry))],['score.json',payloads.get(entry.key)],['source.payload',Buffer.from(fixtures.scores[index].source.content)]])await archive(`${area}/${entry.key}/${name}`,bytes);
  const committed=observations.filter(row=>row.mode==='commit'&&row.status===200),archiveKeys=[...new Set(committed.map(row=>row.body.source.archive_key))];for(const area of ['imports','import-backups'])for(const key of archiveKeys){const rows=committed.filter(row=>row.body.source.archive_key===key),source=rows[0].body.source;for(const [name,bytes]of [['source.bin',sources.get(source.filename)],['source.json',Buffer.from(JSON.stringify(source))],['inventory.json',Buffer.from(JSON.stringify(rows[0].body.inventory))],...rows.map((row,index)=>[`report-${String(1700000000000000000n+BigInt(index)).padStart(32,'0')}-${String(index).padStart(20,'0')}.json`,Buffer.from(JSON.stringify(row.body))])])await archive(`${area}/${key}/${name}`,bytes);}
  for(const phase of BULK_IMPORT_PHASES){for(const [index,[kind,file]]of definitions[phase].entries()){const sequence=index+1,pid=phases.find(row=>row.phase===phase).process_id;await saveJson(`action-${phase}-${sequence}.json`,{version:1,sequence,kind,x:10,y:20,width:1024,height:768,...(file?{file}:{})});await saveJson(`result-${phase}-${sequence}.json`,{ok:true,...(['picker','cancel-picker'].includes(kind)?{owned_dialog:{hwnd:2,class:'#32770',process_id:pid,app_process_id:pid,app_hwnd:1,root_owner_hwnd:1},picker_completion:{dialog_dismissed:true,app_enabled:true,owned_popup_visible:false}}:{})});}await writeFile(join(directory,`native-${phase}.png`),PNG);for(const sequence of Object.values(reports[phase].screenshots))await writeFile(join(directory,`native-action-${phase}-${sequence}.png`),PNG);await saveJson(`snapshot-${phase}.json`,{version:1,files:snapshots});await writeReport(phase);}
  for(const [role,value]of Object.entries(values))await saveJson(`downloads/${seedFiles[role]}`,value);for(const [path,bytes]of [[seedFiles.original,original],[seedFiles.unified,unified],[restartFiles.original,original]])await writeFile(join(directory,'downloads',path),bytes);await saveJson('native-bulk-import.json',native);
  return{directory,native,reports,fixtures,entries,payloads,values,snapshots,saveJson,writeReport};
}

test('rederives authored bulk evidence from exact archives, retained originals, downloads and native actions',async t=>{const f=await evidence(t),proof=await verifyNativeBulkImportEvidence(f.directory);assert.equal(proof.ok,true);assert.equal(proof.entry_count,3);assert.equal(proof.retained_archive_count,6);assert.equal(proof.typing_note_on_count,1);assert.equal(proof.scored_input_count,1);assert.equal(proof.files.filter(row=>row.path.startsWith('downloads/')).length,7);assert.equal(proof.original_sha256,hash(f.fixtures.files.get('原创曲包_日本語.zip')));for(const row of proof.files){const bytes=await readFile(join(f.directory,row.path));assert.equal(row.sha256,hash(bytes));assert.equal(row.bytes,bytes.length);}});

test('host source, executable, phase order, profiles and renderer evidence fail closed',async t=>{const f=await evidence(t);for(const edit of [v=>v.ok=false,v=>v.source_sha+='\n',v=>v.source_tree='invalid',v=>v.executable_sha256='0',v=>v.executable_bytes=0,v=>v.scenario='song-folder',v=>v.profile_reused=true,v=>v.phases.reverse(),v=>v.phases[1].normal_close=false,v=>v.phases[0].executable_tcp_listeners=1,v=>v.phases[2].actions=65,v=>v.phases[1].profile_fresh=false]){const value=clone(f.native);edit(value);await f.saveJson('native-bulk-import.json',value);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/Native|native/);}await f.saveJson('native-bulk-import.json',f.native);for(const edit of [v=>v.ok=false,v=>v.origin='http://localhost',v=>v.profileMarkerAbsent=false,v=>v.openedScoreDatabases=['worldmusichub.scores.v1'],v=>v.errors=['failure'],v=>v.checks=[],v=>v.directory='relative/Scores']){const value=clone(f.reports['bulk-seed']);edit(value);await f.saveJson('renderer-bulk-seed.json',value);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/Renderer|native|Native/);}});

test('real picker results require ownership, completion, sequential actions and exact selected sources',async t=>{const f=await evidence(t),path='result-bulk-seed-4.json',original=JSON.parse(await readFile(join(f.directory,path)));for(const edit of [v=>v.ok=false,v=>delete v.owned_dialog,v=>v.owned_dialog.process_id=999,v=>v.owned_dialog.root_owner_hwnd=99,v=>v.picker_completion.dialog_dismissed=false,v=>v.picker_completion.app_enabled=false]){const value=clone(original);edit(value);await f.saveJson(path,value);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/Native bulk-seed/);}await f.saveJson(path,original);await f.saveJson('action-bulk-seed-21.json',{version:1});await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/bounded and sequential/);await rm(join(f.directory,'action-bulk-seed-21.json'));const action=JSON.parse(await readFile(join(f.directory,'action-bulk-seed-4.json')));action.file='../outside.zip';await f.saveJson('action-bulk-seed-4.json',action);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/picker fixture invalid/);});

test('native summaries, exact byte identities and per-item Keep both cannot replace real outcomes',async t=>{const f=await evidence(t),seed=f.reports['bulk-seed'];for(const edit of [v=>v.importReports[1].body.summary.saved=3,v=>v.importReports[0].body.source.sha256='0'.repeat(64),v=>v.importReports[1].body.items[2].playable=true,v=>v.importReports[12].index=null,v=>v.importReports[12].keepBoth=false,v=>v.importReports[13].body.items[0].status='saved',v=>v.importReports.pop()]){const value=clone(seed);edit(value);await f.saveJson('renderer-bulk-seed.json',value);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/Native|native|Retained|Seed/);}});

test('failure must remain unsaved, actionable and preserve all archive snapshots',async t=>{const f=await evidence(t),failure=f.reports['bulk-failure'];for(const edit of [v=>v.failure.retryVisible=false,v=>v.failure.persistence='saved',v=>v.failure.message='',v=>v.importReports[1].body.code='library_duplicate',v=>v.importReports=[]]){const value=clone(failure);edit(value);await f.saveJson('renderer-bulk-failure.json',value);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/Failed native|Failure/);}await f.saveJson('renderer-bulk-failure.json',failure);const rows=clone(f.snapshots);rows[0].sha256='0'.repeat(64);await f.saveJson('snapshot-bulk-failure.json',{version:1,files:rows});await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/snapshot does not match/);});

test('exact canonical, source, import receipts and independent backups reject tampering',async t=>{const f=await evidence(t),key=f.entries[0].key,paths=[`Scores/songs/${key}/score.json`,`Scores/songs/${key}/source.payload`,`Scores/backups/${key}/metadata.json`,f.snapshots.find(row=>row.path.startsWith('import-backups/')&&row.path.endsWith('/source.bin')).path];for(let path of paths){if(!path.startsWith('Scores/'))path=`Scores/${path}`;const original=await readFile(join(f.directory,path));await writeFile(join(f.directory,path),Buffer.concat([original,Buffer.from('\n')]));await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/exact authored|retained source|byte-identical|Retained import source/);await writeFile(join(f.directory,path),original);}const receipt=f.snapshots.find(row=>row.path.startsWith('imports/')&&row.path.includes('/report-'));await f.saveJson(`Scores/${receipt.path}`,{ok:true});await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/receipt differs/);});

test('exports require distinct successful native downloads and unchanged positive scored take',async t=>{const f=await evidence(t),seed=f.reports['bulk-seed'];for(const edit of [v=>v.files.original='../outside.zip',v=>v.files.afterTake=v.files.beforeTake,v=>v.downloads[0].success=false,v=>v.transportAdmission.rows[1].event.trusted=false]){const value=clone(seed);edit(value);await f.saveJson('renderer-bulk-seed.json',value);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/filename|distinct|download|Native transport/);}await f.writeReport('bulk-seed');for(const role of ['beforeTake','afterTake']){const take=clone(f.values[role]);take.passes[0].inputs=[];await f.saveJson(`downloads/${seed.files[role]}`,take);}await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/scored input/);});

test('PNG screenshots, unlisted archives, failure staging blockers and symlinks fail closed',async t=>{const f=await evidence(t),path=join(f.directory,'native-bulk-seed.png');await writeFile(path,PNG.subarray(0,30));await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/nontrivial PNG/);await writeFile(path,PNG);await mkdir(join(f.directory,'Scores','songs','unlisted'));await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/unlisted archives/);await rm(join(f.directory,'Scores','songs','unlisted'),{recursive:true});await rm(join(f.directory,'Scores','.import-staging'),{recursive:true});await writeFile(join(f.directory,'Scores','.import-staging'),'blocked');await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/ordinary without links/);});

test('evidence filesystem symlinks cannot substitute valid archive bytes',{skip:process.platform==='win32'?'Windows symlink creation needs separate privilege':false},async t=>{const f=await evidence(t),key=f.entries[0].key,primary=join(f.directory,'Scores','songs',key,'score.json'),backup=join(f.directory,'Scores','backups',key,'score.json');await rm(backup);await symlink(primary,backup);await assert.rejects(verifyNativeBulkImportEvidence(f.directory),/ordinary without links/);});

test('ZIP reader rejects duplicate/traversal members, CRC corruption, unlisted bytes and oversized output',()=>{const zip=storedZip([['manifest.json','{}']]);assert.equal(readBulkEvidenceZip(zip).get('manifest.json').toString(),'{}');for(const bytes of [storedZip([['../outside','x']]),storedZip([['same','x'],['same','y']]),Buffer.concat([zip,Buffer.from('junk')])])assert.throws(()=>readBulkEvidenceZip(bytes),/ZIP/);const bad=Buffer.from(zip);bad[30+Buffer.byteLength('manifest.json')]^=1;assert.throws(()=>readBulkEvidenceZip(bad),/CRC/);const unknown=clone(bulkAcceptanceFixtures().scores[0]);unknown.title='Changed';assert.throws(()=>bulkFixtureContentHash(unknown),/Unknown authored/);});

test('CLI rederives proof, check preserves bytes, and failed regeneration removes stale proof',async t=>{const f=await evidence(t),output=join(f.directory,'native-bulk-import-files.json');assert.match((await run(process.execPath,[script,f.directory])).stdout,/Verified three native bulk-import editions/);const proof=JSON.parse(await readFile(output)),stored=Buffer.from(JSON.stringify(proof)+'\n\n');await writeFile(output,stored);for(const args of [['--check',f.directory],[f.directory,'--check']]){assert.match((await run(process.execPath,[script,...args])).stdout,/stored proof matches/);assert.deepEqual(await readFile(output),stored);}const changed=clone(proof);changed.entry_count=99;await writeFile(output,JSON.stringify(changed));await assert.rejects(run(process.execPath,[script,'--check',f.directory]),error=>error.code===1&&/Stored native bulk-import proof differs/.test(error.stderr));assert.deepEqual(JSON.parse(await readFile(output)),changed);await writeFile(join(f.directory,'downloads',f.reports['bulk-seed'].files.original),'corrupt');await assert.rejects(run(process.execPath,[script,f.directory]),error=>error.code===1&&/original export differs/.test(error.stderr));await assert.rejects(readFile(output),{code:'ENOENT'});});

test('only causally observed native chooser blur boundaries may append to the exact retained take',async t=>{
 const f=await evidence(t),before=f.values.beforeTake,after=f.values.afterTake,observations=f.reports['bulk-seed'].chooserObservations,actions=observations.map(({sequence,kind})=>({sequence,kind}));
 assert.equal(validateBulkTakePreservation(before,after,observations,actions).chooser_blur_boundary_count,8);
 const noBlur=clone(observations);for(const row of noBlur)row.blurs=[];assert.equal(validateBulkTakePreservation(before,clone(before),noBlur,actions).chooser_blur_boundary_count,0);
 for(const edit of [
  value=>value.input_evidence.events[0].midi++,value=>value.input_evidence.events.reverse(),value=>value.input_evidence.events.splice(0,1),value=>value.input_evidence.truncated=true,value=>value.input_evidence.omitted_observations++,
  value=>value.passes[0].inputs[0].at_ms++,value=>value.passes[0].captures[0].event_wall_ms++,value=>value.passes[0].assessment.hits=[],
  value=>value.input_evidence.events[3].kind='note_on',value=>value.input_evidence.events[3].kind='note_off',value=>value.input_evidence.events[3].kind='synthetic_release',value=>value.input_evidence.events[3].reason='hidden',value=>value.input_evidence.events[3].midi=60,value=>value.input_evidence.events[3].onset_capture={pass_id:1,event_id:2},value=>value.input_evidence.events[3].event_id++,value=>value.input_evidence.events[3].event_wall_ms=0,value=>value.input_evidence.events[3].received_wall_ms++,value=>value.input_evidence.events[3].unexpected=true
 ]){const value=clone(after);edit(value);assert.throws(()=>validateBulkTakePreservation(before,value,observations,actions),/evidence|Scored take|boundary/i)}
 for(const edit of [value=>value.pop(),value=>value[0].sequence++,value=>value[0].kind='click',value=>value[0].completed=false,value=>value[0].blurs[0].trusted=false,value=>value[0].blurs=[],value=>value[0].blurs[0].started_wall_ms=0,value=>value[0].blurs[0].finished_wall_ms=Infinity,value=>value[0].blurs.push(clone(value[0].blurs[0]))]){const value=clone(observations);edit(value);assert.throws(()=>validateBulkTakePreservation(before,after,value,actions),/chooser|boundary/i)}
 const held=clone(before);held.input_evidence.events.splice(1,1);assert.throws(()=>validateBulkTakePreservation(held,clone(held),noBlur,actions),/unreleased/);
});
