import {validateVsqNativeKey,validateVsqHumanScore} from '../scripts/vsq-human-key-proof.mjs';
import './vsq-audio-thread-proof.test.js';
import {syntheticVsqAudioThreadRun} from './vsq-audio-thread-proof-fixtures.js';
import {syntheticAudioThreadStatus} from './audio-thread-proof-fixtures.js';
import {addNativeProfileEvidence,assertNativeProfileEvidence} from './native-profile-evidence-fixtures.js';
// Original fixture and adversarial evidence checks. Synthetic reports are never
// presented as real-browser/Windows acceptance.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {deflateSync} from 'node:zlib';
import {digest} from './clean-song-package-fixtures.js';
import {storedZip} from './native-import-driver-fixtures.js';
import {runInNewContext} from 'node:vm';
import {vsqAcceptanceFixture,prepareVsqFixtures} from '../scripts/prepare-vsq-song-fixtures.mjs';
import {validateVsqFollowing,validateVsqFollowingCapture,validateVsqFollowingSurface,validateVsqRenderer,validateVsqPickerEvidence,validateVsqPickerGestures,validateVsqTake,verifyNativeVsqSongEvidence,VSQ_COMMON_CHECKS} from '../scripts/verify-native-vsq-song-evidence.mjs';
import {syntheticVsqFingering} from './vsq-fingering-evidence-fixtures.js';
import './vsq-fingering-evidence.test.js';
import {readBulkEvidenceZip} from '../scripts/verify-native-bulk-import-evidence.mjs';
const fixture=vsqAcceptanceFixture(),runtime=fixture.runtime;
const audio={sourceStarts:0,oscillatorStarts:0,activeSources:0,pendingSources:0,worklet:syntheticAudioThreadStatus()};
const liveAudio=()=>({...audio,worklet:syntheticAudioThreadStatus({activeReceivers:1})});
const silentVsqRun=options=>{const run=syntheticVsqAudioThreadRun(runtime,options);run.pcm.blocks.forEach(block=>{block.peak=0;block.rms=0;});return run;};
function following(response=runtime){const points=[0,100,200,500,1000,response.runtime.notes[0].end_ms,1500,2000,3000,response.navigation.written_end_ms,(response.navigation.written_end_ms+response.runtime.end_ms)/2,response.runtime.end_ms].filter(t=>t<=response.runtime.end_ms).sort((a,b)=>a-b);return points.map(positionMs=>{const o=positionMs<response.runtime.end_ms?response.navigation.occurrences.find(o=>o.start_ms<=positionMs&&positionMs<o.end_ms):null;return{positionMs,durationMs:response.runtime.end_ms,ids:o?response.runtime.notes.filter(n=>n.start_ms<=positionMs&&positionMs<n.end_ms).map(n=>n.note_id):[],measure:o?String(o.source_measure_index):'',renderer:'playing',cue:null};});}
function originalReport(){const evidence=syntheticVsqFingering(fixture),tracks=fixture.score.authoring.tracks.map(t=>t.common.name),choice={preview:'choice',listenDisabled:true,practiceDisabled:true,fullVocalDisabled:true,fullVocalVisible:true,choiceVisible:true,limits:8,tracks,audio:{...audio,sourceStarts:0,oscillatorStarts:0,worklet:syntheticAudioThreadStatus({started:0,completed:0})},runtimeRequests:0};return{
 version:1,phase:'vsq-restart',assessmentRequests:[],assessmentResponses:[],assessmentObservations:[],origin:'https://wmh.localhost',profileMarkerAbsent:true,ok:true,stage:'complete',diagnostics:[{stage:'complete',elapsedMs:10}],checks:[...VSQ_COMMON_CHECKS],errors:[],
 chineseChoice:{button:'选择基础音符器乐练习',vocal:'完整歌声不可用',description:'源歌手与参考乐器分开',limits:Array(8).fill('不可用')},inventory:[{key:fixture.key,score_id:fixture.metadata.id,library_format_version:2,revision:1,content_sha256:fixture.opened.clean_package.content_sha256,score_sha256:digest(fixture.opened.score_json),score_bytes:Buffer.byteLength(fixture.opened.score_json),clean_package:fixture.summary}],opened:structuredClone(fixture.opened),beforeChoice:choice,afterChoice:{...choice,preview:'ready',listenDisabled:false,practiceDisabled:false,runtimeRequests:1},reloadChoice:{...choice,runtimeRequests:1},
 pickerObservations:[],responseObservations:[{path:'/api/library/runtime',status:200,state:'consumed'}],runtimeResponses:[{path:'/api/library/runtime',status:200,body:structuredClone(runtime)}],requests:evidence.requests,fingering:evidence.fingering,following:following(),followingCapture:{before:{frame:following()[2],audio:liveAudio()},after:{frame:following()[3],audio:liveAudio()}},followingSurface:{id:'notation-lane-overlay',bounds:{x:18,y:109,width:1244,height:361},viewport:{width:1280,height:720},visibleSvgCount:1},seekPositionMs:2042,seekThread:[silentVsqRun({positionMs:2042})],resumeThread:[syntheticVsqAudioThreadRun(runtime,{cancelMs:250}),syntheticVsqAudioThreadRun(runtime,{positionMs:250,receiverId:2})],soloThread:[syntheticVsqAudioThreadRun(runtime,{soloParts:['vsq-track-1']})],mutedThread:[silentVsqRun({mode:'practice',targetPart:'vsq-track-2',mutedParts:['vsq-track-1'],cancelMs:250})],guitarThread:[syntheticVsqAudioThreadRun(runtime,{mode:'practice',targetPart:'vsq-track-1',instrument:'guitar',cancelMs:250})],listenAudio:liveAudio(),listenThread:[syntheticVsqAudioThreadRun(runtime)],pauseThread:[syntheticVsqAudioThreadRun(runtime,{cancelMs:250})],machineThread:[syntheticVsqAudioThreadRun(runtime,{mode:'practice',targetPart:'vsq-track-2',cancelMs:300})],receiverCleanup:{restored:true,overflow:false,errors:[],cleanupErrors:[]},listenStopped:audio,pauseAudio:audio,navigationAudio:audio,machineStopped:audio,finalAudio:audio,pauseClock:{before:250,after:250},controls:{initial:'vsq-track-1',target:'vsq-track-2',other:'vsq-track-1',humanDisabled:true,humanMachineEnabled:false,otherRestored:true},machinePlaying:{captured:'0',positionMs:300,audio:liveAudio()},
 trusted:[{id:'progress',type:'input',trusted:true},...Array.from({length:2},()=>({type:'click',trusted:true,part:'vsq-track-1'})),...evidence.trusted,{type:'click',trusted:true,id:'vsq-choose-base-notes'},{type:'change',trusted:true,id:'clean-song-target',value:'vsq-track-2'},...[false,true].map(checked=>({type:'change',trusted:true,part:'vsq-track-1',checked}))],imports:[],actions:32,files:{machineTake:'vsq-restart-1.json'},downloads:[{file:'vsq-restart-1.json',complete:true,success:true}]
};}
test('VSQ acceptance ZIP is exactly the original generator metadata and score for both variants',()=>{for(const padding of [false,true]){const f=vsqAcceptanceFixture({padding}),members=readBulkEvidenceZip(f.bytes);assert.equal(members.size,3);for(const [name,b]of f.files)assert.deepEqual(members.get(`songs/original-vsq/${name}`),b);assert.equal(f.score.authoring.tracks.length,2);assert.equal(f.score.notation.parts.length,2);assert.deepEqual(f.score.notation.keys,[]);assert.equal(f.runtime.runtime.notes.length,2);assert.ok(f.runtime.runtime.notes.every(n=>n.dynamics===0));assert.match(f.opened.clean_package.score_json,/9007199254740993/);assert.equal(f.opened.clean_package.runtime,null);assert.equal(f.manifest.generator,'crates/desktop-shell/examples/generate_vsq_fixture.rs');}});
test('following evidence observes native half-open note end, premeasure and source tail without inferred time',()=>{validateVsqFollowing(following(),runtime);const exact=following().find(r=>r.positionMs===runtime.runtime.notes[0].end_ms);assert.deepEqual(exact.ids,[]);assert.equal(exact.measure,'1');const tail=following().find(r=>r.positionMs>runtime.navigation.written_end_ms&&r.positionMs<runtime.runtime.end_ms);assert.equal(tail.measure,'');for(const change of [r=>r[3].positionMs=-1,r=>r[3].ids.pop(),r=>r[3].ids.push('invented'),r=>r[3].measure='0',r=>r[3].durationMs=4000,r=>r.at(-1).positionMs-=1,r=>r.splice(0,6),r=>r.find(v=>v.positionMs===runtime.runtime.notes[0].end_ms).ids.push('vsq-t1-ID#0001'),r=>r.find(v=>v.positionMs>runtime.navigation.written_end_ms&&v.positionMs<runtime.runtime.end_ms).measure='1']){const rows=following();change(rows);assert.throws(()=>validateVsqFollowing(rows,runtime));}});
test('renderer acceptance rejects implicit choice, changed source/runtime, missing tracks and fake input',()=>{validateVsqRenderer(originalReport());for(const change of [r=>r.beforeChoice.audio.sourceStarts=1,r=>r.beforeChoice.listenDisabled=false,r=>r.afterChoice.audio.sourceStarts=1,r=>r.beforeChoice.fullVocalVisible=false,r=>r.beforeChoice.fullVocalDisabled=false,r=>r.beforeChoice.tracks.pop(),r=>r.beforeChoice.limits=7,r=>r.reloadChoice.preview='ready',r=>r.reloadChoice.runtimeRequests=2,r=>r.runtimeResponses[0].body.runtime.notes.pop(),r=>r.runtimeResponses[0].body.navigation.clock_start_ms=0,r=>r.opened.clean_package.score_json=r.opened.clean_package.score_json.replace('9007199254740993','9007199254740992'),r=>r.requests[0].body.choice='full_vocal',r=>r.requests.push({path:'/api/notation-navigation',body:{id:fixture.metadata.id}}),r=>r.machinePlaying.captured='1',r=>r.controls.humanMachineEnabled=true,r=>r.pauseClock.after+=1,r=>r.finalAudio={...audio,activeSources:1},r=>r.trusted[0].trusted=false,r=>r.downloads[0].success=false,r=>r.checks.pop(),r=>r.diagnostics=Array.from({length:49},()=>({stage:'x',elapsedMs:1}))]){const r=structuredClone(originalReport());change(r);assert.throws(()=>validateVsqRenderer(r));}});
test('VSQ machine take must retain exact native target identities and contain no machine-derived inputs',()=>{const take={version:1,score_id:fixture.metadata.id,practice_part:'vsq-track-2',passes:[{id:1,interpretation:vsqInterpretation(),inputs:[],captures:[],assessment:null,timeline:{notes:[structuredClone(runtime.compilation.timeline.notes[1])]}}],input_evidence:{version:1,truncated:false,omitted_observations:0,events:[]}};validateVsqTake(take,fixture);for(const change of [t=>t.passes[0].timeline.notes[0].start_ms=1,t=>t.passes[0].timeline.notes.push(runtime.compilation.timeline.notes[0]),t=>t.passes[0].inputs.push({midi:63}),t=>t.passes[0].captures.push({}),t=>t.passes[0].assessment={},t=>t.input_evidence.truncated=true]){const altered=structuredClone(take);change(altered);assert.throws(()=>validateVsqTake(altered,fixture));}});
test('following observer reads actual DOM only and bounds retained frame data',async()=>{const source=await readFile(new URL('../crates/desktop-shell/vsq-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),create=runInNewContext(`${prefix}\ncreateVsqFollowingObserver`);let callback,cancelled=0;const state={progress:{value:0,max:4083.3371666666667},'written-cursor-status':{dataset:{status:'ready',sourceNoteIds:'["original-note"]',sourceMeasureIndex:'1'}},'clean-song-stage':{dataset:{rendererState:'playing'}},'stage-cue':{dataset:{cueState:'countdown'}}},document={body:{dataset:{screen:'stage'}},getElementById:id=>state[id]},observe=create(document,{request:fn=>(callback=fn,1),cancel:()=>cancelled++,maxRows:2});callback();assert.equal(observe.rows[0].positionMs,0);assert.equal(observe.rows[0].cue,'countdown');assert.deepEqual(JSON.parse(JSON.stringify(observe.rows[0].ids)),['original-note']);state.progress.value=1;callback();assert.equal(observe.rows.length,2);state.progress.value=2;assert.throws(()=>callback(),/exceeded/);observe.stop();assert.equal(cancelled,1);});
test('hosted runner guard refuses local execution before any browser or server launch',async()=>{const {spawnSync}=await import('node:child_process');const env={...process.env};delete env.GITHUB_ACTIONS;delete env.WMH_HOSTED_BROWSER;const child=spawnSync(process.execPath,['scripts/hosted-vsq-song-check.mjs'],{cwd:new URL('../',import.meta.url),env,encoding:'utf8'});assert.equal(child.status,1);assert.match(child.stderr,/Only the authorized hosted browser runner/);});
test('VSQ workflow gate preserves MIDI/media acceptance, same-source EXE checks and exact output ignore',async()=>{const workflow=await readFile(new URL('../.github/workflows/windows-desktop-acceptance.yml',import.meta.url),'utf8'),ignore=await readFile(new URL('../.gitignore',import.meta.url),'utf8');for(const required of ['node scripts/check-clean-song-native.mjs','-Scenario clean-song','-Scenario bulk-import','-Scenario song-folder','scripts/verify-native-clean-song-evidence.mjs --check','scripts/verify-native-vsq-song-evidence.mjs --check','$vsqProof.source_sha','$vsqProof.source_tree','$vsqProof.executable_sha256','desktop-vsq-song/renderer-vsq-*.json'])assert.ok(workflow.includes(required),required);assert.match(ignore,/^\/desktop-vsq-song\/$/m);assert.ok(!ignore.includes('/desktop-*'));assert.ok(workflow.indexOf('verify-native-vsq-song-evidence.mjs --check')<workflow.indexOf('Copy-Item desktop-vsq-song'));});
function syntheticPickerGestures(){
 const state={button:0,buttons:0,defaultPrevented:false,activation:{isActive:true,hasBeenActive:true},focus:{hasFocus:true,activeId:'import-button',visibility:'visible'},trigger:{id:'import-button',tag:'BUTTON',type:'submit',disabled:false,connected:true,inert:false},input:{id:'score-file',tag:'INPUT',type:'file',disabled:false,connected:true,inert:false,multiple:true},dialog:{id:'import-tools-dialog',open:true,modal:true}};
 return[['before-action',null,null],['pointerdown','import-button',true],['pointerup','import-button',true],['click','import-button',true],['click','score-file',false],['change','score-file',true]].map(([type,targetId,trusted])=>({...structuredClone(state),observedAtMs:1050,eventTimeMs:type==='before-action'?null:50,type,targetId,trusted}));
}
function syntheticScreenshot(){const crc=b=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=c>>>1^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;},chunk=(name,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;};const header=Buffer.alloc(13);header.writeUInt32BE(640);header.writeUInt32BE(360,4);header[8]=8;header[9]=2;const pixels=Buffer.alloc(1921*360);let value=17;for(let i=0;i<pixels.length;i++){value=(Math.imul(value,1664525)+1013904223)>>>0;pixels[i]=i%1921?value>>>24:0;}return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
function vsqInterpretation(){return{policy_id:'wmh-vsq-base-note-reference-v1',runtime_profile:'wmh-vsq-base-note-practice-v1',source_sha256:runtime.runtime.source_sha256,package_content_sha256:fixture.opened.clean_package.content_sha256,practice_part:'vsq-track-2',source_target_ids:['vsq-t2-ID#0001']};}
function syntheticAssessment(){return{accuracy_percent:100,hits:[{note_id:'vsq-t2-ID#0001',midi:63,expected_ms:0,actual_ms:100,delta_ms:100,grade:'good'}],misses:[],extras:[]};}
function syntheticTake(human=false){const input={midi:63,velocity:90,at_ms:100};return{version:1,tolerance_ms:180,latency_ms:0,score_id:fixture.metadata.id,practice_part:'vsq-track-2',passes:[{id:1,interpretation:vsqInterpretation(),capture_enabled:true,clock_segments:[{wallStart:1000,wallEnd:3500,positionStart:-2000},{wallStart:3600,wallEnd:7200,positionStart:500}],inputs:human?[input]:[],captures:human?[{event_id:1,event_wall_ms:3100,received_wall_ms:3101,input}]:[],assessment:human?syntheticAssessment():null,timeline:{notes:[runtime.compilation.timeline.notes[1]]}}],input_evidence:{version:1,truncated:false,omitted_observations:0,events:human?[{event_id:1,kind:'note_on',input_kind:'typing_keyboard',encoding:'key_down',midi:63,velocity:90,raw_timestamp_ms:3100,timestamp_basis:'event_monotonic',event_wall_ms:3100,received_wall_ms:3101,onset_capture:{pass_id:1,event_id:1}}]:[]}};}
function syntheticTransport(){const state={passId:'1',captured:'1',cue:'paused',phase:'paused',hidden:false,focused:true,activeElement:'stage-title',openDialogs:[],positionMs:500,durationMs:runtime.runtime.end_ms};return{version:1,stage:'complete',omitted:0,rowBytes:1000,trustedPlayClicks:2,trustedKeyDowns:1,trustedKeyUps:1,current:state,rows:[{kind:'ready',state:{...state,positionMs:0,captured:'0'}},{kind:'key-focus-ready',state:{...state,phase:'capturing',cue:'countdown',positionMs:0}},{kind:'transport',state:{...state,phase:'capturing',positionMs:20}},...['keydown','keyup'].map(type=>({kind:'event',state:{...state,phase:'capturing',positionMs:100,cue:''},event:{type,trusted:true,code:'KeyU',surface:'stage-title',repeat:false,eventTime:type==='keydown'?3100:3110}}))]};}
function addSyntheticHumanScore(r){
 r.transportAdmission=syntheticTransport();r.humanThread=[syntheticVsqAudioThreadRun(runtime,{mode:'practice',targetPart:'vsq-track-2',positionMs:-2000,cancelMs:500}),syntheticVsqAudioThreadRun(runtime,{mode:'practice',targetPart:'vsq-track-2',positionMs:500,receiverId:2})];
 r.keyPreparation={timeOrigin:1700000000000,playAction:7,keyAction:8,readyWallMs:1100,readyPositionMs:0,readyCue:'countdown',focused:true,activeElement:'stage-title',countInMs:2000,mapping:'U',dispatchWallMs:3040,dispatchPositionMs:40};r.completePractice={accuracy:'100%',positionMs:runtime.runtime.end_ms,captured:'1'};
 const request={timeline:{notes:[runtime.compilation.timeline.notes[1]]},inputs:[{midi:63,velocity:90,at_ms:100}],tolerance_ms:180},requestIndex=r.requests.length;r.requests.push({path:'/api/assess',body:request});r.assessmentRequests=[request];r.assessmentResponses=[{path:'/api/assess',status:200,body:syntheticAssessment(),requestIndex}];r.assessmentObservations=[{path:'/api/assess',status:200,state:'consumed',requestIndex}];return r;
}
test('VSQ real-key score requires prepared count-in focus, exact source target and unaltered captured timestamps',()=>{
 const report=addSyntheticHumanScore(structuredClone(originalReport())),take=syntheticTake(true);validateVsqHumanScore(report,fixture);validateVsqTake(take,fixture,{human:true,transport:report.transportAdmission,report});
 for(const mutate of [r=>r.keyPreparation.readyCue='ready',r=>r.keyPreparation.mapping='R',r=>r.keyPreparation.dispatchPositionMs=180,r=>r.keyPreparation.keyAction++,r=>r.transportAdmission.rows[1].state.focused=false,r=>r.transportAdmission.rows[2].event={type:'click'},r=>r.assessmentRequests[0].tolerance_ms=240,r=>r.assessmentRequests[0].timeline.notes[0].midi=60,r=>r.assessmentResponses[0].body.hits[0].expected_ms=500,r=>r.assessmentResponses[0].body.accuracy_percent=99,r=>r.assessmentObservations[0].state='awaiting-consumption',r=>r.humanThread[0].started.positionMs=0]){const changed=structuredClone(report);mutate(changed);assert.throws(()=>validateVsqHumanScore(changed,fixture));}
 for(const mutate of [t=>t.passes[0].interpretation.source_sha256='0'.repeat(64),t=>t.tolerance_ms=240,t=>t.passes[0].clock_segments[0].positionStart=0,t=>t.input_evidence.events[0].raw_timestamp_ms++,t=>t.input_evidence.events[0].timestamp_basis='receipt_fallback',t=>t.passes[0].assessment.accuracy_percent=0]){const changed=structuredClone(take);mutate(changed);assert.throws(()=>validateVsqTake(changed,fixture,{human:true,transport:report.transportAdmission,report}));}
 const result={ok:true,native_key:{app_hwnd:4,foreground:4,app_process_id:42,app_enabled:true,code:'KeyU',virtual_key:0x55,focus_reacquired:false,pointer_clicked:false}};validateVsqNativeKey(result,{process_id:42});for(const mutate of [r=>r.client_click={},r=>r.native_key.foreground=5,r=>r.native_key.code='KeyR',r=>r.native_key.virtual_key=0x52,r=>r.native_key.focus_reacquired=true]){const changed=structuredClone(result);mutate(changed);assert.throws(()=>validateVsqNativeKey(changed,{process_id:42}));}
});
test('VSQ physical key has a closed action and prepares focus before the original onset window',async()=>{
 const [source,windows,native,hosted]=await Promise.all(['../crates/desktop-shell/vsq-song-acceptance.js','../scripts/windows-desktop-acceptance.ps1','../crates/desktop-shell/src/acceptance.rs','../scripts/hosted-vsq-song-check.mjs'].map(name=>readFile(new URL(name,import.meta.url),'utf8')));
 assert.match(source,/if\(kind==='key-ds4'\)assertVsqInputFocus\(document,node\);else/);assert.ok(source.indexOf('await prepareVsqInputFocus')<source.indexOf("'VSQ source-zero capture opens'"));assert.match(source,/\[data-midi="63"\] \.key-shortcut/);assert.match(source,/keyCode:'KeyU'/);assert.match(source,/dispatchPositionMs=Number\(\$\('progress'\)\.value\)/);
 const branch=windows.slice(windows.indexOf("if($Action.kind -eq 'key-ds4')"),windows.indexOf('  [NativeAcceptance]::SetForegroundWindow($window) | Out-Null',windows.indexOf("if($Action.kind -eq 'key-ds4')")));assert.match(branch,/\[NativeAcceptance\]::Key\(0x55\);return/);assert.doesNotMatch(branch,/SetForegroundWindow|Start-Sleep|Click\(/);assert.match(native,/"key-ds4"/);assert.match(hosted,/page\.keyboard\.press\('KeyU'\)/);
});
test('VSQ audio cleanup preserves a startup failure and restores every initialized observer',async()=>{
 const source=await readFile(new URL('../crates/desktop-shell/vsq-song-acceptance.js',import.meta.url),'utf8'),close=runInNewContext(source.slice(0,source.indexOf('(() => {'))+';closeVsqAudioObservers');
 const report={ok:false,error:'original module load failure',errors:[]},calls=[];close(report,{snapshot(){throw Error('snapshot failure');},restore(){calls.push('probe');throw Error('probe restoration failed');}},{restore(){calls.push('receiver');return{restored:true,cleanupErrors:[],errors:[]};}});assert.equal(report.error,'original module load failure');assert.deepEqual(calls,['probe','receiver']);assert.equal(report.errors.length,2);
 const missing={ok:false,error:'receiver unavailable',errors:[]};close(missing,{snapshot:()=>({sourceStarts:0}),restore(){}},undefined);assert.equal(missing.receiverCleanup.restored,false);assert.equal(missing.finalAudio.worklet,null);assert.equal(missing.error,'receiver unavailable');
});
async function originalEvidence(t){const directory=await mkdtemp(join(tmpdir(),'wmh-vsq-verifier-unit-'));t.after(()=>rm(directory,{recursive:true,force:true}));await prepareVsqFixtures(join(directory,'fixtures'));await mkdir(join(directory,'downloads'));const save=async(name,value)=>writeFile(join(directory,name),JSON.stringify(value)),png=syntheticScreenshot(),reports={};const native={version:1,scenario:'vsq-song',ok:true,profile_reused:false,source_sha:'1'.repeat(40),source_tree:'2'.repeat(40),executable_sha256:'3'.repeat(64),executable_bytes:80000,directory:join(directory,'Scores'),phases:[]};
 for(const [index,phase]of ['vsq-seed','vsq-restart'].entries()){const r=structuredClone(originalReport());r.phase=phase;r.directory=native.directory;r.files={machineTake:`${phase}-1.json`};r.actions=32;r.screenshots={choice:2,choiceZh:3,following:4,parts:5,pianoFingering:29,guitarFingering:30,guitarInfeasible:31,...(phase==='vsq-seed'?{preflight:7}:{})};if(phase==='vsq-seed'){r.checks.push('chooser-preflight-all-tracks-save','trusted-human-input','complete-package-export');r.preflight={status:'ready',playable:false,coverage:fixture.score.coverage};r.imports=['preview','commit'].map((mode,index)=>({path:`/api/library/import/${mode}`,status:200,body:{source:{sha256:fixture.manifest.sha256,bytes:fixture.bytes.length,retained:index===1},items:[{status:index===0?'ready':'saved',playable:false,clean_package:fixture.summary}]}}));r.pickerObservations=[{sequence:1,filename:fixture.filename,completed:true,gestures:syntheticPickerGestures(),delegatedClicks:[{type:'click',trusted:false,id:'score-file',sequence:1}],changes:[{type:'change',trusted:true,id:'score-file',sequence:1,filename:fixture.filename}]}];r.trusted.push({type:'change',trusted:true,id:'score-file',pickerSequence:1});r.responseObservations=[...r.imports,...r.runtimeResponses].map(row=>({path:row.path,status:row.status,state:'consumed'}));r.files.humanTake=`${phase}-2.json`;r.files.package=`${phase}-3.zip`;addSyntheticHumanScore(r);await save(`downloads/${r.files.humanTake}`,syntheticTake(true));const entries=[...fixture.files].map(([name,b])=>[`songs/${fixture.key}/${name}`,b]);entries.push(['manifest.json',JSON.stringify({format:'worldmusichub-song-pack',version:2,songs:[{folder:`songs/${fixture.key}`}]})]);await writeFile(join(directory,'downloads',r.files.package),storedZip(entries));}
  r.downloads=Object.values(r.files).map(file=>({file,complete:true,success:true}));reports[phase]=r;await save(`downloads/${r.files.machineTake}`,syntheticTake());const host={phase,process_id:100+index,renderer_ok:true,normal_close:true,launched_new_process:true,profile_fresh:true,profile_reused:false,executable_tcp_listeners:0,renderer_origin:'https://wmh.localhost',actions:r.actions};native.phases.push(host);
  for(let sequence=1;sequence<=r.actions;sequence++){const kind=r.fingering.actions.find(action=>action.sequence===sequence)?.kind||(sequence===1&&index===0?'picker':sequence===6?'select-last':sequence===8&&index===0?'key-ds4':'click');await save(`action-${phase}-${sequence}.json`,{version:1,sequence,kind,x:10,y:20,width:1024,height:768,...(kind==='picker'?{file:fixture.filename}:{})});await save(`result-${phase}-${sequence}.json`,{ok:true,...(kind==='key-ds4'?{native_key:{app_hwnd:1,foreground:1,app_process_id:host.process_id,app_enabled:true,code:'KeyU',virtual_key:0x55,focus_reacquired:false,pointer_clicked:false}}:{client_click:{app_hwnd:1,foreground:1,actual:[10,20],requested:[10,20],viewport:[1024,768],hit_hwnd:1}}),...(kind==='picker'?{owned_dialog:{class:'#32770',hwnd:2,process_id:host.process_id,app_process_id:host.process_id,app_hwnd:1,root_owner_hwnd:1},picker_completion:{dialog_dismissed:true,app_enabled:true,owned_popup_visible:false}}:{})});}
  for(const n of Object.values(r.screenshots))await writeFile(join(directory,`native-action-${phase}-${n}.png`),png);await writeFile(join(directory,`native-${phase}.png`),png);await save(`renderer-${phase}.json`,r);
 }
 const rows=[],archive=async(path,b)=>{await mkdir(join(directory,'Scores',path.slice(0,path.lastIndexOf('/'))),{recursive:true});await writeFile(join(directory,'Scores',path),b);rows.push({path,bytes:b.length,sha256:digest(b)});};for(const area of ['clean-songs','clean-backups']){await archive(`${area}/${fixture.key}/entry.json`,Buffer.from(JSON.stringify(reports['vsq-seed'].inventory[0])));for(const [name,b]of fixture.files)await archive(`${area}/${fixture.key}/package/${name}`,b);}for(const area of ['imports','import-backups'])await archive(`${area}/pack-${fixture.manifest.sha256}/source.bin`,fixture.bytes);for(const phase of ['vsq-seed','vsq-restart'])await save(`snapshot-${phase}.json`,{version:1,files:rows});await addNativeProfileEvidence(native,save);await save('native-vsq-song.json',native);return{directory,native,reports,save};}
test('native verifier rederives original exact bytes and two distinct processes without claiming acoustic fidelity',async t=>{const f=await originalEvidence(t),proof=await verifyNativeVsqSongEvidence(f.directory);assert.equal(proof.ok,true);assert.equal(proof.fixture_sha256,fixture.manifest.sha256);assert.equal(proof.claims.original_vocal_or_acoustic_fidelity,false);assert.equal(proof.claims.actual_audibility,false);assert.ok(proof.files.some(f=>f.path.includes('/package/score.json')));});
test('native verifier rejects byte loss, missing OS chooser ownership and reused process',async t=>{const f=await originalEvidence(t),path=`Scores/clean-backups/${fixture.key}/package/score.json`;await writeFile(join(f.directory,path),fixture.files.get('score.json').subarray(0,-1));await assert.rejects(verifyNativeVsqSongEvidence(f.directory));await writeFile(join(f.directory,path),fixture.files.get('score.json'));const result=JSON.parse(await readFile(join(f.directory,'result-vsq-seed-1.json')));await f.save('result-vsq-seed-1.json',{...result,owned_dialog:undefined});await assert.rejects(verifyNativeVsqSongEvidence(f.directory),/picker ownership/);await f.save('result-vsq-seed-1.json',result);const altered=structuredClone(f.native);altered.phases[1].process_id=altered.phases[0].process_id;await f.save('native-vsq-song.json',altered);await assert.rejects(verifyNativeVsqSongEvidence(f.directory));});
test('VSQ stdio request and shutdown deadlines terminate only their owned test process',async t=>{const {startVsqNativeDriver}=await import('./vsq-native-driver-fixtures.js'),dir=await mkdtemp(join(tmpdir(),'wmh-vsq-driver-timeout-'));t.after(()=>rm(dir,{recursive:true,force:true}));const script=join(dir,'pending.cjs');await writeFile(script,'process.stdin.resume();setInterval(()=>{},1000);');const first=startVsqNativeDriver({binary:process.execPath,directory:script,requestTimeoutMs:40});await assert.rejects(first.fetcher('/api/library/runtime'),/\/api\/library\/runtime exceeded 40ms/);await first.close();const second=startVsqNativeDriver({binary:process.execPath,directory:script,closeTimeoutMs:40});await assert.rejects(second.close(),/process close exceeded 40ms/);});
test('VSQ stdio close rejects a native process failure after its final valid response',async t=>{const {startVsqNativeDriver}=await import('./vsq-native-driver-fixtures.js'),dir=await mkdtemp(join(tmpdir(),'wmh-vsq-driver-exit-'));t.after(()=>rm(dir,{recursive:true,force:true}));const script=join(dir,'exits.cjs');await writeFile(script,'process.stdin.on("data",()=>process.stdout.write(JSON.stringify({status:200,content_type:"application/json",body_base64:"e30="})+"\\n"));process.stdin.on("end",()=>process.exit(7));');const driver=startVsqNativeDriver({binary:process.execPath,directory:script});assert.equal((await driver.fetcher('/api/health')).status,200);await assert.rejects(driver.close(),/process exited \(7\)/);});
async function observationHelpers(){const source=await readFile(new URL('../crates/desktop-shell/vsq-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {'));return runInNewContext(`${prefix}\n({createVsqJsonObserver,createVsqControlObserver,observeVsqFollowingSurface,readVsqFollowingFrame,readVsqFingeringState})`,{structuredClone});}
test('actual JSON consumption is retained before preview adoption aborts, without reading a clone or delaying the caller',async()=>{const {createVsqJsonObserver}=await observationHelpers(),controller=new AbortController(),values=[],errors=[],calls=[];let resolve;const value={profile:'original',notes:[1]},actualPromise=new Promise(done=>resolve=done),original=function(...args){calls.push({receiver:this,args});return actualPromise;},response={status:200,json:original,clone(){throw Error('The aborted clone is not the application body');}},fetchPromise=Promise.resolve(response),observer=createVsqJsonObserver({onValue:row=>values.push(row),onError:error=>errors.push(error)});assert.equal(observer.observe('/api/library/runtime',fetchPromise),fetchPromise);assert.equal(await fetchPromise,response);const argument={unchanged:true},jsonPromise=response.json(argument);assert.equal(jsonPromise,actualPromise);const delivered=jsonPromise.then(result=>{assert.equal(values.length,1,'Observe consumed result before consumer-triggered abort');controller.abort();return result;});resolve(value);assert.equal(await delivered,value);assert.equal(controller.signal.aborted,true);assert.equal(calls[0].receiver,response);assert.deepEqual(calls[0].args,[argument]);assert.deepEqual(JSON.parse(JSON.stringify(values)),[{path:'/api/library/runtime',status:200,body:value}]);value.notes.push(2);assert.deepEqual(values[0].body.notes,[1]);assert.deepEqual(errors,[]);assert.equal(response.json,original);assert.deepEqual(JSON.parse(JSON.stringify(observer.snapshot())),[{path:'/api/library/runtime',status:200,state:'consumed'}]);observer.restore();});
test('real Response JSON promises, values and descriptors survive passive VSQ body observation',async()=>{const {createVsqJsonObserver}=await observationHelpers(),values=[],errors=[],response=new Response(JSON.stringify(runtime),{status:200}),json=Response.prototype.json;let originalPromise;const method=function(...args){originalPromise=Reflect.apply(json,this,args);return originalPromise;};Object.defineProperty(response,'json',{value:method,configurable:true,writable:true,enumerable:false});const descriptor=Object.getOwnPropertyDescriptor(response,'json'),observer=createVsqJsonObserver({onValue:row=>values.push(row),onError:error=>errors.push(error)});await observer.observe('/api/library/runtime',Promise.resolve(response));const returned=response.json();assert.equal(returned,originalPromise);const value=await returned;assert.deepEqual(value,runtime);assert.deepEqual(values[0].body,runtime);assert.deepEqual(Object.getOwnPropertyDescriptor(response,'json'),descriptor);assert.deepEqual(errors,[]);observer.restore();});
test('VSQ observer preserves genuine fetch/body errors and original synchronous exceptions',async()=>{const {createVsqJsonObserver}=await observationHelpers();for(const stage of ['fetch','body','throw']){const errors=[],values=[],failure=Object.assign(Error(`${stage} original error`),{name:'AbortError'}),observer=createVsqJsonObserver({onValue:v=>values.push(v),onError:e=>errors.push(e)});if(stage==='fetch'){const promise=Promise.reject(failure);assert.equal(observer.observe('/api/library/runtime',promise),promise);await assert.rejects(promise,error=>error===failure);}else{let rejected;const response={status:200,json(){if(stage==='throw')throw failure;rejected=Promise.reject(failure);return rejected;}};await observer.observe('/api/library/runtime',Promise.resolve(response));if(stage==='throw')assert.throws(()=>response.json(),error=>error===failure);else{const result=response.json();assert.equal(result,rejected);await assert.rejects(result,error=>error===failure);}}assert.equal(values.length,0);assert.equal(errors.length,1);assert.match(errors[0],/AbortError/);assert.match(errors[0],/original error/);observer.restore();}});
test('VSQ observer cleanup restores an unconsumed response and suppresses late observation only after teardown',async()=>{const {createVsqJsonObserver}=await observationHelpers(),values=[],errors=[];let resolve;const promise=new Promise(done=>resolve=done),original=()=>promise,response={status:200,json:original},observer=createVsqJsonObserver({onValue:v=>values.push(v),onError:e=>errors.push(e)});await observer.observe('/api/library/runtime',Promise.resolve(response));const actual=response.json();assert.equal(actual,promise);assert.equal(observer.snapshot()[0].state,'consuming');observer.restore();assert.equal(response.json,original);resolve({native:'unchanged'});assert.deepEqual(await actual,{native:'unchanged'});assert.deepEqual(values,[]);assert.deepEqual(errors,[]);assert.equal(observer.snapshot()[0].state,'consuming');});
test('only one delegated hidden-input click paired with a trusted original-file chooser change is admissible',async()=>{const {createVsqControlObserver}=await observationHelpers(),listeners=new Map(),document={addEventListener:(type,fn)=>listeners.set(type,fn),removeEventListener:type=>listeners.delete(type)},observer=createVsqControlObserver(document),target={id:'score-file',files:[{name:fixture.filename}]};const dialog={id:'import-tools-dialog',open:true,matches:()=>true},button={id:'import-button',tagName:'BUTTON',type:'submit',disabled:false,isConnected:true,inert:false,closest:()=>dialog};Object.assign(target,{tagName:'INPUT',type:'file',disabled:false,isConnected:true,inert:false,multiple:true});Object.assign(document,{getElementById:id=>id==='import-button'?button:target,hasFocus:()=>true,activeElement:button,visibilityState:'visible',defaultView:{performance:{timeOrigin:1000,now:()=>50},navigator:{userActivation:{isActive:true,hasBeenActive:true}}}});observer.beginPicker(1,fixture.filename);for(const type of ['pointerdown','pointerup','click'])listeners.get(type)({type,isTrusted:true,target:button,button:0,buttons:type==='pointerdown'?1:0,timeStamp:50});listeners.get('click')({type:'click',isTrusted:false,target,timeStamp:50});listeners.get('change')({type:'change',isTrusted:true,target,timeStamp:50});observer.endPicker(1,true);const report=JSON.parse(JSON.stringify({phase:'vsq-seed',pickerObservations:observer.pickers,trusted:observer.trusted}));validateVsqPickerEvidence(report);assert.equal(report.trusted.length,2);for(const change of [r=>r.pickerObservations[0].delegatedClicks.push(r.pickerObservations[0].delegatedClicks[0]),r=>r.pickerObservations[0].changes[0].trusted=false,r=>r.pickerObservations[0].changes[0].filename='other.zip',r=>r.pickerObservations[0].completed=false,r=>r.trusted.find(row=>row.id==='score-file').pickerSequence=2,r=>r.trusted.push({id:'score-file',type:'click',trusted:false}),r=>r.pickerObservations[0].sequence=2]){const altered=structuredClone(report);change(altered);assert.throws(()=>validateVsqPickerEvidence(altered));}listeners.get('click')({type:'click',isTrusted:false,target});assert.equal(observer.trusted.at(-1).trusted,false,'Out-of-picker synthetic clicks remain disallowed');observer.restore();assert.equal(listeners.size,0);});
test('VSQ observation failures never replace the successful application JSON value',async()=>{const {createVsqJsonObserver}=await observationHelpers(),errors=[],value={original:true},promise=Promise.resolve(value),response={status:200,json:()=>promise},observer=createVsqJsonObserver({onValue(){throw Error('bounded observer failed');},onError:e=>errors.push(e)});await observer.observe('/api/library/runtime',Promise.resolve(response));assert.equal(response.json(),promise);assert.equal(await promise,value);assert.equal(errors.length,1);assert.match(errors[0],/observation-failed.*bounded observer failed/);observer.restore();});
test('VSQ chooser observation spans native dismissal through the actual application preflight',async()=>{const source=await readFile(new URL('../crates/desktop-shell/vsq-song-acceptance.js',import.meta.url),'utf8');assert.match(source,/finally\{if\(picker&&!completed\)controls\.endPicker\(sequence,false\)/);const nativeResult=source.indexOf("pickerSequence=await native('picker'"),preflight=source.indexOf("'chooser preflight response'",nativeResult),finish=source.indexOf('controls.endPicker(pickerSequence,completed)',preflight);assert.ok(nativeResult>0&&preflight>nativeResult&&finish>preflight);assert.match(source,/requestObservationActive=false/);assert.match(source,/removeEventListener\('error',onError\)/);assert.match(source,/removeEventListener\('unhandledrejection',onRejection\)/);});
test('following retains the real clean-song scheduling lead-in without treating clamped progress as native time zero',async()=>{
 const {Transport}=await import('../web/transport.js'),{performanceCue}=await import('../web/performance-view.js');
 const transport=new Transport();transport.start(1050,[],0);const position=transport.time(1000),cue=performanceCue({running:true,position,segmentStart:0,countInBeatMs:500},{formatNumber:String,t:key=>key});
 assert.equal(position,-50);assert.ok(cue);assert.equal(cue.detail,'performance.silentCountIn');
 const preRoll={positionMs:Math.max(0,position),durationMs:runtime.runtime.end_ms,ids:[],measure:'',renderer:'playing',cue:'countdown'},rows=[following()[0],preRoll,...following().slice(1)];
 validateVsqFollowing(rows,runtime);
 for(const change of [r=>r.cue=null,r=>r.positionMs=1,r=>r.renderer='ready',r=>r.ids.push(runtime.runtime.notes[0].note_id),r=>r.measure='1']){const altered=structuredClone(rows);change(altered[1]);assert.throws(()=>validateVsqFollowing(altered,runtime));}
 const positive=structuredClone(rows);positive[3].ids=[];assert.throws(()=>validateVsqFollowing(positive,runtime),/exact native interval/);
 const source=await readFile(new URL('../web/app.js',import.meta.url),'utf8');assert.match(source,/performance\.now\(\)\+\(state\.cleanSong\?50:0\)/);
});
test('following surface observation accepts pointer-inert score paint and rejects absent or invisible notation',async()=>{
 const {observeVsqFollowingSurface}=await observationHelpers(),bounds={x:18,y:109,width:1244,height:361},svgBounds={x:20,y:110,width:800,height:250},style={display:'block',visibility:'visible',opacity:'0.6',pointerEvents:'none'},svgStyle={...style,opacity:'1'};
 const svg={getBoundingClientRect:()=>svgBounds},surface={id:'notation-lane-overlay',hidden:false,getBoundingClientRect:()=>bounds,querySelectorAll:()=>[svg]},document={getElementById:()=>surface,elementFromPoint(){throw Error('Score paint is not an input target');},defaultView:{innerWidth:1280,innerHeight:720,getComputedStyle:node=>node===surface?style:svgStyle}};
 const observed=JSON.parse(JSON.stringify(observeVsqFollowingSurface(document)));validateVsqFollowingSurface(observed);assert.equal(observed.visibleSvgCount,1);
 for(const [object,key,value]of [[surface,'hidden',true],[style,'display','none'],[style,'visibility','hidden'],[style,'opacity','0'],[bounds,'x',1280],[bounds,'height',0],[svgBounds,'y',900],[svgStyle,'display','none']]){const before=object[key];object[key]=value;assert.throws(()=>observeVsqFollowingSurface(document),/VSQ following/);object[key]=before;}
 for(const change of [r=>r.id='written-cursor-status',r=>r.visibleSvgCount=0,r=>r.bounds.x=1280,r=>r.bounds.height=0,r=>r.viewport.width=0]){const altered=structuredClone(observed);change(altered);assert.throws(()=>validateVsqFollowingSurface(altered));}
});
test('all screenshot markers use foreground targets through the unchanged strict native hit test',async()=>{
 const source=await readFile(new URL('../crates/desktop-shell/vsq-song-acceptance.js',import.meta.url),'utf8'),start=source.indexOf('async function native('),end=source.indexOf(' const inventory=',start),actions=[];
 let hit=null;const document={elementFromPoint:()=>hit},make=(id,bounds={x:10,y:10,width:200,height:30})=>({id,disabled:false,scrollIntoView(){},focus(){},getBoundingClientRect:()=>bounds,contains:node=>node===hit&&node?.parentId===id});
 const native=runInNewContext(`let sequence=0;${source.slice(start,end)}\nnative`,{assert:(value,message)=>assert.ok(value,message),document,innerWidth:1280,innerHeight:720,frame:async()=>{},json:async(path,body)=>actions.push(body),until:async condition=>assert.equal(await condition(),true),fetcher:async()=>({status:200,ok:true,json:async()=>({ok:true})})});
 const markers=[...source.matchAll(/report\.screenshots\.(\w+)=await native\('click',\$\('([^']+)'\)\);/g)].map(([,role,id])=>({role,id}));
 assert.deepEqual(markers,[{role:'preflight',id:'bulk-import-title'},{role:'choice',id:'clean-song-preview-status'},{role:'choiceZh',id:'clean-song-preview-status'},{role:'following',id:'stage-title'},{role:'parts',id:'clean-song-stage-status'},{role:'pianoFingering',id:'piano-guidance-items'},{role:'guitarFingering',id:'guitar-live-route'},{role:'guitarInfeasible',id:'guitar-plan-status'}]);
 for(const {id}of markers){const target=make(id);hit=target;await native('click',target);}
 assert.equal(actions.length,8);const background=make('written-cursor-status');hit=make('notation-lane-overlay');await assert.rejects(native('click',background),/obscured/);
 const button=make('play-button');hit=make('blocking-dialog');await assert.rejects(native('click',button),/obscured/);const outside=make('vsq-choose-base-notes',{x:1280,y:20,width:200,height:30});hit=outside;await assert.rejects(native('click',outside),/outside viewport/);assert.equal(actions.length,8,'Rejected targets must never dispatch an action');
 hit={parentId:button.id};await native('click',button);assert.equal(actions.length,9,'A control may be hit through its own child');
});
test('live following screenshot requires exact native notes and real active audio at both capture boundaries',()=>{
 const original=originalReport().followingCapture;validateVsqFollowingCapture(original,runtime);
 for(const change of [r=>delete r.before,r=>r.after.frame.ids=[],r=>r.after.frame.measure='0',r=>r.before.audio.worklet.activeReceivers=0,r=>r.after.audio.worklet.activeReceivers=0,r=>r.after.frame.renderer='ended',r=>r.after.frame.positionMs=runtime.runtime.end_ms,r=>r.after.frame=following()[1],r=>r.after.frame.cue='complete']){const altered=structuredClone(original);change(altered);assert.throws(()=>validateVsqFollowingCapture(altered,runtime));}
});
test('live screenshot is bounded by observed playback while the following observer continues through native end',async()=>{
 const source=await readFile(new URL('../crates/desktop-shell/vsq-song-acceptance.js',import.meta.url),'utf8'),start=source.indexOf("checkpoint('listen-native-following')"),before=source.indexOf('report.followingCapture={before:',start),capture=source.indexOf("report.screenshots.following=await native('click',$('stage-title'))",before),after=source.indexOf('report.followingCapture.after=',capture),end=source.indexOf("'native playback end'",after),stop=source.indexOf('follow.stop()',end);
 assert.ok(start>0&&before>start&&capture>before&&after>capture&&end>after&&stop>end);
});
async function hostedChooserFixture({emit=true,duplicate=false,inputId='score-file',multiple=true,samePage=true,timeoutMs=50}={}){
 const {EventEmitter}=await import('node:events'),{createVsqHostedChooser}=await import('../scripts/vsq-hosted-chooser.mjs'),page=new EventEmitter(),clicks=[],files=[],errors=[];let time=1000;
 const input={id:inputId,tagName:'INPUT',type:'file',disabled:false,multiple:true,isConnected:true},chooser={page:()=>samePage?page:{},isMultiple:()=>multiple,element:()=>({evaluate:async evaluate=>evaluate(input)}),setFiles:async file=>files.push(file)};
 page.mouse={click:async(x,y)=>{clicks.push({x,y});if(emit){page.emit('filechooser',chooser);if(duplicate)page.emit('filechooser',chooser);}}};
 const observer=createVsqHostedChooser(page,{timeoutMs,onError:error=>errors.push(error),now:()=>++time});return{page,observer,chooser,clicks,files,errors};
}
test('persistent hosted chooser records installation before navigation and binds one actual coordinate click to the original file input',async()=>{
 const f=await hostedChooserFixture();f.observer.navigation('start');f.observer.navigation('end');await f.observer.choose({sequence:1,x:640,y:457.140625},fixture.filename);f.observer.assertComplete([1]);
 assert.deepEqual(f.clicks,[{x:640,y:457.140625}]);assert.deepEqual(f.files,[fixture.filename]);assert.deepEqual(f.errors,[]);
 assert.deepEqual(f.observer.evidence.timeline.map(row=>row.stage),['listener-installed','navigation-start','navigation-end','action-armed','mouse-click-start','chooser-event','mouse-click-end','files-set']);assert.ok(f.observer.evidence.timeline.every((row,index,rows)=>row.order===index+1&&(!index||row.atMs>rows[index-1].atMs)));
 f.observer.stop();assert.equal(f.page.listenerCount('filechooser'),0);
 const source=await readFile(new URL('../scripts/hosted-vsq-song-check.mjs',import.meta.url),'utf8'),install=source.indexOf('chooserObserver=createVsqHostedChooser(page'),navigation=source.indexOf("chooserObserver.navigation('start')"),close=source.indexOf('await context.close();context=null;await nativeBridge.drain();assert.deepEqual(phaseReport.page_errors,[])'),stop=source.indexOf('chooserObserver.stop()',close);assert.ok(install>0&&navigation>install&&close>navigation&&stop>close);assert.ok(!source.includes("waitForEvent('filechooser'"));
});
test('hosted chooser rejects duplicate, wrong-input, wrong-page and changed multiple state before any file selection',async()=>{
 for(const options of [{duplicate:true},{inputId:'score-image-file'},{multiple:false},{samePage:false}]){const f=await hostedChooserFixture(options);f.observer.navigation('start');f.observer.navigation('end');await assert.rejects(f.observer.choose({sequence:1,x:10,y:20},fixture.filename));assert.equal(f.clicks.length,1);assert.deepEqual(f.files,[]);if(options.duplicate){assert.equal(f.observer.evidence.extra_events,1);assert.equal(f.errors.length,1);}assert.throws(()=>f.observer.assertComplete([1]));f.observer.stop();}
});
test('chooser timeout retains later events as failures until the page closes and never retries the click',async()=>{
 const f=await hostedChooserFixture({emit:false,timeoutMs:20});f.observer.navigation('start');f.observer.navigation('end');await assert.rejects(f.observer.choose({sequence:1,x:10,y:20},fixture.filename),/filechooser #1 waiting-event exceeded 20ms/);f.page.emit('filechooser',f.chooser);assert.equal(f.observer.evidence.late_events,1);assert.equal(f.observer.evidence.unowned_events,1);assert.equal(f.observer.evidence.events[0].afterSequence,1);assert.equal(f.observer.evidence.events[0].owned,false);assert.equal(f.clicks.length,1);assert.deepEqual(f.files,[]);assert.throws(()=>f.observer.assertComplete([1]),/late, extra/);f.observer.stop();assert.equal(f.page.listenerCount('filechooser'),0);
});
test('unowned and extra chooser events remain bounded, counted and fatal rather than disappearing during cleanup',async()=>{
 const f=await hostedChooserFixture();f.observer.navigation('start');f.observer.navigation('end');await f.observer.choose({sequence:1,x:10,y:20},fixture.filename);
 for(let i=0;i<5;i++)f.page.emit('filechooser',f.chooser);
 assert.equal(f.observer.evidence.events.length,4);assert.equal(f.observer.evidence.extra_events,5);assert.equal(f.observer.evidence.unowned_events,5);assert.equal(f.observer.evidence.omitted_events,2);assert.equal(f.errors.length,2);assert.throws(()=>f.observer.assertComplete([1]));assert.equal(f.files.length,1);f.observer.stop();
});
test('picker gesture evidence requires trusted Import events, active delegation, enabled controls, focus, modal ownership and timing',()=>{
 validateVsqPickerGestures(syntheticPickerGestures());
 for(const change of [r=>r.splice(1,1),r=>r[1].trusted=false,r=>r[3].targetId='other-button',r=>r[3].activation.isActive=false,r=>r[4].activation.isActive=false,r=>r[3].focus.hasFocus=false,r=>r[4].focus.activeId='score-file',r=>r[2].button=1,r=>r[0].trigger.disabled=true,r=>r[4].input.type='text',r=>r[3].dialog.modal=false,r=>r[2].observedAtMs=0,r=>r[4].eventTimeMs=null]){const rows=syntheticPickerGestures();change(rows);assert.throws(()=>validateVsqPickerGestures(rows));}
});

test('owned chooser identity observation has a hard deadline and cannot select files after it expires',async()=>{
 const f=await hostedChooserFixture({timeoutMs:20});let resolve;f.chooser.element=()=>({evaluate:()=>new Promise(done=>resolve=done)});f.observer.navigation('start');f.observer.navigation('end');await assert.rejects(f.observer.choose({sequence:1,x:10,y:20},fixture.filename),/input-identity exceeded 20ms/);resolve({id:'score-file',tag:'INPUT',type:'file',disabled:false,multiple:true,connected:true});await Promise.resolve();await Promise.resolve();assert.deepEqual(f.files,[]);assert.throws(()=>f.observer.assertComplete([1]));f.observer.stop();
});
const browserPending404='Failed to load resource: the server responded with a status of 404 (Not Found)';
async function consoleFixture(){const {createVsqHostedConsole}=await import('../scripts/vsq-hosted-console.mjs');let now=1000;const origin='https://wmh.localhost',observer=createVsqHostedConsole({origin,now:()=>++now}),url=sequence=>`${origin}/__desktop_smoke/result/${sequence}`,message=(source=url(1),text=browserPending404,type='error',extra={})=>({type:()=>type,text:()=>text,location:()=>({url:source,lineNumber:0,columnNumber:0,...extra})}),pending=(sequence=1)=>observer.pendingResponse({sequence,url:url(sequence),method:'GET',owned:true,status:404,body:{error:'pending'}});return{observer,url,message,pending,origin};}
test('browser console aggregates repeated exact source identities with complete counts and first/last events',async()=>{
 const f=await consoleFixture();for(let sequence=1;sequence<=38;sequence++)for(let repeat=0;repeat<2;repeat++){f.pending(sequence).finish(true);f.observer.observe(f.message(f.url(sequence)));}f.observer.assertComplete();const e=f.observer.evidence;
 assert.equal(e.total_events,76);assert.equal(e.expected_events,76);assert.equal(e.unexpected_events,0);assert.equal(e.overflow.count,0);assert.equal(e.groups.length,38);assert.equal(e.pending_responses.length,38);
 for(const [index,row]of e.groups.entries()){assert.equal(row.count,2);assert.equal(row.type,'error');assert.equal(row.text,browserPending404);assert.deepEqual(row.location,{url:f.url(index+1),lineNumber:0,columnNumber:0});assert.equal(row.classification,'owned-pending-result');assert.equal(row.first.index,index*2+1);assert.equal(row.last.index,index*2+2);assert.ok(row.first.atMs<row.last.atMs);assert.equal(e.pending_responses[index].fulfilled,2);}
});
test('console repetition never consumes the distinct-identity budget and source field ordering does not split identity',async()=>{
 const f=await consoleFixture();for(let i=0;i<500;i++){f.pending().finish(true);f.observer.observe(i%2?{...f.message(),location:()=>({columnNumber:0,url:f.url(1),lineNumber:0})}:f.message());}f.observer.assertComplete();assert.equal(f.observer.evidence.groups.length,1);assert.equal(f.observer.evidence.groups[0].count,500);assert.equal(f.observer.evidence.total_events,500);assert.equal(f.observer.evidence.overflow.count,0);
});
test('only exact resource errors backed by owned fulfilled pending responses are expected',async()=>{
 for(const variant of ['application-source','unknown-source','wrong-text','activation-warning','wrong-type','wrong-location','excess-count','before-owned-response']){const f=await consoleFixture();if(variant!=='before-owned-response')f.pending().finish(true);
  const source=variant==='application-source'?`${f.origin}/api/library/runtime`:variant==='unknown-source'?'':f.url(1),text=variant==='wrong-text'?'Failed to load resource: 404 but not the recorded response':variant==='activation-warning'?'File chooser blocked: user activation is required':browserPending404,type=['activation-warning','wrong-type'].includes(variant)?'warning':'error';
  f.observer.observe(f.message(source,text,type,variant==='wrong-location'?{lineNumber:1}:{}));if(variant==='excess-count')f.observer.observe(f.message());if(variant==='before-owned-response')f.pending().finish(true);
  assert.throws(()=>f.observer.assertComplete(),/unexpected browser console/);assert.equal(f.observer.evidence.groups[0].text,text);assert.equal(f.observer.evidence.groups[0].type,type);assert.equal(f.observer.evidence.groups[0].location.url,source);assert.ok(f.observer.evidence.unexpected_events>0);
 }
});
test('pending-response ledger rejects unowned requests and retains failed or unsettled fulfillment',async()=>{
 const f=await consoleFixture();for(const altered of [{sequence:65},{url:f.url(1)+'?unknown=1'},{method:'POST'},{owned:false},{status:500},{body:{error:'different'}}])assert.throws(()=>f.observer.pendingResponse({sequence:1,url:f.url(1),method:'GET',owned:true,status:404,body:{error:'pending'},...altered}));
 const receipt=f.pending();f.observer.observe(f.message());assert.throws(()=>f.observer.assertComplete(),/accounting is incomplete/);receipt.finish(false);assert.throws(()=>receipt.finish(true),/settled twice/);assert.throws(()=>f.observer.assertComplete(),/accounting is incomplete/);assert.equal(f.observer.evidence.pending_responses[0].failed,1);assert.equal(f.observer.evidence.groups[0].classification,'unexpected');
});
test('unexpected console groups and oversized full identities fail with bounded counted overflow instead of truncated success',async()=>{
 const f=await consoleFixture();for(let i=0;i<35;i++)f.observer.observe(f.message(`${f.origin}/unknown-${i}`,'Actual application warning','warning'));assert.throws(()=>f.observer.assertComplete(),/diagnostic bound exceeded/);const e=f.observer.evidence;assert.equal(e.groups.length,32);assert.equal(e.total_events,35);assert.equal(e.overflow.count,3);assert.equal(e.overflow.first.index,33);assert.equal(e.overflow.last.index,35);assert.equal(e.unexpected_events,35);
 const large=await consoleFixture();large.observer.observe(large.message(large.url(1),'x'.repeat(1025)));assert.throws(()=>large.observer.assertComplete(),/diagnostic bound exceeded/);assert.equal(large.observer.evidence.groups.length,0);assert.equal(large.observer.evidence.overflow.count,1);assert.match(large.observer.evidence.overflow.first.identity_sha256,/^[0-9a-f]{64}$/);
});
test('hosted console diagnostics use actual response receipts and retain fatal checks through page close',async()=>{
 const source=await readFile(new URL('../scripts/hosted-vsq-song-check.mjs',import.meta.url),'utf8');assert.match(source,/consoleObserver\.pendingResponse\(\{sequence,url:q\.url\(\),method:q\.method\(\),owned:actionPending&&phaseReport\.actions\.at\(-1\)\?\.sequence===sequence,status:404,body:\{error:'pending'\}\}\)/);assert.match(source,/await route\.fulfill\(\{status:404,json:\{error:'pending'\}\}\);pending\.finish\(true\)/);assert.match(source,/catch\(error\)\{pending\.finish\(false\);throw error;/);assert.match(source,/page\.on\('console',message=>consoleObserver\.observe\(message\)\)/);assert.equal((source.match(/consoleObserver\.assertComplete\(\)/g)||[]).length,2);assert.match(source,/await context\.close\(\);context=null;await nativeBridge\.drain\(\);assert\.deepEqual\(phaseReport\.page_errors,\[\]\);consoleObserver\.assertComplete\(\)/);assert.match(source,/consoleObserver\?\.reconcile\(\)/);
});

test('console events arriving before fulfill resolves are reconciled only against its completed receipt',async()=>{
 const f=await consoleFixture(),receipt=f.pending();f.observer.observe(f.message());assert.equal(f.observer.reconcile().groups[0].classification,'unexpected');receipt.finish(true);f.observer.assertComplete();assert.equal(f.observer.evidence.groups[0].classification,'owned-pending-result');assert.equal(f.observer.evidence.expected_events,1);
 const info=await consoleFixture();info.observer.observe(info.message(`${info.origin}/app.js`,'Startup information','info'));info.observer.assertComplete();assert.equal(info.observer.evidence.informational_events,1);assert.equal(info.observer.evidence.groups[0].text,'Startup information');
});

test('native fingering JSON observations preserve the caller promise and bind the consumed body to its request index',async()=>{
 const {createVsqJsonObserver}=await observationHelpers(),rows=[],errors=[],body={source:{choice:'base_notes_instrumental'},plan:{status:'ready'}},original=Promise.resolve(body),response={status:200,json:()=>original};
 const observer=createVsqJsonObserver({onValue:row=>rows.push(row),onError:error=>errors.push(error),maxRows:1});
 await observer.observe('/api/library/fingering/piano',Promise.resolve(response),17);assert.equal(response.json(),original);assert.equal(await original,body);
 assert.deepEqual(JSON.parse(JSON.stringify(rows)),[{path:'/api/library/fingering/piano',status:200,body,requestIndex:17}]);
 assert.deepEqual(JSON.parse(JSON.stringify(observer.snapshot())),[{path:'/api/library/fingering/piano',status:200,state:'consumed',requestIndex:17}]);assert.deepEqual(errors,[]);observer.restore();
});
test('trusted fingering actions are read through control children without exempting synthetic setting changes',async()=>{
 const {createVsqControlObserver}=await observationHelpers(),listeners=new Map(),document={addEventListener:(type,fn)=>listeners.set(type,fn),removeEventListener:type=>listeners.delete(type)};
 const observer=createVsqControlObserver(document),control={id:'piano-fingering-replan'},child={closest:selector=>selector.includes('#piano-fingering-replan')?control:null};
 listeners.get('click')({type:'click',isTrusted:true,target:child});assert.equal(observer.trusted[0].id,control.id);assert.equal(observer.trusted[0].trusted,true);
 const select={id:'instrument',value:'guitar',closest:selector=>selector.includes('#instrument')?select:null};listeners.get('change')({type:'change',isTrusted:false,target:select});assert.equal(observer.trusted[1].trusted,false);assert.equal(observer.trusted[1].value,'guitar');observer.restore();assert.equal(listeners.size,0);
});
test('fingering appendix leaves original playback/export first and uses only real native controls for value changes',async()=>{
 const source=await readFile(new URL('../crates/desktop-shell/vsq-song-acceptance.js',import.meta.url),'utf8'),exported=source.indexOf("checkpoint('exact-package-export')"),appendix=source.indexOf("checkpoint('native-fingering-setup')"),reload=source.indexOf("checkpoint('reload-choice-reset')");
 assert.ok(exported<appendix&&appendix<reload);const code=source.slice(appendix,reload);
 assert.ok(code.includes('fingeringObservationActive=true')&&code.includes('fingeringObservationActive=false'));
 assert.ok(code.includes('validatePianoFingering')&&code.includes('validateGuitarFingering')&&code.includes('fingeringResponse(row.body,fingeringSource(ctx))'));
 assert.doesNotMatch(code,/\.value\s*=(?!=)|dispatchEvent|setTimeout|\.setSettings|\.prepare\(/,'Acceptance cannot replace user controls, delay native responses or invoke application planners');
 assert.ok(code.includes("await guidanceAction('select-last','guitar-lock-fret')")&&code.includes("guidanceResponse(from,'guitar','infeasible_under_model')"));
});

test('vsq-song requires distinct phase profiles and matching fresh host records in the hashed proof',async t=>{
 const f=await originalEvidence(t);await assertNativeProfileEvidence({directory:f.directory,native:f.native,save:f.save,verify:verifyNativeVsqSongEvidence,nativeFile:'native-vsq-song.json'});
});

test('VSQ acceptance requires actual source-bound Worklet evidence and keeps Windows origin strict',()=>{
 for(const mutate of [r=>delete r.listenThread,r=>r.listenThread[0].messages[0].isTrusted=false,r=>r.listenThread[0].plan.notes.pop(),r=>r.machineThread[0].plan.notes.push(r.listenThread[0].plan.notes[1]),r=>r.pauseThread[0].terminals[0].record.type='ended',r=>r.receiverCleanup.restored=false,r=>r.beforeChoice.audio.worklet.receivers=1,r=>r.finalAudio.worklet.pendingReceivers=1]){const report=structuredClone(originalReport());mutate(report);assert.throws(()=>validateVsqRenderer(report));}
 const report=structuredClone(originalReport());report.origin='http://127.0.0.1:43127';assert.throws(()=>validateVsqRenderer(report));validateVsqRenderer(report,fixture,{expectedOrigin:report.origin});assert.throws(()=>validateVsqRenderer(report,fixture,{expectedOrigin:'http://0.0.0.0:43127'}));
});
