import {readPlaybackClock} from '../web/playback-clock-view.js';
import {addNativeProfileEvidence,assertNativeProfileEvidence} from './native-profile-evidence-fixtures.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {deflateSync} from 'node:zlib';
import {spawnSync} from 'node:child_process';
import {performanceAcceptanceFixtures,preparePerformanceFixtures} from '../scripts/prepare-performance-song-fixtures.mjs';
import {validatePerformanceRun,validatePerformanceRenderer,validatePerformanceTakes,verifyNativePerformanceSongEvidence,PERFORMANCE_PHASES,PERFORMANCE_CHECKS,PERFORMANCE_REPORT_BYTES} from '../scripts/verify-native-performance-song-evidence.mjs';
import {createCleanPerformancePlayer} from '../web/clean-performance-player.js';
import {storedZip} from './native-import-driver-fixtures.js';
import {digest} from './clean-song-package-fixtures.js';
import {freePracticeApp,fixtureScoreServer} from './free-practice-app-fixtures.js';
const pack=performanceAcceptanceFixtures(),renderer=await readFile(new URL('../crates/desktop-shell/performance-song-acceptance.js',import.meta.url),'utf8');
const scope={structuredClone};vm.createContext(scope);vm.runInContext(renderer.split('(() => {')[0],scope);const observe=vm.runInContext('observeCompletePerformanceAudio',scope);
const activateOriginal=vm.runInContext('activatePerformanceOriginalScore',scope);
const navigationSource=await readFile(new URL('../crates/desktop-shell/acceptance-wait.js',import.meta.url),'utf8');
const {createAcceptanceNavigation,createAcceptanceWait}=vm.runInNewContext(`${navigationSource}\n({createAcceptanceNavigation,createAcceptanceWait})`,{AbortController,setTimeout,clearTimeout});

// Ordinary Node DOM contracts exercise the real menu/preview handlers. They
// neither generate trusted input nor constitute browser/native acceptance.
async function setupFixture({suppressStart=false,deferCompilation=false}={}) {
 const serve=await fixtureScoreServer();let compiles=0,release;
 const app=await freePracticeApp({fetchResult:(path,body)=>{
  if(path==='/api/compile'&&++compiles===2&&deferCompilation)return new Promise(resolve=>{release=()=>resolve(serve(path,body));});
  return serve(path,body);
 }}),clicks=[],wait=createAcceptanceWait(),prototype=app.window.HTMLElement.prototype,geometry=Object.getOwnPropertyDescriptor(prototype,'getBoundingClientRect');
 Object.defineProperty(prototype,'getBoundingClientRect',{configurable:true,writable:true,value(){return {width:120,height:40};}});
 const click=id=>{clicks.push(id);if(id!=='start-listen'||!suppressStart)app.$(id).click();};
 const menu=createAcceptanceNavigation({document:app.document,click,until:(condition,label)=>wait.until(condition,label,suppressStart?40:5000)});
 return {app,clicks,menu,click,release:()=>release?.(),compiles:()=>compiles,async close(){try{release?.();await app.close();}finally{if(geometry)Object.defineProperty(prototype,'getBoundingClientRect',geometry);else delete prototype.getBoundingClientRect;}}};
}
test('performance setup admits the original preview through real app controls before human transport preparation',async()=>{
 const f=await setupFixture({deferCompilation:true});try{
  await f.menu.enterLibrary();assert.equal(f.app.$('resume-session').hidden,true);assert.equal(f.app.$('play-button').disabled,true);
  const preview=f.app.$('preview-title').textContent,identity=f.app.$('song-lobby').dataset.previewId;
  let settled=false;const pending=activateOriginal({document:f.app.document,click:f.click,menu:f.menu});pending.then(()=>{settled=true;});
  await f.app.until(()=>f.compiles()===2);await f.app.tick();assert.equal(settled,false);assert.equal(f.app.document.body.dataset.screen,'library');
  assert.deepEqual(f.app.audio(),{contexts:0,unlocks:0},'Scripted setup cannot wait on autoplay permission');
  f.release();const setup=await pending;
  assert.deepEqual(JSON.parse(JSON.stringify(setup)),{kind:'scripted-menu',controls:['sound-button','start-listen'],previewId:identity,title:preview});
  assert.deepEqual(f.clicks,['home-single-player','sound-button','start-listen']);
  assert.equal(f.menu.ready('stage','play-button'),true);assert.equal(f.app.$('resume-session').hidden,false);
  assert.equal(f.app.$('stage-title').textContent,preview);assert.ok(readPlaybackClock(f.app.document).durationMs>0);
  assert.equal(f.app.$('hud-captured').textContent,'0');assert.deepEqual(f.app.audio(),{contexts:0,unlocks:0});
 }finally{await f.close();}
});
test('performance setup fails when Listen does not admit a stage and never retries or resumes an empty session',async()=>{
 const f=await setupFixture({suppressStart:true});try{
  await f.menu.enterLibrary();await assert.rejects(activateOriginal({document:f.app.document,click:f.click,menu:f.menu}),/Timed out: original score admitted to stage/);
  assert.deepEqual(f.clicks,['home-single-player','sound-button','start-listen']);assert.equal(f.app.document.body.dataset.screen,'library');
  assert.equal(f.app.$('resume-session').hidden,true);assert.equal(f.app.$('play-button').disabled,true);assert.deepEqual(f.app.audio(),{contexts:0,unlocks:0});
 }finally{await f.close();}
});
class Param{constructor(){this.value=0;}setValueAtTime(value){this.value=value;return this;}linearRampToValueAtTime(){return this;}}
class Node{constructor(context){this.context=context;this.gain=new Param();this.pan=new Param();this.frequency=new Param();this.Q=new Param();this.type='sine';}connect(node){assert.equal(node.context,this.context);return node;}disconnect(){}start(){}stop(){}}
class Audio{constructor(){this.currentTime=0;this.sampleRate=48000;this.state='running';}createGain(){return new Node(this);}createStereoPanner(){return new Node(this);}createOscillator(){return new Node(this);}createBufferSource(){const n=new Node(this);delete n.frequency;delete n.type;return n;}createBiquadFilter(){return new Node(this);}createBuffer(channels,length){return{getChannelData:()=>new Float32Array(length)};}}
const runs=new Map();
async function actualReceiverRun(f,muted=null){const key=f.key+':'+muted;if(runs.has(key))return structuredClone(runs.get(key));const original=Audio.prototype.createOscillator,probe=observe({AudioContext:Audio}),context=new Audio(),output=context.createGain();let pending=new Map(),id=0;const timers={setTimeout:fn=>{pending.set(++id,fn);return id;},clearTimeout:id=>pending.delete(id)};const player=createCleanPerformancePlayer(f.reference,{contextFactory:()=>({context,output}),timers});if(muted!==null)player.setTrackMuted(muted,true);await player.play({userGesture:true,acceptedPolicyId:f.reference.policy.id});for(let t=.02;t<5.2;t+=.02){context.currentTime=t;const callbacks=[...pending.values()];pending.clear();callbacks.forEach(fn=>fn());}assert.equal(player.snapshot().state,'ended');const audio=JSON.parse(JSON.stringify(probe.snapshot()));probe.restore();assert.equal(Audio.prototype.createOscillator,original);assert.equal(pending.size,0);const value={mutedTracks:muted===null?[]:[muted],elapsedMs:5200,clock:'0:05.0 / 0:05.0',audio};runs.set(key,value);return structuredClone(value);}
function live(snapshot){const v=structuredClone(snapshot),now=v.sources[0].starts[0]+.1;for(const r of v.sources){r.disconnected=false;r.currentTime=now;}v.activeSources=v.sources.filter(r=>r.starts[0]<=now&&r.stops.at(-1)>now).length;v.pendingSources=v.sources.filter(r=>r.starts[0]>now&&r.stops.at(-1)>r.starts[0]).length;return v;}
const empty=()=>({sourceStarts:0,oscillatorStarts:0,activeSources:0,pendingSources:0,sources:[],parameters:[]});
function choice(f,accepted=false){return{preview:'performance',notation:'Notation unavailable · Practice targets and grades unavailable',policy:f.reference.policy.id,accepted,acceptDisabled:!f.reference.playable,policyLabel:f.reference.logical_device_mapping?'I select this reference sound, event playback and logical device mapping policy':'Accept reference policy',routing:route(f),problems:{hidden:f.reference.playable,text:f.reference.playable?'':'unsupported_bank_select'},playDisabled:!accepted||!f.reference.playable,listenDisabled:true,practiceDisabled:true,counts:{tracks:f.reference.trackCount,events:f.reference.eventCount,attacks:f.reference.voices.length},tracks:f.reference.tracks.map((t,index)=>({index,events:t.source_event_count,attacks:f.reference.voices.filter(v=>v.trackIndex===index).length,text:t.name,checked:false,disabled:!f.reference.playable||!t.independent})),audio:empty()};}
function route(f,zh=false){const device=f.reference.logical_device_mapping?.device_name;return{hidden:!device,text:!device?'':zh?`逻辑目标“${device}”映射到所选程序合成参考接收器。未验证源设备与原始音色。`:`Logical destination “${device}” is mapped to the selected procedural reference receiver. The source device and timbre are unverified.`};}
function chinese(f){return{coverage:'记谱不可用 · 练习目标与评分不可用',policy:f.reference.logical_device_mapping?'我选择此参考声音、事件播放与逻辑设备映射策略':'接受参考演奏',routing:route(f,true)};}
function gestures(){const base={button:0,buttons:0,defaultPrevented:false,activation:{isActive:true,hasBeenActive:true},focus:{hasFocus:true,activeId:'import-button',visibility:'visible'},trigger:{id:'import-button',tag:'BUTTON',type:'submit',disabled:false,connected:true,inert:false},input:{id:'score-file',tag:'INPUT',type:'file',disabled:false,connected:true,inert:false,multiple:true},dialog:{id:'import-tools-dialog',open:true,modal:true}};return[['before-action',null,null],['pointerdown','import-button',true],['pointerup','import-button',true],['click','import-button',true],['click','score-file',false],['change','score-file',true]].map(([type,targetId,trusted])=>({...structuredClone(base),observedAtMs:1050,eventTimeMs:type==='before-action'?null:50,type,targetId,trusted}));}
function transport(){const state={passId:'1',captured:'1',cue:'paused',phase:'paused',hidden:false,openDialogs:[],positionMs:500,durationMs:32000};return{version:1,stage:'complete',omitted:0,rowBytes:1000,trustedPlayClicks:2,trustedKeyDowns:1,trustedKeyUps:1,current:state,rows:[{kind:'ready',state:{...state,positionMs:0,captured:'0'}},{kind:'transport',state:{...state,phase:'capturing',positionMs:200}},...['keydown','keyup'].map(type=>({kind:'event',state,event:{type,trusted:true,code:'KeyR',surface:'stage-title',repeat:false}}))]};}
function take(){const input={midi:60,velocity:90,at_ms:100};return{version:1,score_id:'original-authored-practice',practice_part:null,passes:[{id:1,capture_enabled:true,inputs:[input],captures:[{event_id:1,event_wall_ms:1100,received_wall_ms:1101,input}],assessment:null,timeline:{notes:[{id:'authored-note',midi:60,start_ms:0,duration_ms:1000}]}}],input_evidence:{version:1,truncated:false,omitted_observations:0,events:[{event_id:1,kind:'note_on',input_kind:'typing_keyboard',encoding:'key_down',midi:60,velocity:90,event_wall_ms:1100,received_wall_ms:1101,onset_capture:{pass_id:1,event_id:1}}]}};}
async function report(phase='performance-seed'){
 const selected=phase==='performance-restart'?pack.fixtures.filter(f=>f.reference.playable):pack.fixtures.filter(f=>f.name.includes(phase==='performance-controls'?'controls':'overlap')),trusted=[];
 const r={version:1,phase,origin:'https://wmh.localhost',ok:true,stage:'complete',profileMarkerAbsent:true,checks:[...PERFORMANCE_CHECKS],errors:[],diagnostics:[{stage:'complete',elapsedMs:100}],inventory:pack.fixtures.map(f=>({key:f.key,library_format_version:2,revision:1,content_sha256:f.opened.clean_package.content_sha256,score_sha256:f.metadata.score.sha256,score_bytes:f.files.get('score.json').length,score_id:f.metadata.id,title:f.metadata.title,retained_source:null,clean_package:f.summary})),opened:pack.fixtures.map(f=>({key:f.key,...f.opened})),variants:[],blocked:[],beforeTakeState:{captured:'1'},afterTakeState:{captured:'1'},requests:[],referenceRequestStart:0,imports:[],trusted,pickerObservations:[],responseObservations:[],actions:phase==='performance-seed'?64:phase==='performance-controls'?50:47,files:{beforeTake:`${phase}-1.json`,afterTake:`${phase}-2.json`},transportAdmission:transport(),screenshots:{}};
 const humanStart=phase==='performance-seed'?4:0;r.baselineScope={humanActionStart:humanStart,humanActionEnd:humanStart+3,readyAfterAction:humanStart+4};r.originalScoreSetup={kind:'scripted-menu',controls:['sound-button','start-listen'],previewId:'original-catalog-score',title:'Original catalog score'};
 if(phase==='performance-seed'){const initial={screen:'library',previewId:r.originalScoreSetup.previewId,previewStatus:'ready',previewTitle:r.originalScoreSetup.title,stageTitle:'Your stage',resumeHidden:true,playDisabled:true,resultsDisabled:true,captured:'0',pass:'',revision:''};r.requests=[{path:'/api/library/import/preview'},{path:'/api/library/import/commit'}];r.referenceRequestStart=2;r.importSetup={before:initial,after:structuredClone(initial),actionStart:0,actionEnd:4,requestStart:0,requestEnd:2,audio:empty()};}
 for(const [index,f]of selected.entries()){const variants=[await actualReceiverRun(f)];if(phase!=='performance-restart')for(let i=0;i<f.reference.trackCount;i++){variants.push(await actualReceiverRun(f,i));for(const checked of [true,false])trusted.push({trusted:true,id:`complete-performance-mute-${i}`,type:'change',checked});}trusted.push({trusted:true,id:'complete-performance-policy-accept',type:'change',checked:true});r.variants.push({key:f.key,beforeChoice:choice(f),afterChoice:choice(f,true),reloadChoice:choice(f),chineseChoice:chinese(f),runs:variants,liveCapture:{before:live(variants[0].audio),after:live(variants[0].audio)},...(phase!=='performance-seed'?{playing:live(variants[0].audio),pauseAudio:empty(),stopAudio:empty(),navigationAudio:empty(),pauseClock:{before:'0:01.0 / 0:05.0',after:'0:01.0 / 0:05.0'}}:{})});r.screenshots[`choice-${index+1}`]=10+index*2;if(phase!=='performance-seed')r.screenshots[`playing-${index+1}`]=11+index*2;}
 if(phase==='performance-seed'){r.checks.push('chooser-preflight-all-songs-all-tracks-save','exact-complete-pack-export');r.imports=['preview','commit'].map((mode,i)=>({path:`/api/library/import/${mode}`,status:200,body:{source:{sha256:pack.manifest.sha256,bytes:pack.bytes.length,retained:i===1},items:pack.fixtures.map(f=>({status:i===0?'ready':'saved',playable:false,clean_package:f.summary}))}}));r.preflight=pack.fixtures.map(f=>({status:'ready',playable:false,coverage:f.score.coverage}));r.responseObservations=r.imports.map(row=>({path:row.path,status:200,state:'consumed'}));r.pickerObservations=[{sequence:1,filename:pack.filename,completed:true,gestures:gestures(),delegatedClicks:[{type:'click',trusted:false,id:'score-file',sequence:1}],changes:[{type:'change',trusted:true,id:'score-file',sequence:1,filename:pack.filename}]}];trusted.push({type:'change',trusted:true,id:'score-file',pickerSequence:1});r.files.package=`${phase}-3.zip`;r.screenshots.preflight=3;r.screenshots.playing=4;}
 if(phase!=='performance-seed'){const f=pack.fixtures.find(f=>!f.reference.playable);r.blocked=[{key:f.key,beforeChoice:choice(f),afterChoice:choice(f),chineseChoice:chinese(f)}];r.screenshots['blocked-bank']=20;r.checks.push('named-route-rpn12-disclosure-and-bank-block');}
 r.downloads=Object.values(r.files).map(file=>({file,complete:true,success:true}));return r;
}
test('production receiver and transparent audio observer prove every authored track mute and exact sustain gates',async()=>{for(const f of pack.fixtures.filter(f=>f.reference.playable)){for(const mute of [null,...f.reference.tracks.map((_,i)=>i)])validatePerformanceRun(await actualReceiverRun(f,mute),f);}const control=pack.fixtures[1],voice=control.reference.voices[0];assert.notEqual(voice.releaseEventId,voice.sustainReleaseEventId);assert.equal(voice.endReason,'sustain_release');});
test('source timing, waveform/pitch, muted-track inventory, sustain ends and live controller changes cannot be forged',async()=>{const f=pack.fixtures[1],good=await actualReceiverRun(f);for(const edit of [r=>r.audio.sources.pop(),r=>r.audio.sources[0].starts[0]+=.1,r=>r.audio.sources[0].stops[0]-=1,r=>r.audio.sources[0].wave='invalid-wave',r=>r.audio.sources[0].frequencies[0].value+=1,r=>r.audio.sources[0].disconnected=false,r=>r.audio.parameters=r.audio.parameters.filter(p=>p.kind!=='pan'),r=>r.mutedTracks=[1],r=>r.elapsedMs=100]){const bad=structuredClone(good);edit(bad);assert.throws(()=>validatePerformanceRun(bad,f));}});
test('three renderer contracts require exact source bytes, all tracks, null notation and fresh explicit policy',async()=>{for(const phase of PERFORMANCE_PHASES)validatePerformanceRenderer(await report(phase));const good=await report();for(const edit of [r=>r.opened[0].score_json='{}',r=>r.opened[0].clean_package.score_json+=' ',r=>r.inventory.pop(),r=>r.variants[0].beforeChoice.accepted=true,r=>r.variants[0].beforeChoice.practiceDisabled=false,r=>r.variants[0].beforeChoice.tracks.pop(),r=>r.variants[0].runs.pop(),r=>r.variants[0].liveCapture.after.activeSources=0,r=>r.variants[0].reloadChoice.accepted=true,r=>r.trusted[0].trusted=false,r=>r.requests.push({path:'/api/library/fingering/piano'}),r=>r.pickerObservations[0].changes[0].trusted=false,r=>r.pickerObservations[0].gestures[3].activation.isActive=false,r=>r.checks.pop(),r=>r.actions=65,r=>r.baselineScope.humanActionStart=0,r=>r.importSetup.after.previewId='native:changed',r=>r.importSetup.audio.sourceStarts=1,r=>r.importSetup.requestEnd=0,r=>r.originalScoreSetup.kind='trusted-human']){const bad=structuredClone(good);edit(bad);assert.throws(()=>validatePerformanceRenderer(bad));}});
test('named route disclosure and bank rejection cannot be omitted or reported as audible',async()=>{
 const good=await report('performance-controls');
 for(const edit of [
  r=>r.variants[1].beforeChoice.routing.hidden=true,r=>r.variants[1].beforeChoice.routing.text+=' verified timbre',
  r=>r.variants[1].chineseChoice.routing.text='逻辑目标',r=>r.variants[1].chineseChoice.policy='参考演奏',
  r=>r.variants[1].beforeChoice.policy=r.variants[1].beforeChoice.policy.replace(':single-named-device-v1',''),
  r=>r.blocked=[],r=>r.blocked[0].afterChoice.acceptDisabled=false,r=>r.blocked[0].afterChoice.playDisabled=false,
  r=>r.blocked[0].afterChoice.audio.sourceStarts=1,r=>r.blocked[0].beforeChoice.problems.hidden=true,
  r=>r.blocked[0].beforeChoice.problems.text='unrelated error',r=>r.blocked[0].afterChoice.accepted=true,
 ]){const bad=structuredClone(good);edit(bad);assert.throws(()=>validatePerformanceRenderer(bad));}
});
test('all phase contract reports remain inside unchanged action and evidence limits',async()=>{
 for(const phase of PERFORMANCE_PHASES){const r=await report(phase);validatePerformanceRenderer(r);assert.ok(r.actions<=64);assert.ok(Buffer.byteLength(JSON.stringify(r))<PERFORMANCE_REPORT_BYTES);}
});
test('typed source cannot become a grading target and machine sound cannot alter prior authored input or grade',async()=>{const r=await report(),before=take();validatePerformanceTakes(before,structuredClone(before),r);for(const edit of [t=>t.passes[0].inputs.push({midi:61,velocity:90,at_ms:200}),t=>t.passes[0].assessment={score:100},t=>t.input_evidence.events[0].midi=62,t=>t.input_evidence.events.push({event_id:2,kind:'boundary',reason:'blur',event_wall_ms:1200,received_wall_ms:1200,boundary_wall_ms:1200,timestamp_basis:'application_clock'}),t=>t.score_id=pack.fixtures[0].score.id]){const after=structuredClone(before);edit(after);assert.throws(()=>validatePerformanceTakes(before,after,r));}const fabricated={...before,score_id:pack.fixtures[0].score.id};assert.throws(()=>validatePerformanceTakes(fabricated,fabricated,r));});
function png(){const crc=b=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=c>>>1^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;},chunk=(name,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;};const header=Buffer.alloc(13);header.writeUInt32BE(640);header.writeUInt32BE(360,4);header[8]=8;header[9]=2;const pixels=Buffer.alloc(1921*360);let value=17;for(let i=0;i<pixels.length;i++){value=(Math.imul(value,1664525)+1013904223)>>>0;pixels[i]=i%1921?value>>>24:0;}return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
async function syntheticEvidence(t){const directory=await mkdtemp(join(tmpdir(),'wmh-performance-verifier-unit-'));t.after(()=>rm(directory,{recursive:true,force:true}));await preparePerformanceFixtures(join(directory,'fixtures'));await mkdir(join(directory,'downloads'));const save=async(name,value)=>writeFile(join(directory,name),JSON.stringify(value)),image=png(),reports={};const native={version:1,scenario:'performance-song',ok:true,profile_reused:false,source_sha:'1'.repeat(40),source_tree:'2'.repeat(40),executable_sha256:'3'.repeat(64),executable_bytes:80000,os:'Microsoft Windows test fixture',directory:join(directory,'Scores'),phases:[]};
 for(const [index,phase]of PERFORMANCE_PHASES.entries()){const r=await report(phase);r.directory=native.directory;reports[phase]=r;for(const kind of ['beforeTake','afterTake'])await save(`downloads/${r.files[kind]}`,take());if(r.files.package){const entries=pack.fixtures.flatMap(f=>[...f.files].map(([name,b])=>[`songs/${f.key}/${name}`,b]));entries.push(['manifest.json',JSON.stringify({format:'worldmusichub-song-pack',version:2,songs:pack.fixtures.map(f=>({folder:`songs/${f.key}`}))})]);await writeFile(join(directory,'downloads',r.files.package),storedZip(entries));}
 const host={phase,process_id:100+index,renderer_ok:true,normal_close:true,launched_new_process:true,profile_fresh:true,profile_reused:false,executable_tcp_listeners:0,renderer_origin:'https://wmh.localhost',actions:r.actions};native.phases.push(host);const keyCount=1+(index===0?0:r.variants.length);
 for(let n=1;n<=r.actions;n++){const kind=n===1&&index===0?'picker':n===r.baselineScope.humanActionStart+2||n>r.actions-(keyCount-1)?'key-r':'click';await save(`action-${phase}-${n}.json`,{version:1,sequence:n,kind,x:10,y:20,width:1280,height:720,...(kind==='picker'?{file:pack.filename}:{})});await save(`result-${phase}-${n}.json`,{ok:true,client_click:{app_hwnd:1,foreground:1,actual:[10,20],requested:[10,20],viewport:[1280,720],hit_hwnd:1},...(kind==='picker'?{owned_dialog:{class:'#32770',hwnd:2,process_id:host.process_id,app_process_id:host.process_id,app_hwnd:1,root_owner_hwnd:1},picker_completion:{dialog_dismissed:true,app_enabled:true,owned_popup_visible:false}}:{})});}
 for(const n of Object.values(r.screenshots))await writeFile(join(directory,`native-action-${phase}-${n}.png`),image);await writeFile(join(directory,`native-${phase}.png`),image);await save(`renderer-${phase}.json`,r);}
 const rows=[],archive=async(path,b)=>{await mkdir(join(directory,'Scores',path.slice(0,path.lastIndexOf('/'))),{recursive:true});await writeFile(join(directory,'Scores',path),b);rows.push({path,bytes:b.length,sha256:digest(b)});};for(const area of ['clean-songs','clean-backups'])for(const f of pack.fixtures){await archive(`${area}/${f.key}/entry.json`,Buffer.from(JSON.stringify(reports[PERFORMANCE_PHASES[0]].inventory.find(e=>e.key===f.key))));for(const [name,b]of f.files)await archive(`${area}/${f.key}/package/${name}`,b);}for(const area of ['imports','import-backups'])await archive(`${area}/pack-${pack.manifest.sha256}/source.bin`,pack.bytes);for(const phase of PERFORMANCE_PHASES)await save(`snapshot-${phase}.json`,{version:1,files:rows});await addNativeProfileEvidence(native,save);await save('native-performance-song.json',native);return{directory,native,reports,save};}
test('synthetic native verifier fixture checks process/OS ownership and stored bytes without constituting Windows acceptance',async t=>{const e=await syntheticEvidence(t),p=await verifyNativePerformanceSongEvidence(e.directory);assert.equal(p.ok,true);assert.equal(p.claims.practice_targets,false);assert.equal(p.claims.actual_audibility,false);assert.ok(p.files.some(f=>f.path.includes('/package/score.json')));});
test('the real Python packaging gate accepts every claim emitted by the real Node verifier',async t=>{
 // Synthetic files exercise the complete cross-language packaging boundary.
 // No Windows executable, GUI, browser or audio device is run by this test.
 const e=await syntheticEvidence(t),executable=join(e.directory,'synthetic-executable.bin'),bytes=Buffer.from('Original synthetic packaging contract bytes');
 await writeFile(executable,bytes);e.native.executable_sha256=digest(bytes);e.native.executable_bytes=bytes.length;await e.save('native-performance-song.json',e.native);
 const proof=await verifyNativePerformanceSongEvidence(e.directory);await e.save('native-performance-song-files.json',proof);
 const script=`import importlib.util,json,sys\nfrom pathlib import Path\nspec=importlib.util.spec_from_file_location('native_manifest',Path('scripts/native-release-manifest.py'))\nmodule=importlib.util.module_from_spec(spec)\nspec.loader.exec_module(module)\nprint(json.dumps(module.accepted_performance_song_evidence(*sys.argv[1:])))\n`;
 const child=spawnSync(process.platform==='win32'?'python':'python3',['-c',script,e.directory,executable,e.native.source_sha,e.native.source_tree],{cwd:new URL('../',import.meta.url),encoding:'utf8',timeout:45000});
 assert.ifError(child.error);assert.equal(child.signal,null);assert.equal(child.status,0,child.stderr);const packaged=JSON.parse(child.stdout);
 assert.equal(packaged.native_performance_song_validated,true);assert.deepEqual(packaged.native_performance_song_claims,proof.claims);
 for(const name of ['named_route_disclosure_both_locales','centered_rpn12_exact_events','unsupported_bank_blocked_before_audio'])assert.equal(packaged.native_performance_song_claims[name],true);
 assert.equal(packaged.native_performance_song_claims.actual_audibility,false);assert.equal(packaged.native_performance_song_claims.practice_targets,false);
 assert.deepEqual(Object.keys(packaged.native_performance_song_reports_sha256).sort(),['native-performance-song.json',...PERFORMANCE_PHASES.flatMap(phase=>[`renderer-${phase}.json`,`profile-${phase}.json`])].sort());
});
test('native evidence rejects reused processes, driver-shaped host evidence and forged owned-dialog completion',async t=>{const e=await syntheticEvidence(t);for(const edit of [n=>n.phases[1].process_id=n.phases[0].process_id,n=>n.phases[0].normal_close=false,n=>n.os='Linux stdio',n=>n.executable_sha256='unknown']){const bad=structuredClone(e.native);edit(bad);await e.save('native-performance-song.json',bad);await assert.rejects(verifyNativePerformanceSongEvidence(e.directory));}await e.save('native-performance-song.json',e.native);const name='result-performance-seed-1.json',good=JSON.parse(await readFile(join(e.directory,name)));await e.save(name,{...good,picker_completion:{...good.picker_completion,owned_popup_visible:true}});await assert.rejects(verifyNativePerformanceSongEvidence(e.directory));});
test('native evidence rejects package mutation, duplicate sidecars and missing screenshot pixels',async t=>{const e=await syntheticEvidence(t),f=pack.fixtures[0],path=`Scores/clean-songs/${f.key}/package/score.json`,before=await readFile(join(e.directory,path));await writeFile(join(e.directory,path),Buffer.concat([before,Buffer.from(' ')]));await assert.rejects(verifyNativePerformanceSongEvidence(e.directory));await writeFile(join(e.directory,path),before);await writeFile(join(e.directory,`Scores/clean-songs/${f.key}/package/runtime.json`),'{}');await assert.rejects(verifyNativePerformanceSongEvidence(e.directory));await rm(join(e.directory,`Scores/clean-songs/${f.key}/package/runtime.json`));await writeFile(join(e.directory,'native-performance-seed.png'),Buffer.from('not a screenshot'));await assert.rejects(verifyNativePerformanceSongEvidence(e.directory));});
test('hosted entry point refuses local launch and retains real chooser/console/native driver paths',()=>{const env={...process.env};delete env.GITHUB_ACTIONS;delete env.WMH_HOSTED_BROWSER;const child=spawnSync(process.execPath,['scripts/hosted-performance-song-check.mjs'],{cwd:new URL('../',import.meta.url),env,encoding:'utf8'});assert.equal(child.status,1);assert.match(child.stderr,/Only the authorized hosted browser runner/);});

test('performance-song requires distinct phase profiles and matching fresh host records in the hashed proof',async t=>{
 const f=await syntheticEvidence(t);await assertNativeProfileEvidence({directory:f.directory,native:f.native,save:f.save,verify:verifyNativePerformanceSongEvidence,nativeFile:'native-performance-song.json'});
});
