import {mockNativeOriginalPracticeResponse} from './native-basic-admission-fixtures.js';
// Pure adversarial verifier records. These never claim a Windows execution.
import test from 'node:test';
import {withMockBasicEligibility} from './basic-human-admission-fixtures.js';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {assistanceNativeFixtures,progressionNativeFixtures,ASSISTANCE_PHASES} from '../scripts/native-assistance-fixtures.mjs';
import {ASSISTANCE_SOURCE_FILES,ASSISTANCE_CLAIMS,validateAssistanceRequestCompletion} from '../scripts/verify-native-assistance-evidence.mjs';
import {PROGRESSION_NATIVE_FILES,progressionExpectedSchedules,progressionExpectedAudioPlan,validateNativeProgressionAudio,validateNativeProgressionTake,nativeProgressionResponse,validateNativeProgressionRequests,validateNativeProgressionView,validateNativeProgressionControls,validateNativeProgressionStorage} from '../scripts/native-progression-proof.mjs';
import {syntheticAudioThreadRun,syntheticAudioThreadStatus} from './audio-thread-proof-fixtures.js';
import {progressionText} from '../web/practice-progression-locales.js';
const f=progressionNativeFixtures(),original=assistanceNativeFixtures(),p=f.basic.layers.balanced.response.checked,c=p.assistance,clone=structuredClone;
function take({human=false,off=false,capture=true}={}){
 const selected=off?original.basic.original.checked:c,identity=off?null:{plan:clone(c.plan),receipt:clone(c.receipt),human_target_ids:c.human_targets.groups.map(g=>g.target_id),machine_occurrence_ids:clone(c.machine_occurrence_ids),scored_mode_allowed:c.scored_mode_allowed},proof=off?null:clone(p.plan),song_mod={config:{parts:c.plan.selection.selected_part_ids.map(partId=>({partId,performer:'human',instrument:partId==='midi-t1-c1-r0'?'reed':'source'}))}},input={midi:72,velocity:90,at_ms:750};
 return{practice_assistance:identity,practice_progression:proof,...(off?{practice_assistance_disabled:true}:{}),practice_selection:{kind:'all',part_ids:clone(c.plan.selection.selected_part_ids)},target_plan:clone(selected.human_targets),song_mod,latency_ms:0,...(capture?{input_evidence:{version:1,truncated:false,omitted_observations:0,events:human?[{kind:'note_on',input_kind:'typing_keyboard',encoding:'key_down',midi:72,raw_timestamp_ms:850,onset_capture:{pass_id:1,event_id:1}}]:[]}}:{}),passes:[{id:1,capture_enabled:capture,pending:false,timeline:clone(selected.human_targets.timeline),clock_segments:[{wallStart:100,wallEnd:1100,positionStart:0}],interpretation:{basic_practice_admission:{receipt:clone(selected.receipt),selection_digest:selected.plan.selection_digest},practice_assistance:clone(identity),practice_progression:clone(proof),...(off?{practice_assistance_disabled:true}:{}),song_mod:clone(song_mod),source_revision:{songId:JSON.parse(original.basic.opened.clean_package.score_json).notation.id,sourceRevision:{kind:'clean-package-sha256',value:f.basic.source.content_sha256}}},inputs:human?[input]:[],captures:human?[{event_id:1,event_wall_ms:850,received_wall_ms:851,input}]:[],assessment:{hits:human?[{note_id:'midi-t1-e11'}]:[],misses:selected.human_targets.timeline.notes.filter(n=>!human||n.id!=='midi-t1-e11').map(n=>n.id),extras:[]}}]};
}
function audio(off=false){
 const sourceSha256=original.basic.opened.clean_package.runtime.source_sha256,make=(receiverId,paused=false)=>syntheticAudioThreadRun(off?[]:progressionExpectedSchedules(),{receiverId,sourceSha256,durationMs:1000,sourceNotes:6,off,cancelMs:paused?300:null,planOracle:progressionExpectedAudioPlan});
 return{phase:off?'assistance-off-restart':'assistance-progression',progressionRuns:off?{progressionOffRestart:[make(1)]}:{progressionMachineOnly:[make(1)],progressionHuman:[make(2)],paused:[make(3,true)]},audioStatus:syntheticAudioThreadStatus({started:off?1:3,completed:off?1:2})};
}
function view(response,{layer=response?.checked.plan.layer,draft=false}={}){return{mode:'progression',visible:true,layer,state:draft?'unchecked':'checked',rows:draft?[{layer:null,selected:null,current:null,text:progressionText('en','unchecked')}]:response.checked.layers.map(row=>({layer:row.layer,selected:String(row.layer===layer),current:row.layer===layer?'step':null,text:progressionText('en','row',{name:progressionText('en',row.layer),human:row.human_target_count,units:row.human_source_unit_count})+(row.equals_previous_layer?' · '+progressionText('en','equal'):'')+(!row.human_target_count?' · '+progressionText('en','empty'):'' )}))};}
function preference(kind,layer='balanced'){
 const source=f[kind].source,preference_key=JSON.stringify([source.key,source.content_sha256,source.profile,source.choice,source.runtime_policy]);
 return['worldmusichub.practice-progression.v1.'+encodeURIComponent(preference_key),JSON.stringify({format:'wmc-practice-progression-preference',version:1,preference_key,source,mode:layer==='off'?'off':'progression',plan:layer==='off'?null:kind==='vsq'?f.vsq.narrow_scope.checked.plan:f.basic.layers[layer].response.checked.plan})];
}
function storage(){const legacy={legacy:'exact prior v1 bytes'},balanced=Object.fromEntries([preference('basic')]),off=Object.fromEntries([preference('basic','off')]),final={...off,...Object.fromEntries([preference('vsq','single')])};return[{storageAfter:clone(legacy)},{storageAfter:clone(legacy)},{phase:'assistance-progression',storageBefore:clone(legacy),storageAfter:clone(legacy),progressionStorageBefore:{},progressionSaved:balanced,progressionPaused:{storage:clone(balanced)},progressionResetStorage:Object.fromEntries([preference('basic','single')]),progressionOffStorage:off,progressionStorageAfter:final},{phase:'assistance-off-restart',storageBefore:clone(legacy),storageAfter:clone(legacy),progressionStorageBefore:clone(final),progressionStorageAfter:clone(final)}];}
function requests(off=false){
 const takes=off?{progressionOffRestart:take({off:true})}:{progressionMachineOnly:take(),progressionHuman:take({human:true}),progressionOff:take({off:true,capture:false})},rows=[],add=(path,request,response)=>{rows.push({path,request:clone(request),response:clone(response),status:200,observation:'consumed',signalGeneration:null,signalAbortedAtStart:false,signalAborted:false,canceled:false,started:{actionSequence:rows.length+1,screen:'library',previewId:'native:'+f.basic.source.key},settled:{actionSequence:rows.length+1,screen:'library',previewId:'native:'+f.basic.source.key}});};
 if(!off){for(let i=0;i<2;i++)add('/api/library/progression/validate',{source:f.basic.source,plan:p.plan},f.basic.layers.balanced.response);add('/api/library/practice-admission',{source:f.basic.source,pitch_mod:{format:'wmc-pitch-mod',version:1,semitones:0},selection:c.plan.selection,plan:c.plan},{source:f.basic.source,checked:c});add('/api/library/runtime',{key:f.vsq.source.key,profile:'wmh-vsq-clean-v1',choice:'base_notes_instrumental'},original.vsq.selected_runtime);for(const response of [f.vsq.layers.single.response,f.vsq.narrow_scope])add('/api/library/progression/generate',{source:f.vsq.source,selection:response.checked.plan.selection,layer:response.checked.plan.layer},response);}
 const offRequestStart=rows.length,compact=original.basic.opened.clean_package.runtime.compilation.timeline,timeline={duration_ms:compact.duration_ms,notes:compact.notes.map(([id,part_id,midi,velocity,start_ms,duration_ms])=>({id,part_id,midi,velocity,start_ms,duration_ms,source_note_id:id,source_note_ids:[id],voice:'1',staff:1}))},request={timeline,profile:c.plan.selection.profile};
 add('/api/library/practice-admission',{source:original.basic.source,pitch_mod:{format:'wmc-pitch-mod',version:1,semitones:0},selection:original.basic.original.checked.plan.selection},mockNativeOriginalPracticeResponse(original.basic.original));add('/api/instrument-check',request,{changed_source_notes:false,note_options:timeline.notes.map(n=>({note_id:n.id,midi:n.midi,playable:true,positions:[]}))});const selected=off?takes.progressionOffRestart:takes.progressionOff;add('/api/assess',{timeline:selected.passes[0].timeline,inputs:selected.passes[0].inputs},selected.passes[0].assessment);
 return withMockBasicEligibility({originalFixtures:original,progressionFixtures:f,takes,report:{phase:off?'assistance-off-restart':'assistance-progression',requests:rows,requestsRestored:true,actions:rows.length,offRequestStart,offRequestEnd:rows.length,offAssessAction:rows.length}});
}
test('native progression uses the exact original imports, strict chosen proof and genuinely nested API vectors',()=>{
 for(const kind of ['basic','vsq']){assert.deepEqual(f[kind].source,original[kind].source);let ids=new Set();for(const layer of ['single','balanced','dense']){const response=f[kind].layers[layer].response;assert.deepEqual(Object.keys(response.checked).sort(),['assistance','layers','plan']);assert.equal(response.checked.layers.length,3);const next=new Set(response.checked.assistance.human_targets.groups.flatMap(g=>g.source_occurrence_ids));for(const id of ids)assert.ok(next.has(id));ids=next;assert.equal(response.checked.assistance.coverage.human_occurrence_count+response.checked.assistance.machine_occurrence_ids.length,response.checked.assistance.coverage.occurrence_count);assert.deepEqual(nativeProgressionResponse({source:f[kind].source,selection:response.checked.plan.selection,layer}),response);}}
 assert.equal(c.plan.mode,'explicit');assert.notEqual(c.plan.selection_digest,original.basic.automatic.checked.plan.selection_digest);assert.deepEqual(progressionExpectedSchedules().map(n=>n.noteId),['midi-t1-e4','midi-t1-e13']);assert.deepEqual(progressionExpectedAudioPlan(progressionExpectedSchedules(),{sampleRate:48000}).timbres,[3,0]);
 assert.ok(f.vsq.narrow_scope.checked.assistance.exclusion_reasons.some(r=>r.code==='cross_scope_physical_group'));assert.equal(f.vsq.narrow_scope.checked.assistance.human_targets.target_count,0);assert.equal(f.vsq.narrow_scope.checked.assistance.scored_mode_allowed,false);
});
test('progressive take verifier admits one genuine human input, silent machine-only and ordinary Off shapes',()=>{for(const options of [{},{human:true},{off:true},{off:true,capture:false}])validateNativeProgressionTake(take(options),options);});
test('progressive take verifier rejects stale layer proof, missing allocation, machine score and altered native timestamp',()=>{
 for(const mutate of [t=>t.practice_progression.plan_digest='f'.repeat(64),t=>t.practice_progression.layer='dense',t=>t.practice_assistance.machine_occurrence_ids=[],t=>t.passes[0].interpretation.practice_progression=null,t=>t.passes[0].assessment.hits[0].note_id='midi-t1-e4',t=>t.input_evidence.events[0].input_kind='machine',t=>t.passes[0].captures[0].event_wall_ms++,t=>t.passes[0].clock_segments[0].wallStart++,t=>t.passes[0].captures[0].event_id++,t=>t.passes[0].inputs.push({midi:60,at_ms:125})]){const t=take({human:true});mutate(t);assert.throws(()=>validateNativeProgressionTake(t,{human:true}));}
});
test('progressive worklet verifier requires source gates, actual PCM, authenticated raw ports, paused cancellation and ordinary Off',()=>{
 validateNativeProgressionAudio(audio());validateNativeProgressionAudio(audio(true));
 for(const mutate of [r=>r.progressionRuns.progressionMachineOnly[0].pcm.blocks[0].peak=0,r=>r.progressionRuns.progressionHuman[0].plan.assistanceFingerprint='f'.repeat(64),r=>r.progressionRuns.paused[0].terminals[0].record.frame++,r=>r.progressionRuns.progressionMachineOnly[0].plan.notes[0][3]++,r=>r.progressionRuns.progressionHuman[0].rawTerminals[0].isTrusted=false,r=>r.progressionRuns.paused[0].receiverId=1,r=>r.audioStatus.started++,r=>r.progressionRuns.progressionHuman=[]]){const r=audio();mutate(r);assert.throws(()=>validateNativeProgressionAudio(r));}
 const r=audio(true);r.progressionRuns.progressionOffRestart[0].plan.assistanceFingerprint='f'.repeat(64);assert.throws(()=>validateNativeProgressionAudio(r));
});
test('progressive summaries bind all three stages and only the current chosen assistance',()=>{
 for(const response of [f.basic.layers.balanced.response,f.vsq.layers.single.response,f.vsq.narrow_scope])validateNativeProgressionView(view(response),response);
 validateNativeProgressionView(view(null,{layer:'single',draft:true}),null,{layer:'single',draft:true});
 for(const mutate of [v=>v.mode='automatic',v=>v.rows.pop(),v=>v.rows[0].text='invented counts',v=>v.rows[1].selected='false',v=>v.rows[2].current='step',v=>v.layer='dense']){const v=view(f.basic.layers.balanced.response);mutate(v);assert.throws(()=>validateNativeProgressionView(v,f.basic.layers.balanced.response));}
});
test('new namespace preserves legacy bytes and pins Off across the fourth process without reviving Original',()=>{
 validateNativeProgressionStorage(storage());
 for(const mutate of [r=>r[2].storageAfter={},r=>r[3].storageBefore={},r=>r[3].progressionStorageBefore={},r=>r[2].progressionSaved=Object.fromEntries([preference('basic','single')]),r=>r[2].progressionResetStorage=Object.fromEntries([preference('basic')]),r=>r[3].progressionStorageAfter=Object.fromEntries([preference('basic')])]){const rows=storage();mutate(rows);assert.throws(()=>validateNativeProgressionStorage(rows));}
});
test('consumed requests reject wrong source, stale plan, extra layer DTOs and hidden Original calls during Off',()=>{
 for(const off of [false,true]){const {report,takes,...options}=requests(off);validateNativeProgressionRequests(report,takes,validateAssistanceRequestCompletion,options);}
 for(const mutate of [r=>r.requests[0].request.plan.plan_digest='f'.repeat(64),r=>r.requests[0].response.checked.layers.reverse(),r=>r.requests[0].response.checked.other_assistance={},r=>r.requests.at(-1).request.inputs.push({midi:60,at_ms:125}),r=>r.requests[r.offRequestStart].request.selection.selected_part_ids.pop(),r=>r.requests[r.offRequestStart].path='/api/library/assistance/original',r=>r.requests[0].observation='awaiting-json']){const {report,takes,...options}=requests();mutate(report);assert.throws(()=>validateNativeProgressionRequests(report,takes,validateAssistanceRequestCompletion,options));}
});
test('phase registration, source receipts and Windows job retain v1 then add bounded progression and Off restart',()=>{
 assert.deepEqual(ASSISTANCE_PHASES,['assistance-seed','assistance-restart','assistance-progression','assistance-off-restart']);assert.deepEqual(Object.keys(PROGRESSION_NATIVE_FILES),ASSISTANCE_PHASES.slice(2));
 for(const path of ['crates/score-core/src/practice_progression.rs','crates/practice-server/src/practice_progression_api.rs','crates/desktop-shell/src/native_progression.rs','web/practice-progression.js','web/practice-progression-receipt.js','web/practice-progression-view.js','web/practice-progression-locales.js','scripts/native-progression-proof.mjs','tests/native-progression-evidence.test.js'])assert.ok(ASSISTANCE_SOURCE_FILES.includes(path),path);
 for(const path of ['crates/desktop-shell/src/acceptance.rs','scripts/windows-desktop-profile.ps1','scripts/windows-desktop-acceptance.ps1']){const source=readFileSync(new URL('../'+path,import.meta.url),'utf8');for(const phase of ASSISTANCE_PHASES)assert.ok(source.includes(phase),`${path}: ${phase}`);}
 for(const key of ['full_acceptance','release_ready','physical_audio','physical_midi'])assert.equal(ASSISTANCE_CLAIMS[key],false);
 const renderer=readFileSync(new URL('../scripts/native-assistance-renderer.js',import.meta.url),'utf8');new vm.Script(renderer);assert.doesNotMatch(renderer,/KeyboardEvent|new AudioContext|\.core\.process/);assert.ok(renderer.includes("native('assistance-key-c5',$('stage-title'))"));
});

function controls(){
 const report={phase:'assistance-progression',checkpoints:[],controls:[],trusted:[],requests:[]};let sequence=0;
 for(const [label,response]of [['progression-balanced-checked',f.basic.layers.balanced.response],['progression-change-checked',f.basic.layers.single.response],['progression-reset-checked',f.basic.layers.single.response],['progression-vsq-checked',f.vsq.layers.single.response],['progression-vsq-empty-checked',f.vsq.narrow_scope]]){const actionSequence=++sequence;report.checkpoints.push({label,actionSequence,progression:view(response),applyDisabled:true});report.controls.push({sequence,id:'song-mod-assistance-check',kind:'click'});report.requests.push({started:{actionSequence},observation:'consumed',response:clone(response)});}
 report.checkpoints.push({label:'progression-balanced-reopened',progression:view(f.basic.layers.balanced.response)});
 for(const [label,layer]of [['progression-balanced-draft','balanced'],['progression-change-draft','single']]){report.checkpoints.push({label,actionSequence:++sequence,applyDisabled:true,progression:view(null,{layer,draft:true})});report.controls.push({sequence,id:'song-mod-progression-layer',kind:layer==='single'?'select-first':'select-second'});report.trusted.push({sequence,id:'song-mod-progression-layer',type:'change',trusted:true,owned:true,value:layer});}
 report.trusted.push({id:'song-mod-assistance-mode',type:'change',trusted:true,owned:true,value:'progression'});report.checkpoints.push({label:'progression-off-draft',applyDisabled:true});const paused={running:false,completed:false,positionMs:300};report.progressionPaused={before:paused,after:clone(paused),storage:{recipe:'unchanged'},afterStorage:{recipe:'unchanged'}};
 report.offSourceStarts=3;report.progressionReset={historyHidden:true,exportDisabled:true,assessmentDisabled:false,passOptions:[''],clock:{running:false,positionMs:0},sourceStarts:3};report.progressionOff={...clone(report.progressionReset),summary:'Note assistance is off'};report.offAfterAssessment={clock:{running:false},sourceStarts:3};report.zeroHuman={startDisabled:true,clock:{running:false},sourceStarts:3};report.vsqBeforeChoice={startDisabled:true,modDisabled:true,sourceStarts:3};report.controls.push({id:'vsq-choose-base-notes'},{id:'song-mod-assistance-reset'},{id:'song-mod-assistance-reset'});return report;
}
test('native progression controls require current Check, owned stage changes, paused Cancel, explicit reset and zero-human gate',()=>{
 validateNativeProgressionControls(controls());validateNativeProgressionControls({phase:'assistance-off-restart',checkpoints:[{label:'progression-off-restored',status:'editing',progression:{mode:'original',visible:false}}]});
 for(const mutate of [r=>r.checkpoints[0].progression.rows.pop(),r=>r.requests[0].observation='awaiting-json',r=>r.requests[0].started.actionSequence++,r=>r.trusted[0].trusted=false,r=>r.trusted[1].owned=false,r=>r.progressionPaused.after.positionMs++,r=>r.progressionPaused.afterStorage={},r=>r.progressionReset.historyHidden=false,r=>r.progressionOff.sourceStarts++,r=>r.zeroHuman.startDisabled=false,r=>r.vsqBeforeChoice.modDisabled=false,r=>r.checkpoints.find(c=>c.label==='progression-change-checked').applyDisabled=false]){const r=controls();mutate(r);assert.throws(()=>validateNativeProgressionControls(r));}
});
