import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {runInNewContext} from 'node:vm';
import {deflateSync} from 'node:zlib';
import {storedZip} from './native-import-driver-fixtures.js';
import {digest} from './clean-song-package-fixtures.js';
import {cleanAcceptanceFixture,prepareCleanFixtures} from '../scripts/prepare-clean-song-fixtures.mjs';
import {verifyNativeCleanSongEvidence,CLEAN_PHASES,CLEAN_CHECKS,CLEAN_REPORT_BYTES} from '../scripts/verify-native-clean-song-evidence.mjs';
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
function crc32(b){let c=0xffffffff;for(const v of b){c^=v;for(let bit=0;bit<8;bit++)c=c>>>1^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function screenshot(){const chunk=(n,p)=>{const b=Buffer.alloc(p.length+12);b.writeUInt32BE(p.length);b.write(n,4);p.copy(b,8);b.writeUInt32BE(crc32(b.subarray(4,-4)),b.length-4);return b;},header=Buffer.alloc(13);header.writeUInt32BE(640);header.writeUInt32BE(360,4);header[8]=8;header[9]=2;const p=Buffer.alloc((640*3+1)*360);let state=17;for(let i=0;i<p.length;i++){state=(Math.imul(state,1664525)+1013904223)>>>0;p[i]=i%(640*3+1)===0?0:state>>>24;}return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(p)),chunk('IEND',Buffer.alloc(0))]);}
const PNG=screenshot();
function take(scoreId,target,human=false){const input={midi:60,velocity:90,at_ms:100};return{version:1,score_id:scoreId,practice_part:target,passes:[{id:1,capture_enabled:true,inputs:human?[input]:[],captures:human?[{event_id:1,event_wall_ms:1100,received_wall_ms:1101,input:{...input}}]:[],assessment:null}],input_evidence:{version:1,truncated:false,omitted_observations:0,events:human?[{event_id:1,kind:'note_on',source_id:'keyboard-r',source_generation:null,input_kind:'typing_keyboard',encoding:'key_down',midi:60,velocity:90,event_wall_ms:1100,received_wall_ms:1101,onset_capture:{pass_id:1,event_id:1}},{event_id:2,kind:'note_off',source_id:'keyboard-r',source_generation:null,input_kind:'typing_keyboard',encoding:'key_up',event_wall_ms:1110,received_wall_ms:1111,onset_capture:null},{event_id:3,kind:'boundary',source_id:null,reason:'pause',event_wall_ms:1120,received_wall_ms:1120,onset_capture:null}]:[]}};}
function transport(){const state={passId:'1',captured:'1',cue:'paused',phase:'paused',hidden:false,openDialogs:[],positionMs:900,durationMs:32000};return{version:1,stage:'complete',omitted:0,rowBytes:3000,trustedPlayClicks:2,trustedKeyDowns:1,trustedKeyUps:1,current:state,rows:[{kind:'ready',elapsedMs:0,state:{...state,positionMs:500,captured:'0'}},{kind:'event',elapsedMs:10,state:{...state},event:{type:'click',trusted:true,control:'play-button'}},{kind:'transport',elapsedMs:20,state:{...state,phase:'capturing',positionMs:600}},{kind:'event',elapsedMs:30,state:{...state},event:{type:'keydown',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}},{kind:'event',elapsedMs:40,state:{...state},event:{type:'keyup',trusted:true,code:'KeyR',surface:'stage-title',repeat:false}},{kind:'event',elapsedMs:50,state:{...state},event:{type:'click',trusted:true,control:'play-button'}}]};}
// Protocol fixtures exercise the verifier only. No Windows, browser, server or audio is launched.
async function evidence(t){
 const directory=await mkdtemp(join(tmpdir(),'wmh-clean-proof-'));t.after(()=>rm(directory,{recursive:true,force:true}));await mkdir(join(directory,'downloads'));await prepareCleanFixtures(join(directory,'fixtures'));const fixture=cleanAcceptanceFixture(),identity=digest(JSON.stringify(fixture.metadata)),key=`song-${identity}`,runtime=JSON.parse(await readFile(new URL('./fixtures/clean-song-v2-long-runtime.json',import.meta.url))),parts=fixture.score.performance.parts.map(p=>p.id),assets=fixture.metadata.media.map(({id,role,mime,bytes,sha256,offset_ms})=>({id,role,mime,bytes,sha256,handle:`asset-${digest(`${identity}\0${id}\0${sha256}`)}`,...(offset_ms===undefined?{}:{offset_ms})}));
 const entry={library_format_version:2,revision:1,key,content_sha256:identity,score_id:fixture.metadata.id,title:fixture.metadata.title,retained_source:null,clean_package:{version:2,content_sha256:identity,bytes:[...fixture.files.values()].reduce((sum,b)=>sum+b.length,0),media:assets,coverage:fixture.score.coverage,notation_available:true}};
 const pkg={key,content_sha256:identity,metadata_sha256:digest(fixture.files.get('metadata.json')),score_sha256:digest(fixture.files.get('score.json')),runtime_sha256:digest(JSON.stringify(stable(runtime))),tracks:3,parts,notes:30,events:14,source_events:74,duration_ms:32000,media:assets};
 const exported=storedZip([...[...fixture.files].map(([p,b])=>[`songs/${key}/${p}`,b]),['manifest.json',JSON.stringify({format:'worldmusichub-song-pack',version:2,songs:[{folder:`songs/${key}`} ]})]]);
 const definitions={'clean-seed':[['picker',fixture.filename],['click'],['click'],['select-last'],['click'],['click'],['click'],['click'],['click'],['key-r'],['click'],['picker','clean-seed-3.zip'],['click']], 'clean-restart':[['click'],['select-last'],['click'],['click'],['click'],['click']]};
 const native={version:1,scenario:'clean-song',ok:true,profile_reused:false,source_sha:'1'.repeat(40),source_tree:'2'.repeat(40),executable_sha256:'3'.repeat(64),executable_bytes:80000,directory:join(directory,'Scores'),phases:CLEAN_PHASES.map((phase,i)=>({phase,process_id:100+i,renderer_ok:true,normal_close:true,renderer_origin:'https://wmh.localhost',executable_tcp_listeners:0,launched_new_process:true,profile_fresh:true,profile_reused:false,actions:definitions[phase].length}))};
 const media=Object.fromEntries(fixture.metadata.media.map(a=>[a.role,{role:a.role,width:a.role==='cover'?96:a.role==='background'?160:320,height:a.role==='cover'?64:a.role==='background'?90:180,drawnWidth:100,drawnHeight:80,bytes:a.bytes,sha256:a.sha256,pixels_sha256:'4'.repeat(64),unique_pixel_values:128,visible:true,...(a.role==='pv'?{muted:true,paused:false,currentTime:.5,readyState:4}:{})}]));
 const files={'clean-seed':{machineTake:'clean-seed-1.json',humanTake:'clean-seed-2.json',package:'clean-seed-3.zip',afterReimportTake:'clean-seed-4.json'},'clean-restart':{machineTake:'clean-restart-1.json'}},reports={},rows=[];
 const save=async(path,value)=>writeFile(join(directory,path),JSON.stringify(value,null,2)+'\n');
 for(const phase of CLEAN_PHASES){const host=native.phases.find(p=>p.phase===phase),grades=Object.fromEntries(Array.from({length:11},(_,i)=>[`grade-${i}`,'—']));reports[phase]={version:1,phase,ok:true,origin:'https://wmh.localhost',profileMarkerAbsent:true,actions:host.actions,checks:[...CLEAN_CHECKS[phase]],errors:[],openedScoreDatabases:[],package:structuredClone(pkg),directory:native.directory,inventory:[entry],media:structuredClone(media),following:{status:'ready',ordinaryNavigationRequests:0},machineBefore:{captured:'0',grades},machinePlaying:{captured:'0',grades,positionMs:600,audio:{sourceStarts:3,oscillatorStarts:3}},audioStopped:{sourceStarts:3,activeSources:0,pendingSources:0},videoFrames:{count:5,last:{presentedFrames:5,width:320,height:180,mediaTime:.5}},controls:{initialTarget:parts[0],target:parts[1],other:parts[0],humanDisabled:true,humanMachineEnabled:false,otherRestored:true},trusted:[{type:'change',trusted:true,id:'clean-song-target',value:parts[1]},{type:'change',trusted:true,part:parts[0],checked:false},{type:'change',trusted:true,part:parts[0],checked:true}],chooserObservations:definitions[phase].flatMap(([kind],i)=>kind==='picker'?[{sequence:i+1,kind,started_wall_ms:2000+i*100,finished_wall_ms:2050+i*100,completed:true,blurs:[]}]:[]),files:files[phase],downloads:Object.values(files[phase]).map(file=>({file,complete:true,success:true})),screenshots:phase==='clean-seed'?{cover:3,parts:5,playing:7,preflight:2}:{cover:1,parts:3,playing:5},importReports:[]};
  for(const [i,[kind,file]]of definitions[phase].entries()){await save(`action-${phase}-${i+1}.json`,{version:1,sequence:i+1,kind,x:10,y:20,width:1024,height:768,...(file?{file}:{})});await save(`result-${phase}-${i+1}.json`,{ok:true,client_click:{app_hwnd:1,foreground:1,actual:[10,20],requested:[10,20],viewport:[1024,768],hit_hwnd:1},...(kind==='picker'?{owned_dialog:{class:'#32770',hwnd:2,app_hwnd:1,root_owner_hwnd:1,process_id:host.process_id,app_process_id:host.process_id},picker_completion:{dialog_dismissed:true,app_enabled:true,owned_popup_visible:false}}:{})});}
  for(const n of Object.values(reports[phase].screenshots))await writeFile(join(directory,`native-action-${phase}-${n}.png`),PNG);await writeFile(join(directory,`native-${phase}.png`),PNG);await save(`downloads/${files[phase].machineTake}`,take(fixture.metadata.id,parts[1]));
 }
 const seed=reports['clean-seed'];seed.reimportAfterSequence=11;seed.transportAdmission=transport();const human=take(fixture.metadata.id,parts[1],true);await save(`downloads/${seed.files.humanTake}`,human);await save(`downloads/${seed.files.afterReimportTake}`,human);await writeFile(join(directory,'downloads',seed.files.package),exported);
 for(const [i,source]of [fixture.bytes,fixture.bytes,exported,exported].entries()){const mode=i%2?'commit':'preview';seed.importReports.push({status:200,filename:i<2?fixture.filename:seed.files.package,mode,body:{mode,source:{sha256:digest(source),bytes:source.length,retained:mode==='commit'},items:[{status:['ready','saved','duplicate','duplicate'][i],playable:true}]}});}
 const archive=async(path,b)=>{await mkdir(join(directory,'Scores',path.slice(0,path.lastIndexOf('/'))),{recursive:true});await writeFile(join(directory,'Scores',path),b);rows.push({path,bytes:b.length,sha256:digest(b)});};
 for(const area of ['clean-songs','clean-backups']){await archive(`${area}/${key}/entry.json`,Buffer.from(JSON.stringify(entry)));for(const [p,b]of fixture.files)await archive(`${area}/${key}/package/${p}`,b);}
 for(const area of ['imports','import-backups'])for(const source of [fixture.bytes,exported])await archive(`${area}/pack-${digest(source)}/source.bin`,source);
 for(const phase of CLEAN_PHASES){await save(`snapshot-${phase}.json`,{version:1,files:rows});await save(`renderer-${phase}.json`,reports[phase]);}await save('native-clean-song.json',native);return{directory,fixture,entry,key,native,reports,save,rows};
}

test('clean native verifier rederives the complete authored package and new-process evidence',async t=>{const f=await evidence(t),proof=await verifyNativeCleanSongEvidence(f.directory);assert.equal(proof.ok,true);assert.equal(proof.notes,30);assert.equal(proof.events,14);assert.equal(proof.source_events,74);assert.equal(proof.decoded_media,3);assert.equal(proof.claims.actual_audibility,false);assert.equal(proof.claims.latency_or_hardware,false);});
test('clean native verifier rejects changed native process, media, inputs and inventory',async t=>{const f=await evidence(t),original=f.reports['clean-restart'];for(const change of [r=>r.package.events=74,r=>r.package.source_events=73,r=>r.media.pv.sha256='0'.repeat(64),r=>r.media.cover.width=0,r=>r.videoFrames.count=0,r=>delete r.following,r=>r.following.status='unavailable',r=>r.following.ordinaryNavigationRequests=1,r=>r.machinePlaying.captured='1',r=>r.machinePlaying.grades={grade:100},r=>r.audioStopped.pendingSources=1,r=>r.trusted[0].trusted=false,r=>r.controls.humanMachineEnabled=true,r=>r.inventory=[]]){const value=structuredClone(original);change(value);await f.save('renderer-clean-restart.json',value);await assert.rejects(verifyNativeCleanSongEvidence(f.directory));}await f.save('renderer-clean-restart.json',original);const host=structuredClone(f.native);host.phases[1].process_id=host.phases[0].process_id;await f.save('native-clean-song.json',host);await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/new process/);});
test('clean native verifier rejects exact asset loss, backup tampering and absent native chooser ownership',async t=>{const f=await evidence(t),path=`Scores/clean-backups/${f.key}/package/media/pv.webm`,original=await readFile(join(f.directory,path));await writeFile(join(f.directory,path),original.subarray(0,-1));await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/exact file changed/);await writeFile(join(f.directory,path),original);await f.save('result-clean-seed-1.json',{ok:true,client_click:{app_hwnd:1,foreground:1,actual:[10,20],requested:[10,20],viewport:[1024,768],hit_hwnd:1}});await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/picker ownership/);});
test('clean native verifier rejects machine notes masquerading as recorded human input',async t=>{const f=await evidence(t),path=`downloads/${f.reports['clean-seed'].files.machineTake}`;await f.save(path,take(f.fixture.metadata.id,f.reports['clean-seed'].controls.target,true));await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/Machine sources entered/);});
test('clean report producer, Rust admission, verifier and boundary tests share 1 MiB budget',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),post=runInNewContext(`${prefix}\npostCleanAcceptanceReport`,{TextEncoder});assert.equal(CLEAN_REPORT_BYTES,1024*1024);const rust=await readFile(new URL('../crates/desktop-shell/src/acceptance.rs',import.meta.url),'utf8');assert.match(rust,/MAX_CLEAN_REPORT_BYTES: usize = 1024 \* 1024/);assert.match(rust,/MAX_CLEAN_REPORT_BYTES \+ 1/);let sent=[];const waits={json:async(_,path,options)=>{sent.push(JSON.parse(options.body));return{};}};const large={version:1,phase:'clean-seed',ok:true,padding:'x'.repeat(77092)};assert.equal((await post({report:large,fetcher:null,waits})).delivered,true);assert.deepEqual(sent[0],large);sent=[];assert.equal((await post({report:{...large,padding:'x'.repeat(CLEAN_REPORT_BYTES)},fetcher:null,waits})).delivered,false);assert.equal(sent.length,1);assert.equal(sent[0].ok,false);assert.equal(sent[0].report_failure.limit_bytes,CLEAN_REPORT_BYTES);});
test('clean chooser observation waits until later native blur handlers finish',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),create=runInNewContext(`${prefix}\ncreateCleanChooserObserver`),listeners={},pending=[];let time=1;const target={addEventListener:(name,fn)=>listeners[name]=fn,removeEventListener:()=>{}};const observer=create({target,now:()=>time,defer:fn=>pending.push(fn)});observer.begin(1,'picker');time=2;listeners.blur({target,isTrusted:true});time=3;let ended=false;const task=observer.end(1,true).then(()=>ended=true);await Promise.resolve();assert.equal(ended,false);time=4;pending[0]();await task;assert.equal(observer.records[0].blurs[0].finished_wall_ms,4);assert.equal(observer.records[0].finished_wall_ms,4);});
test('actual Rust fixture has fourteen state commands and thirty paired notes covering seventy-four source events',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),validate=runInNewContext(`${prefix}\nvalidateCleanFixtureInventory`);const score=JSON.parse(await readFile(new URL('./fixtures/clean-song-v2-long/score.json',import.meta.url))),runtime=JSON.parse(await readFile(new URL('./fixtures/clean-song-v2-long-runtime.json',import.meta.url)));assert.deepEqual(JSON.parse(JSON.stringify(validate(score,runtime))),{tracks:3,parts:score.performance.parts.map(p=>p.id),notes:30,events:14,source_events:74,duration_ms:32000});for(const mutate of [(s,r)=>s.performance.notes.pop(),(s,r)=>s.performance.events.pop(),(s,r)=>s.coverage.source_events--,(s,r)=>s.coverage.represented_events--,(s,r)=>r.events.pop(),(s,r)=>r.notes.pop()]){const s=structuredClone(score),r=structuredClone(runtime);mutate(s,r);assert.throws(()=>validate(s,r),/inventory changed/);}});
test('native PV observation is preceded by real Reset and clock readiness',async()=>{const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8');const reset=source.indexOf("await native('click',$('reset-button'))"),ready=source.indexOf("Number($('progress').value)===0&&!$('play-button').disabled",reset),callback=source.indexOf('playback.startFrames()',ready),play=source.indexOf("await native('click',$('play-button'))",callback);assert.ok(reset>0&&ready>reset&&callback>ready&&play>callback);assert.ok(!source.includes("$('progress').value=0"));});

test('clean reimport preserves distinct boundary and receipt clocks within its observed chooser interval',async t=>{
 const f=await evidence(t),seed=f.reports['clean-seed'],row=seed.chooserObservations.find(item=>item.sequence>seed.reimportAfterSequence),time=row.started_wall_ms+10;
 row.blurs=[{trusted:true,started_wall_ms:time-1,finished_wall_ms:time+1}];await f.save('renderer-clean-seed.json',seed);
 const file=`downloads/${seed.files.afterReimportTake}`,value=JSON.parse(await readFile(join(f.directory,file),'utf8'));
 value.input_evidence.events.push({event_id:4,kind:'boundary',source_id:null,source_generation:null,input_kind:null,channel:null,midi:null,velocity:null,encoding:null,reason:'blur',event_wall_ms:time,received_wall_ms:time+.1,timestamp_basis:'application_clock',raw_timestamp_ms:null,boundary_wall_ms:time,onset_capture:null});
 await f.save(file,value);assert.equal((await verifyNativeCleanSongEvidence(f.directory)).ok,true);
 for(const edit of [event=>event.received_wall_ms=time-1,event=>event.received_wall_ms=time+2,event=>event.received_wall_ms=String(time),event=>event.boundary_wall_ms=event.received_wall_ms]){const changed=structuredClone(value);edit(changed.input_evidence.events.at(-1));await f.save(file,changed);await assert.rejects(verifyNativeCleanSongEvidence(f.directory),/boundary|evidence/i);}
});

async function blobObservation(t,limits={}){
 const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {'));
 const create=runInNewContext(`${prefix}\ncreateCleanMediaBlobObserver`,{Blob}),calls=[],revokes=[],live=[];
 const urls={createObjectURL(...args){calls.push({receiver:this,args});const url=Reflect.apply(URL.createObjectURL,this,args);live.push(url);return url;},revokeObjectURL(...args){revokes.push({receiver:this,args});return Reflect.apply(URL.revokeObjectURL,this,args);}},originals={...urls};
 const observer=create({urls,...limits});t.after(()=>{observer.restore();for(const url of live)URL.revokeObjectURL(url);});return{source,create,observer,urls,originals,calls,revokes};
}
test('clean media observes exact real Blob bytes without creating or substituting URLs',async t=>{
 const f=await blobObservation(t),blob=new Blob(['actual native asset'],{type:'image/png'}),extra={untouched:true};
 blob.arrayBuffer=()=>{throw Error('Instance byte substitution must not be read');};
 const source=f.urls.createObjectURL(blob,extra),node={currentSrc:source};
 assert.equal(f.calls.length,1);assert.equal(f.calls[0].receiver,f.urls);assert.deepEqual(f.calls[0].args,[blob,extra]);assert.match(source,/^blob:/);
 assert.equal(Buffer.from(await f.observer.readBytes(node,source)).toString(),'actual native asset');assert.equal(f.calls.length,1);
 assert.equal(f.urls.revokeObjectURL(source,extra),undefined);assert.equal(f.revokes.length,1);assert.equal(f.revokes[0].receiver,f.urls);assert.deepEqual(f.revokes[0].args,[source,extra]);
 f.observer.restore();assert.equal(f.urls.createObjectURL,f.originals.createObjectURL);assert.equal(f.urls.revokeObjectURL,f.originals.revokeObjectURL);
 await assert.rejects(f.observer.readBytes(node,source),/stopped/);
});
test('clean media rejects missing, revoked and mismatched currentSrc associations',async t=>{
 const f=await blobObservation(t),first=f.urls.createObjectURL(new Blob(['first'])),second=f.urls.createObjectURL(new Blob(['other'])),node={currentSrc:first};
 await assert.rejects(f.observer.readBytes(node,'blob:missing'),/missing|current/);
 await assert.rejects(f.observer.readBytes({currentSrc:'https://wmh.localhost/asset'},'https://wmh.localhost/asset'),/missing|current/);
 await assert.rejects(f.observer.readBytes(node,second),/current/);
 node.currentSrc=second;assert.equal(Buffer.from(await f.observer.readBytes(node,second)).toString(),'other');
 assert.notEqual(digest(Buffer.from(await f.observer.readBytes(node,second))),digest('first'));
 f.urls.revokeObjectURL(second);await assert.rejects(f.observer.readBytes(node,second),/revoked/);
 assert.equal(f.calls.length,2);assert.equal(f.revokes.length,1);
});
test('clean media rejects source changes or revocation during the actual Blob read',async t=>{
 const f=await blobObservation(t),blob=new Blob(['asset']),source=f.urls.createObjectURL(blob),other=f.urls.createObjectURL(blob),node={currentSrc:source};
 const changed=f.observer.readBytes(node,source);node.currentSrc=other;await assert.rejects(changed,/current/);
 const revoked=f.observer.readBytes(node,other);f.urls.revokeObjectURL(other);await assert.rejects(revoked,/revoked/);
});
test('clean media fails closed for native revocation with a coercible non-string argument',async t=>{
 const f=await blobObservation(t),source=f.urls.createObjectURL(new Blob(['asset']));let conversions=0;
 const argument={toString(){conversions++;return source;}};f.urls.revokeObjectURL(argument);assert.equal(conversions,1);assert.equal(f.revokes[0].args[0],argument);
 await assert.rejects(f.observer.readBytes({currentSrc:source},source),/revocation identity/);
});
test('clean Blob bounds fail evidence while preserving native creation and revocation',async t=>{
 for(const [limits,contents,pattern]of [[{maxBlobBytes:4},['large'],/byte observation bound/],[{maxBlobBytes:4},[''],/byte observation bound/],[{maxRetainedBytes:5},['abc','def'],/retained Blob observation bound/],[{maxUrls:1},['one','two'],/URL observation bound/]]){
  const f=await blobObservation(t,limits),sources=contents.map(value=>f.urls.createObjectURL(new Blob([value])));
  assert.equal(f.calls.length,contents.length);assert.ok(sources.every(value=>value.startsWith('blob:')));assert.throws(()=>f.observer.assertHealthy(),pattern);
  await assert.rejects(f.observer.readBytes({currentSrc:sources.at(-1)},sources.at(-1)),pattern);
  for(const source of sources)f.urls.revokeObjectURL(source);assert.equal(f.revokes.length,sources.length);
  const later=f.urls.createObjectURL(new Blob(['still native']));assert.match(later,/^blob:/);assert.equal(f.calls.length,contents.length+1);
 }
});
test('clean Blob observation releases retained bytes but keeps a lifetime creation bound',async t=>{
 const f=await blobObservation(t,{maxBlobBytes:3,maxRetainedBytes:3,maxUrls:2}),first=f.urls.createObjectURL(new Blob(['one']));
 f.urls.revokeObjectURL(first);const second=f.urls.createObjectURL(new Blob(['two']));assert.equal(Buffer.from(await f.observer.readBytes({currentSrc:second},second)).toString(),'two');
 f.urls.revokeObjectURL(second);f.urls.createObjectURL(new Blob(['new']));assert.throws(()=>f.observer.assertHealthy(),/URL observation bound/);
});
test('clean Blob observation forwards native errors and rejects fake Blob shapes',async t=>{
 const f=await blobObservation(t);assert.throws(()=>f.urls.createObjectURL({size:3,arrayBuffer:async()=>new ArrayBuffer(3)}),/Blob/);f.observer.assertHealthy();
 const fake={size:3,arrayBuffer:async()=>new ArrayBuffer(3)},urls={createObjectURL:()=> 'blob:fake',revokeObjectURL:()=>{}},observer=f.create({urls});
 assert.equal(urls.createObjectURL(fake),'blob:fake');assert.throws(()=>observer.assertHealthy());await assert.rejects(observer.readBytes({currentSrc:'blob:fake'},'blob:fake'));observer.restore();
});
test('clean media keeps decoded canvas pixels and video frame checks under the production CSP',async()=>{
 const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),rust=await readFile(new URL('../crates/desktop-shell/src/lib.rs',import.meta.url),'utf8');
 assert.match(source,/const source=node.currentSrc,canvas=document.createElement\('canvas'\)/);assert.match(source,/context.drawImage\(node,0,0\)/);assert.match(source,/getImageData\(0,0,width,height\)/);assert.match(source,/new Set\(pixels\).size>16/);assert.match(source,/await mediaBlobs.readBytes\(node,source\)/);assert.match(source,/state.videoFrames.count>=2&&state.videoFrames.last\?\.mediaTime>0/);
 assert.doesNotMatch(source,/fetcher\(node.currentSrc\)|new Blob\(/);assert.match(rust,/img-src 'self' blob: data:; connect-src 'self'; media-src 'self' blob:/);
});

async function playbackHelpers(){
 const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {'));
 return runInNewContext(`${prefix}\n({createCleanAssetRequestObserver,createCleanPlaybackObserver,cleanPlaybackAdmission,awaitCleanPlaybackAdmission,retainCleanPlaybackEvidence})`,{TextEncoder});
}
function playbackVideo(play=()=>Promise.resolve()){
 const listeners=new Map(),callbacks=new Map();let next=0;
 const video=Object.assign(Object.create({play}),{src:'blob:owned-src',currentSrc:'blob:owned-src',readyState:1,networkState:1,duration:2,currentTime:0,paused:true,ended:false,muted:true,hidden:true,videoWidth:0,videoHeight:0,error:null,
  getAttribute:name=>name==='src'?video.src:null,addEventListener(name,listener){if(!listeners.has(name))listeners.set(name,new Set());listeners.get(name).add(listener);},removeEventListener(name,listener){listeners.get(name)?.delete(listener);},
  requestVideoFrameCallback(callback){callbacks.set(++next,callback);return next;},cancelVideoFrameCallback(id){callbacks.delete(id);}});
 return{video,listeners,callbacks,emit(type,target=video){for(const listener of listeners.get(type)||[])listener({type,target,isTrusted:true});},frame(metadata){const entry=callbacks.entries().next().value;if(entry){callbacks.delete(entry[0]);entry[1](0,metadata);}}};
}
const plain=value=>JSON.parse(JSON.stringify(value));
function playbackObservation(create,fixture,overrides={}){
 return create({video:fixture.video,readAudio:()=>({sourceStarts:3,oscillatorStarts:3,activeSources:2,pendingSources:1}),readPosition:()=>700,readRenderer:()=> 'playing',readMediaStatus:()=>'',style:()=>({display:'block'}),now:()=>100,...overrides});
}
test('clean playback separates audio admission from absent PV within the original deadline',async()=>{
 const {awaitCleanPlaybackAdmission,cleanPlaybackAdmission}=await playbackHelpers(),state={audio:{sourceStarts:3},positionMs:700,rendererState:'playing',videoFrames:{count:0,last:null}},observer={state:()=>structuredClone(state)},evidence={},calls=[];let time=100;
 const timeout=Error('PV did not present');const until=async(condition,label,milliseconds)=>{calls.push({label,milliseconds});if(!condition())throw timeout;time+=450;};
 await assert.rejects(awaitCleanPlaybackAdmission({observer,until,evidence,now:()=>time}),error=>error===timeout);
 assert.equal(evidence.stage,'video-presentation');assert.equal(evidence.audioAdmission.audio.sourceStarts,3);assert.equal(evidence.videoPresentation,undefined);assert.deepEqual(plain(cleanPlaybackAdmission(state)),{audio:true,video:false});
 assert.equal(calls.length,2);assert.match(calls[0].label,/audio scheduling.*clock/);assert.match(calls[1].label,/decoded PV/);assert.equal(calls[0].milliseconds,25000);assert.equal(calls[1].milliseconds,24550);
 state.audio.sourceStarts=0;const noAudio={};calls.length=0;await assert.rejects(awaitCleanPlaybackAdmission({observer,until,evidence:noAudio,now:()=>time}),error=>error===timeout);assert.equal(noAudio.stage,'audio-admission');assert.equal(noAudio.audioAdmission,undefined);assert.equal(calls.length,1);
});
test('clean playback still requires concurrent scheduling, clock, renderer and presented frames',async()=>{
 const {awaitCleanPlaybackAdmission,cleanPlaybackAdmission}=await playbackHelpers(),ready={audio:{sourceStarts:3},positionMs:700,rendererState:'playing',videoFrames:{count:2,last:{mediaTime:.3}}};
 assert.deepEqual(plain(cleanPlaybackAdmission(ready)),{audio:true,video:true});
 for(const change of [state=>state.audio.sourceStarts=0,state=>state.positionMs=300,state=>state.rendererState='paused']){const state=structuredClone(ready);change(state);assert.equal(cleanPlaybackAdmission(state).audio,false);}
 for(const change of [state=>state.videoFrames.count=1,state=>state.videoFrames.last.mediaTime=0,state=>state.videoFrames.last=null]){const state=structuredClone(ready);change(state);assert.ok(!cleanPlaybackAdmission(state).video);}
 let state=structuredClone(ready),calls=0;const evidence={};await assert.rejects(awaitCleanPlaybackAdmission({observer:{state:()=>structuredClone(state)},evidence,now:()=>0,until:async condition=>{assert.equal(condition(),++calls===1);if(calls===1)state.rendererState='paused';else throw Error('audio no longer admitted');}}),/no longer admitted/);
 assert.equal(evidence.stage,'video-presentation');assert.equal(evidence.audioAdmission.rendererState,'playing');assert.equal(evidence.videoPresentation,undefined);
 state=structuredClone(ready);const complete={};await awaitCleanPlaybackAdmission({observer:{state:()=>structuredClone(state)},evidence:complete,now:()=>0,until:async condition=>assert.equal(condition(),true)});assert.deepEqual(plain(complete.videoPresentation),ready);
});
test('clean video play observation preserves receiver, arguments, exact promise and exception',async()=>{
 const {createCleanPlaybackObserver}=await playbackHelpers(),calls=[],resolved=Promise.resolve('native-result');let result=resolved,thrown=null;
 const original=function(...args){calls.push({receiver:this,args});if(thrown)throw thrown;return result;},fixture=playbackVideo(original),observer=playbackObservation(createCleanPlaybackObserver,fixture),token={unchanged:true};
 assert.equal(fixture.video.play(token,7),resolved);assert.equal(await resolved,'native-result');assert.equal(calls[0].receiver,fixture.video);assert.deepEqual(calls[0].args,[token,7]);assert.equal(observer.snapshot().trace.playResolved,1);
 const foreign={};assert.equal(Reflect.apply(fixture.video.play,foreign,[token]),resolved);assert.equal(calls[1].receiver,foreign);assert.deepEqual(calls[1].args,[token]);assert.equal(observer.snapshot().trace.playAttempts,1);
 const rejection=Object.assign(Error('decoder rejected'.repeat(100)),{name:'NotSupportedError'});let reject;result=new Promise((_,fail)=>reject=fail);assert.equal(fixture.video.play(token),result);reject(rejection);await assert.rejects(result,error=>error===rejection);
 const trace=observer.snapshot().trace,row=trace.rows.find(row=>row.kind==='play-rejected');assert.equal(trace.playRejected,1);assert.equal(row.error.name,'NotSupportedError');assert.equal(row.error.message.length,512);
 thrown=Error('native synchronous failure');assert.throws(()=>fixture.video.play(token),error=>error===thrown);assert.equal(calls.at(-1).receiver,fixture.video);assert.deepEqual(calls.at(-1).args,[token]);assert.equal(observer.snapshot().trace.playThrew,1);
 thrown=null;result=undefined;assert.equal(fixture.video.play(token),undefined);assert.equal(observer.snapshot().trace.rows.at(-1).kind,'play-returned-without-native-promise');
 observer.restore();assert.equal(fixture.video.play,original);assert.equal(Object.hasOwn(fixture.video,'play'),false);assert.ok([...fixture.listeners.values()].every(set=>set.size===0));
});
test('clean media readiness and frame observations are capped, detached and passive',async()=>{
 const {createCleanPlaybackObserver}=await playbackHelpers(),fixture=playbackVideo(),handler=()=>{},observer=playbackObservation(createCleanPlaybackObserver,fixture,{maxRows:3,maxBytes:2048});fixture.video.onloadeddata=handler;
 fixture.emit('loadedmetadata',{});assert.equal(observer.snapshot().trace.rows.length,1);
 fixture.video.readyState=2;fixture.video.videoWidth=320;fixture.video.videoHeight=180;fixture.emit('loadeddata');fixture.video.hidden=false;
 observer.startFrames();assert.throws(()=>observer.startFrames(),/already started/);for(let i=1;i<=20;i++)fixture.frame({mediaTime:i/30,presentedFrames:i,width:320,height:180});
 for(let i=0;i<100;i++)fixture.emit('waiting');const snapshot=observer.snapshot();assert.equal(snapshot.current.videoFrames.count,16);assert.equal(snapshot.current.videoFrames.last.presentedFrames,16);assert.equal(fixture.callbacks.size,0);
 assert.equal(snapshot.trace.rows.length,3);assert.ok(snapshot.trace.omitted>=99);assert.ok(snapshot.trace.rowBytes<=2048);assert.ok(Buffer.byteLength(JSON.stringify(snapshot.trace.rows))<=2048);assert.equal(snapshot.trace.rows.at(-1).event,'waiting');assert.equal(snapshot.trace.playAttempts,0);assert.equal(snapshot.trace.mediaEvents.loadeddata.count,1);assert.equal(snapshot.trace.mediaEvents.waiting.count,100);assert.equal(snapshot.trace.mediaEvents.loadedmetadata,undefined);assert.equal(fixture.video.onloadeddata,handler);assert.equal(fixture.video.paused,true);assert.equal(fixture.video.currentTime,0);
 fixture.video.error={code:3,message:'decode failed'};fixture.video.duration=NaN;fixture.video.currentSrc='';fixture.emit('error');const failed=observer.snapshot().current;assert.equal(failed.video.currentSrcPresent,false);assert.equal(failed.video.srcIsBlob,true);assert.equal(failed.video.duration,null);assert.deepEqual(plain(failed.video.error),{code:3,message:'decode failed'});assert.equal(snapshot.current.video.error,null);
 observer.restore();fixture.emit('playing');assert.equal(observer.snapshot().trace.rows.at(-1).event,'error');
});
test('clean video restores its exact own play descriptor and stops pending outcome observation',async()=>{
 const {createCleanPlaybackObserver}=await playbackHelpers();let resolve;const result=new Promise(done=>resolve=done),original=()=>result,fixture=playbackVideo();Object.defineProperty(fixture.video,'play',{value:original,writable:true,enumerable:false,configurable:true});const descriptor=Object.getOwnPropertyDescriptor(fixture.video,'play'),observer=playbackObservation(createCleanPlaybackObserver,fixture);
 const savedWrapper=fixture.video.play;assert.equal(fixture.video.play(),result);observer.startFrames();assert.equal(fixture.callbacks.size,1);observer.restore();const before=observer.snapshot();resolve('finished');assert.equal(await result,'finished');assert.equal(observer.snapshot().trace.playResolved,0);assert.equal(observer.snapshot().trace.rows.length,before.trace.rows.length);assert.equal(fixture.callbacks.size,0);assert.deepEqual(Object.getOwnPropertyDescriptor(fixture.video,'play'),descriptor);
 assert.equal(Reflect.apply(savedWrapper,fixture.video,[]),result);assert.equal(observer.snapshot().trace.playAttempts,1);
});
test('clean evidence retains failure and success state before either probe is restored',async()=>{
 const {createCleanPlaybackObserver,retainCleanPlaybackEvidence}=await playbackHelpers();
 for(const fail of [false,true]){
  const fixture=playbackVideo(),audio={sourceStarts:7,oscillatorStarts:7,activeSources:2,pendingSources:1},order=[],observer=playbackObservation(createCleanPlaybackObserver,fixture,{readAudio:()=>audio,readMediaStatus:()=> 'PV unavailable'}),snapshot=observer.snapshot,restore=observer.restore,report={},failure=Error('Timed out: actual clean decoded PV frame presentation');
  observer.snapshot=()=>{order.push('snapshot');return snapshot();};observer.restore=()=>{order.push('video-restore');restore();fixture.video.currentSrc='';};
  const task=retainCleanPlaybackEvidence({report,observer,restoreAudio:()=>{order.push('audio-restore');audio.sourceStarts=0;},run:async evidence=>{evidence.stage='video-presentation';fixture.video.error={code:3,message:'decoder failed'};fixture.emit('error');if(fail)throw failure;return'completed';}});
  if(fail)await assert.rejects(task,error=>error===failure);else assert.equal(await task,'completed');
  assert.deepEqual(order,['snapshot','video-restore','audio-restore']);const evidence=report.playbackEvidence;assert.equal(evidence.status,fail?'failed':'passed');assert.equal(evidence.stage,'video-presentation');assert.equal(evidence.final.current.audio.sourceStarts,7);assert.equal(evidence.final.current.positionMs,700);assert.equal(evidence.final.current.rendererState,'playing');assert.equal(evidence.final.current.mediaStatus,'PV unavailable');assert.equal(evidence.final.current.video.currentSrcPresent,true);assert.equal(evidence.final.current.video.readyState,1);assert.equal(evidence.final.current.video.networkState,1);assert.equal(evidence.final.current.video.paused,true);assert.equal(evidence.final.current.video.ended,false);assert.equal(evidence.final.current.video.hidden,true);assert.equal(evidence.final.current.video.display,'block');assert.equal(evidence.final.current.videoFrames.count,0);assert.equal(evidence.final.current.videoFrames.last,null);assert.equal(evidence.final.current.video.error.code,3);assert.equal(evidence.final.trace.rows.at(-1).event,'error');
 }
 const original=Error('original timeout'),report={};await assert.rejects(retainCleanPlaybackEvidence({report,observer:{snapshot(){throw Error('snapshot unavailable');},restore(){throw Error('restore failed');}},restoreAudio(){throw Error('audio cleanup failed');},run:async()=>{throw original;}}),error=>error===original);assert.equal(report.playbackEvidence.status,'failed');assert.equal(report.playbackEvidence.observationError,'Error: snapshot unavailable');
});
test('clean asset observation preserves the fetch promise and reads only cloned failure metadata',async()=>{
 const {createCleanAssetRequestObserver}=await playbackHelpers(),observer=createCleanAssetRequestObserver({now:()=>100,maxRows:3}),path='/api/library/asset',options={body:JSON.stringify({key:'song-fixture',handle:'asset-fixture'})};let clones=0,reads=0;
 const success={status:200,ok:true,clone(){throw Error('Successful bytes must not be cloned or read');}},ok=Promise.resolve(success);assert.equal(observer.observe(path,options,ok),ok);assert.equal(await ok,success);
 const failure={status:503,ok:false,clone(){clones++;return{async json(){reads++;return{code:'library_busy',error:'Another large operation is active',bytes:'must not retain'};}};}},failed=Promise.resolve(failure);assert.equal(observer.observe(path,options,failed),failed);assert.equal(await failed,failure);await new Promise(setImmediate);
 const snapshot=observer.snapshot();assert.equal(clones,1);assert.equal(reads,1);assert.equal(snapshot.rows[0].outcome,'response-ok');assert.equal(snapshot.rows[0].errorRead,null);assert.equal(snapshot.rows[1].handle,'asset-fixture');assert.equal(snapshot.rows[1].status,503);assert.equal(snapshot.rows[1].errorCode,'library_busy');assert.equal(snapshot.rows[1].errorRead,'parsed');assert.equal(snapshot.rows[1].error,'Another large operation is active');assert.ok(!JSON.stringify(snapshot).includes('must not retain'));
 let reject;const rejected=new Promise((_,fail)=>reject=fail),reason=Object.assign(Error('request aborted'),{name:'AbortError'});assert.equal(observer.observe(path,options,rejected),rejected);reject(reason);await assert.rejects(rejected,error=>error===reason);assert.equal(observer.snapshot().rows[2].outcome,'fetch-rejected');assert.equal(observer.snapshot().rows[2].errorCode,'AbortError');
 const other=Promise.resolve(success);observer.observe('/api/library/load',options,other);assert.equal(observer.snapshot().requests,3);
 const unreadable=Promise.resolve({status:503,ok:false,clone:()=>({json:async()=>{throw Error('bad error JSON');}})});observer.observe(path,options,unreadable);await unreadable;await new Promise(setImmediate);const capped=observer.snapshot();assert.equal(capped.rows.length,3);assert.equal(capped.omitted,1);assert.equal(capped.rows.at(-1).errorRead,'unreadable');assert.equal(snapshot.rows.length,2);
 observer.stop();observer.observe(path,options,ok);assert.equal(observer.snapshot().requests,4);
});
test('clean navigation observation filters the selected score and requires actual readiness',async()=>{
 const source=await readFile(new URL('../crates/desktop-shell/clean-song-acceptance.js',import.meta.url),'utf8'),prefix=source.slice(0,source.indexOf('(() => {')),create=runInNewContext(`${prefix}\ncreateCleanNavigationObserver`),observer=create(),path='/api/notation-navigation',options=id=>({body:JSON.stringify({id})});
 observer.observe(path,options('bundled'));assert.throws(()=>observer.ready('ready'));observer.select('clean');observer.observe(path,options('bundled'));observer.observe('/api/compile',options('clean'));
 assert.throws(()=>observer.ready('loading'),/not ready/);assert.deepEqual(JSON.parse(JSON.stringify(observer.ready('ready'))),{status:'ready',ordinaryNavigationRequests:0});
 observer.observe(path,options('clean'));assert.throws(()=>observer.ready('ready'),/ordinary notation navigation/);
 for(const body of [null,'{','x'.repeat(1024*1024+1)]){const invalid=create();invalid.select('clean');invalid.observe(path,{body});assert.throws(()=>invalid.ready('ready'));}
});
