import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
import {completePracticeFixture} from '../scripts/prepare-complete-practice-fixtures.mjs';
import {vsqAcceptanceFixture} from '../scripts/prepare-vsq-song-fixtures.mjs';
import {COMPLETE_SCREENSHOTS,completePracticeWindowIds,validateCompleteGeometry} from '../scripts/verify-complete-practice-evidence.mjs';
import {NATIVE_PART_ACTIVITY_STATES,validateNativePartActivityGeometry,validateCompletePracticeStripEvidence} from '../scripts/verify-native-part-activity.mjs';
const f=completePracticeFixture(),v=vsqAcceptanceFixture(),renderer=()=>readFile(new URL('../crates/desktop-shell/complete-practice-acceptance.js',import.meta.url),'utf8');
// Synthetic mutation fixtures only. They establish verifier behavior, not GUI,
// source import, native input, worklet execution or real speaker output.
const box=(x,y,width,height,visible=true)=>({hidden:!visible,visible,display:visible?'block':'none',visibility:'visible',position:'static',rect:visible?{x,y,width,height}:{x:0,y:0,width:0,height:0}});
function geometry({width=1280,height=720,eligible=true}={}){
 const visible=eligible&&width>1000&&height>650,host={...box(20,height-66,width-40,56,visible),hidden:!eligible};
 return{version:2,viewport:{width,height,dpr:1,documentWidth:width,documentHeight:height},host,strip:structuredClone(host),outsideHuman:true,rows:eligible?[{...box(170,height-58,width-210,40,visible),hidden:false}]:[],surfaces:{stageHud:box(20,10,width-40,30),humanHud:box(20,50,width-40,40),notation:{...box(20,100,width-40,70),id:'notation-lane-overlay',visibleSvgCount:1},instrument:box(20,180,width-40,Math.max(60,height-380)),keyboard:box(20,200,width-40,120),firstKey:box(20,200,20,120),transport:box(20,height-150,width-40,40),play:box(60,height-150,80,40),reset:box(20,height-150,30,40)}};
}
function run(index,isVsq=false,notes){return{receiverId:index+1,planGeneration:1,positionFrame:index===2?86400:0,prepared:{generation:1},started:{anchorFrame:128},plan:{protocol:'wmh-basic-key-audio-v1',policyId:isVsq?'wmh-vsq-base-note-reference-v1':'wmh-basic-key-reference-v1',identityKind:isVsq?'vsq-authored-note':'midi-note',sourceSha256:isVsq?v.runtime.runtime.source_sha256:f.manifest.source.sha256,sampleRate:48000,durationFrames:isVsq?196001:240000,sourceNotes:isVsq?2:6,notes:notes||[['midi-t3-e1','event1',0,240000,60,70,0],['midi-t3-e2','event2',0,240000,115,70,0]]}};}
function report(phase='complete-practice-seed',viewport){
 const seed=phase.endsWith('seed'),audio=seed?[run(0),run(1),run(2)]:[run(0),run(1,true),run(2,true,[]),run(3,true,[['vsq-t1-ID#0001','vsq-event',0,68101,63,90,2]]),run(4,true,[])];
 const r={phase,audio,activityObserverRestored:true,opened:{clean_package:{runtime:{parts:f.score.notation.parts.map(({id})=>({id}))}}},samples:{},trusted:[],modActions:[],vsqMixedStartAction:10,vsqMutedResetAction:19,vsqMutedStartAction:20};
 const sequence={'vsq-all':9,'vsq-playing':11,'vsq-silent':12,'vsq-mixed':13,'vsq-muted':21};
 for(const [name,state]of Object.entries(NATIVE_PART_ACTIVITY_STATES[phase])){
  const live=['playing','silent','muted'].includes(state),isVsq=name.startsWith('vsq-')&&state!==null,index=isVsq?state==='muted'?4:3:name==='active-human'?1:name==='human-ended'?2:0,current=audio[index],position=state==='ended'?5000:name==='active-human'?1800:state==='silent'||name==='vsq-mixed'?2200:300,partId=isVsq?'vsq-track-1':'midi-t3-c3-r0',label=isVsq?'Test voice':'Track 3 / ch 3';
  const clock={version:1,phase:live?'playing':state||'ready',available:true,positionMs:position,transportPositionMs:position,durationMs:isVsq?v.runtime.compilation.timeline.duration_ms:5000,running:live,completed:state==='ended'};
  const e={...geometry({...viewport,eligible:state!==null}),clock,captureWindow:{before:structuredClone(clock),after:structuredClone(clock)},screen:'stage',mode:name==='vsq-listen'?'listen':'practice',rendererState:clock.phase,ariaLabel:'Machine accompaniment',ariaLive:'off',keyboardInput:'off',liveRegions:[{className:'part-activity-page-label',value:'polite'}],forbiddenSurfaces:0,navigation:{hidden:true,page:'Page 1 of 1',previous:{disabled:true,label:'Previous accompaniment parts',focused:false,focusVisible:false},next:{disabled:true,label:'Next accompaniment parts',focused:false,focusVisible:false}}};
  if(state){e.receiver={index,receiverId:current.receiverId,planGeneration:current.planGeneration,positionFrame:current.positionFrame,plan:structuredClone(current.plan)};e.admission={current:{status:live?'ready':'unavailable',reason:live?null:'no_current_activity_admission',source:1,runtime:2,running:live,plans:live?1:0},admitted:{receiverIndex:index,source:1,runtime:2,epoch:index+1,identity:{sourceToken:3,runtimeToken:4,planToken:index+5,ownershipToken:index+5},parts:[{partId,label,machineSubset:false}],gates:current.plan.notes.map(n=>({partId,occurrenceId:n[0],startMs:n[2]*1000/48000,endMs:n[3]*1000/48000})),durationMs:current.plan.durationFrames*1000/48000,frame:{positionMs:live?position:isVsq?2100:200,transport:'running',rendererState:'running',countIn:false,soundEnabled:true,mutedPartIds:state==='muted'?[partId]:[]}}};Object.assign(e.rows[0],{state,stateText:{playing:'Playing',silent:'Silent',muted:'Muted',paused:'Paused',ended:'Ended'}[state],label,labelTitle:label,source:'Original instrument: not identified',machine:'Machine',subsetHidden:true});}
  r.samples[name]={sequence:sequence[name]||1,position,strip:e,audioPrepared:index+1,geometry:{width:e.viewport.width,height:e.viewport.height,dpr:1,documentWidth:e.viewport.width},captured:'0',sourceTargets:isVsq?['vsq-t2-ID#0001']:f.manifest.human_source_ids};
 }
 if(!seed){r.vsqMixed=[structuredClone(audio[3])];r.vsqMuted=[structuredClone(audio[4])];r.trusted=[{id:'start-performance',type:'click',sequence:10,trusted:true},{id:'reset-button',type:'click',sequence:19,trusted:true},{id:'play-button',type:'click',sequence:20,trusted:true}];r.modActions=[{field:'mute',part:'vsq-track-1',checked:true,sequence:18}];}
 if(!seed){
  r.vsqMixedRequestStart=0;r.vsqMutedRequestStart=2;r.vsqMutedResetClock={positionMs:0,transportPositionMs:0,available:true,running:false,completed:false};
  r.modReadiness={'vsq-muted':{requestStart:0,targetRequestIndex:0,checkRequestIndex:1,humanParts:['vsq-track-2'],outsideSourceIds:[],playDisabled:false,gateHidden:true,retryDisabled:false}};
  const timeline={notes:[{id:'vsq-t2-ID#0001',part_id:'vsq-track-2'}]};r.requests=[{path:'/api/practice-targets',body:{timeline}},{path:'/api/instrument-check',body:{timeline:structuredClone(timeline)}}];
  r.responses=[{path:'/api/practice-targets',requestIndex:0,status:200,body:{playable:true,groups:[{part_ids:['vsq-track-2']}]}},{path:'/api/instrument-check',requestIndex:1,status:200,body:{note_options:[{note_id:'vsq-t2-ID#0001',playable:true}]}}];
 }
 return r;
}
const check=r=>validateCompletePracticeStripEvidence(r,f,v);
test('mandatory Basic/VSQ checkpoints accept genuine-shape retired receipts and reject missing legacy evidence',()=>{
 for(const phase of Object.keys(NATIVE_PART_ACTIVITY_STATES)){assert.deepEqual(COMPLETE_SCREENSHOTS[phase],Object.keys(NATIVE_PART_ACTIVITY_STATES[phase]));check(report(phase));check(report(phase,{width:960,height:640}));const old=report(phase);for(const s of Object.values(old.samples))delete s.strip;assert.throws(()=>check(old),/mandatory production strip evidence missing/);}
});
test('page live region accepts extra styling classes but requires exactly one polite semantic page label',()=>{
 for(const phase of Object.keys(NATIVE_PART_ACTIVITY_STATES)){
  const value=report(phase);for(const sample of Object.values(value.samples))sample.strip.liveRegions[0].className='part-activity-page part-activity-page-label';check(value);
  for(const regions of [undefined,[],[{className:'part-activity-page-label',value:'polite'},{className:'part-activity-row',value:'polite'}],[{className:'part-activity-page',value:'polite'}],[{className:'prefix-part-activity-page-label',value:'polite'}],[{className:'part-activity-page-label',value:'assertive'}]]){
   const invalid=structuredClone(value);Object.values(invalid.samples)[0].strip.liveRegions=regions;assert.throws(()=>check(invalid));
  }
 }
});
test('native gate rejects stale retirement, false active states, changed original ownership and missing mute',()=>{
 for(const mutate of [r=>delete r.samples['active-human'],r=>r.activityObserverRestored=false,r=>r.samples['active-human'].strip.rows=[],r=>r.samples['active-human'].strip.rows[0].stateText='Playing',r=>r.samples['active-human'].strip.rows[0].state='playing',r=>r.samples['active-human'].strip.admission.admitted=null,r=>r.samples['active-human'].strip.admission.current.source++,r=>r.samples['active-human'].strip.admission.current.runtime++,r=>r.samples['active-human'].strip.admission.current.running=true,r=>r.samples['active-human'].strip.admission.current.plans=1,r=>r.samples['active-human'].strip.admission.current.status='ready',r=>r.samples['human-ended'].strip.admission.admitted.frame.transport='unavailable',r=>r.samples['human-ended'].strip.admission.admitted.frame.positionMs=5171.703174603152,r=>r.samples['human-ended'].strip.admission.current.plans=1,r=>r.samples['human-ended'].strip.admission.current.status='ready',r=>r.samples['active-human'].strip.admission.admitted.receiverIndex=0,r=>r.samples['active-human'].strip.admission.admitted.identity.planToken=5,r=>r.samples['active-human'].strip.admission.admitted.gates.pop(),r=>r.samples['active-human'].strip.receiver.plan.sourceSha256='0'.repeat(64),r=>r.samples['active-human'].strip.admission.admitted.parts[0].partId='human',r=>r.samples['active-human'].strip.captureWindow.before.positionMs++,r=>r.samples['multi-restored'].strip.admission.admitted.epoch++,r=>r.samples['multi-visible'].strip.surfaces.keyboard.rect.height--,r=>r.samples.reset.strip.host.hidden=false,r=>r.samples['active-human'].strip.liveRegions.push({className:'part-activity-row',value:'polite'}),r=>r.samples['active-human'].strip.forbiddenSurfaces=1]){const value=report();mutate(value);assert.throws(()=>check(value));}
 for(const mutate of [r=>delete r.samples['vsq-playing'],r=>r.vsqMixed=[],r=>r.vsqMuted=[],r=>r.samples['vsq-muted'].strip.admission.admitted.frame.mutedPartIds=[],r=>r.modActions=[],r=>r.samples['vsq-playing'].strip.admission.current.status='unavailable',r=>r.samples['vsq-playing'].strip.admission.admitted.frame.positionMs++,r=>r.samples['vsq-silent'].strip.rows[0].state='playing',r=>r.samples['vsq-playing'].strip.captureWindow.before.positionMs=1600,r=>r.samples['vsq-silent'].strip.captureWindow.before.positionMs=1000,r=>r.samples['vsq-mixed'].sourceTargets=['vsq-t1-ID#0001'],r=>r.samples['vsq-mixed'].captured='1',r=>r.trusted[0].trusted=false,r=>r.samples['vsq-mixed'].strip.navigation.next.focused=true]){const value=report('complete-practice-restart');mutate(value);assert.throws(()=>check(value));}
});
test('muted restart requires trusted ordered Reset, retained human compatibility and fresh source-zero receiver',()=>{
 for(const mutate of [r=>delete r.vsqMutedResetAction,r=>r.vsqMutedResetAction=17,r=>r.vsqMutedResetAction=20,r=>r.trusted[1].trusted=false,r=>r.trusted[1].id='play-button',r=>r.vsqMutedResetClock.positionMs=2200,r=>r.vsqMutedResetClock.running=true,r=>r.audio[4].positionFrame=105600,r=>delete r.modReadiness,r=>r.modReadiness['vsq-muted'].checkRequestIndex=2,r=>r.modReadiness['vsq-muted'].retryDisabled=true,r=>r.modReadiness['vsq-muted'].outsideSourceIds=['vsq-t2-ID#0001'],r=>r.requests[0].body.timeline.notes[0].part_id='vsq-track-1',r=>r.responses[0].body.groups[0].part_ids=['vsq-track-1'],r=>r.responses[1].status=503,r=>r.responses[1].body.note_options[0].playable=false]){
  const value=report('complete-practice-restart');mutate(value);assert.throws(()=>check(value));
 }
});
test('bounded strip geometry enforces vertical overflow, non-overlap and fixed human dimensions without widening old native geometry',()=>{
 for(const [width,height,visible]of [[1280,720,true],[1280,651,true],[1280,650,false],[1000,720,false],[1001,720,true],[1920,1080,true],[960,640,false],[844,390,false],[390,844,false]])assert.equal(validateNativePartActivityGeometry(geometry({width,height}),{eligible:true}).visible,visible);
 for(const mutate of [e=>e.viewport.documentHeight+=2,e=>e.viewport.documentWidth+=2,e=>e.host.rect.height=54,e=>e.host.position='absolute',e=>e.host.rect.y=700,e=>e.surfaces.transport.rect.y=e.host.rect.y,e=>e.surfaces.humanHud.visible=false,e=>e.surfaces.notation.rect.y=700,e=>e.surfaces.notation.visible=false,e=>e.surfaces.notation.id='notation-panel',e=>e.surfaces.notation.visibleSvgCount=0,e=>e.outsideHuman=false,e=>e.rows[0].rect.width=2000,e=>e.viewport.dpr=0]){const value=geometry();mutate(value);assert.throws(()=>validateNativePartActivityGeometry(value,{eligible:true}));}
 const collapsed=geometry({width:960,height:640});collapsed.host.rect.height=56;assert.throws(()=>validateNativePartActivityGeometry(collapsed,{eligible:true}));const phase='complete-practice-seed',g={version:1,kind:'native-window-geometry',phase,process_id:1,owner_process_id:1,hwnd:1,root_hwnd:1,foreground_hwnd:1,reported_viewport:[1920,1080],client_rect:[0,0,1920,1080],stage:`native-action-${phase}-1`};assert.throws(()=>validateCompleteGeometry(g,{width:1920,height:1080,dpr:1,documentWidth:1920},{phase,processId:1,png:{width:1920,height:1080},sequence:1}));
});
test('mixed VSQ visible source windows use original track2 human ownership and original track1 gate/rest',()=>{
 for(const name of ['vsq-playing','vsq-silent','vsq-mixed','vsq-muted']){const read=position=>completePracticeWindowIds({phase:'complete-practice-restart',name,position,reducedMotion:true});assert.deepEqual(read(300),{human:['vsq-t2-ID#0001'],machine:['vsq-t1-ID#0001']});assert.deepEqual(read(v.runtime.compilation.timeline.notes[0].duration_ms),{human:[],machine:[]});}
});
test('observer forwards real facade result and retains saved live receipt while current facade truthfully becomes unavailable',async()=>{
 const source=await renderer(),context=vm.createContext({structuredClone});vm.runInContext(source.slice(0,source.indexOf('(() => {'))+';globalThis.observe=observeCompletePracticeActivity;',context);
 const tokens={sourceToken:{},runtimeToken:{},planToken:{},ownershipToken:{}},value={status:'ready',epoch:1,snapshot:{...tokens,parts:[{partId:'original',label:'Original',machineSubset:false}],gates:[],durationMs:1000},frame:{positionMs:42,transport:'running',rendererState:'running',countIn:false,soundEnabled:true,mutedPartIds:[]}},calls=[];
 class Player{activityPlayback(...args){calls.push({owner:this,args});return this.result;}}const original=Player.prototype.activityPlayback,observer=context.observe(Player,{getAudioCount:()=>1}),player=new Player();player.song={runtime:{}};player.basicKeys={running:true,plan:{}};player.result=value;const frame={positionMs:42};assert.equal(player.activityPlayback(frame),value);assert.equal(calls[0].owner,player);assert.equal(calls[0].args[0],frame);const first=JSON.parse(JSON.stringify(observer.snapshot()));assert.equal(first.admitted.frame.positionMs,42);assert.equal(first.admitted.receiverIndex,0);
 player.result={status:'unavailable',reason:'no_current_activity_admission'};player.basicKeys={running:false,plan:null};assert.equal(player.activityPlayback({positionMs:100,transport:'paused'}),player.result);const stopped=JSON.parse(JSON.stringify(observer.snapshot()));assert.equal(stopped.current.status,'unavailable');assert.equal(stopped.current.running,false);assert.deepEqual(stopped.admitted,first.admitted);player.song={runtime:{}};assert.notEqual(observer.snapshot().current.source,first.admitted.source);assert.equal(observer.restore(),true);assert.equal(Player.prototype.activityPlayback,original);assert.doesNotMatch(source.slice(source.indexOf('function observeCompletePracticeActivity'),source.indexOf('(() => {')),/currentTime|performance\.now|samplePartActivity|compilePartActivity|requestAnimationFrame/);
});
test('activity observer retains only bounded genuine frames and never borrows a prior receiver or source',async()=>{
 const source=await renderer(),context=vm.createContext({structuredClone});vm.runInContext(source.slice(0,source.indexOf('(() => {'))+';globalThis.observe=observeCompletePracticeActivity;',context);
 const make=()=>({status:'ready',epoch:1,snapshot:{sourceToken:{},runtimeToken:{},planToken:{},ownershipToken:{},parts:[],gates:[],durationMs:5000},frame:{positionMs:4900,transport:'running',rendererState:'running',countIn:false,soundEnabled:true,mutedPartIds:[]}}),invalids=[{transport:'unavailable',rendererState:'stopped',positionMs:5171.703174603152},{positionMs:5171.703174603152},{positionMs:-1},{positionMs:NaN},{transport:'preparing'},{transport:'ready'},{transport:'stopped'},{rendererState:'stopped'},{rendererState:'suspended'},{countIn:true},{transport:'ended',positionMs:4900}];
 let receiverCount=1,calls=0;class Player{activityPlayback(){calls++;return this.result;}}const original=Player.prototype.activityPlayback,observer=context.observe(Player,{getAudioCount:()=>receiverCount}),p=new Player();p.song={runtime:{}};p.basicKeys={running:true,plan:{}};const value=make(),read=()=>JSON.parse(JSON.stringify(observer.snapshot()));
 try{
  for(const frame of invalids){p.result={...value,frame:{...value.frame,...frame}};assert.equal(p.activityPlayback(),p.result);assert.equal(read().admitted,null,'No genuine initial frame means no retired receipt');}
  p.result=value;assert.equal(p.activityPlayback(),value);const admitted=read().admitted;
  for(const frame of invalids){p.result={...value,frame:{...value.frame,...frame}};const before=calls;assert.equal(p.activityPlayback(),p.result);assert.equal(calls,before+1,'The observer forwards exactly one production call');assert.deepEqual(read().admitted,admitted,'Terminal/invalid frames cannot overwrite genuine admission');assert.equal(read().current.status,'ready','Current facade status is never rewritten');}
  for(const change of [()=>receiverCount++,()=>{p.song={runtime:{}};},()=>{p.song.runtime={};},()=>{p.result={...value,snapshot:{...value.snapshot,planToken:{}},frame:{...value.frame,transport:'preparing'}};},()=>{p.result={...value,epoch:2,frame:{...value.frame,transport:'preparing'}};}]){
   p.result=value;p.activityPlayback();p.result={status:'unavailable',reason:'no_current_activity_admission'};change();p.activityPlayback();assert.equal(read().admitted,null,'A new receiver/source/runtime/plan/epoch needs its own genuine frame');
  }
  p.result=value;p.activityPlayback();receiverCount++;assert.equal(read().admitted,null,'Snapshot cannot borrow a saved frame after receiver replacement');
  receiverCount=0;p.result=value;p.activityPlayback();assert.equal(read().admitted,null,'No prepared receiver cannot produce a retained receipt');
 }finally{observer.restore();assert.equal(Player.prototype.activityPlayback,original);}
});
test('production Basic facade terminal grace cannot overwrite its genuine prior running admission',async()=>{
 const [{CleanSongPlayer},{basicKeySong},{basicKeyAudioHarness},{BASIC_KEY_RENDITION}]=await Promise.all([import('../web/clean-song-player.js'),import('./basic-key-rendition-fixtures.js'),import('./basic-key-audio-harness.js'),import('../web/basic-key-player.js')]);
 const source=await renderer(),context=vm.createContext({structuredClone});vm.runInContext(source.slice(0,source.indexOf('(() => {'))+';globalThis.observe=observeCompletePracticeActivity;',context);
 const audio=basicKeyAudioHarness(),old=Object.getOwnPropertyDescriptor(globalThis,'AudioWorkletNode');globalThis.AudioWorkletNode=class{constructor(){return audio.nodeFactory();}};
 const player=new CleanSongPlayer({getPositionMs:()=>0}),observer=context.observe(CleanSongPlayer,{getAudioCount:()=>audio.nodes.length}),song=basicKeySong();player.select(song);
 try{
  await player.start({context:audio.context,output:audio.output,acceptedPolicyId:BASIC_KEY_RENDITION,mode:'listen'});
  const running=player.activityPlayback({positionMs:100,transport:'running',countIn:false,soundEnabled:true});assert.equal(running.status,'ready');assert.equal(running.frame.rendererState,'running');const genuine=JSON.parse(JSON.stringify(observer.snapshot().admitted)),duration=running.snapshot.durationMs;
  while(audio.context.currentTime<duration/1000+.2)audio.renderBlock();audio.deliverMain();await Promise.resolve();assert.equal(player.basicKeys.running,false);
  const late=player.activityPlayback({positionMs:duration+171.703174603152,transport:'running',countIn:false,soundEnabled:true});assert.equal(late.status,'ready');assert.equal(late.frame.transport,'unavailable');assert.equal(late.frame.rendererState,'stopped');assert.ok(late.frame.positionMs>duration);assert.deepEqual(JSON.parse(JSON.stringify(observer.snapshot().admitted)),genuine);
  player.pause();const retired=player.activityPlayback({positionMs:duration,transport:'ended',countIn:false,soundEnabled:true});assert.equal(retired.status,'unavailable');const captured=JSON.parse(JSON.stringify(observer.snapshot()));assert.equal(captured.current.status,'unavailable');assert.equal(captured.current.plans,0);assert.equal(captured.current.running,false);assert.deepEqual(captured.admitted,genuine);
 }finally{observer.restore();player.destroy();if(old)Object.defineProperty(globalThis,'AudioWorkletNode',old);else delete globalThis.AudioWorkletNode;}
});
test('read-only DOM sampler records retained hidden text with zero geometry, plus navigation focus state',async()=>{
 const source=await renderer(),context=vm.createContext({structuredClone});vm.runInContext(source.slice(0,source.indexOf('(() => {'))+';globalThis.capture=captureCompletePracticeStrip;',context);
 const {document}=parseHTML('<html><head></head><body data-screen="stage"><select id="session-mode"><option selected value="practice">Practice</option></select><div id="clean-song-stage" data-renderer-state="paused"></div><div class="part-activity-host"><section class="part-activity-strip" aria-label="Machine accompaniment" aria-live="off" data-keyboard-input="off"><div class="part-activity-pages" hidden><button class="part-activity-previous" disabled aria-label="Previous accompaniment parts"></button><span class="part-activity-page-label" aria-live="polite">Page 1 of 1</span><button class="part-activity-next" disabled aria-label="Next accompaniment parts"></button></div><li class="part-activity-row" data-state="paused"><span class="part-activity-name" title="Actual label">Actual label</span><span class="part-activity-source">Original instrument: not identified</span><span class="part-activity-machine">Machine</span><span class="part-activity-subset" hidden></span><span class="part-activity-state">Paused</span></li></section></div></body></html>');
 for(const node of document.querySelectorAll('*')){node.getBoundingClientRect=()=>node.closest('[hidden]')?{x:0,y:0,width:0,height:0}:{x:10,y:20,width:400,height:56};const original=node.matches;node.matches=function(selector){return selector===':focus-visible'?false:original.call(this,selector);};}Object.defineProperties(document.documentElement,{scrollWidth:{value:1280},scrollHeight:{value:720}});const root={innerWidth:1280,innerHeight:720,devicePixelRatio:1,getComputedStyle:node=>({display:node.closest('[hidden]')?'none':'block',visibility:'visible',position:'static'})};const before=document.documentElement.outerHTML,e=context.capture({document,root,clock:{positionMs:42},admission:null,audio:[]});assert.equal(e.rows[0].state,'paused');assert.equal(e.rows[0].label,'Actual label');assert.equal(e.navigation.next.focused,false);assert.equal(e.navigation.next.focusVisible,false);assert.equal(document.documentElement.outerHTML,before);document.querySelector('.part-activity-host').hidden=true;const hidden=context.capture({document,root,clock:{positionMs:42},admission:null,audio:[]});assert.equal(hidden.host.rect.height,0);assert.equal(hidden.rows[0].visible,false);assert.equal(hidden.rows[0].state,'paused');
});
test('notation sampler binds lane paint, rejects hidden ancestors and never substitutes collapsed controls',async()=>{
 const source=await renderer(),context=vm.createContext({structuredClone});vm.runInContext(source.slice(0,source.indexOf('(() => {'))+';globalThis.capture=captureCompletePracticeStrip;',context);
 const {document}=parseHTML('<html><head></head><body data-screen="stage"><select id="session-mode"><option selected value="practice">Practice</option></select><div id="clean-song-stage" data-renderer-state="paused"></div><div class="part-activity-host"><section class="part-activity-strip"><div class="part-activity-pages"><button class="part-activity-previous"></button><span class="part-activity-page-label"></span><button class="part-activity-next"></button></div></section></div><details id="notation-tools"><summary>Score options</summary><aside id="notation-dock"><section class="notation-panel"><svg></svg></section></aside></details><div id="lane-parent"><div id="notation-lane-overlay"><div id="score-paint"><svg id="score-svg"></svg></div></div></body></html>');
 const $=id=>document.getElementById(id),bounds=new Map(),styles=new Map(),lane=$('notation-lane-overlay'),svg=$('score-svg'),parent=$('lane-parent'),controls=document.querySelector('.notation-panel');
 for(const node of document.querySelectorAll('*')){node.getBoundingClientRect=()=>bounds.get(node)||{x:20,y:100,width:1240,height:70};const original=node.matches;node.matches=function(selector){return selector===':focus-visible'?false:original.call(this,selector);};}
 // Recorded wrong-surface rectangle from exact699 multi-visible/action14.
 bounds.set(controls,{x:728,y:172.46875,width:518,height:662.90625});Object.defineProperties(document.documentElement,{scrollWidth:{value:1280},scrollHeight:{value:720}});
 const root={innerWidth:1280,innerHeight:720,devicePixelRatio:1,getComputedStyle:node=>({display:'block',visibility:'visible',position:'static',opacity:'1',...styles.get(node)})},capture=()=>context.capture({document,root,clock:{positionMs:145},admission:null,audio:[]}),validate=()=>{const e=geometry();e.surfaces.notation=JSON.parse(JSON.stringify(capture().surfaces.notation));return validateNativePartActivityGeometry(e,{eligible:true});};
 const before=document.documentElement.outerHTML,observed=capture();assert.equal(observed.surfaces.notation.id,'notation-lane-overlay');assert.equal(observed.surfaces.notation.visibleSvgCount,1);validate();assert.equal(document.documentElement.outerHTML,before,'The sampler must not open Score options or change layout');
 for(const [node,style]of [[lane,{display:'none'}],[parent,{visibility:'hidden'}],[parent,{opacity:'0'}],[parent,{contentVisibility:'hidden'}],[svg,{display:'none'}],[$('score-paint'),{visibility:'hidden'}]]){styles.set(node,style);assert.throws(validate);styles.delete(node);}
 parent.hidden=true;assert.throws(validate);parent.hidden=false;
 bounds.set(lane,{x:20,y:700,width:1240,height:70});assert.throws(validate,/notation: clipped or outside viewport/);bounds.delete(lane);
 bounds.set(svg,{x:20,y:800,width:100,height:40});assert.throws(validate,/visible score SVG paint/);bounds.delete(svg);
 const home=parent;controls.append(lane);assert.equal(capture().surfaces.notation.visible,false,'Closed details ancestry is invisible even with positive own rects');assert.throws(validate);home.append(lane);validate();
 lane.remove();assert.equal(capture().surfaces.notation,null,'An absent score viewport cannot fall back to the visible-looking controls panel');assert.throws(validate);
});
test('mandatory source/EXE/profile/audio gates and original seed ledger count remain beside new native strip gate',async()=>{
 const source=await readFile(new URL('../scripts/verify-complete-practice-evidence.mjs',import.meta.url),'utf8');for(const token of ['validateCompletePracticeStripEvidence(r,f,vsqAcceptanceFixture())','validateCompletePracticeAudio(r,f)','assert.equal(r.audio.length,3','validateCompleteGeometry(await json','if(sourceSha)assert.equal(native.source_sha,sourceSha)','if(sourceTree)assert.equal(native.source_tree,sourceTree)','assert.equal(digest(b),native.executable_sha256)','await verifyCompletePracticeProfiles(native,json)'])assert.ok(source.includes(token),token);assert.match(source,/validateVsqAudioThreadRuns\(r.vsqMixed,v,\{mode:'practice',targetPart:'vsq-track-2',complete:false,natural:false,pcm:true\}\)/);assert.match(source,/validateVsqAudioThreadRuns\(r.vsqMuted,v,\{mode:'practice',targetPart:'vsq-track-2',mutedParts:\['vsq-track-1'\]/);const app=await renderer();assert.match(app,/muted:\{'vsq-track-1':true\}/);assert.match(app,/captureWindow=\{before,after:report.samples\[name\].strip.clock\}/);assert.match(app,/assert\(sequence<64,'Native action bound'\)/);
});


test('native label oracle joins checked source notation and ignores misleading runtime labels',()=>{
 for(const phase of Object.keys(NATIVE_PART_ACTIVITY_STATES)){
  const value=report(phase);
  for(const part of value.opened.clean_package.runtime.parts)part.name='Invented runtime instrument';
  check(value);
  const name=phase.endsWith('seed')?'multi-visible':'vsq-playing',e=value.samples[name].strip;
  for(const wrong of ['Invented runtime instrument',e.admission.admitted.parts[0].partId]){
   const invalid=structuredClone(value),row=invalid.samples[name].strip;
   row.admission.admitted.parts[0].label=wrong;row.rows[0].label=wrong;row.rows[0].labelTitle=wrong;
   assert.throws(()=>check(invalid));
  }
 }
});
