/** One persistent set of controls, moved into accessible secondary surfaces. */
export function setupGameShell({pausePlayback,onScreen,onNotation,onPanel=()=>{}}) {
  const $=id=>document.getElementById(id),root=document.querySelector('.app-shell'),stage=$('workspace'),sidebar=document.querySelector('.sidebar');
  const header=document.createElement('header');header.className='shell-header';header.innerHTML='<div id="shell-brand"></div><nav aria-label="Session tools"><button id="library-button-slot" hidden></button><button id="import-tools-button" class="button secondary" aria-haspopup="dialog">Import · 导入</button><button id="score-tools-button" class="button secondary" aria-haspopup="dialog">Score · 乐谱</button><button id="settings-button" class="button secondary" aria-haspopup="dialog">Settings · 设置</button><button id="results-button" class="button secondary" aria-haspopup="dialog">Results · 结果</button></nav>';
  const lobby=document.createElement('section');lobby.id='song-lobby';lobby.setAttribute('aria-labelledby','lobby-title');lobby.innerHTML='<div class="lobby-heading"><div><span class="eyebrow">CHOOSE YOUR NEXT SESSION</span><h1 id="lobby-title" tabindex="-1">Your music. Your stage.<span>选一首，进入音乐。</span></h1></div><button id="resume-session" class="button secondary" hidden>Resume session · 返回演奏</button></div><div class="lobby-grid"><section class="song-browser" aria-label="Bundled score list"><div class="song-filters"><label>Search scores · 搜索<input id="catalog-search" type="search" placeholder="Title or composer" maxlength="160"></label><label>Edition · 版本<select id="catalog-origin"><option value="all">All editions · 全部</option><option value="original">Original exercises · 原创练习</option><option value="edition">Source editions · 来源版本</option></select></label></div><div id="lobby-catalog"></div></section><section class="song-preview" aria-labelledby="preview-title"><div class="preview-art" aria-hidden="true"><span>♪</span><i></i><i></i><i></i></div><div class="preview-copy"><span class="eyebrow">SELECTED SCORE · 待演奏</span><h2 id="preview-title">Choose your first score</h2><p id="preview-meta">Browse the list or import a local score.</p><p id="preview-status" role="status">Browsing keeps your current session intact.</p><label id="preview-part-label" hidden>Target part · 演奏声部<select id="preview-part"><option value="">All parts · 所有声部</option></select></label><p id="preview-gate" role="status"></p><details id="preview-notices" hidden><summary id="preview-notices-title">Source &amp; preparation notices</summary><ul id="preview-notice-list"></ul><p>Review the complete score notices in Score after activation. Event retention does not certify expressive playback.</p></details><div class="preview-actions"><button id="start-listen" class="button secondary" disabled>▶ Listen · 开始聆听</button><button id="start-practice" class="button primary" disabled>▶ Practice · 开始练习</button></div><p class="preview-footnote">Browsing this bundled list preserves your paused take. Start opens a new take; Resume returns to the existing one. Import, reviewed activation and Open saved copy explicitly replace the paused score and clear its take history.</p><button id="preview-setup" class="button ghost">Instrument setup · 乐器设置</button></div></section></div>';
  root.prepend(header,lobby);lobby.setAttribute('role','main');const skip=document.querySelector('.skip-link');skip.href='#lobby-title';skip.textContent='Skip to song selection';$('shell-brand').append(sidebar.querySelector('.brand'));$('library-button-slot').replaceWith($('library-button'));
  for(const selector of ['.library-heading','#catalog-status','#catalog'])$('lobby-catalog').append(sidebar.querySelector(selector));
  const dialogs=new Map();let screen='library',notation=false;
  function dialog(name,title,nodes) {
    const el=document.createElement('dialog');el.id=`${name}-dialog`;el.className='shell-dialog';el.setAttribute('aria-labelledby',`${name}-title`);
    const heading=document.createElement('header');heading.className='shell-dialog-heading';const h=document.createElement('h2');h.id=`${name}-title`;h.textContent=title;const close=document.createElement('button');close.className='button secondary';close.dataset.closePanel=name;close.textContent='Close · 关闭';heading.append(h,close);el.append(heading);
    const content=document.createElement('div');content.className='shell-dialog-content';for(const node of nodes)if(node)content.append(node);el.append(content);document.body.append(el);dialogs.set(name,el);
    // Native dialog closing restores its opener. A queued close handler must not
    // refocus the opener after the user has already moved to another control.
    close.addEventListener('click',()=>el.close());return el;
  }
  const piece=document.querySelector('.piece-panel');
  dialog('settings','Session settings · 演奏设置',[piece.querySelector('.control-grid'),$('instrument-settings'),document.querySelector('.practice-target-row'),$('physical-target-note'),document.querySelector('.practice-options'),sidebar.querySelector('.theme-settings'),$('midi-help')]);
  dialog('score-tools','Current score & sources · 当前乐谱与来源',[piece,$('score-details'),$('engraving-license-note')]);
  const importDialog=dialog('import-tools','Bring your music · 导入与审阅',[sidebar.querySelector('.import-box'),sidebar.querySelector('.wanted-tracks'),document.querySelector('.mobile-import')]);
  const importNotice=document.createElement('p');importNotice.className='notice';importNotice.textContent='Importing a valid score or activating a reviewed draft replaces the paused score and clears its in-memory take history. Export take data in Results first if you want to keep it. Playback stays paused. 导入或确认使用乐谱将替换当前乐谱，并清除未导出的练习记录。';importDialog.querySelector('.shell-dialog-content').prepend(importNotice);
  dialog('results','Practice results · 练习结果',[document.querySelector('.feedback-panel')]);
  sidebar.remove();document.querySelector('.topbar')?.remove();document.querySelector('.page-footer')?.remove();
  const hud=document.createElement('div');hud.className='stage-hud';hud.innerHTML='<button id="back-to-library" class="button secondary">← Songs · 曲库</button><div class="stage-heading"><h1 id="stage-title" tabindex="-1">Your stage</h1><p id="stage-subtitle"></p></div><button id="notation-toggle" class="button secondary" aria-expanded="false" aria-controls="notation-dock">Notation · 看谱</button>';
  const dock=document.createElement('aside');dock.id='notation-dock';dock.hidden=true;dock.append(document.querySelector('.notation-panel'));stage.prepend(hud);stage.append(dock);
  const notice=$('notice');header.after(notice);stage.hidden=true;document.body.dataset.screen='library';
  function open(name){const el=dialogs.get(name);if(!el)return;pausePlayback();onPanel(name);if(!el.open)el.showModal();}
  for(const name of dialogs.keys())$(`${name}-button`).addEventListener('click',()=>open(name));
  $('preview-setup').addEventListener('click',()=>open('settings'));
  function show(next){if(next!=='library'&&next!=='stage')return;pausePlayback();for(const el of dialogs.values())if(el.open)el.close();screen=next;stage.hidden=next!=='stage';lobby.hidden=next!=='library';document.body.dataset.screen=next;const heading=next==='stage'?'stage-title':'lobby-title';skip.href=`#${heading}`;skip.textContent=next==='stage'?'Skip to performance':'Skip to song selection';onScreen(next);$(heading).focus();}
  $('back-to-library').addEventListener('click',()=>show('library'));$('resume-session').addEventListener('click',()=>show('stage'));
  $('notation-toggle').addEventListener('click',()=>{notation=!notation;dock.hidden=!notation;$('notation-toggle').setAttribute('aria-expanded',String(notation));stage.classList.toggle('with-notation',notation);onNotation(notation)});
  return {show,open,screen:()=>screen,notationVisible:()=>notation,
    update({score,mode,part,compatibility,passes=0}){$('resume-session').hidden=!score;$('score-tools-button').disabled=!score;$('results-button').disabled=!score;$('stage-title').textContent=score?.title||'Your stage';$('stage-subtitle').textContent=score?`${mode==='practice'?'PRACTICE · 练习':'LISTEN · 聆听'} · ${part||'All parts · 所有声部'}${passes?` · ${passes} take${passes===1?'':'s'}`:''}`:'';$('results-button').textContent=passes?`Results · 结果 (${passes})`:'Results · 结果';if(score)$('resume-session').title=`Return to ${score.title}; playback stays paused`;}
  };
}
