/** Small editorial directory, checked against these official pages on 2026-09-30. */
export const SCORE_SOURCES = Object.freeze([
  {id:'openscore-lieder',name:'OpenScore / Lieder',category:'Art songs · 艺术歌曲',url:'https://github.com/OpenScore/Lieder',rightsUrl:'https://github.com/OpenScore/Lieder/blob/main/LICENSE.txt',rightsLabel:'Repository CC0 license',formats:'MSCX source · MusicXML / MIDI / PDF export routes',routes:['musicxml','midi','image'],description:'The repository publishes CC0 score editions in MuseScore’s MSCX format. Its README describes individual exports and conversion with MuseScore.',rights:'Check the exact edition and retain the supplied credits. CC0 applies to the published corpus editions; the project asks for acknowledgment.',importNote:'WorldMusicHub does not import MSCX or MSCZ. Obtain a MusicXML/MXL export using an appropriate editor or the linked score page, then review the result. Export availability is not guaranteed.',keywords:'openscore lieder cc0 mscx mscz musescore voice vocal 艺术歌曲 声乐'},
  {id:'mutopia',name:'Mutopia Project',category:'Typeset editions · 排印乐谱',url:'https://www.mutopiaproject.org/',rightsUrl:'https://www.mutopiaproject.org/legal.html',rightsLabel:'Mutopia licensing guide',formats:'PDF · MIDI · LilyPond source',routes:['midi','image'],description:'A directory of typeset scores with PDF, MIDI and editable LilyPond files. Each piece lists its own license.',rights:'Check that piece’s public-domain dedication, CC BY or CC BY-SA terms and version. Keep attribution and any applicable share-alike requirements with the edition.',importNote:'MIDI may enter the bounded importer, but notation is inferred. PDF needs image/OMR review; LilyPond (.ly) is not imported directly. Some musical features may be rejected.',keywords:'mutopia pdf midi lilypond ly public domain cc by cc by-sa 公版 钢琴 吉他'},
  {id:'imslp',name:'IMSLP / Petrucci Music Library',category:'Score editions & scans · 乐谱版本与扫描',url:'https://imslp.org/wiki/Main_Page',rightsUrl:'https://imslp.org/wiki/IMSLP:Copyright_Made_Simple',rightsLabel:'IMSLP copyright guide',formats:'Primarily PDF editions and scans',routes:['image'],description:'A starting point for finding score editions and scans. A composer or work page can contain several different editions.',rights:'Check the exact file, editor, publication and your country. The site’s availability or a public-domain composition does not establish that every edition is usable everywhere.',importNote:'A PDF is not a playable score in this app. Export a suitable page or staff crop locally as PNG/JPEG, review uncertain recognition, and confirm every note. Complex pages need a suitable external workflow.',keywords:'imslp petrucci pdf scans editions copyright 公版 扫描 版本 总谱'}
].map(source=>Object.freeze({...source,routes:Object.freeze(source.routes)})));
export function filterScoreSources(query='',route='all') {
  const terms=String(query).normalize('NFKC').trim().toLowerCase().split(/\s+/).filter(Boolean);
  return SCORE_SOURCES.filter(source=>(route==='all'||source.routes.includes(route))&&terms.every(term=>`${source.name} ${source.category} ${source.formats} ${source.keywords}`.normalize('NFKC').toLowerCase().includes(term)));
}
export function unsupportedImportHint(filename) {
  if(/\.pdf$/i.test(filename))return 'PDF is not imported as playable music. Export a clean staff crop locally as PNG/JPEG and use Review image, or review MusicXML from an appropriate external OMR workflow. Every recognized note still needs checking.';
  if(/\.(mscx|mscz)$/i.test(filename))return 'MuseScore source files are not imported directly. Use an appropriate score editor to export MusicXML (.musicxml/.xml/.mxl), keep the original file and credits, then import and review the export.';
  if(/\.(ly|ily)$/i.test(filename))return 'LilyPond source is not imported directly. Keep the original source and license; obtain a supported export or use a printed/image review workflow. Renaming the extension does not convert the score.';
  if(/\.(png|jpe?g)$/i.test(filename))return 'Use Review image for PNG/JPEG. Images need manual pitch and rhythm confirmation; they are not score JSON.';
  return null;
}
export function setupSourceDirectory({pausePlayback,onScoreFile,onImageFile}) {
  const $=id=>document.getElementById(id),dialog=document.createElement('dialog');dialog.id='score-source-directory';dialog.className='review-dialog source-directory';dialog.setAttribute('aria-labelledby','source-directory-title');
  dialog.innerHTML=`<div class="review-header"><div><span class="eyebrow">FIND A SOURCE, THEN REVIEW · 找谱与核对</span><h2 id="source-directory-title">A few good starting points.</h2></div><button id="source-directory-close" class="button ghost" aria-label="Close score source directory">✕</button></div>
    <p class="review-explanation">Three vetted starting points, not a comprehensive catalog. These links open official sites in a new tab. WorldMusicHub does not search those sites, fetch scores, download files or upload your music automatically. A listing does not guarantee a usable file, permission or successful playback.</p>
    <div class="source-filters"><label for="source-search">Search these sources · 查找来源<input id="source-search" type="search" maxlength="100" placeholder="Name, format or keyword" autocomplete="off"></label><label for="source-route">Possible import route · 导入路径<select id="source-route"><option value="all">All three sources · 所有来源</option><option value="musicxml">MusicXML export / conversion</option><option value="midi">MIDI, with inferred notation</option><option value="image">PDF / image review required</option></select></label></div><p id="source-result-count" class="source-result-count" role="status"></p><div id="source-cards" class="source-cards"></div><p id="source-empty" class="review-explanation" hidden>No match in this small directory. Clear the search or choose another route; this is not a search of the external collections.</p>
    <section class="source-checklist" aria-labelledby="source-checklist-title"><h3 id="source-checklist-title">Before you import · 导入前</h3><ol><li><strong>Identify the edition and rights.</strong> Keep the exact score/file URL, composer, editor/arranger, publication details, license/version and required attribution. Check your jurisdiction and intended use. A directory card is not a legal clearance.</li><li><strong>Keep the original alongside conversions.</strong> Save the source file and rights notice. Record the conversion tool and changes. Imported notation does not automatically acquire the website’s license or credits.</li><li><strong>Choose a supported route.</strong> Prefer a supported MusicXML/MXL export when available. MIDI keeps performance timing but notation is inferred. The app-specific .jianpu text dialect is limited to one melody. MSCX/MSCZ, LilyPond and PDF cannot be imported directly.</li><li><strong>Review before practice.</strong> Read import diagnostics, compare pitches/rhythm/voices with the source, choose the correct part and instrument range, and listen first. PNG/JPEG recognition is limited to a clean single treble staff and never infers rhythm. It requires explicit manual confirmation.</li><li><strong>Keep an archive.</strong> Preserve provenance fields and original-source payloads in canonical JSON when supplied. Save a local copy explicitly and export a backup. This directory does not add license metadata to your score.</li></ol></section>
    <p class="source-reviewed">Official pages checked 30 Sep 2026. Availability, export options and terms can change. Read the linked source and rights pages for the actual edition.</p><div class="review-actions"><button id="source-directory-done" class="button secondary">Close guide · 关闭</button><button id="source-choose-image" class="button secondary">Review local PNG/JPEG · 图片</button><button id="source-choose-score" class="button primary">Choose local score file · 导入</button></div>`;
  document.body.append(dialog);
  function render(){
    const sources=filterScoreSources($('source-search').value,$('source-route').value);$('source-result-count').textContent=`${sources.length} of ${SCORE_SOURCES.length} directory sources · local filtering only`;$('source-empty').hidden=sources.length>0;$('source-cards').replaceChildren();
    for(const source of sources){
      const card=document.createElement('article');card.className='source-card';card.dataset.sourceId=source.id;
      const heading=document.createElement('h3');heading.textContent=source.name;const category=document.createElement('span');category.className='source-category';category.textContent=source.category;
      const formats=document.createElement('p');formats.className='source-formats';formats.textContent=source.formats;card.append(category,heading,formats);
      for(const [label,content]of [['',source.description],['Rights check · 权利核对: ',source.rights],['Import route · 导入路径: ',source.importNote]]){const paragraph=document.createElement('p');if(label){const strong=document.createElement('strong');strong.textContent=label;paragraph.append(strong)}paragraph.append(document.createTextNode(content));card.append(paragraph)}
      const links=document.createElement('div');links.className='source-card-links';for(const [label,url]of [['Visit official source ↗',source.url],[`${source.rightsLabel} ↗`,source.rightsUrl]]){const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=label;links.append(link)}card.append(links);$('source-cards').append(card);
    }
  }
  function close(){dialog.close()}
  for(const id of ['source-directory-button','mobile-sources-button'])$(id).addEventListener('click',()=>{pausePlayback();render();dialog.showModal()});
  for(const id of ['source-directory-close','source-directory-done'])$(id).addEventListener('click',close);
  $('source-search').addEventListener('input',render);$('source-route').addEventListener('change',render);
  $('source-choose-score').addEventListener('click',()=>{close();onScoreFile()});$('source-choose-image').addEventListener('click',()=>{close();onImageFile()});
  return{close};
}
